force-app/main/default/objects/Case/fields/Account_Specialist__c.field-meta.xml
<CustomField>
    <fullName>Account_Specialist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Tax Res Functionality</description>
    <label>Account Specialist</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mass_Email_Step__c.field-meta.xml
<CustomField>
    <fullName>Mass_Email_Step__c</fullName>
    <label>Automation Triggered</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>First Response</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Resolution</fullName>
            </value>
            <value>
                <fullName>Skip Email Alert</fullName>
            </value>
            <value>
                <fullName>Tax Res Ready for Checklist Email</fullName>
            </value>
            <value>
                <fullName>Tax Res Research in progress Email</fullName>
            </value>
            <value>
                <fullName>No Notice Attached Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>SUI Rate Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>Skip Ready for Checklist Email</fullName>
            </value>
            <value>
                <fullName>Skip Research in progress Email</fullName>
            </value>
            <value>
                <fullName>Prior to Gusto Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>After Gusto Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>Duplicate Notice Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>Duplicate Notice F/P Check</fullName>
            </value>
            <value>
                <fullName>Previously Answered Auto-Solve Fired</fullName>
            </value>
            <value>
                <fullName>Previously Answered Auto-Solve Fired Closed/Solved</fullName>
            </value>
            <value>
                <fullName>Below Tolerance Auto-Solve fired</fullName>
            </value>
            <value>
                <fullName>DE6601/DE2176 Merge</fullName>
            </value>
            <value>
                <fullName>P&amp;I Late Deposit/Amendment Auto-Solve Fired</fullName>
            </value>
            <value>
                <fullName>P&amp;I Late Deposit/Amendment Partial Auto-Solve Fired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/p_i__c.field-meta.xml
<CustomField>
    <fullName>p_i__c</fullName>
    <label>p&amp;i</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Role__c/fields/BT_Notes__c.field-meta.xml
<CustomField>
    <fullName>BT_Notes__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <label>BT Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/User_Role__c/fields/POD_Captain__c.field-meta.xml
<CustomField>
    <fullName>POD_Captain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Tex Res Functionality</description>
    <label>POD Captain</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gustie_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_Role__c/fields/User_Skill_Team__c.field-meta.xml
<CustomField>
    <fullName>User_Skill_Team__c</fullName>
    <description>FW: Hold the team of Skills user have</description>
    <label>User Skill Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Implementation Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Facilitator</fullName>
            </value>
            <value>
                <fullName>Benefit Transfer</fullName>
            </value>
            <value>
                <fullName>Benefits Advising</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Carrier IO</fullName>
            </value>
            <value>
                <fullName>BYB Advocate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User_Skill__c/User_Skill__c.object-meta.xml
<CustomObject>
    <label>User Skill</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Skill__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Role</label>
    <referenceTo>User_Role__c</referenceTo>
    <relationshipLabel>User Skills</relationshipLabel>
    <relationshipName>User_Role</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaxResChecklistController.cls
/**
 * @name         TaxResChecklistController
 * @author       Pravesh Rana
 * @date         06/04/2021
 * @description  Support class for "TaxResCaseActions" & "TaxResChecklistCmp" lwc component
 * @test class   TaxResChecklistControllerTest
 * @revisions    Date ------------ Name ------------ Comments
 **/
public with sharing class TaxResChecklistController {
	static Id LOGGED_IN_USERID = UserInfo.getUserId();
	static String TAX_RES_LSI = 'TaxRes_LSI';
	static String TAX_RES = 'Tax Res';
	static String PE_CAPTAIN = 'PE/Captain';
	static String STATUS_OPEN = CaseUtils.STATUS_OPEN;
	static String STATUS_DONE = 'Done';
	static String STATUS_REJECT = 'Reject';
	public static String ACTIVE = 'Active';
	public static String SEND_NOTICE_PAGES = 'Send notice pages';
	static String SUCCESS = 'success';
	static String CASE_STATUS_OPEN = CaseUtils.STATUS_OPEN;

	public TaxResChecklistController() {
	}

	/**
	 * @Author      : Pravesh Rana
	 * @Description : return "User_Role" record related to "Logged in User"
	 * @Parm        : N/A
	 * @Return      : User_Role object instance
	 **/
	@AuraEnabled
	public static User_Role__c getLoggedInUserRoleDetails() {
		try {
			List<User_Role__c> list_ObjUserRoles = [
				SELECT
					Id,
					User_Skill_Team__c,
					POD_Captain__c,
					(
						SELECT Id
						FROM User_Role__r
						WHERE User_Skill_Role_Name__c = :CaseUtils.TAXRES_ACCOUNT_SPECIALIST
						LIMIT 1
					)
				FROM User_Role__c
				WHERE User__c = :LOGGED_IN_USERID
			];

			if (list_ObjUserRoles.size() > 0) {
				return list_ObjUserRoles[0];
			}
		} catch (Exception objException) {
			User_Role__c objUserRole = new User_Role__c();
			objUserRole.BT_Notes__c = objException.getMessage();
			return objUserRole;
		}

		return null;
	}

	/**
	 * @Author      : Pravesh Rana
	 * @Description : query "email template" record based on parameter
	 * @Parm        : String [unique email template DeveloperName]
	 * @Return      : EmailTemplate
	 **/
	@AuraEnabled
	public static List<EmailTemplate> getEmailTemplateBody(String strEmailUniqueName) {
		try {
			if (String.isNotBlank(strEmailUniqueName)) {
				List<String> list_templateName = strEmailUniqueName.split(',');
				List<EmailTemplate> list_objEmailTemplates = [
					SELECT Id, HtmlValue, Name
					FROM EmailTemplate
					WHERE DeveloperName IN :list_templateName
				];
				if (list_objEmailTemplates.size() > 0) {
					return list_objEmailTemplates;
				}
			}
		} catch (Exception objException) {
			throw new AuraHandledException(objException.getMessage());
		}
		return new List<EmailTemplate>();
	}

	/**
	 * @Author      : Anand Singh
	 * @Description : Tranfer Case to LSI
	 * @Parm        : String [case id]
	 * @Return      : String [result/error/exception information]
	 **/
	@AuraEnabled
	public static String TransferToLSI(String strObjCaseId) {
		String strReturnMessage = null;
		try {
			if (String.isNotBlank(strObjCaseId)) {
				Case objCase = new Case(Id = strObjCaseId);
				List<Group> list_Group = GlobalQueryHelper.getGroupsByName(TAX_RES_LSI);
				if (list_Group.size() > 0) {
					objCase.OwnerId = list_Group[0].Id;
				}
				objCase.Status = CASE_STATUS_OPEN;
				objCase.Account_Specialist__c = null;
				CaseTriggerHelper.skipTrigger = true;
				update objCase;
				strReturnMessage = SUCCESS;
			}
		} catch (Exception objException) {
			strReturnMessage = objException.getMessage();
		}
		return strReturnMessage;
	}

	/**
	 * @Author      : Shyam Nasare
	 * @Description : Update Case Automation Triggered
	 * @Parm        : String Action, String CaseId
	 * @Return      : String [result/error/exception information]
	 **/
	@AuraEnabled
	public static String updateCaseForPILateDepositAutosolve(String strAction, String strObjCaseId) {
		String strReturnMessage = null;
		try {
			//CaseTriggerHelper.skipTrigger = true;
			List<Case> list_ObjCaseRecord = TaxResNoticeIndexDetailsController.getCasesWithTNDC(new List<Id>{ strObjCaseId });
			Case objCaseToUpdate = new Case(Id = strObjCaseId);
			if (strAction == 'confirmAutosolve') {
				objCaseToUpdate.p_i__c = CaseUtils.STATUS_PI_AUTOSOLVE_STATUS_APPROVED;
				TaxResAutoSolveUtil.handleFieldSync(list_ObjCaseRecord[0], objCaseToUpdate, TaxResNoticeIndexDetailsController.populateAutoSolvePackageDetails(list_ObjCaseRecord[0], TaxResAutoSolveUtil.PI_LATE_DEPOSIT_AUTOSOLVE_PACKAGE));
			} else if (strAction == 'declineAutosolve') {
				List<String> list_MassEmailStepValues = (list_ObjCaseRecord[0].Mass_Email_Step__c).split(';');
				if(list_MassEmailStepValues != null && list_MassEmailStepValues.contains(TaxResNoticeIndexDetailsController.PI_LATE_DEPOSIT_PARTIAL_AUTOSOLVE_FIRED)) {
					list_MassEmailStepValues.remove(list_MassEmailStepValues.indexOf(TaxResNoticeIndexDetailsController.PI_LATE_DEPOSIT_PARTIAL_AUTOSOLVE_FIRED));
					objCaseToUpdate.Mass_Email_Step__c = String.join(list_MassEmailStepValues, ';');
				}
				objCaseToUpdate.p_i__c = CaseUtils.STATUS_PI_AUTOSOLVE_STATUS_DENIED;
			}
			update objCaseToUpdate;
			strReturnMessage = SUCCESS;
		} catch (Exception objException) {
			System.debug(objException);
			strReturnMessage = objException.getMessage();
		}
		return strReturnMessage;
	}
}