force-app/main/default/objects/Case/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Notification__c.field-meta.xml
<CustomField>
    <fullName>Order_Notification__c</fullName>
    <description>To notify customer based on order status/checklist progress.</description>
    <label>Order Notification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Intro Email</fullName>
            </value>
            <value>
                <fullName>Intro Email - ADP Run</fullName>
            </value>
            <value>
                <fullName>Intro Email - IOP/QBOI</fullName>
            </value>
            <value>
                <fullName>Intro Email - IOP/QBOI - Admin</fullName>
            </value>
            <value>
                <fullName>Intro Email - Exception Request</fullName>
            </value>
            <value>
                <fullName>Employees Onboarded</fullName>
            </value>
            <value>
                <fullName>Payroll History</fullName>
            </value>
            <value>
                <fullName>Final Step Not Completed</fullName>
            </value>
            <value>
                <fullName>Post Risk Approval</fullName>
            </value>
            <value>
                <fullName>Run Payroll</fullName>
            </value>
            <value>
                <fullName>Handoff To Care</fullName>
            </value>
            <value>
                <fullName>Handoff To Concierge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/Order_Facilitator_Checklist__c.object-meta.xml
<CustomObject>
    <description>Checklists related to Order</description>
    <label>Order Facilitator Checklist</label>
    <nameField>
        <displayFormat>OFC{000000}</displayFormat>
        <label>Order Facilitator Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Facilitator Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Blocked_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Timestamp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Blocked Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Blocked_Username__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Username__c</fullName>
    <description>Username of the user who marked the checklist as Blocked</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Blocked Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Name__c</fullName>
    <description>Name of checklist, copied over fom BOR Master Checklist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Completed_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Completed_Timestamp__c</fullName>
    <label>Completed Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Completed_Username__c.field-meta.xml
<CustomField>
    <fullName>Completed_Username__c</fullName>
    <description>Username of the user who marked the checklist as complete</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Completed Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To notate if a checklist is blocked.</description>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To mark if a checklist is completed</description>
    <label>Is Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Lookup to Order object to Identify which checklists apply to a particular order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Facilitator Checklists</relationshipLabel>
    <relationshipName>Order_Facilitator_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderFacilitatorChecklistTriggerHelper.cls
/*
 * Description : Handler to handle trigger events on Order Facilitator Checklist
 */
public with sharing class OrderFacilitatorChecklistTriggerHelper {
	public static Boolean skipTrigger = false;
	/*
	 * Description : Called on BeforeInsert event
	 */
    public void onBeforeInsert(List<Order_Facilitator_Checklist__c> lstOrderChklst){
    	//set timestamp for blocked and checked chekclists
    	setTimestamps(lstOrderChklst,NULL);
    }
    /*
	 * Description : Called on BeforeUpdate event
	 */
    public void onBeforeUpdate(List<Order_Facilitator_Checklist__c> lstOrderChklst,Map<Id,Order_Facilitator_Checklist__c> oldChkLstValues){
    	//set timestamp for blocked and checked chekclists
    	setTimestamps(lstOrderChklst,oldChkLstValues);
    	
    }
    /*
	 * Description : Set timestamps when Checklist is marked as completed or Blocked and tracks the user who made this change
	 */
    private void setTimestamps(List<Order_Facilitator_Checklist__c> lstOrderChklst,Map<Id,Order_Facilitator_Checklist__c> oldChkLstValues){
    	String userFullName = userInfo.getFirstName()+' '+userInfo.getLastName();
    	Map<Id,String> mapOrderNotification;
    	for(Order_Facilitator_Checklist__c check:lstOrderChklst){
    		Order_Facilitator_Checklist__c oldChk;
    		if(NULL != oldChkLstValues && oldChkLstValues.size() > 0 && oldChkLstValues.containsKey(check.Id)){
    			oldChk = oldChkLstValues.get(check.Id);
    		}	
			//Checklist is marked as blocked
			if(check.Is_Blocked__c && ((oldChk != NULL && !oldChk.Is_Blocked__c) || NULL == oldChk)){
				check.Blocked_Timestamp__c = system.now();
				check.Blocked_Username__c = userFullName;
			}
			
			//Checklist is marked as completed
			if(check.Is_Completed__c && ((oldChk != NULL && !oldChk.Is_Completed__c) || NULL == oldChk)){
				check.Completed_Timestamp__c = system.now();
				check.Completed_Username__c = userFullName;
				
				//For Added Employees and Added Historical Payrolls checklists, call function to update case.Order_Notification__c field
				if('* Added Employees'.equalsIgnoreCase(check.Checklist_Name__c) || '* Added Historical Payrolls + QA\'d'.equalsIgnoreCase(check.Checklist_Name__c)){
						if (NULL == mapOrderNotification) mapOrderNotification = new Map<Id,String>();
						String strNotification = '* Added Employees'.equalsIgnoreCase(check.Checklist_Name__c) ? 'Employees Onboarded' : 'Payroll History';
						mapOrderNotification.put(check.Order__c,strNotification);
					}
				}
    	}
    	
    	if(NULL != mapOrderNotification){
    		Set<Id> setOrderId = mapOrderNotification.keySet();
    		//get orders related to chekclists which satisfy the notification criteria
    		// SJAY - 12/03/2020 - Commented dynamic query and replacing it with a regular SOQL query.
    		//List<Order> lstOrder = Database.Query('SELECT Id,Case__c,Bulk_Migration__c FROM Order WHERE Bulk_Migration__c = null AND Case__c != NULL AND Id IN :setOrderId');
    		List<Order> lstOrder  = [SELECT Id,Case__c,Bulk_Migration__c FROM Order WHERE Bulk_Migration__c = null AND Case__c != NULL AND Id IN :setOrderId];
    		
            if(NULL != lstOrder && lstOrder.size() > 0){
                // SJAY - 12/03/2020 - Commented call to OrderTriggerHelper method and instead calling method  locally. 
    			//OrderTriggerHelper handler = new OrderTriggerHelper();
    			//handler.updateCaseForNotification(lstOrder,mapOrderNotification);
				
                updateCaseForNotification(lstOrder,mapOrderNotification);
    		}
    	}
    }
    
    /*
	* Update Case based on which notification has to be sent out to customer
	* Paramters: lstOrders is list of orders, mapOrderNotification is map with Key as OrderId and value as notification criteria
	*/
    public void updateCaseForNotification(List<Order> lstOrders,Map<Id,String> mapOrderNotification){
        if(NULL != lstOrders && lstOrders.size() > 0 && NULL != mapOrderNotification && mapOrderNotification.size() > 0){
            List<Case> lstCaseToUpdate = new List<Case>();
            
            //Update related case for non Bulk Orders
            for(Order objOrder : lstOrders){
                if(objOrder.Bulk_Migration__c == NULL && mapOrderNotification.containsKey(objOrder.Id)){
                    lstCaseToUpdate.add(new Case(Id = objOrder.Case__c,Order_Notification__c=mapOrderNotification.get(objOrder.Id)));
                }
            }
            
            if(lstCaseToUpdate.size() > 0){
                //skip Case trigger
                CaseTriggerHelper.skipTrigger = true;
                update lstCaseToUpdate;
                CaseTriggerHelper.skipTrigger = false;
            }
        }
    }    
    
}