force-app/main/default/objects/Case/fields/Call_End__c.field-meta.xml
<CustomField>
    <fullName>Call_End__c</fullName>
    <description>The time call ended from Genesys</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Call_Start__c.field-meta.xml
<CustomField>
    <fullName>Call_Start__c</fullName>
    <description>The time phone call started from Genesys</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Call Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>IF(   ISPICKVAL(Origin, &apos;Phone&apos;) &amp;&amp; Source__c == &apos;C2CB&apos;,
      &apos;Phone&apos;,
      IF( ISPICKVAL(Origin, &apos;Gusto&apos;) &amp;&amp; NOT(ISBLANK(Integration_Id__c)) &amp;&amp; ISBLANK(IVR_Routing_Log__c),
      &apos;Email&apos;, 
      IF( First_Level__c = &apos;wallet_chatbot&apos; &amp;&amp; ISPICKVAL(Origin, &apos;Gusto&apos;), &apos;Wallet Chatbot&apos;, 
IF( NOT(ISBLANK(First_Level__c)) &amp;&amp; ISPICKVAL(Origin, &apos;Gusto&apos;), &apos;Chat&apos;,
IF( ISPICKVAL(Origin, &apos;Gusto Wallet&apos;) &amp;&amp; ISBLANK(Integration_Id__c), &apos;Chat&apos;,
IF( ISPICKVAL(Origin, &apos;Gusto Wallet&apos;) &amp;&amp; NOT(ISBLANK(Integration_Id__c)), &apos;Email&apos;,
IF( IVR_Type__c=&apos;Voicemail&apos; &amp;&amp; OR(IVR_Queue_Name__c=&apos;Dedicated TAM&apos;, IVR_Queue_Name__c=&apos;Tax Filing Compliance&apos;, IVR_Queue_Name__c=&apos;Tax Operations&apos;), &apos;Voicemail&apos;,null))) 
))
)
)</formula>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Duration_in_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_Seconds__c</fullName>
    <label>Duration in Second(s)</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>ContractorPayment</fullName>
                <label>Contractor Payment</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>AgentPayment</fullName>
                <label>Agent Payment</label>
            </value>
            <value>
                <fullName>HistoricalCompany</fullName>
                <label>Historical Company</label>
            </value>
            <value>
                <fullName>PenaltyCase</fullName>
                <label>Penalty Case</label>
            </value>
            <value>
                <fullName>Payroll Care Email</fullName>
            </value>
            <value>
                <fullName>InternationalContractorPayments::Db::InternationalContractorPayment</fullName>
            </value>
            <value>
                <fullName>InternationalEmployeePayroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/Case_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Case Audit Log</label>
    <nameField>
        <displayFormat>CAL-{00000000}</displayFormat>
        <label>Case Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Audit Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Business_Hours__c.field-meta.xml
<CustomField>
    <fullName>Business_Hours__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Hours</label>
    <referenceTo>BusinessHours</referenceTo>
    <relationshipName>Case_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Audit Logs</relationshipLabel>
    <relationshipName>Case_Audit_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>CallBack</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Duration_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Seconds__c</fullName>
    <label>Duration In Seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Duration_in_Seconds_Adjusted__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_Seconds_Adjusted__c</fullName>
    <label>Duration in Seconds Adjusted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Status Change</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Gusto</fullName>
            </value>
            <value>
                <fullName>Panda</fullName>
            </value>
            <value>
                <fullName>Hippo</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>ApIntego</fullName>
            </value>
            <value>
                <fullName>Success Email</fullName>
            </value>
            <value>
                <fullName>Cobra Email</fullName>
            </value>
            <value>
                <fullName>Partner Setup</fullName>
            </value>
            <value>
                <fullName>Partner Transfer</fullName>
            </value>
            <value>
                <fullName>Phone Callback</fullName>
            </value>
            <value>
                <fullName>Outgoing Sales Email</fullName>
            </value>
            <value>
                <fullName>QSEHRA Email</fullName>
            </value>
            <value>
                <fullName>Outreach Email</fullName>
            </value>
            <value>
                <fullName>Follow Up Email</fullName>
            </value>
            <value>
                <fullName>Contact Carrier</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Auto First Response Email</fullName>
            </value>
            <value>
                <fullName>Email-POC</fullName>
            </value>
            <value>
                <fullName>Email Status Change</fullName>
            </value>
            <value>
                <fullName>Owner Change</fullName>
            </value>
            <value>
                <fullName>Intercom</fullName>
            </value>
            <value>
                <fullName>Internal Chat</fullName>
            </value>
            <value>
                <fullName>Gusto Wallet</fullName>
            </value>
            <value>
                <fullName>Ticket</fullName>
            </value>
            <value>
                <fullName>Electronic Notice</fullName>
            </value>
            <value>
                <fullName>Screen Scrape</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/From_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>From_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>From Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/From_Status__c.field-meta.xml
<CustomField>
    <fullName>From_Status__c</fullName>
    <label>From Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Response Received</fullName>
            </value>
            <value>
                <fullName>Solved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Live_Channel_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Live_Channel_Start_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Live Channel Start Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Live_Channel_Wait_Time_In_Seconds__c.field-meta.xml
<CustomField>
    <fullName>Live_Channel_Wait_Time_In_Seconds__c</fullName>
    <label>Live Channel Wait Time In Seconds</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/To_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>To_Date_Time__c</fullName>
    <label>To Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Touchpoint__c.field-meta.xml
<CustomField>
    <fullName>Touchpoint__c</fullName>
    <label>Touchpoint</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/classes/CaseAuditLogTriggerHelper.cls
public class CaseAuditLogTriggerHelper {
	public static boolean skipTrigger = false;
	public static integer counter = 0;
	public static boolean blnException = false; //only for testing
	Map<Id, Case> map_IdToCase;

	private static final String NEW_MESSAGE = 'New Message';
	private static final String STATUS_CHANGE = 'Status Change';

	public void OnBeforeInsert(List<Case_Audit_Log__c> logs) {
		counter++;
		processInfo(logs);
	}

	public void OnAfterInsert(Map<ID, Case_Audit_Log__c> newLogMap) {
		if (CaseTriggerHelper.processStatusChange == true) {
			casetriggerhelper.skipTrigger = true;
		}
	}

	public void OnBeforeUpdate(Map<ID, Case_Audit_Log__c> oldLogMap, Map<ID, Case_Audit_Log__c> newLogMap) {
		counter++;
		processInfo(newLogMap.values());
	}

	public void OnBeforeDelete(Case_Audit_Log__c[] logToDelete, Map<ID, Case_Audit_Log__c> oldLogMap) {
		counter++;
	}

	public void OnAfterDelete(Case_Audit_Log__c[] deletedLogs, Map<ID, Case_Audit_Log__c> oldLogMap) {
		counter++;
	}

	public void OnUndelete(Case_Audit_Log__c[] restoredLogs) {
		counter++;
	}

	private void processInfo(List<Case_Audit_Log__c> list_Logs) {
		createCollections(list_Logs);

		for (Case_Audit_Log__c objLog : list_Logs) {
			/*
			if case origin = email and case record type = payroll care or benefits care
				if event type = email and from status = new message and direction = inbound then touchpoint = 0
				if event type = email and from status = new message and direction = outbound then touchpoint = 1
				if event type = phone and direction = outbound then touchpoint = 1

			if case origin = phone and case record type = payroll care or benefits care
				if event type = phone and direction = inbound then touchpoint = 1
				if event type = phone and direction = outbound then touchpoint = 1
				if event type = email and direction = outbound and from status = new message then touchpoint = 1
				if event type = email and direction = inbound and from status = new message then touchpoint = 0

			if case origin = chat and case record type = payroll care or benefits care
				if event type = chat and from status = new message and direction = inbound then touchpoint = 1
				if event type = email and from status = new message and direction = outbound then touchpoint = 1
				if event type = phone and direction = outbound then touchpoint = 1
			*/
			Case objCase = map_IdToCase.get(objLog.Case__c);
			if (
				(objCase.RecordTypeId == CaseUtils.RECTYPE_PAYROLL_CARE || objCase.RecordTypeId == CaseUtils.RECTYPE_BENEFITS_CARE || objCase.RecordTypeId == CaseUtils.RECTYPE_ENGAGEMENT) &&
				objCase.Status != CaseUtils.STATUS_CLOSED
			) {
				if (
					objCase.Origin == CaseUtils.ORIGIN_EMAIL || 
					objCase.Origin == CaseUtils.ORIGIN_FOLLOW_UP_EMAIL || 
					objCase.Origin == CaseUtils.ORIGIN_ESCALATION ||
					(objCase.Origin == CaseUtils.ORIGIN_GUSTO && objCase.Channel__c == CaseUtils.ORIGIN_EMAIL)
				) {
					if (objLog.Event_Type__c == CaseUtils.ORIGIN_EMAIL && objLog.From_Status__c == NEW_MESSAGE) {
						if (objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_INBOUND) {
							objLog.Touchpoint__c = 0;
						} else if (objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_OUTBOUND) {
							objLog.Touchpoint__c = 1;
						}
					} else if (objLog.Event_Type__c == CaseUtils.ORIGIN_PHONE && objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_OUTBOUND) {
						objLog.Touchpoint__c = 1;
					}
				} else if (objCase.Origin == CaseUtils.ORIGIN_PHONE) {
					if (objLog.Event_Type__c == CaseUtils.ORIGIN_PHONE) {
						if (String.isNotBlank(objLog.Direction__c)) {
							objLog.Touchpoint__c = 1;
						}
					} else if (objLog.Event_Type__c == CaseUtils.ORIGIN_EMAIL) {
						if (objLog.From_Status__c == NEW_MESSAGE) {
							if (objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_INBOUND) {
								objLog.Touchpoint__c = 0;
							} else if (objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_OUTBOUND) {
								objLog.Touchpoint__c = 1;
							}
						}
					}
				} else if (
					objCase.Channel__c == CaseUtils.ORIGIN_CHAT ||
					(objCase.Origin == CaseUtils.ORIGIN_GUSTO && objCase.Channel__c == CaseUtils.ORIGIN_CHAT)
				) {
					if (objLog.Event_Type__c == CaseUtils.ORIGIN_CHAT && objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_INBOUND) {
						objLog.Touchpoint__c = 1;
					} else if (objLog.Event_Type__c == CaseUtils.ORIGIN_EMAIL && objLog.From_Status__c == NEW_MESSAGE && objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_OUTBOUND) {
						objLog.Touchpoint__c = 1;
					} else if (objLog.Event_Type__c == CaseUtils.ORIGIN_PHONE && objLog.Direction__c == EmailMessageUtil.CASE_DIRECTION_OUTBOUND) {
						objLog.Touchpoint__c = 1;
					}
				}
			}

			if (objLog.Business_Hours__c != null && objLog.From_Date_Time__c != null && objLog.To_Date_Time__c != null) {
				Id hoursId = objLog.Business_Hours__c;
				DateTime fromTime = objLog.From_Date_Time__c;
				DateTime toTime = objLog.To_Date_Time__c;

				Long milliSeconds = 0;
				/* calculating duration in seconds for all event types */
				milliSeconds = objLog.To_Date_Time__c.getTime() - objLog.From_Date_Time__c.getTime();

				if (milliSeconds > 0) {
					objLog.Duration_in_seconds__c = milliSeconds / 1000;
				}

				/*
					Author: Alex
					Date: 7/30/2020
					Desc: populate new Duration in Seconds Adjusted field
				*/
				try {
					Decimal decDIS = 0;
					if (!map_IdToCase.isEmpty()) {
						if (
							objLog.Case__c != null &&
							objLog.From_Date_Time__c != null &&
							map_IdToCase.get(objLog.Case__c).Call_Start__c != null &&
							objLog.To_Date_Time__c != null &&
							map_IdToCase.get(objLog.Case__c).Call_End__c != null
						) {
							if (
								Math.max(objLog.From_Date_Time__c.getTime(), map_IdToCase.get(objLog.Case__c).Call_Start__c.getTime()) <
								Math.min(objLog.To_Date_Time__c.getTime(), map_IdToCase.get(objLog.Case__c).Call_End__c.getTime())
							) {
								//if CAL started after call start and before call end and ends after call end
								//take difference of Call End and log's To Date Time
								//set Duration in Seconds Adjusted to difference
								if (objLog.Event_Type__c == STATUS_CHANGE) {
									Decimal decBefore = (map_IdToCase.get(objLog.Case__c).Call_Start__c.getTime() - objLog.From_Date_Time__c.getTime()) / 1000;
									if (decBefore > 0) {
										decDis = decBefore;
									}

									Decimal decAfter = (objLog.To_Date_Time__c.getTime() - map_IdToCase.get(objLog.Case__c)?.Call_End__c.getTime()) / 1000;
									if (decAfter > 0) {
										decDIS += decAfter;
									}
								}
							} else {
								decDIS = objLog.Duration_in_seconds__c;
							}
						}
					}
					//if we did not have Call Start/Call End
					if (map_IdToCase.get(objLog.Case__c).Call_Start__c == null || map_IdToCase.get(objLog.Case__c).Call_End__c == null) {
						decDIS = objLog.Duration_in_seconds__c;
					}
					objLog.Duration_In_Seconds_Adjusted__c = decDIS;
					if (Test.isRunningTest() && blnException == true) {
						Integer i = 0 / 0;
					}
				} catch (Exception objExcept) {
					ExceptionLogUtil.logException('CaseAuditLogTriggerHelper', 'processInfo', objExcept.getMessage(), objExcept.getStackTraceString());
				}
			}
			if (objLog.Business_Hours__c != null && objLog.Live_Channel_Start_Time__c != null && objLog.From_Date_Time__c != null) {
				Id hoursId = objLog.Business_Hours__c;
				DateTime fromTime = objLog.Live_Channel_Start_Time__c;
				DateTime toTime = objLog.From_Date_Time__c;
				Long milliSeconds = BusinessHours.diff(hoursId, fromTime, toTime);
				objLog.Live_Channel_Wait_Time_In_Seconds__c = milliSeconds / 1000;
			}
		}
	}
	/**
	 * @author Alex Xiong
	 * @description method for building collection variables
	 */
	private void createCollections(List<Case_Audit_Log__c> list_Logs) {
		Set<Id> set_CaseIds = new Set<Id>();

		for (Case_Audit_Log__c objCal : list_Logs) {
			set_CaseIds.add(objCal.Case__c);
		}
		queryCases(set_CaseIds);
	}

	/**
	 * @author Alex Xiong
	 * @description queries cases
	 */
	private void queryCases(Set<Id> set_CaseIds) {
		map_IdToCase = new Map<Id, Case>();

		for (Case objCase : [SELECT Id, Status, Call_Start__c, Call_End__c, Origin, Channel__c, RecordTypeId FROM Case WHERE Id IN :set_CaseIds]) {
			map_IdToCase.put(objCase.Id, objCase);
		}
	}
}