force-app/main/default/objects/Case/fields/Call_Recording__c.field-meta.xml
<CustomField>
    <fullName>Call_Recording__c</fullName>
    <formula>HYPERLINK(&quot;https://na1.nice-incontact.com/player/#/cxone-player/acd-contacts/&quot;&amp;  Genesys_Call_Id__c  , &quot;Recording Link&quot;,&quot;_new&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call Recording</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/IVR_Intent_Grouping__c.field-meta.xml
<CustomField>
    <fullName>IVR_Intent_Grouping__c</fullName>
    <label>IVR Intent Grouping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/IVR_Routing_Log__c.field-meta.xml
<CustomField>
    <fullName>IVR_Routing_Log__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IVR Routing Log</label>
    <referenceTo>IVR_Routing_Log__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IVR_Intent_Grouping__c/IVR_Intent_Grouping__c.object-meta.xml
<CustomObject>
    <label>IVR Intent Grouping</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IVR Intent Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IVR Intent Groupings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IVR_Intent_Grouping__c/fields/Intent_Code__c.field-meta.xml
<CustomField>
    <fullName>Intent_Code__c</fullName>
    <externalId>true</externalId>
    <label>Intent Code</label>
    <length>60</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/IVR_Intent_Grouping__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Class 1</fullName>
            </value>
            <value>
                <fullName>Payroll Class 2</fullName>
            </value>
            <value>
                <fullName>Payroll Class 3</fullName>
            </value>
            <value>
                <fullName>Benefits Class 1</fullName>
            </value>
            <value>
                <fullName>Benefits Class 2</fullName>
            </value>
            <value>
                <fullName>Benefits Class 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/IVR_Routing_Log__c.object-meta.xml
<CustomObject>
    <label>IVR Routing Log</label>
    <nameField>
        <displayFormat>IVR-{000000000}</displayFormat>
        <label>IVR Routing Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IVR Routing Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IVR_Routing_Log__c/fields/ANI__c.field-meta.xml
<CustomField>
    <fullName>ANI__c</fullName>
    <label>ANI</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <label>Approved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No Action</fullName>
            </value>
            <value>
                <fullName>Disregard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Bot_Review_Skipped__c.field-meta.xml
<CustomField>
    <fullName>Bot_Review_Skipped__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bot Review Skipped</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Call_Recording__c.field-meta.xml
<CustomField>
    <fullName>Call_Recording__c</fullName>
    <formula>HYPERLINK(&quot;https://apps.mypurecloud.com/directory/#/engage/admin/interactions/&quot;&amp; ConversationId__c  , &quot;Recording Link&quot;,&quot;_new&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call Recording</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/IVR_Routing_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>IVR Routing Logs</relationshipLabel>
    <relationshipName>IVR_Routing_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason__c</fullName>
    <formula>Text(Case__r.Confirm_Case_Reason__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Reason</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Case_Skill__c.field-meta.xml
<CustomField>
    <fullName>Case_Skill__c</fullName>
    <formula>IF( NOT(ISBLANK(TEXT(Case__r.Class__c))) ,Case__r.Case_Reason_Skill__c, null)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Skill</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/CIP_Auth__c.field-meta.xml
<CustomField>
    <fullName>CIP_Auth__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIP Auth</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/CIP_Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>CIP_Customer_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIP Customer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/CIP_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>CIP_Queue_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>CIP Queue Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>CIP Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/ConversationId__c.field-meta.xml
<CustomField>
    <fullName>ConversationId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ConversationId</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/IVR_Routing_Log__c/fields/Correct_Intent_Grouping__c.field-meta.xml
<CustomField>
    <fullName>Correct_Intent_Grouping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Correct Intent Grouping</label>
    <referenceTo>IVR_Intent_Grouping__c</referenceTo>
    <relationshipLabel>IVR Routing Logs (Correct Intent Grouping)</relationshipLabel>
    <relationshipName>IVR_Routing_Logs1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/isIVRinPlay__c.field-meta.xml
<CustomField>
    <fullName>isIVRinPlay__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isIVRinPlay</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/IVR_Intent_Grouping__c.field-meta.xml
<CustomField>
    <fullName>IVR_Intent_Grouping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IVR Intent Grouping</label>
    <referenceTo>IVR_Intent_Grouping__c</referenceTo>
    <relationshipLabel>IVR Routing Logs (IVR Intent Grouping)</relationshipLabel>
    <relationshipName>IVR_Routing_Logs2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Lex_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Lex_Transcript__c</fullName>
    <label>Lex Transcript</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Skill</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/IVR_Routing_Log__c/fields/Transcript_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Transcript_Reviewed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transcript Reviewed</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/IVR_Routing_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IVR_Routing_Log__c/fields/Utterance__c.field-meta.xml
<CustomField>
    <fullName>Utterance__c</fullName>
    <label>Utterance</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines user types - Integration, Admin, UXR Manager, etc. It can be used in flows and trigger logic for customization and automation.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>UX Researcher Mng</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IVRRoutingLogDetailCustomController.cls
/**
 * @name         IVRRoutingLogDetailCustomController
 * @author       Sanjay Paryani
 * @date         10/23/2019
 * @description  Class to show IVR Routing logs with Case Feed on the VF page IVRRoutingLogDetailCustom
 * @revisions    Date ------------ Name ------------ Comments
 *				11/05/2019		  SanjayP			Added method skipAndSave() to skip a record and go to the next one.
 *				11/05/2019		  SanjayP			Added locking mechanism to the IVR Routing Logs play mode.
 **/
public with sharing class IVRRoutingLogDetailCustomController {
	public string selectedQueueId { get; set; }
	public boolean isPlay { get; set; } //indicates that user has clicked play or not
	public boolean isPlayEmpty { get; set; } //indicates that current queue is empty
	public string currentIVRRLogId { get; set; }
	public string currentIntentGrouping { get; set; }
	public List<String> intentGroupings { get; set; }
	public IVR_Routing_Log__c selectedIVRRLog { get; set; }
	// using this for scenario when  user is in "Play mode" and clicked on "Save" button
	public boolean isNext = false;
	// this indicates if Skip button is clicked for a particualr IVR record
	public boolean isSkipped = false;
	public List<IVR_Routing_Log__c> IVRRecords { get; set; }
	public set<id> alreadyPlayedIVRRLogIdSet = new Set<id>();
	list<SelectOption> userQueueList = new List<SelectOption>();

	public IVRRoutingLogDetailCustomController() {
		isPlay = false;
		isPlayEmpty = false;
		selectedIVRRLog = new IVR_Routing_Log__c();
		this.getIVRs();
	}

	public void getIntentGroupings() {
		intentGroupings = new List<String>();
		for (IVR_Intent_Grouping__c ivrg : [SELECT Id, Name, Intent_Code__c, Skill__c FROM IVR_Intent_Grouping__c ORDER BY Name ASC LIMIT 999]) {
			intentGroupings.add(ivrg.Name);
		}
	}

	public void getIVRDetail() {
		List<IVR_Routing_Log__c> tempIVRRecordPlayList = new List<IVR_Routing_Log__c>();
		if (!isPlay && String.isNotBlank(currentIVRRLogId)) {
			tempIVRRecordPlayList = [
						SELECT
							Bot_Review_Skipped__c,
							Case_Reason__c,
							isIVRinPlay__c,
							IVR_Intent_Grouping__r.Name,
							Case_Skill__c,
							Skill__c,
							CreatedDate,
							Type__c,
							ConversationId__c,
							CIP_Queue_Name__c,
							ANI__c,
							CIP_Auth__c,
							Company_Name__c,
							CIP_Customer_Name__c,
							Lex_Transcript__c,
							Id,
							IVR_Intent_Grouping__c,
							OwnerId,
							Call_Recording__c,
							Correct_Intent_Grouping__c,
							Case__c,
							Case__r.CaseNumber,
							Utterance__c,
							Approved__c,
							Name,
							Correct_Intent_Grouping__r.Name
						FROM IVR_Routing_Log__c
						WHERE Id = :currentIVRRLogId
						LIMIT 1
				];
		} else if(isPlay) {
				if (string.isblank(selectedQueueId) || selectedQueueId == '1') {
					selectedQueueId = userInfo.getUserId();
				}

			tempIVRRecordPlayList = [
					SELECT
						Bot_Review_Skipped__c,
						Case_Reason__c,
						isIVRinPlay__c,
						IVR_Intent_Grouping__r.Name,
						Case_Skill__c,
						Skill__c,
						CreatedDate,
						Type__c,
						ConversationId__c,
						CIP_Queue_Name__c,
						CIP_Auth__c,
						CIP_Customer_Name__c,
						Lex_Transcript__c,
						Id,
						IVR_Intent_Grouping__c,
						OwnerId,
						Call_Recording__c,
						Correct_Intent_Grouping__c,
						Case__c,
						Case__r.CaseNumber,
						Utterance__c,
						Approved__c,
						Name,
						Correct_Intent_Grouping__r.Name
					FROM IVR_Routing_Log__c
					WHERE Transcript_Reviewed__c = FALSE AND isIVRinPlay__c = FALSE AND Bot_Review_Skipped__c = FALSE AND OwnerId = :selectedQueueId AND Id NOT IN :alreadyPlayedIVRRLogIdSet
					ORDER BY CreatedDate ASC
					LIMIT 20
				];
		}
		if (!tempIVRRecordPlayList.isEmpty()) {
			selectedIVRRLog = tempIVRRecordPlayList.get(0);
				} else {
					selectedIVRRLog = new IVR_Routing_Log__c();
					return;
				}
			getIntentGroupings();
		}

	public list<SelectOption> getIVRQueueList() {
		list<SelectOption> queueList = new List<SelectOption>();
		queueList.add(new SelectOption('1', 'My IVR Routing Logs'));

		for (QueueSobject qu : [SELECT Id, SobjectType, QueueId, Queue.Name, Queue.Type, Queue.RelatedId FROM QueueSobject WHERE SobjectType = 'IVR_Routing_Log__c' AND Queue.Type = 'Queue']) {
			queueList.add(new SelectOption(qu.QueueId, qu.Queue.Name));
		}

		return queueList;
	}

	public PageReference getIVRs() {
		isPlayEmpty = false;
		String query = '';
		query = 'select Bot_Review_Skipped__c,isIVRinPlay__c,Case_Reason__c,IVR_Intent_Grouping__r.Name,Case_Skill__c,Skill__c,CreatedDate,Type__c,ConversationId__c,CIP_Queue_Name__c,CIP_Auth__c,CIP_Customer_Name__c,Lex_Transcript__c,Id,IVR_Intent_Grouping__c,OwnerId,Call_Recording__c,Correct_Intent_Grouping__c,Case__c,Case__r.CaseNumber,Utterance__c,Approved__c,Name,Correct_Intent_Grouping__r.Name';
		query += ' from IVR_Routing_Log__c where Transcript_Reviewed__c = false and isIVRinPlay__c = false and Bot_Review_Skipped__c = false ';
		if (!string.isBlank(selectedQueueId) && selectedQueueId != '1') {
			query += ' and ownerId=:selectedQueueId ';
		} else {
			id userIdd = userInfo.getUserId();
			query += ' and ownerId=:userIdd ';
		}
		query += ' order BY CreatedDate asc limit 1000 ';

		IVRRecords = Database.query(query);
		return null;
	}

	public void saveIVRRecord() {
		List<IVR_Routing_Log__c> ivrToUpdateList = new List<IVR_Routing_Log__c>();

		try {
			if (isPlay && isNext) {
				selectedIVRRLog.isIVRinPlay__c = false;
				selectedIVRRLog.Transcript_Reviewed__c = true;
			}
			if (isSkipped) {
				selectedIVRRLog.Bot_Review_Skipped__c = true;
				selectedIVRRLog.Transcript_Reviewed__c = false;
			}
			if (!String.isBlank(currentIntentGrouping)) {
				List<IVR_Intent_Grouping__c> intentGroupingsList = [SELECT ID, Name FROM IVR_Intent_Grouping__c WHERE Name = :currentIntentGrouping];
				if (intentGroupingsList.size() > 0) {
					selectedIVRRLog.Correct_Intent_Grouping__c = intentGroupingsList.get(0).Id;
				} else {
					selectedIVRRLog.Correct_Intent_Grouping__c = null;
				}
			}
			ivrToUpdateList.add(selectedIVRRLog);
			Database.update(ivrToUpdateList);
		} catch (exception ex) {
			apexPages.addMessage(new apexPages.Message(apexPages.Severity.error, ex.getMessage()));
		}

		if (!apexPages.hasMessages()) {
			if (!isPlay) {
				selectedIVRRLog = new IVR_Routing_Log__c();
			}
		}
	}

	public void cancelUpdate() {
		try {
			selectedIVRRLog.Transcript_Reviewed__c = false;
			selectedIVRRLog.isIVRinPlay__c = false;
			update selectedIVRRLog;
		} catch (exception ex) {
		}

		selectedIVRRLog = new IVR_Routing_Log__c();
		isPlay = false;
	}

	public void saveNextRecord() {
		isNext = true;
		saveIVRRecord();
		isNext = false;

		if (apexPages.hasMessages()) {
			return;
		}

		alreadyPlayedIVRRLogIdSet.add(selectedIVRRLog.id);
		getIVRs();
		startPlay();
	}

	public void skipAndSave() {
		isSkipped = true;
		saveIVRRecord();
		isSkipped = false;

		if (apexPages.hasMessages()) {
			return;
		}

		alreadyPlayedIVRRLogIdSet.add(selectedIVRRLog.id);
		getIVRs();
		startPlay();
	}

	public void startPlay() {
		getIVRs();
		if (IVRRecords.size() > 0) {
			isPlay = true;
			isPlayEmpty = false;
			getIVRDetail();
			if (selectedIVRRLog != null && selectedIVRRLog.id != null) {
					selectedIVRRLog.isIVRinPlay__c = false;
					try {
						update selectedIVRRLog;
					} catch (exception ex) {
						apexPages.addMessage(new apexPages.Message(apexPages.Severity.Error, ex.getMessage()));
					}
				
			} else {
				isPlayEmpty = true;
				isPlay = false;
			}
		} else {
			isPlayEmpty = true;
			isPlay = false;
			selectedIVRRLog = new IVR_Routing_Log__c();
		}
	}
}