force-app/main/default/objects/Case/fields/Date_Time_Solved__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Solved__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Time Solved</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Request_Deletion_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Request_Deletion_Confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Privacy Requests. The requester is confirming they want their information deleted.</description>
    <label>Privacy Request Deletion Confirmation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Privacy_Request_Info_Confirmation__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Request_Info_Confirmation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For Privacy Requests. By checking this field, the requester is confirming the info they provided is to the best of their knowledge.</description>
    <label>Privacy Request Info Confirmation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Privacy_Requester_Data__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Requester_Data__c</fullName>
    <description>Privacy Requests. Data Collection records&apos; Details will be put in here.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Privacy Requester Data</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Privacy_Requester_Email__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Requester_Email__c</fullName>
    <description>Privacy Requester&apos;s email address</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Privacy Requester Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Privacy_Requester_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Requester_First_Name__c</fullName>
    <description>Privacy Requester&apos;s first name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requester First Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Privacy_Requester_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Requester_Last_Name__c</fullName>
    <description>Privacy Requester&apos;s last name</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Requester Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Request_Type__c</fullName>
    <description>For privacy requests. The type of request from the requester.</description>
    <label>Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disclosure</fullName>
            </value>
            <value>
                <fullName>Deletion</fullName>
            </value>
            <value>
                <fullName>Disclosure and Deletion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Routing_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Routing_Case_Reason__c</fullName>
    <label>Routing Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1099 Adjustment</fullName>
            </value>
            <value>
                <fullName>Response to NPS Survey</fullName>
            </value>
            <value>
                <fullName>Deduction or Garnishment</fullName>
            </value>
            <value>
                <fullName>Benefit Reversal</fullName>
            </value>
            <value>
                <fullName>Soft Suspend</fullName>
                <label>soft suspend</label>
            </value>
            <value>
                <fullName>Time Tracking ER</fullName>
            </value>
            <value>
                <fullName>Time Tracking EE</fullName>
                <label>time tracking EE</label>
            </value>
            <value>
                <fullName>Destroy or Delete Account (not cancel)</fullName>
            </value>
            <value>
                <fullName>EFTPS Question</fullName>
            </value>
            <value>
                <fullName>IRS/State Notice</fullName>
            </value>
            <value>
                <fullName>Unsupported State - Workers Comp&apos;</fullName>
            </value>
            <value>
                <fullName>Gusto Giving</fullName>
            </value>
            <value>
                <fullName>Cancel Account</fullName>
            </value>
            <value>
                <fullName>PTO Policy</fullName>
            </value>
            <value>
                <fullName>External Workers&apos; Comp</fullName>
            </value>
            <value>
                <fullName>EoY Spot Check Squad Action Required</fullName>
            </value>
            <value>
                <fullName>Benefits Adjustment</fullName>
                <label>benefits adjustment</label>
            </value>
            <value>
                <fullName>POA Responses</fullName>
            </value>
            <value>
                <fullName>Onboarding Audit</fullName>
            </value>
            <value>
                <fullName>Benefit Adjustment</fullName>
                <label>benefit adjustment</label>
            </value>
            <value>
                <fullName>External Covid Reporting</fullName>
            </value>
            <value>
                <fullName>QSEHRA</fullName>
            </value>
            <value>
                <fullName>Route to FSC</fullName>
            </value>
            <value>
                <fullName>Route to PRC</fullName>
            </value>
            <value>
                <fullName>Route to Modern Bank</fullName>
            </value>
            <value>
                <fullName>Route to Risk</fullName>
            </value>
            <value>
                <fullName>Route to Sales</fullName>
            </value>
            <value>
                <fullName>Route to Tax Ops</fullName>
            </value>
            <value>
                <fullName>Route to Tax Res</fullName>
            </value>
            <value>
                <fullName>Route to Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Status_Detail__c</fullName>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Termed for Non-Payment</fullName>
            </value>
            <value>
                <fullName>SSN Verification</fullName>
            </value>
            <value>
                <fullName>Name Verification</fullName>
            </value>
            <value>
                <fullName>Birthday Verification</fullName>
            </value>
            <value>
                <fullName>Cross-Team Escalation</fullName>
            </value>
            <value>
                <fullName>Pending Due to Carrier</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>No Group ID</fullName>
            </value>
            <value>
                <fullName>RFI</fullName>
            </value>
            <value>
                <fullName>Researching</fullName>
            </value>
            <value>
                <fullName>Contacting Agency</fullName>
            </value>
            <value>
                <fullName>Processing Corrections</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Agency</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Gusto</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Client</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Bank</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>Awaiting Info</fullName>
            </value>
            <value>
                <fullName>Inactionable Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PrivacyRequestsPortalCtrlTest.cls
/*  
        @CreaedBy     ::: Prashant Bhatt (Lirik)
        @CreatedDate  ::: 11/12/2019
        Desc          ::: test class for PrivacyRequestsPortalCtrl class. Page Used  -PrivacyRequestsPortal   
*/
@isTest
public with sharing class PrivacyRequestsPortalCtrlTest {
	@isTest
	public static void testPrivacyFRequestsPortal() {
		//create a account, case and data collection record.
		Account acc = TestUtility.CompanyAccount();

		Case objCase = new Case();
		objCase.RecordTypeId = cache.getRecordTypeId('Case', 'Privacy Request');
		objCase.Type = 'Benefits Care';
		objCase.Request_Type__c = 'Deletion';
		objCase.Origin = 'Email';
		objCase.Privacy_Request_Info_Confirmation__c = false;
		objCase.Privacy_Request_Deletion_Confirmation__c = true;
		objCase.Status = 'Request Denied';
		objCase.Status_Detail__c = 'Location';
		objCase.Privacy_Requester_First_Name__c = 'testFirstName';
		objCase.Privacy_Requester_Last_Name__c = 'testLastName';
		objCase.Privacy_Requester_Data__c = 'testPrivacydata';
		objCase.Privacy_Requester_Email__c = 'test@test.com';
		objCase.CreatedDate = system.today();
		objCase.Date_Time_Solved__c = system.now().addHours(6);
		objCase.Routing_Case_Reason__c = 'Test Reason';
		insert objCase;

		Test.startTest();
		String action = EncodingUtil.base64Encode(Blob.valueOf('testcookie'));
		Cookie cookie = new Cookie('prAuth', action, null, 31536000, false);

		PageReference pageRef = Page.PrivacyRequestsPortal;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('id', String.valueOf(objCase.Id));
		ApexPages.currentPage().setCookies(new List<Cookie>{ cookie });

		PrivacyRequestsPortalCtrl privacyRequestsPortalTestobj = new PrivacyRequestsPortalCtrl();
		privacyRequestsPortalTestobj.requestCase = objCase;
		privacyRequestsPortalTestobj.blobFile = blob.valueOf('blobtestvalue');
		privacyRequestsPortalTestobj.validateCookie();
		privacyRequestsPortalTestobj.toggleShowInformation();
		privacyRequestsPortalTestobj.toggleSubmitButton();

		privacyRequestsPortalTestobj.strFileName = 'testcontentfilename';
		privacyRequestsPortalTestobj.blobFile = Blob.valueof('blobtestversion');

		privacyRequestsPortalTestobj.uploadFile2();
		privacyRequestsPortalTestobj.save();
		privacyRequestsPortalTestobj.saveAndSubmit();
		Test.stopTest();
	}
	@isTest
	public static void testPrivacyFRequestsPortal1() {
		//create a account, case and data collection record.
		Account acc = TestUtility.CompanyAccount();

		Case objCase = new Case();
		objCase.RecordTypeId = cache.getRecordTypeId('Case', 'Privacy Request');
		objCase.Type = 'Benefits Care';
		objCase.Request_Type__c = 'Disclosure';
		objCase.Origin = 'Email';
		objCase.Privacy_Request_Info_Confirmation__c = true;
		objCase.Privacy_Request_Deletion_Confirmation__c = true;
		objCase.Status = 'Ready to Disclose';
		objCase.Privacy_Requester_First_Name__c = 'testFirstName';
		objCase.Privacy_Requester_Last_Name__c = 'testLastName';
		objCase.Privacy_Requester_Data__c = 'testPrivacydata';
		objCase.Privacy_Requester_Email__c = 'test@test.com';
		objCase.CreatedDate = system.today();
		objCase.Date_Time_Solved__c = system.now().addHours(6);
		objCase.Routing_Case_Reason__c = 'Test Reason';
		insert objCase;

		Test.startTest();
		PageReference pageRef = Page.PrivacyRequestsPortal;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('id', String.valueOf(objCase.Id));

		PrivacyRequestsPortalCtrl privacyRequestsPortalTestobj = new PrivacyRequestsPortalCtrl();
		privacyRequestsPortalTestobj.requestCase = objCase;
		privacyRequestsPortalTestobj.blobFile = blob.valueOf('blobtestvalue');
		//validate Cookie method test for actual page reference vs return page reference
		PageReference returnPageUrl = privacyRequestsPortalTestobj.validateCookie();
		PageReference expectedPage = new PageReference('/apex/PrivacyRequestsPortalEntrance');
		System.assertEquals(expectedPage.getUrl(), returnPageUrl.getUrl());

		privacyRequestsPortalTestobj.toggleShowInformation();
		privacyRequestsPortalTestobj.toggleSubmitButton();

		privacyRequestsPortalTestobj.strFileName = 'testcontentfilename';
		privacyRequestsPortalTestobj.blobFile = Blob.valueof('blobtestversion');

		privacyRequestsPortalTestobj.uploadFile();
		privacyRequestsPortalTestobj.save();
		privacyRequestsPortalTestobj.saveAndSubmit();

		privacyRequestsPortalTestobj.boolIsDelete = true;
		privacyRequestsPortalTestobj.save();
		privacyRequestsPortalTestobj.saveAndSubmit();

		Test.stopTest();
	}

	@isTest
	public static void testPrivacyFRequestsPortalException() {
		//create a account, case and data collection record.
		Account acc = TestUtility.CompanyAccount();

		Case objCase = new Case();
		objCase.RecordTypeId = cache.getRecordTypeId('Case', 'Privacy Request');
		objCase.Type = 'Benefits Care';
		objCase.Request_Type__c = 'Disclosure';
		objCase.Origin = 'Email';
		objCase.Privacy_Request_Info_Confirmation__c = true;
		objCase.Privacy_Request_Deletion_Confirmation__c = true;
		objCase.Status = 'Request Denied';
		objCase.Privacy_Requester_First_Name__c = 'testFirstName';
		objCase.Privacy_Requester_Last_Name__c = 'testLastName';
		objCase.Privacy_Requester_Data__c = 'testPrivacydata';
		objCase.Privacy_Requester_Email__c = 'test@test.com';
		objCase.CreatedDate = system.today();
		objCase.Date_Time_Solved__c = system.now().addHours(6);
		objCase.Routing_Case_Reason__c = 'Test Reason';
		insert objCase;

		Test.startTest();
		PageReference pageRef = Page.PrivacyRequestsPortal;
		Test.setCurrentPage(pageRef);
		pageRef.getParameters().put('id', String.valueOf(objCase.Id));

		PrivacyRequestsPortalCtrl privacyRequestsPortalTestobj = new PrivacyRequestsPortalCtrl();
		objCase.Status = 'Request_Denied';
		privacyRequestsPortalTestobj.requestCase = objCase;
		privacyRequestsPortalTestobj.blobFile = blob.valueOf('blobtestvalue');
		//validate Cookie method test for actual page reference vs return page reference
		PageReference returnPageUrl = privacyRequestsPortalTestobj.validateCookie();
		PageReference expectedPage = new PageReference('/apex/PrivacyRequestsPortalEntrance');
		System.assertEquals(expectedPage.getUrl(), returnPageUrl.getUrl());

		privacyRequestsPortalTestobj.boolInfoConfirm = false;
		privacyRequestsPortalTestobj.toggleShowInformation();
		privacyRequestsPortalTestobj.toggleSubmitButton();

		privacyRequestsPortalTestobj.strFileName = 'testcontentfilename';
		privacyRequestsPortalTestobj.blobFile = Blob.valueof('blobtestversion');
		privacyRequestsPortalTestobj.save();
		privacyRequestsPortalTestobj.saveAndSubmit();

		Test.stopTest();
	}
}