unpackaged/main/default/objects/HI_Open_Enrollment_Window__c/HI_Open_Enrollment_Window__c.object-meta.xml
<CustomObject>
    <label>HI Open Enrollment Window</label>
    <nameField>
        <displayFormat>OEW-{0000}</displayFormat>
        <label>Open Enrollment Windows Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI Open Enrollment Windows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HIOpenEnrollmentWindowBatch.cls
public with sharing class HIOpenEnrollmentWindowBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        string queryString = 'Select Id from HI_Open_Enrollment_Window__c where Processing_State__c=\'Error\' or Processing_State__c=\'Queued\'';
        
        return Database.getQueryLocator(queryString);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope){
        HIOpenEnrollmentWindowTriggerHelper.queue=true;
        List<HI_Open_Enrollment_Window__c> windowList= (List<HI_Open_Enrollment_Window__c>)scope;
        
        update windowList;
    }
    
    public void finish(Database.BatchableContext BC){
        
        AsyncApexJob objAsyncJob = [SELECT Id, Status, NumberOfErrors, TotalJobItems FROM AsyncApexJob WHERE Id = :BC.getJobId()];
		Utils.processBatchFinish(objAsyncJob, 'HIOpenEnrollmentWindowBatch', false);
    }
}