unpackaged/main/default/objects/Recovery_Case_Class_Assignment_Setting__c/Recovery_Case_Class_Assignment_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains class assignment setting for recovery cases.</description>
    <label>Recovery Case Class Assignment Setting</label>
</CustomObject>

force-app/main/default/objects/Recovery_Case_Class_Assignment_Setting__c/fields/Eligible_Class__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Eligible Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recovery_Case_Class_Assignment_Setting__c/fields/Recovery_Amount_End_Limit__c.field-meta.xml
<CustomField>
    <fullName>Recovery_Amount_End_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Recovery Amount End Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Recovery_Case_Class_Assignment_Setting__c/fields/Recovery_Amount_Starting_Limit__c.field-meta.xml
<CustomField>
    <fullName>Recovery_Amount_Starting_Limit__c</fullName>
    <label>Recovery Amount Starting Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recovery_Case_Class_Assignment_Setting__c/fields/Task_Us__c.field-meta.xml
<CustomField>
    <fullName>Task_Us__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Task Us</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RecoveryCaseClassSettingUpdateTest.cls
@isTest
public class RecoveryCaseClassSettingUpdateTest {
	@TestSetup
	static void dataSetupMethod() {
		Recovery_Case_Class_Assignment_Setting__c settObj = new Recovery_Case_Class_Assignment_Setting__c();
		settObj.Name = '1';
		settObj.Error_Code__c = 'R01';
		settObj.Recovery_Amount_Starting_Limit__c = 1;
		settObj.Recovery_Amount_End_Limit__c = 50;
		settObj.Eligible_Class__c = 'Class 1';
		settObj.Task_Us__c = false;

		insert settObj;
	}

	@isTest
	static void updateObjectTestMethod() {
		RecoveryCaseClassSettingUpdateController classInstance = new RecoveryCaseClassSettingUpdateController();
		system.assert(classInstance.lst_wrapper.size() > 0);
		classInstance.saveCustomSetting();
		classInstance.closeCurrentPage();
	}
}