unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

unpackaged/main/default/objects/Configuration_Settings__c/fields/Payment_Invoice_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Payment_Invoice_Batch_Size__c</fullName>
    <description>batch size for payment invoice</description>
    <label>Payment Invoice Batch Size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Invoice_Run_Log__c/Invoice_Run_Log__c.object-meta.xml
<CustomObject>
    <description>Object used to track number of invoices received from the billing system (Zuora) for each batch.</description>
    <label>Invoice Run Log</label>
    <nameField>
        <displayFormat>INV-RUN-{0000}</displayFormat>
        <label>Invoice Run Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Run Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Invoice_Run_Log__c/fields/Batch_Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Batch_Processing_State__c</fullName>
    <description>Indicates status of batch job</description>
    <label>Batch Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Invoice_Run_Log__c/fields/Number_of_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Invoice__c</fullName>
    <description>Number of invoices received from the billing system (Zuora).</description>
    <label>Number of Invoices</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Run_Log__c/fields/Period_End__c.field-meta.xml
<CustomField>
    <fullName>Period_End__c</fullName>
    <description>Invoice Period End Date</description>
    <label>Period End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Run_Log__c/fields/Period_Start__c.field-meta.xml
<CustomField>
    <fullName>Period_Start__c</fullName>
    <description>Invoice Period Start Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Period Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice_Run_Log__c/fields/Workflow_Run_Number__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Run_Number__c</fullName>
    <description>Unique workflow run number identifier from the billing system (Zuora).</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Workflow Run Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Invoice__c/Payment_Invoice__c.object-meta.xml
<CustomObject>
    <label>Payment Invoice</label>
    <nameField>
        <label>Invoice Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Invoice__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <description>The last day of the invoice period.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The last day of the invoice period.</inlineHelpText>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Invoice__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <description>The first day of the invoice Period.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The first day of the invoice Period.</inlineHelpText>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Payment_Invoice__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <description>Indicates the processing state of a payment invoice (Example: Queued, Error, etc.).</description>
    <inlineHelpText>Indicates the processing state of a payment invoice (Example: Queued, Error, etc.).</inlineHelpText>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Invoice__c/fields/Workflow_Run_Number__c.field-meta.xml
<CustomField>
    <fullName>Workflow_Run_Number__c</fullName>
    <description>Unique workflow run number identifier from the billing system (Zuora). Matched to Invoice Run Log record. Used to compare the number of Payment Invoices for the Workflow Run Number to the Number of Invoices on the Invoice Run Log.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Unique workflow run number identifier from the billing system (Zuora). Matched to Invoice Run Log record. Used to compare the number of Payment Invoices for the Workflow Run Number to the Number of Invoices on the Invoice Run Log.</inlineHelpText>
    <label>Workflow Run Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Processing_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Queued</fullName>
        <default>true</default>
        <label>Queued</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Dead</fullName>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Retry</fullName>
    </customValue>
    <customValue>
        <fullName>Manually Enqueued</fullName>
    </customValue>
    <description>Processing state for integration</description>
    <masterLabel>Integration Processing States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentInvoiceQueryHelper.cls
/**
 * @name         : PaymentInvoiceQueryHelper
 * @author       : Praveen Sethu
 * @date         : 08-24-2022
 * @description  : Query Helper class to get payment invoice data
 * @test classes : PaymentInvoiceQueryHelperTest
 **/
public class PaymentInvoiceQueryHelper {
	/**
	 * @Author      : Praveeen Sethu
	 * @Description : Gets count of Payment Invoice records for specific start and end date
	 * @Parm        : list_InvoiceRunLogs - Invoice Run Log record Id
	 * @Return      : N/A
	 **/
	@InvocableMethod(label='Get Payment Invoices By Date' description='Returns list of Payment Invoices for specific period start and end date.' category='Payment_Invoice__c')
	public static List<Integer> getPaymentInvoicesByDate(List<Id> list_InvoiceRunLogs) {
		Set<String> list_PendingStates = new Set<String>{ IntegrationUtils.ERROR_STATE, IntegrationUtils.QUEUED_STATE, IntegrationUtils.BACKLOG };
		Integer intPaymentInvoiceCount = 0;
		Id idInvoiceRunLog = list_InvoiceRunLogs.get(0);
		if (idInvoiceRunLog != null) {
			Invoice_Run_Log__c objInvoiceRunLog = [
				SELECT Id, Period_Start__c, Period_End__c, Workflow_Run_Number__c, Batch_Processing_State__c, Number_of_Invoice__c
				FROM Invoice_Run_Log__c
				WHERE Id = :idInvoiceRunLog
			];

			if (objInvoiceRunLog != null) {
				if (objInvoiceRunLog.Batch_Processing_State__c == IntegrationUtils.PROCESSED_STATE) {
					// if batch job is processed - get invoices with pending processing states
					intPaymentInvoiceCount = [
						SELECT COUNT()
						FROM Payment_Invoice__c
						WHERE
							Workflow_Run_Number__c = :objInvoiceRunLog.Workflow_Run_Number__c
							AND Period_Start_Date__c = :objInvoiceRunLog.Period_Start__c
							AND Period_End_Date__c = :objInvoiceRunLog.Period_End__c
							AND Processing_State__c IN :list_PendingStates
					];
				} else {
					// if batch job is not processed - get all invoices for a workflow run number & period start, end dates
					intPaymentInvoiceCount = [
						SELECT COUNT()
						FROM Payment_Invoice__c
						WHERE
							Workflow_Run_Number__c = :objInvoiceRunLog.Workflow_Run_Number__c
							AND Period_Start_Date__c = :objInvoiceRunLog.Period_Start__c
							AND Period_End_Date__c = :objInvoiceRunLog.Period_End__c
					];

					if (intPaymentInvoiceCount == objInvoiceRunLog.Number_of_Invoice__c) {
						Configuration_Settings__c config = Configuration_Settings__c.getOrgDefaults();
						Integer intBatchSize = config.Payment_Invoice_Batch_Size__c != null ? config.Payment_Invoice_Batch_Size__c.intValue() : 5;

						Database.executeBatch(new PaymentInvoiceBatch(objInvoiceRunLog), intBatchSize);
					}
				}
			}
		}
		return new List<Integer>{ intPaymentInvoiceCount };
	}
}