unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

unpackaged/main/default/objects/Configuration_Settings__c/fields/Calculate_Reseller_Metrics_Batch__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Reseller_Metrics_Batch__c</fullName>
    <label>Calculate Reseller Metrics Batch</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculateResellerMetricsScheduler.cls
/**
 * @description  Scheduler class for calculating reseller metrics
 * @author       Praveen Sethu
 * @date         01-28-2023
 * @see          CalculateResellerMetricsBatchTest
 **/

public with sharing class CalculateResellerMetricsScheduler implements Schedulable {
	public void execute(SchedulableContext sc) {
		Configuration_Settings__c config = Configuration_Settings__c.getOrgDefaults();
		Integer intBatchSize = config.Calculate_Reseller_Metrics_Batch__c.intValue() != null &&
			config.Calculate_Reseller_Metrics_Batch__c.intValue() != 0
			? config.Calculate_Reseller_Metrics_Batch__c.intValue()
			: 1;

		Database.executeBatch(new CalculateResellerMetricsBatch(), intBatchSize);
	}
}