unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Configuration_Settings__c/fields/Privacy_Requests_Cookie_Key__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Requests_Cookie_Key__c</fullName>
    <description>DO NOT EDIT. For Privacy Requests. The key used to encrypt cookie to access the Privacy Request page.</description>
    <inlineHelpText>DO NOT EDIT. For Privacy Requests (CCPA).</inlineHelpText>
    <label>Privacy Requests Cookie Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PrivacyRequestsUtil.cls
public with sharing class PrivacyRequestsUtil { // change to util class
    public static void updateCookieKey() {
        Blob blobKey = crypto.generateAesKey(128);
        String key = EncodingUtil.base64Encode(blobKey);

        Configuration_Settings__c configSettings = Configuration_Settings__c.getOrgDefaults();
        configSettings.Privacy_Requests_Cookie_Key__c = key;
        upsert configSettings;
    }
}