unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Configuration_Settings__c/fields/ZP_Company_Migration_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Migration_Batch_Size__c</fullName>
    <description>Batch size for re-processing errored and queued ZP Company Migration records</description>
    <label>ZP Company Migration Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ZP_Company__c/ZP_Company__c.object-meta.xml
<CustomObject>
    <label>ZP Company</label>
    <nameField>
        <displayFormat>COMPANY-{000000000}</displayFormat>
        <label>ZP Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ZP_Company__c/fields/Is_Large_Firm_Id__c.field-meta.xml
<CustomField>
    <fullName>Is_Large_Firm_Id__c</fullName>
    <description>Boolean field that will return true if managing or original accounting firm Id is a large firm.</description>
    <formula>AND(
NOT(ISBLANK(Managing_Accounting_Firm_Id__c)),
CONTAINS($Label.Large_Firm_Id,Managing_Accounting_Firm_Id__c)
)
||
AND(
NOT(ISBLANK(Original_Accounting_Firm_Id__c)),
CONTAINS($Label.Large_Firm_Id,Original_Accounting_Firm_Id__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Boolean field that will return true if managing or original accounting firm Id is a large firm.</inlineHelpText>
    <label>Is Large Firm Id</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ZP_Company__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <description>The current processing state for this record.  Only values in Queued are processed.</description>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Processing_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Queued</fullName>
        <default>true</default>
        <label>Queued</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Dead</fullName>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Retry</fullName>
    </customValue>
    <customValue>
        <fullName>Manually Enqueued</fullName>
    </customValue>
    <description>Processing state for integration</description>
    <masterLabel>Integration Processing States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ZPCompanyBatch.cls
/**
 * @author       Praveen Sethu
 * @description  Main batch class to process company records that are not linked to large firms
 * @see ZPCompanyBatchTest
 */
public without sharing class ZPCompanyBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
	public Database.QueryLocator start(Database.BatchableContext bc) {
		String strQuery = 'SELECT Id FROM ZP_Company__c WHERE Is_Large_Firm_Id__c = FALSE AND (Processing_State__c=\'Error\' OR Processing_State__c=\'Queued\')';
		return Database.getQueryLocator(strQuery);
	}

	public void execute(Database.BatchableContext bc, List<sObject> scope) {
		try {
			ZPCompanyTriggerHelper.queue = true;
			List<ZP_Company__c> companyList = (List<ZP_Company__c>) scope;

			update companyList;
		} catch (Exception objException) {
			ExceptionLogUtil.logException('ZPCompanyBatch', 'execute', null, objException);
		}
	}

	public void finish(Database.BatchableContext BC) {
		List<String> list_BatchPendingStatus = new List<String>{ 'Holding', 'Queued', 'Preparing', 'Processing' };
		Configuration_Settings__c config = Configuration_Settings__c.getOrgDefaults();

		Integer intMigrationBatch = config.ZP_Company_Migration_Batch_Size__c != null &&
			config.ZP_Company_Migration_Batch_Size__c.intValue() != null &&
			config.ZP_Company_Migration_Batch_Size__c.intValue() != 0
			? config.ZP_Company_Migration_Batch_Size__c.intValue()
			: 1;

		Database.executeBatch(new ZPCompanyMigrationBatch(''), intMigrationBatch);

		AsyncApexJob objAsyncJob = [SELECT Id, Status, NumberOfErrors, TotalJobItems FROM AsyncApexJob WHERE Id = :BC.getJobId()];
		Utils.processBatchFinish(objAsyncJob, 'ZPCompanyBatch', false);

		// check if there are any large firms that need to be processed
		Integer intLargeFirmCount = [SELECT COUNT() FROM ZP_Company__c WHERE Is_Large_Firm_Id__c = TRUE AND Processing_State__c IN ('Queued', 'Error')];
		if (intLargeFirmCount > 0) {
			// Abort old jobs before starting a new one
			List<AsyncApexJob> list_jobs = [SELECT Id, JobItemsProcessed, TotalJobItems FROM AsyncApexJob WHERE Status IN :list_BatchPendingStatus AND ApexClass.Name IN ('ZPCompanyLargeFirmBatch') LIMIT 150];

			// Add dummy apex job during test runs
			if (Test.isRunningTest()) {
				list_jobs.add(new AsyncApexJob());
			}
			if (!list_jobs.isEmpty()) {
				try {
					for (AsyncApexJob job : list_jobs) {
						System.abortJob(job.Id);
					}
				} catch (Exception ex) {
					ExceptionLogUtil.logException('ZPCompanyBatchScheduler', 'process', ex);
				}
			}

			Database.executeBatch(new ZPCompanyLargeFirmBatch(), 1);
		}
	}
}