force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/Carrier_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Unique_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchDMLTest.cls
/**
 * @name         BatchDMLTest
 * @author       Sanjay Paryani
 * @date         05/28/2020
 * @description  Test class for BatchDML
 * @revisions    Date ------------ Name ------------ Comments
 **/
@isTest
private class BatchDMLTest {
	@isTest
	static void test_BatchDMLInsert() {
		List<Carrier__c> list_Carriers = new List<Carrier__c>();
		List<Carrier__c> list_CarriersToUpdate = new List<Carrier__c>();
		List<Carrier__c> list_CarriersToDelete = new List<Carrier__c>();

		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care California').setUniqueName('Test Care').setState('CA').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care New York').setUniqueName('Test Care').setState('NY').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Alegeus').setUniqueName('Alegeus').setState('NY;TX;CA,MO').setPartnerType('TAdA').build());

		Test.startTest();
		if (!list_Carriers.isEmpty()) {
			BatchDML.Operation batchInsert = BatchDML.Operation.INS;
			ID batchInsertJobID = System.enqueueJob(new BatchDML(batchInsert, list_Carriers, false));
		}
		System.assertNotEquals(0, list_Carriers.size(), 'The list cannot be empty.');
		Test.stopTest();
	}

	@isTest
	static void test_BatchDMLUpdate() {
		List<Carrier__c> list_Carriers = new List<Carrier__c>();
		List<Carrier__c> list_CarriersToUpdate = new List<Carrier__c>();
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care California').setUniqueName('Test Care').setState('CA').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care New York').setUniqueName('Test Care').setState('NY').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Alegeus').setUniqueName('Alegeus').setState('NY;TX;CA,MO').setPartnerType('TAdA').build());
		insert list_Carriers;

		for (Carrier__c c : [SELECT Id, Name, Carrier_Unique_Name__c, State__c FROM Carrier__c LIMIT 2]) {
			list_CarriersToUpdate.add(c);
		}

		Test.startTest();
		if (!list_Carriers.isEmpty()) {
			list_CarriersToUpdate[0].Carrier_Unique_Name__c = 'Test Care';
			list_CarriersToUpdate[1].Carrier_Unique_Name__c = 'Test Care';

			BatchDML.Operation batchUpdate = BatchDML.Operation.UPD;
			ID batchUpdateJobID = System.enqueueJob(new BatchDML(batchUpdate, list_CarriersToUpdate, false));
		}
		System.assertNotEquals(0, list_CarriersToUpdate.size(), 'The list cannot be empty.');
		Test.stopTest();
	}

	@isTest
	static void test_BatchDMLDelete() {
		List<Carrier__c> list_Carriers = new List<Carrier__c>();
		List<Carrier__c> list_CarriersToDelete = new List<Carrier__c>();
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care California').setUniqueName('Test Care').setState('CA').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Test Care New York').setUniqueName('Test Care').setState('NY').build());
		list_Carriers.add(new TestDataFactory.CarrierBuilder().setName('Alegeus').setUniqueName('Alegeus').setState('NY;TX;CA,MO').setPartnerType('TAdA').build());
		insert list_Carriers;

		for (Carrier__c c : [SELECT Id, Name, Carrier_Unique_Name__c, State__c FROM Carrier__c]) {
			list_CarriersToDelete.add(c);
		}

		Test.startTest();
		BatchDML.Operation batchDelete = BatchDML.Operation.DEL;
		ID batchDeleteJobID = System.enqueueJob(new BatchDML(batchDelete, list_CarriersToDelete, false));
		System.assertNotEquals(0, list_CarriersToDelete.size(), 'The list cannot be empty.');
		Test.stopTest();
	}
}