force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/Confirmation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Confirmation Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <formula>Benefit_Order__r.Coverage_Effective_Date__c</formula>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Stage__c</fullName>
    <description>The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.

The Previous Implementation Stage and Implementation stage should be in sync. This status is mapped to previous implementation stage and OB message is sent to app using Kafka.</description>
    <label>Implementation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>Ready For Qualification</fullName>
                <default>true</default>
                <label>Ready For Qualification</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>OE Extended</fullName>
            </value>
            <value>
                <fullName>OE Verification/Checking Participation</fullName>
            </value>
            <value>
                <fullName>Ready for Submission Prep</fullName>
            </value>
            <value>
                <fullName>Submission Prep</fullName>
            </value>
            <value>
                <fullName>Ready for Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Item</fullName>
            </value>
            <value>
                <fullName>Approved Pending EE Audit</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier Switch</fullName>
            </value>
            <value>
                <fullName>New to Gusto</fullName>
            </value>
            <value>
                <fullName>New line of Coverage</fullName>
            </value>
            <value>
                <fullName>Same carrier, plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Same Carrier, NO Plan/Group Level Changes</fullName>
            </value>
            <value>
                <fullName>TAdA: No Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>TAdA: Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>Terminated Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/Parent_Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Parent_Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders (Parent Carrier Order)</relationshipLabel>
    <relationshipName>Carrier_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Stage_Detail__c.field-meta.xml
<CustomField>
    <fullName>Stage_Detail__c</fullName>
    <description>The picklist values for the Status Detail on the Benefit Order and the Stage Detail on the Carrier Order must be kept in sync.</description>
    <label>Implementation Stage Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Implementation_Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Carve out group</fullName>
            </value>
            <value>
                <fullName>[NP] Duplicate: Changed Carrier (Bundle Ancillary)</fullName>
            </value>
            <value>
                <fullName>[NP] Duplicate: Changed Carrier (ER Choice)</fullName>
            </value>
            <value>
                <fullName>[NP] Duplicate: Changed Carrier (Failed QA)</fullName>
            </value>
            <value>
                <fullName>[NP+R] Duplicate: Other</fullName>
            </value>
            <value>
                <fullName>Effective Date Not Supported</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Company not authorized in state</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Existing Carrier - Transferred to BOR Opportunity</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Husband/Wife Only</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Insufficient Payroll</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: No eligible employees</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Not enough EE&apos;s in state</fullName>
            </value>
            <value>
                <fullName>[NP+R] Ineligible: No workers&apos; compensation</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Owner Only</fullName>
            </value>
            <value>
                <fullName>[NP] Ineligible: Unsupported State</fullName>
            </value>
            <value>
                <fullName>Nonpayment of premium under a previous policy</fullName>
            </value>
            <value>
                <fullName>[NP] Non-Responsive Employer</fullName>
            </value>
            <value>
                <fullName>Owner only group</fullName>
            </value>
            <value>
                <fullName>[NP+R] Participation: Ancillary Participation Not Met</fullName>
            </value>
            <value>
                <fullName>[NP+R] Participation: Medical Participation Not Met</fullName>
            </value>
            <value>
                <fullName>Participation rate not met</fullName>
            </value>
            <value>
                <fullName>Post Signature Cancel</fullName>
            </value>
            <value>
                <fullName>[NP] Post-Signature Cancel: Chose Competitor - Earlier Effective Date</fullName>
            </value>
            <value>
                <fullName>[NP] Post-Signature Cancel: Did Not Become Gusto Customer</fullName>
            </value>
            <value>
                <fullName>[NP+R] Post-Signature Cancel: No Longer Interested</fullName>
            </value>
            <value>
                <fullName>[NP] Post-Signature Cancel: Too Expensive</fullName>
            </value>
            <value>
                <fullName>Post Signature Ineligible</fullName>
            </value>
            <value>
                <fullName>[R] Renewal: Carrier Canceled - Nonpayment</fullName>
            </value>
            <value>
                <fullName>[R] Renewal: Carrier Canceled - Recertification</fullName>
            </value>
            <value>
                <fullName>[R] Renewal: Switched to new broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Submission_Completion_Notes__c.field-meta.xml
<CustomField>
    <fullName>Submission_Completion_Notes__c</fullName>
    <description>This field is filled by the fulfillment team when moving a Carrier Order from submission to confirmation stage.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Submission Completion Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CarrierOrderMoveToConfirmationCtrl.cls
/**
 * @author       Deepika Saini
 * @date         22nd June 2024
 * @description  This class is used to validate the Move To Confirmation functionality .
 * @testclass	 CarrierOrderMoveToConfirmationCtrlTest
 **/

public with sharing class CarrierOrderMoveToConfirmationCtrl {
	/**
	 * @author      Deepika Saini
	 * @description This method used to Update Implemetation Stage to Ready For Confirmation
	 * @param       Id - Id of Carrier Order
	 *              String - String of Submission Completion Notes
	 * @return      Boolean - Returns True or false
	 */
	@AuraEnabled
	public static Boolean moveToConfirmation(Id carrierOrderId, String strSubmissionNotes) {
		try {
			List<Carrier_Order__c> list_CarrierOrders = [
				SELECT Id, Name, Implementation_Stage__c, Stage_Detail__c, Order_Type__c, Carrier__c, Effective_Date__c, Submission_Completion_Notes__c
				FROM Carrier_Order__c
				WHERE id = :carrierOrderId
			];

			if (!list_CarrierOrders.isEmpty()) {
				for (Carrier_Order__c objCo : list_CarrierOrders) {
					objCo.Submission_Completion_Notes__c = strSubmissionNotes;
					if (
						objCo.Implementation_Stage__c != CarrierOrderUtil.CO_STATUS_APPROVED ||
						objCo.Implementation_Stage__c != CarrierOrderUtil.STAGE_CANCELLED ||
						objCo.Implementation_Stage__c != BenefitOrderUtil.STATUS_CLOSED_LOST ||
						objCo.Implementation_Stage__c != CarrierOrderUtil.STAGE_CLOSED_ADMIN
					) {
						objCo.Implementation_Stage__c = CarrierOrderUtil.CO_STATUS_READY_FOR_CONFIRMATION;
					}
				}
				OnboardingPlayModeUtility.setFirstPlayDateForCarrierOrders(TicketUtil.STR_ORDER, list_CarrierOrders);
			}

			Map<Id, Carrier_Order__c> map_CarrierOrderToBeUpdated = new Map<Id, Carrier_Order__c>();
			if (list_CarrierOrders != null && list_CarrierOrders.size() > 0) {
				for (Carrier_Order__c objCO : list_CarrierOrders) {
					map_CarrierOrderToBeUpdated.put(objCO.Id, objCO);
				}
				List<Carrier_Order__c> list_ChildCarrierOrder = getChildCarrierOrderStatus(carrierOrderId);
				if (!list_ChildCarrierOrder.isEmpty()) {
					for (Carrier_Order__c objChildCO : list_ChildCarrierOrder) {
						map_CarrierOrderToBeUpdated.put(objChildCO.Id, objChildCO);
					}
				}
				if (!map_CarrierOrderToBeUpdated.isEmpty()) {
					update map_CarrierOrderToBeUpdated.values();
				}
			}
			return true;
		} catch (exception ex) {
			throw new AuraHandledException(ex.getMessage());
		}
	}

	/**
	 * @author      Deepika Saini
	 * @description This method used to Update Implemetation Stage to Ready For Confirmation of Child Records
	 * @param       Id - Id of Parent Carrier Order
	 * @return      List of CO
	 */
	public static List<Carrier_Order__c> getChildCarrierOrderStatus(Id parentCarrierId) {
		List<Carrier_Order__c> list_ChildCarrierOrders = new List<Carrier_Order__c>();
		for (Carrier_Order__c co : [SELECT id, name FROM Carrier_Order__c WHERE Parent_Carrier_Order__c = :parentCarrierId]) {
			co.Implementation_Stage__c = CarrierOrderUtil.CO_STATUS_READY_FOR_CONFIRMATION;
			list_ChildCarrierOrders.add(co);
		}
		return list_ChildCarrierOrders;
	}

	@AuraEnabled
	public static List<Carrier_Order__c> getCarrierOrderRecord(Id idCarrierOrder){
		return [SELECT Id, Submission_Completion_Notes__c, Implementation_Stage__c, OwnerId, Confirmation_Owner__c FROM Carrier_Order__c WHERE Id = :idCarrierOrder];
	}
}