force-app/main/default/objects/HI_Benefits_Signatory__c/HI_Benefits_Signatory__c.object-meta.xml
<CustomObject>
    <label>HI Benefits Signatory</label>
    <nameField>
        <displayFormat>Benefits-Signatory-{0000000000}</displayFormat>
        <label>Hi Benefits Signatorie Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hi Benefits Signatories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HI_Benefits_Signatory__c/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <label>ZP User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HIBenefitSignatoryQueueTest.cls
@isTest
public class HIBenefitSignatoryQueueTest {

    @isTest
    static void processSignatoryInfo() {
        HIBenefitSignatoryTriggerHelper.queue=false;
        HI_Benefits_Signatory__c signatory = new HI_Benefits_Signatory__c();
        signatory.Company_Id__c='werwerr';
        signatory.ZP_User_Id__c='';
        insert signatory;
        
        List<HI_Benefits_Signatory__c> signatoryList = new List<HI_Benefits_Signatory__c>();
        signatoryList.add(signatory);
        HIBenefitSignatoryQueue updateJob = new HIBenefitSignatoryQueue(signatoryList);
            ID jobID = System.enqueueJob(updateJob);
        
        signatory=[Select Id, Processing_State__c from HI_Benefits_Signatory__c where Id=:signatory.Id];
        system.assertEquals(IntegrationUtils.QUEUED_STATE, signatory.Processing_State__c);
    }    
}