force-app/main/default/objects/AI_Interaction_Detail__c/AI_Interaction_Detail__c.object-meta.xml
<CustomObject>
    <description>Object captures interaction with AI.
Data provided, related case, response received, if any errors.</description>
    <label>AI Interaction Detail</label>
    <nameField>
        <displayFormat>AID-{00000000}</displayFormat>
        <label>AI Interaction Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AI Interaction Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Agent_Feedback__c.field-meta.xml
<CustomField>
    <fullName>Agent_Feedback__c</fullName>
    <description>It will used to store agent feedback for the interaction with the captain</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Agent Feedback</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to link AI Interaction details with chat transcript to display chat history.</description>
    <label>Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>AI Interaction Details</relationshipLabel>
    <relationshipName>AI_Interaction_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Interaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Id__c</fullName>
    <description>Captures unique interaction Id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Interaction Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Interaction_Rating__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Rating__c</fullName>
    <description>It will used to store agent rating for the interaction with the captain</description>
    <label>Interaction Rating</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>10</fullName>
                <isActive>false</isActive>
                <label>10</label>
            </value>
            <value>
                <fullName>6</fullName>
                <isActive>false</isActive>
                <label>6</label>
            </value>
            <value>
                <fullName>7</fullName>
                <isActive>false</isActive>
                <label>7</label>
            </value>
            <value>
                <fullName>8</fullName>
                <isActive>false</isActive>
                <label>8</label>
            </value>
            <value>
                <fullName>9</fullName>
                <isActive>false</isActive>
                <label>9</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Chat Type For Different Chat Component</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CX Co-Pilot</fullName>
            </value>
            <value>
                <fullName>Benefits Co-Pilot</fullName>
            </value>
            <value>
                <fullName>Case Completion</fullName>
            </value>
            <value>
                <fullName>Dingo AI CX Co-Pilot</fullName>
            </value>
            <value>
                <fullName>Co-Pilot Load</fullName>
            </value>
            <value>
                <fullName>Agent Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChimaAISupportAuraCtrl.cls
/**
 * @name         : ChimaAISupportAuraCtrl
 * @author       : Yogesh Kherajani
 * @date         : 24/04/2024
 * @description  : Controller class for Chima AI to link chat transcript record with interaction records
 * @see 		 : ChimaAISupportAuraCtrlTest
 **/
public without sharing class ChimaAISupportAuraCtrl {
	private static final String AGENT_FEEDBACK = 'Agent Feedback';

	/**
	 * @Author      : Yogesh Kherajani
	 * @Description : Link chat transcript record with interaction records
	 * @param       : strCaseRecId - Case Record Id
	 * @param		: lst_AIInteractionDetailIds - List AI Interaction Ids
	 **/
	@AuraEnabled
	public static void handleUpdateLiveChatTranscriptOnAIInteraction(String strChatKey, List<String> lst_AIInteractionDetailIds) {
		try {
			LiveChatTranscript objLiveChatTranscript = [SELECT Id FROM LiveChatTranscript WHERE ChatKey = :strChatKey];

			List<AI_Interaction_Detail__c> lst_AIInteractionDetail = new List<AI_Interaction_Detail__c>();

			for (String strAIInteractionDetailId : lst_AIInteractionDetailIds) {
				AI_Interaction_Detail__c objAIInteractionDetail = new AI_Interaction_Detail__c();
				objAIInteractionDetail.Id = strAIInteractionDetailId;
				objAIInteractionDetail.Chat_Transcript__c = objLiveChatTranscript.Id;

				lst_AIInteractionDetail.add(objAIInteractionDetail);
			}

			if (!lst_AIInteractionDetail.isEmpty()) {
				update lst_AIInteractionDetail;
			}
		} catch (Exception objException) {
			ExceptionLogUtil.logException('ChimaAISupportAuraCtrl', 'handleUpdateLiveChatTranscriptOnAIInteraction', objException);
			throw new AuraHandledException(objException.getMessage());
		}
	}

	/**
	 * @Author      : Yogesh Kherajani
	 * @Description : Create AI Interaction detail for agent feedback for interaction with captain
	 * @param       : strChatKey - Live agent session key
	 * @param		: strFeedback - feedback provided by agent for interaction with captain
	 * @param		: strInteractionRating - rating provide by agent for interaction with captain
	 **/
	@AuraEnabled
	public static void updateAgentFeedback(String strChatKey, String strFeedback, String strInteractionRating) {
		//Get the LiveChatTranscript Id for the specific chatkey
		List<LiveChatTranscript> lst_LiveChatTranscript = [SELECT Id FROM LiveChatTranscript WHERE ChatKey = :strChatKey];

		if (!lst_LiveChatTranscript.isEmpty()) {
			try {
				//Create AI Interaction Record
				AI_Interaction_Detail__c objAIInteractionDetail = new AI_Interaction_Detail__c();
				objAIInteractionDetail.Interaction_Id__c = 'conversationid' + Datetime.now().getTime();
				objAIInteractionDetail.Type__c = AGENT_FEEDBACK;
				objAIInteractionDetail.Interaction_Rating__c = strInteractionRating;
				objAIInteractionDetail.Agent_Feedback__c = strFeedback;
				objAIInteractionDetail.Chat_Transcript__c = lst_LiveChatTranscript[0].Id;

				insert objAIInteractionDetail;
			} catch (Exception objException) {
				ExceptionLogUtil.logException('ChimaAISupportAuraCtrl', 'updateAgentFeedback', objException);
				throw new AuraHandledException(objException.getMessage());
			}
		}
	}

	/**
	 * @Author      : Yogesh Kherajani
	 * @Description : Get live chat transcript details
	 * @param       : strChatKey - Live agent session key
	 **/
	@AuraEnabled
	public static List<LiveChatTranscript> getLiveChatTranscriptDetail(String strChatKey) {
		//Get the LiveChatTranscript Id for the specific chatkey
		return [SELECT Id, Owner.Name FROM LiveChatTranscript WHERE ChatKey = :strChatKey];
	}
}