unpackaged/main/default/objects/Account/fields/Account_Route_Count__c.field-meta.xml
<CustomField>
    <fullName>Account_Route_Count__c</fullName>
    <description>Used for RingLead Routing. Incremented by 1 every time account is sent to RingLead for routing.</description>
    <label>Account Route Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>true</active>
    <description>Used to identify entities that help sell Gusto to other companies or their own clients. Generally associated with the Accountants segment, though not all Resellers are truly Accountants/CPAs</description>
    <label>Reseller</label>
</RecordType>

force-app/main/default/objects/RingLead_Routing_Credentials__c/RingLead_Routing_Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting used to store endpoint, api token related to RingLead</description>
    <label>RingLead Routing Credentials</label>
</CustomObject>

force-app/main/default/objects/RingLead_Routing_Credentials__c/fields/API_Token__c.field-meta.xml
<CustomField>
    <fullName>API_Token__c</fullName>
    <description>Workato Integration API Token</description>
    <label>API Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RingLead_Routing_Credentials__c/fields/Send_Account_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Send_Account_Endpoint__c</fullName>
    <description>Endpoint for sending accounts from Salesforce to RingLead via Workato</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Send Account Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendAccountToRingLeadTest.cls
/**
 * @description  Test sending account to RingLead
 * @author       Praveen Sethu
 * @date         11-11-2022
 **/
@isTest
public with sharing class SendAccountToRingLeadTest {
	/**
	 * @description Test sending account to RingLead
	 * @author      Praveen Sethu
	 **/
	@isTest
	static void testSendLeadToRingLead() {
		RingLead_Routing_Credentials__c objCredential = new RingLead_Routing_Credentials__c(Send_Account_Endpoint__c = 'https://ringlead.sendaccount.com/send', API_Token__c = 'api-token');
		insert objCredential;

		AccountTriggerHelper.skipTrigger = true;
		// Set mock callout class
		Test.setMock(HttpCalloutMock.class, new RingLeadMockResponseTest());

		Account objAccount = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.RESELLER_ACCOUNT_RT_ID).setName('Test Reseller Account 1').build();
		insert objAccount;

		Test.startTest();
		SendAccountToRingLead.sendAccountToRingLead(new List<SendAccountToRingLead.RequestWrapper>{ new SendAccountToRingLead.RequestWrapper(objAccount.Id) });
		Test.stopTest();

		// assert if account route count is updated
		Account objAccAssert = [SELECT Id, Account_Route_Count__c FROM Account WHERE Id = :objAccount.Id];
		System.assertEquals(2, objAccAssert.Account_Route_Count__c);
	}
}