unpackaged/main/default/objects/Account/fields/AM_Tier__c.field-meta.xml
<CustomField>
    <fullName>AM_Tier__c</fullName>
    <label>Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Starter</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll_Product_Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/HIGroupEvent__c.object-meta.xml
<CustomObject>
    <description>HI event table to handle all order/TTQ related events,</description>
    <label>HIGroupEvent</label>
    <nameField>
        <label>HIGroupEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HIGroupEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HIGroupEvent__c/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <description>Will contain application/Carrier Id, present in the json</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Application Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Source_ID__c,&quot;hawaiian_ice-renewal-&quot;, &quot;&quot;) ,&quot;hawaiian_ice-new_plans_application-&quot;, &quot;&quot;),&quot;hawaiian_ice-commuter_benefit-&quot;, &quot;&quot;),&quot;hawaiian_ice-benefit_change_application-&quot;,&quot;&quot;),&quot;hawaiian_ice-account_benefit_interest-&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Benefits_Current_Setup_Step__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Current_Setup_Step__c</fullName>
    <label>Benefits Current Setup Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Selecting Benefits</fullName>
            </value>
            <value>
                <fullName>Selecting Carriers</fullName>
            </value>
            <value>
                <fullName>Answering Additional Questions</fullName>
            </value>
            <value>
                <fullName>Signing Forms</fullName>
            </value>
            <value>
                <fullName>Forms Signed</fullName>
            </value>
            <value>
                <fullName>Selecting Employee Eligibility</fullName>
            </value>
            <value>
                <fullName>Receiving Medical Education</fullName>
            </value>
            <value>
                <fullName>Selecting Base Tier</fullName>
            </value>
            <value>
                <fullName>Selecting Base Plan</fullName>
            </value>
            <value>
                <fullName>Selecting Complementary Plans</fullName>
            </value>
            <value>
                <fullName>Selecting Non-Medical Plans</fullName>
            </value>
            <value>
                <fullName>Collecting Company Information</fullName>
            </value>
            <value>
                <fullName>Answering Survey</fullName>
            </value>
            <value>
                <fullName>Entering Flow</fullName>
            </value>
            <value>
                <fullName>ER Completed Survey</fullName>
            </value>
            <value>
                <fullName>Choosing Plans</fullName>
            </value>
            <value>
                <fullName>Confirming Plans</fullName>
            </value>
            <value>
                <fullName>Awaiting Offerings</fullName>
            </value>
            <value>
                <fullName>Awaiting Education</fullName>
            </value>
            <value>
                <fullName>Receiving Education</fullName>
            </value>
            <value>
                <fullName>Review Current Plans</fullName>
            </value>
            <value>
                <fullName>Selecting Offerings</fullName>
            </value>
            <value>
                <fullName>Reviewing Summary</fullName>
            </value>
            <value>
                <fullName>Verifying Eligibility</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HI_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>HI_Effective_Date__c</fullName>
    <description>The requested coverage effective date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <description>Payroll tier from account</description>
    <formula>TEXT(Account.Tier__c)</formula>
    <inlineHelpText>Payroll tier from account</inlineHelpText>
    <label>Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/State__c/fields/Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>Abbreviation__c</fullName>
    <description>Two letter state abbreviation.</description>
    <label>Abbreviation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique state abbreviation used for external lookups and relationships.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HI State Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tier_Config__c/Tier_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration used to store names of old tiers and plans</description>
    <label>Tier Config</label>
</CustomObject>

force-app/main/default/objects/Tier_Config__c/fields/New_Tier_1__c.field-meta.xml
<CustomField>
    <fullName>New_Tier_1__c</fullName>
    <description>Name of the new Tier - Typically it is called Simple</description>
    <label>New Tier 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Payroll_Product_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Core</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge</fullName>
    </customValue>
    <customValue>
        <fullName>Select</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy Premium</fullName>
    </customValue>
    <customValue>
        <fullName>contractor_only</fullName>
        <label>Contractor Only</label>
    </customValue>
    <customValue>
        <fullName>Simple</fullName>
    </customValue>
    <customValue>
        <fullName>Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Premium CRB</fullName>
    </customValue>
    <customValue>
        <fullName>Premium Multi-EIN</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>basic</fullName>
        <isActive>false</isActive>
        <label>basic</label>
    </customValue>
    <description>The tiers of our main payroll product, which defines the Account customer tier</description>
    <masterLabel>Payroll Product Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HIGroupEventRenewalAlternateRequestTest.cls
/**
 * @name         HIGroupEventRenewalAlternateRequestTest
 * @author       Bhagat Singh
 * @date         23 July 2021
 * @description  Test class for HIGroupEventRenewalAlternateRequest class.
 **/
@isTest
private class HIGroupEventRenewalAlternateRequestTest {
	/**
	 * @Author      : Bhagat Singh
	 * @Description : Test Class setup method
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	@testSetup
	static void setupData() {
		skipTrigger(true);
		// insert org default tier config settings
		Tier_Config__c objTierConfig = new TestDataFactory.TierConfigBuilder().build();
		insert objTierConfig;

		State__c objState = new State__c(Name = 'California', Abbreviation__c = 'CA', Key__c = 'CA');
		insert objState;

		Opportunity objOpp = TestUtility.BenefitsRenewalOpportunity();
		Account objAcc = new Account(
			Id = objOpp.AccountId,
			ZP_Company_Id__c = '72239',
			Tier__c = objTierConfig.New_Tier_1__c,
			AM_Tier__c = 'Gold',
			ShippingState = 'California',
			BillingState = 'California'
		);
		update objAcc;

		objOpp.Source_ID__c = 'hawaiian_ice-new_plans_application-11001';
		objOpp.HI_Effective_Date__c = System.today().addDays(2);
		objOpp.Benefits_Current_Setup_Step__c = 'Completed';
		update objOpp;

		skipTrigger(false);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Test renewal_alternates_requested : Negative case - Opportunity record not found
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesOpportunityRecordNotFound() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Application_Id__c = '11001',
			Company_Id__c = '72240',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued',
			Event_Info__c = '{"event_id":11001,"company_id":72240,"application_id":11001,"alternate_packages_requested_timestamp":"1637901413","event_type":"renewal_alternates_requested"}'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.RENEWAL_DEAD_UNPROCESSED_EVENT);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Test renewal_alternates_requested : Postive case - update opportunity stage
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void testUpdateOpportunityStage() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Application_Id__c = '11001',
			Company_Id__c = '72239',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued',
			Event_Info__c = '{"event_id":11001,"company_id":72239,"application_id":11001,"alternate_packages_requested_timestamp":"1637901413","event_type":"renewal_alternates_requested"}'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Id, StageName FROM Opportunity WHERE Application_Id__c = '11001' AND Account.ZP_Company_Id__c = '72239'].StageName == HIGroupEventRenewalAlternateRequest.OPP_STAGE_NAME);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Validate : Event Info required field
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoEventInfo() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_EVENT_INFO_MISSING);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Validate : Application Id required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoApplicationId() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued',
			Event_Info__c = '{"event_id":11001,"company_id":72239,"application_id":"","alternate_packages_requested_timestamp":"1637901413","event_type":"renewal_alternates_requested"}'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_APPLICATION_ID_MISSING);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Validate : Company Id required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoCompanyId() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued',
			Event_Info__c = '{"event_id":11001,"company_id":"","application_id":11001,"alternate_packages_requested_timestamp":"1637901413","event_type":"renewal_alternates_requested"}',
			Application_Id__c = '11001'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_COMPANY_ID_MISSING);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Validate : alternate_packages_requested_timestamp required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationRequestDate() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
			Name = 'renewal_alternates_requested',
			Event_Id__c = '11001',
			Event_Type__c = 'renewal_alternates_requested',
			Processing_State__c = 'Queued',
			Event_Info__c = '{"event_id":11001,"company_id":"72239","application_id":11001,"alternate_packages_requested_timestamp":"","event_type":"renewal_alternates_requested"}',
			Application_Id__c = '11001',
			Company_Id__c = '72239'
		);
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_ALTERNATE_REQ_DATE);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Validate : ErrorLog created, if any exception occured.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidateErrorLogs() {
		Test.startTest();
		try {
			HIGroupEvent__c objHIGroupEvent = new HIGroupEvent__c(
				Name = 'renewal_alternates_requested',
				Event_Id__c = '11001',
				Processing_State__c = 'Blank',
				Event_Info__c = '{"event_id":11001,"company_id":"72239","application_id":11001,"alternate_packages_requested_timestamp":"1637901413","event_type":"renewal_alternates_requested"}'
			);

			insert objHIGroupEvent;
		} catch (Exception objExp) {
			HIGroupEventRenewalAlternateRequest.createErrorLog(objExp);
		}

		Test.stopTest();

		List<Exception_Log__c> list_ErrorLogs = [SELECT Id FROM Exception_Log__c WHERE Class_Name__c = 'HIGroupEventRenewalAlternateRequest'];
		System.assert(list_ErrorLogs.size() > 0);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Skip Trigger, which is not required for this functionality
	 * @Parm        : Boolean
	 * @Return      : N/A
	 **/
	public static void skipTrigger(Boolean blnFlag) {
		OpportunityTriggerHelper.skipTrigger = blnFlag;
		AccountTriggerHelper.skipTrigger = blnFlag;
	}
}