unpackaged/main/default/objects/Account/fields/AM_Tier__c.field-meta.xml
<CustomField>
    <fullName>AM_Tier__c</fullName>
    <label>Partner Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Starter</fullName>
            </value>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Silver</fullName>
            </value>
            <value>
                <fullName>Gold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll_Product_Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Benefit_Order__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <formula>TEXT(Account__r.Tier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tier</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Transition_to_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Transition_to_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transition to Fulfillment</label>
    <referenceTo>Transition_to_Fulfillment__c</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <formula>Opportunity__r.Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HI Carrier Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Benefit_Order__r.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <description>Contact Tier</description>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Big Desk</fullName>
            </value>
            <value>
                <fullName>Emerging</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Contacts associated with Carriers</description>
    <label>Carrier</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Benefits_Current_Setup_Step__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Current_Setup_Step__c</fullName>
    <label>Benefits Current Setup Step</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Selecting Benefits</fullName>
            </value>
            <value>
                <fullName>Selecting Carriers</fullName>
            </value>
            <value>
                <fullName>Answering Additional Questions</fullName>
            </value>
            <value>
                <fullName>Signing Forms</fullName>
            </value>
            <value>
                <fullName>Forms Signed</fullName>
            </value>
            <value>
                <fullName>Selecting Employee Eligibility</fullName>
            </value>
            <value>
                <fullName>Receiving Medical Education</fullName>
            </value>
            <value>
                <fullName>Selecting Base Tier</fullName>
            </value>
            <value>
                <fullName>Selecting Base Plan</fullName>
            </value>
            <value>
                <fullName>Selecting Complementary Plans</fullName>
            </value>
            <value>
                <fullName>Selecting Non-Medical Plans</fullName>
            </value>
            <value>
                <fullName>Collecting Company Information</fullName>
            </value>
            <value>
                <fullName>Answering Survey</fullName>
            </value>
            <value>
                <fullName>Entering Flow</fullName>
            </value>
            <value>
                <fullName>ER Completed Survey</fullName>
            </value>
            <value>
                <fullName>Choosing Plans</fullName>
            </value>
            <value>
                <fullName>Confirming Plans</fullName>
            </value>
            <value>
                <fullName>Awaiting Offerings</fullName>
            </value>
            <value>
                <fullName>Awaiting Education</fullName>
            </value>
            <value>
                <fullName>Receiving Education</fullName>
            </value>
            <value>
                <fullName>Review Current Plans</fullName>
            </value>
            <value>
                <fullName>Selecting Offerings</fullName>
            </value>
            <value>
                <fullName>Reviewing Summary</fullName>
            </value>
            <value>
                <fullName>Verifying Eligibility</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/HI_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>HI_Effective_Date__c</fullName>
    <description>The requested coverage effective date.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ZenPayroll or Hawaiian Ice External Id
Prefixed with model name for uniqueness.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <description>Payroll tier from account</description>
    <formula>TEXT(Account.Tier__c)</formula>
    <inlineHelpText>Payroll tier from account</inlineHelpText>
    <label>Tier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ID of company migration record in Zen Payroll</description>
    <externalId>true</externalId>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>Tier 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Transition_to_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Transition_to_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transition to Fulfillment</label>
    <referenceTo>Transition_to_Fulfillment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Zp_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Zp_Company_ID__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <label>Zp Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>false</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>A benefits Policy</description>
    <label>Policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tier_Config__c/Tier_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration used to store names of old tiers and plans</description>
    <label>Tier Config</label>
</CustomObject>

force-app/main/default/objects/Tier_Config__c/fields/New_Tier_1__c.field-meta.xml
<CustomField>
    <fullName>New_Tier_1__c</fullName>
    <description>Name of the new Tier - Typically it is called Simple</description>
    <label>New Tier 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Payroll_Product_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Core</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge</fullName>
    </customValue>
    <customValue>
        <fullName>Select</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy Premium</fullName>
    </customValue>
    <customValue>
        <fullName>contractor_only</fullName>
        <label>Contractor Only</label>
    </customValue>
    <customValue>
        <fullName>Simple</fullName>
    </customValue>
    <customValue>
        <fullName>Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Premium CRB</fullName>
    </customValue>
    <customValue>
        <fullName>Premium Multi-EIN</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>basic</fullName>
        <isActive>false</isActive>
        <label>basic</label>
    </customValue>
    <description>The tiers of our main payroll product, which defines the Account customer tier</description>
    <masterLabel>Payroll Product Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HIGroupEventTTSNotePostOEEmailTest.cls
/**
 * @name         HIGroupEventTTSNotePostOEEmailTest
 * @author       Deepika Saini
 * @date         10-07-2021
 * @description  Test class for HIGroupEventTTSNotePostOEEmail class.
 **/
@isTest
private class HIGroupEventTTSNotePostOEEmailTest {
	public final static Id SUBMISSION_NEW_PLAN_TTF_RT_ID = Cache.getRecordTypeId('Transition_To_Fulfillment__c', 'Submission New Plan');
	/**
	 * @Author      : Deepika Saini
	 * @Description : Test Class setup method
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	@testSetup
	static void setupData() {
		Utils.skipTrigger(true);

		// insert org default tier config settings
		Tier_Config__c objTierConfig = new TestDataFactory.TierConfigBuilder().build();
		insert objTierConfig;
		
		skipTrigger(true);
		Opportunity objOpp = TestUtility.BenefitsNewPlanOpportunity();

		Account objAcc = new Account(
			Id = objOpp.AccountId,
			ZP_Company_Id__c = '72239',
			Tier__c = objTierConfig.New_Tier_1__c,
			AM_Tier__c = 'Gold',
			ShippingState = 'California',
			BillingState = 'California'
		);
		update objAcc;

		objOpp.Source_ID__c = 'hawaiian_ice-new_plans_application-11001';
		objOpp.HI_Effective_Date__c = System.today().addDays(5);
		objOpp.Benefits_Current_Setup_Step__c = 'Verifying Eligibility';
		update objOpp;

		Benefit_Order__c objBO = TestUtility.createTestBenefitOrder('New Plan', objOpp.Id, 'Test BO ', false);
		objBO.Account__c = objOpp.AccountId;
		objBO.Status_Detail__c = 'STATUS DETAIL';
		objBO.Coverage_Effective_Date__c = Date.today().addDays(5);
		insert objBO;

		Contact objContact = new TestDataFactory.ContactBuilder()
			.setRecordTypeId('Company')
			.setAccountId(objAcc.Id)
			.setFirstName('Test')
			.setLastName('User01')
			.setEmail('testuser01@gusto.com')
			.setZPUserId('75001')
			.build();
		insert objContact;

		Carrier__c objCarrier = TestUtility.Carrier();
		objCarrier.Carrier_Id__c = '8';
		objCarrier.Id__c = '2';
        update objCarrier;

		Carrier_Order__c objCO = (Carrier_Order__c) Carrier_Order__c.SObjectType.newSObject();
		objCO.Name = 'TEST CARRIER ORDER';
		objCO.Carrier__c = objCarrier.Id;
		objCO.Benefit_Order__c = objBO.Id;
		objCO.Order_Type__c = 'Same Carrier, NO Plan/Group Level Changes';
		objCO.Order_Assignment__c = 'Same Carrier, NO Plan/Group Level Changes';
		objCO.Member_Submission_Date__c = Date.today().addDays(25);
		objCO.Group_Number__c = '120022';
		insert objCO;

		Policy__c objPolicy = TestUtility.createTestPolicy(objOpp.Id, objCarrier.Id, true, 'Test Policy 1', objCO.Id, false);
		objPolicy.Benefit_Type__c = 'Vision';
		insert objPolicy;

		Case objCase = TestUtility.createCustomerCase(objOpp.Id, objBO.Id, objAcc.Id, objContact.Id, 'Benefits New Plan Case');
		insert objCase;

		List<Contact> list_Contact = new List<Contact>();
		list_Contact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId('Company')
				.setAccountId(objAcc.Id)
				.setFirstName('User 1')
				.setLastName('My')
				.setEmail('mycaseuser1@gusto.com')
				.setZPUserId('75101')
				.build()
		);
		list_Contact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId('Company')
				.setAccountId(objAcc.Id)
				.setFirstName('User 2')
				.setLastName('My')
				.setEmail('mycaseuser2@gusto.com')
				.setZPUserId('75102')
				.build()
		);
		list_Contact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId('Company')
				.setAccountId(objAcc.Id)
				.setFirstName('User 3')
				.setLastName('My')
				.setEmail('mycaseuser3@gusto.com')
				.setZPUserId('75103')
				.build()
		);
		insert list_Contact;

		List<CaseTeamRole> list_CaseTeamRoles = [SELECT Id FROM CaseTeamRole WHERE Name = 'Customer Contact'];
		Id idCaseTeamRole = null;
		if (list_CaseTeamRoles != null && list_CaseTeamRoles.size() > 0) {
			idCaseTeamRole = list_CaseTeamRoles[0].Id;
		}

		Id idNewPlan = Cache.getRecordTypeId('Case', 'Benefits New Plan Case');
		List<CaseTeamMember> list_CaseTeams = new List<CaseTeamMember>();
		list_CaseTeams.add(new CaseTeamMember(MemberId = list_Contact[0].Id, ParentId = objCase.Id, TeamRoleId = idCaseTeamRole));
		list_CaseTeams.add(new CaseTeamMember(MemberId = list_Contact[1].Id, ParentId = objCase.Id, TeamRoleId = idCaseTeamRole));
		list_CaseTeams.add(new CaseTeamMember(MemberId = list_Contact[2].Id, ParentId = objCase.Id, TeamRoleId = idCaseTeamRole));
		insert list_CaseTeams;

		List<Email_Macro__c> list_EmailMacro = new List<Email_Macro__c>();
		list_EmailMacro.add(new TestDataFactory.EmailMacroBuilder().setMacroIdentifier('OE_EMAIL_GHOST_PLAN').setBody('[Ghost Plan Removed] only allows companies to offer the plans that employees chose during open enrollment. No one on your team enrolled in the [Plan Name] plan, so this will be removed from your company\'s offerings for this policy year. You can choose to add this plan again during your renewal next year.').build());
		insert list_EmailMacro;

		Utils.skipTrigger(false);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Positive Case
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventPositiveCase() {
		skipTrigger(true);
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo('{"event_id":"11001","company_id":"72239","application_id":"11001","application_type":"New Plan"}')
			.setApplicationId('11001')
			.setApplicationType('New Plan')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();
		if(OrganizationUtilities.canSendEmails()){
			List<EmailMessage> list_EmailMessage = [SELECT Id, CcAddress, HtmlBody FROM EmailMessage WHERE Email_Template_Name__c = :HIGroupEventTTSNotePostOEEmail.NEWPLAN_EMAIL_TEMPLATE];
			System.assert(list_EmailMessage.size() > 0);
			String strCCAddress = list_EmailMessage[0].CcAddress;
			System.assert(strCCAddress.contains('mycaseuser1@gusto.com'));
			System.assert(strCCAddress.contains('mycaseuser2@gusto.com'));
			System.assert(strCCAddress.contains('mycaseuser3@gusto.com'));
			Id idAutomationQueue = GlobalQueryHelper.getQueueIdByName('Automation Queue');
		}
		List<Carrier_Order__c> list_COs = [SELECT Id, OwnerId FROM Carrier_Order__c WHERE Carrier__r.Carrier_Id__c = '8'];
		System.assert(list_COs.size() > 0);
		//System.assert(list_COs[0].OwnerId == idAutomationQueue);
		skipTrigger(false);
	}

	/**
	 * @Author      : Bhagat Singh
	 * @Description : Ghost Plan Positive Case
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventGhostPlanPositiveCase() {
		skipTrigger(true);
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo(
				'{"event_id":"11001","company_id":"72239","application_id":"11001","application_type":"New Plan","ghost_plans":[{"carrier_name":"Guardian","plan_details":["Guardian plan 1","Guardian plan 2"]},{"carrier_name":"UnitedHealthcare","plan_details":["UH plan 1","UH plan 2"]}]}'
			)
			.setApplicationId('11001')
			.setApplicationType('New Plan')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Id, RecordTypeId FROM Transition_To_Fulfillment__c].RecordTypeId == SUBMISSION_NEW_PLAN_TTF_RT_ID);
		if(OrganizationUtilities.canSendEmails()) {
			List<EmailMessage> list_EmailMessage = [SELECT Id, CcAddress, HtmlBody FROM EmailMessage WHERE Email_Template_Name__c = :HIGroupEventTTSNotePostOEEmail.NEWPLAN_EMAIL_TEMPLATE];
			System.assert(list_EmailMessage.size() > 0);
			String strEmailBody = list_EmailMessage[0].HtmlBody;
			System.assert(strEmailBody.contains('Guardian, UnitedHealthcare'));
		}
		skipTrigger(false);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Validate : Event Info required field
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoEventInfo() {
		Test.startTest();

		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_EVENT_INFO_MISSING);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Validate : Application Id required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoApplicationId() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo('{"event_id":"11001","company_id":"","application_id":"","application_type":""}')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_APPLICATION_ID_MISSING);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Validate : Application Type required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoApplicationType() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo('{"event_id":"11001","company_id":"","application_id":"","application_type":""}')
			.setApplicationId('11001')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_APPLICATION_TYPE_MISSING);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Validate : Company Id required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventValidationNoCompanyId() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo('{"event_id":"11001","company_id":"","application_id":"11001","application_type":"New Plan"}')
			.setApplicationId('11001')
			.setApplicationType('New Plan')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_COMPANY_ID_MISSING);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Validate : Application type is Invalid required field.
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	static testMethod void tesHIGroupEventInvalidApplicationType() {
		Test.startTest();
		HIGroupEvent__c objHIGroupEvent = new TestDataFactory.HIGroupEventBuilder()
			.setName('OE_post_email')
			.setEventId('11001')
			.setEventType(HIGroupEventUtil.EVENT_TYPE_TTS_NOTE_POST_OE_EMAIL)
			.setProcessingState('Queued')
			.setEventInfo('{"event_id":"11001","company_id":"12354","application_id":"11001","application_type":"Benefits BoR"}')
			.setApplicationId('11001')
			.setApplicationType('Benefits BoR')
			.build();
		insert objHIGroupEvent;

		Test.stopTest();

		System.assert([SELECT Message__c FROM HIGroupEvent__c WHERE Id = :objHIGroupEvent.Id].Message__c == HIGroupEventUtil.ERROR_APPLICATION_TYPE_INVALID);
	}

	/**
	 * @Author      : David (Dato) Tsamalashvili
	 * @Description : Skip Trigger, which is not required for this functionality
	 * @Parm        : Boolean
	 * @Return      : N/A
	 **/
	public static void skipTrigger(Boolean blnFlag) {
		AccountTriggerHelper.skipTrigger = blnFlag;
		ContactTriggerHelper.skipTrigger = blnFlag;
		OpportunityTriggerHelper.skipTrigger = blnFlag;
		CaseTriggerHelper.skipTrigger = blnFlag;
		PolicyHelper.skipTrigger = blnFlag;
	}
}