unpackaged/main/default/objects/Account/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <inlineHelpText>All states with active employees or contractors.</inlineHelpText>
    <label>State(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Active_Employee_Count__c.field-meta.xml
<CustomField>
    <fullName>Active_Employee_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Active Employee Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_Entry_Assist__c.field-meta.xml
<CustomField>
    <fullName>Data_Entry_Assist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[User].Is_Migration_Specialist__c must be true.</description>
    <label>Facilitator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Specialist_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Deductions_List__c.field-meta.xml
<CustomField>
    <fullName>Deductions_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Deductions List</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Facilitator_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Due_Date__c</fullName>
    <label>Facilitator Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/First_Check_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Check_Date__c</fullName>
    <description>MIGRATION_ATTRIBUTES 
first_check_date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>First Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Advocate Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/States__c.field-meta.xml
<CustomField>
    <fullName>States__c</fullName>
    <label>States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/Order_Facilitator_Checklist__c.object-meta.xml
<CustomObject>
    <description>Checklists related to Order</description>
    <label>Order Facilitator Checklist</label>
    <nameField>
        <displayFormat>OFC{000000}</displayFormat>
        <label>Order Facilitator Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Facilitator Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Blocked_Username__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Username__c</fullName>
    <description>Username of the user who marked the checklist as Blocked</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Blocked Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Name__c</fullName>
    <description>Name of checklist, copied over fom BOR Master Checklist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To notate if a checklist is blocked.</description>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Checked__c.field-meta.xml
<CustomField>
    <fullName>Is_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Advocates has selected the checklist or not.</description>
    <label>Is Checked?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To mark if a checklist is completed</description>
    <label>Is Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Lookup to Order object to Identify which checklists apply to a particular order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Facilitator Checklists</relationshipLabel>
    <relationshipName>Order_Facilitator_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/State_Abbreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FeedCommentTriggerHelperTest.cls
/*****************************************************************************************************************************
 * Info : FeedCommentTriggerHelper is used to cover FeedCommentTriggerHelperTest
 *        which is related with 'Feed Comment', Order, User, Account and 'Order Facilitator Checklist' Object.
 *
 * Created by : Lirik on 10/22/2019
 ******************************************************************************************************************************/
@isTest
public class FeedCommentTriggerHelperTest {
	@isTest
	static void testCallOnfeedCommentTriggerHelper() {
		// insert accounts list
		List<Account> testAccountList = new List<Account>();
		List<Order> lstUpdateOrder = new List<Order>();
		Id companyRecordTypeId = Cache.getRecordTypeId('Account', 'Company');

		for (Integer i = 0; i < 2; i++) {
			Account ac = new TestDataFactory.AccountBuilder().setRecordTypeId(companyRecordTypeId).setName('TestAccount').build();
			testAccountList.add(ac);
		}

		AccounTTriggerHelper.SkipTrigger = true;
		insert testAccountList;

		// assert if accounts are inserted successfully
		for (Account acc : testAccountList) {
			System.assertNotEquals(null, acc.Id, 'Account Id should not be null.');
		}

		Order ord = new Order();
		ord.AccountId = testAccountList[0].Id;
		ord.OwnerId = System.UserInfo.getUserId();
		ord.Active_Employee_Count__c = 10;
		ord.EffectiveDate = System.today();
		ord.Status = 'Drafted';
		ord.States__c = 'HI; AK; CA; AZ; NM; OR; WA; CO; OH; PA; KY';
		ord.Deductions_List__c = 'Test,Test';
		ord.Data_Entry_Assist__c = System.UserInfo.getUserId();
		ord.Bulk_Migration__c = null;
		ord.RecordTypeId = cache.getRecordTypeId('Order', 'Company Migration');
		ord.First_Check_Date__c = System.now().date();
		ord.Facilitator_Due_Date__c = System.now().date();
		ord.Follow_Up_Date__c = System.now().date();
		lstUpdateOrder.add(ord);
		insert lstUpdateOrder;
		ord.OwnerId = System.UserInfo.getUserId();
		update ord;
		List<FeedComment> feeds = new List<FeedComment>();
		Map<ID, FeedComment> newFeedMap = new Map<ID, FeedComment>();

		Order_Facilitator_Checklist__c ordFaciCheck = new Order_Facilitator_Checklist__c(
			Blocked_Username__c = 'UnameTest',
			Checklist_Name__c = 'Test',
			Is_Blocked__c = false,
			Is_Checked__c = true,
			Is_Completed__c = true,
			Order__c = lstUpdateOrder[0].Id
		);
		OrderFacilitatorChecklistTriggerHelper.skipTrigger = true;
		insert ordFaciCheck;

		FeedItem feeItem = new FeedItem();
		feeItem.ParentId = ordFaciCheck.Id;
		feeItem.body = '@' + System.UserInfo.getFirstName() + ' ' + System.UserInfo.getLastName();
		FeedItemTriggerHelper.skipTrigger = true;
		insert feeItem;

		FeedComment feedCom = new FeedComment(
			createddate = System.Today(),
			FeedItemId = feeItem.Id,
			CommentType = 'TextComment',
			CommentBody = '@' + System.UserInfo.getFirstName() + ' ' + System.UserInfo.getLastName()
		);
		FeedCommentTriggerHelper.skipTrigger = true;
		insert feedCom;

		newFeedMap.put(feedCom.Id, feedCom);

		feedCom.CommentBody = System.UserInfo.getUserName();
		FeedCommentTriggerHelper.skipTrigger = true;
		update feedCom;

		newFeedMap.put(feedCom.Id, feedCom);

		delete feedCom;
		FeedCommentTriggerHelperTest feedCommentTrgr = new FeedCommentTriggerHelperTest();
	}
}