unpackaged/main/default/objects/Account/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Analytics_Time_Tracker__c/Analytics_Time_Tracker__c.object-meta.xml
<CustomObject>
    <description>To hold timestamp for different events on which reporting is to be done</description>
    <label>Analytics Time Tracker</label>
    <nameField>
        <displayFormat>ATT-{000000}</displayFormat>
        <label>Analytics Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analytics Time Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Analytics_Time_Tracker__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Tax Res Functionality</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Analytics Time Trackers</relationshipLabel>
    <relationshipName>Analytics_Time_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Analytics_Time_Tracker__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Analytics Time Trackers</relationshipLabel>
    <relationshipName>Analytics_Time_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analytics_Time_Tracker__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/BOR_Master_Checklist__c/BOR_Master_Checklist__c.object-meta.xml
<CustomObject>
    <label>BOR Master Checklist</label>
    <nameField>
        <displayFormat>MCL{000000}</displayFormat>
        <label>BOR Master Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MasterChecklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOR_Master_Checklist__c/fields/BOR_Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>BOR_Checklist_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>BOR Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOR_Master_Checklist__c/fields/BOR_Checklist_Status__c.field-meta.xml
<CustomField>
    <fullName>BOR_Checklist_Status__c</fullName>
    <label>BOR Checklist Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/BOR_Master_Checklist__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Order in which checklists are to be displayed</description>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/BOR_Master_Checklist__c/recordTypes/Payroll.recordType-meta.xml
<RecordType>
    <fullName>Payroll</fullName>
    <active>true</active>
    <description>Used for payroll transfer</description>
    <label>Payroll</label>
</RecordType>

force-app/main/default/objects/Bulk_Migration_Request__c/Bulk_Migration_Request__c.object-meta.xml
<CustomObject>
    <label>Bulk Migration Request</label>
    <nameField>
        <displayFormat>BMR-{0000}</displayFormat>
        <label>Bulk Migration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Migration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <description>This field is populated by the app to salesforce integration</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Blocked Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Name</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Blocked_Reason__c.field-meta.xml
<CustomField>
    <fullName>Blocked_Reason__c</fullName>
    <description>If &apos;Blocked Reason&apos; is populated, order will NOT be playable</description>
    <label>Blocked Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pausing this account for urgent 2FA access elsewhere</fullName>
            </value>
            <value>
                <fullName>Became unblocked on a higher priority order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Bulk_Migration__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_Entry_Assist__c.field-meta.xml
<CustomField>
    <fullName>Data_Entry_Assist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[User].Is_Migration_Specialist__c must be true.</description>
    <label>Facilitator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Specialist_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Facilitator_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Follow_Up_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Facilitator Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Facilitator_Follow_Up_Date_Reason__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Follow_Up_Date_Reason__c</fullName>
    <label>Facilitator Follow Up Date Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EPD JIRA</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Zp_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Zp_Company_ID__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <label>Zp Company ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/Order_Facilitator_Checklist__c.object-meta.xml
<CustomObject>
    <description>Checklists related to Order</description>
    <label>Order Facilitator Checklist</label>
    <nameField>
        <displayFormat>OFC{000000}</displayFormat>
        <label>Order Facilitator Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Facilitator Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Name__c</fullName>
    <description>Name of checklist, copied over fom BOR Master Checklist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To notate if a checklist is blocked.</description>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Checked__c.field-meta.xml
<CustomField>
    <fullName>Is_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Advocates has selected the checklist or not.</description>
    <label>Is Checked?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Is_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To mark if a checklist is completed</description>
    <label>Is Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Lookup to Order object to Identify which checklists apply to a particular order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Facilitator Checklists</relationshipLabel>
    <relationshipName>Order_Facilitator_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Order in which checklists are displayed</description>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateEditOrdFaciChkLstCtrlTest.cls
/*****************************************************************************************************************************
 * Info : CreateEditOrdersFacilitatorCheckListCtrl is used to cover CreateEditOrdFaciChkLstCtrlTest
 *        which is related with 'Feed Comment', Order, User, Account and 'Order Facilitator Checklist' Object.
 *
 * Created by : Lirik on 10/22/2019
 ******************************************************************************************************************************/
@isTest
public class CreateEditOrdFaciChkLstCtrlTest {
	@testSetup
	private static void setupTestData() {
		//Create a user who will be the facilitator
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Direct Sales User'];

		User objFacilitator = new TestDataFactory.UserBuilder()
			.setAlias('tuser')
			.setEmail('facilitator@testorg.com')
			.setFirstName('Test')
			.setLastName('User')
			.setProfileId(p.Id)
			.setUserName('facilitator@testorg.com')
			.setIsActive(true)
			.build();
		insert objFacilitator;

		//Insert Account
		Account account = new Account();
		account.RecordTypeId = Cache.getRecordTypeId('Account', 'Company');
		account.ZP_Company_Id__c = 'TestChkLst241019';
		account.Name = 'TestAccountChecklist';

		Account account1 = new Account();
		account1.RecordTypeId = Cache.getRecordTypeId('Account', 'Company');
		account1.ZP_Company_Id__c = 'TestChkLst241020';
		account1.Name = 'TestAccountChecklist';

		AccountTriggerHelper.skiptrigger = true;
		insert new List<Account>{ account, account1 };

		//Contact
		Contact objContact1 = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Contact', 'Company'))
			.setAccountId(account.Id)
			.setEmail('testAddress1@domain.com')
			.setFirstName('fName1')
			.setLastName('lName1')
			.build();
		insert objContact1;

		//Opportunity
		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Opportunity', 'Company Opportunity'))
			.setAccountId(account.Id)
			.setName('TestOppty1')
			.setCloseDate(Date.today())
			.setStage('New')
			.build();

		Opportunity objOpportunity1 = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Opportunity', 'Company Opportunity'))
			.setAccountId(account1.Id)
			.setName('TestOppty1')
			.setCloseDate(Date.today())
			.setStage('New')
			.build();

		OpportunityTriggerHelper.skiptrigger = true;
		insert new List<Opportunity>{ objOpportunity, objOpportunity1 };

		//Order
		
		
		Order objOrder = new TestDataFactory.OrderBuilder()
		.setRecordTypeId(Cache.getRecordTypeId('Order', 'Company Migration'))
		.setAccountId(account.Id)
		.setOpportunityId(objOpportunity.Id)
		.setDataEntryAssist(objFacilitator.Id)
		.setEffectiveDate(Date.today())
		.setStatus('Drafted')
		.build();

		Order objOrder1 = new TestDataFactory.OrderBuilder()
		.setRecordTypeId(Cache.getRecordTypeId('Order', 'Company Migration'))
		.setAccountId(account.Id)
		.setOpportunityId(objOpportunity.Id)
		.setDataEntryAssist(objFacilitator.Id)
		.setEffectiveDate(Date.today())
		.setStatus('Drafted')
		.build();

		OrderTriggerHelper.skipTrigger = true;
		insert new List<Order>{ objOrder, objOrder1 };

		//Case
		Case objCase = new Case(
			Subject = 'Test CAse',
			Order__c = objOrder.Id,
			RecordTypeId = Cache.getRecordTypeId('Case', 'Payroll Transfer Case'),
			ContactId = objContact1.Id
		);

		insert objCase;

		//insert BMR
		Bulk_Migration_Request__c objBMR = new Bulk_Migration_Request__c();
		insert objBMR;

		OrderTriggerHelper.SkipTrigger = true;
		objOrder.Case__c = objCase.Id;
		objOrder.Bulk_Migration__c = objBMR.Id;
		objOrder1.Bulk_Migration__c = objBMR.Id;
		update new List<Order>{ objOrder, objOrder1 };

		Id idBenefitsMasterChk = Cache.getRecordTypeId('BOR_Master_Checklist__c', 'Payroll');

		List<BOR_Master_Checklist__c> masterCheckList = new List<BOR_Master_Checklist__c>();
		BOR_Master_Checklist__c checkList1 = new BOR_Master_Checklist__c(RecordTypeId = idBenefitsMasterChk);
		checklist1.BOR_Checklist_Name__c = '* Added Employees';
		checklist1.Sequence__c = 1;
		checklist1.Mandatory__c = true;
		checklist1.BOR_Checklist_Status__c = 'Active';
		masterCheckList.add(checklist1);
		BOR_Master_Checklist__c checkList2 = new BOR_Master_Checklist__c(RecordTypeId = idBenefitsMasterChk);
		checklist2.BOR_Checklist_Name__c = '* Added Historical Payrolls + QA\'d';
		checklist2.Sequence__c = 2;
		checklist2.Mandatory__c = true;
		checklist2.BOR_Checklist_Status__c = 'Active';
		masterCheckList.add(checklist2);
		BOR_Master_Checklist__c checkList3 = new BOR_Master_Checklist__c(RecordTypeId = idBenefitsMasterChk);
		checklist3.BOR_Checklist_Name__c = 'Test CheckList3';
		checklist3.Sequence__c = 3;
		checklist3.Mandatory__c = true;
		checklist3.BOR_Checklist_Status__c = 'Active';
		masterCheckList.add(checklist3);
		insert masterCheckList;
	}

	@isTest
	private static void testSaveChecklistWithAssociatedOrder() {
		List<Order> lstOrder = [SELECT Id FROM Order WHERE RecordType.Name = 'Company Migration' LIMIT 1];
		Order objOrder = lstOrder != null ? lstOrder[0] : null;
		if (objOrder != null) {
			ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

			test.startTest();
			CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
			ctrl.saveChecklists();

			System.assert([SELECT COUNT() FROM Order_FAcilitator_Checklist__c WHERE Order__c = :objOrder.Id] > 0, 'Order count should be greater than 0.');
			test.stopTest();
		}
	}

	@isTest
	private static void testSaveChecklistWithoutOrder() {
		Order objOrder = new Order();

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
		ctrl.saveChecklists();

		System.assert([SELECT COUNT() FROM Order_FAcilitator_Checklist__c] == 0, 'Count should be 0.');
		test.stopTest();
	}

	@isTest
	private static void testSaveChecklistWithOrderIdAndFeed() {
		List<Order> lstOrder = [SELECT Id FROM Order WHERE RecordType.Name = 'Company Migration' LIMIT 1];
		Order objOrder = lstOrder != null ? lstOrder[0] : null;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(new Order());

		PageReference pageRef = Page.CreateEditOrderFacilitatorChecklist;
		pageRef.getParameters().put('orderId', objOrder.Id);
		test.setCurrentPageReference(pageRef);
		test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
		ctrl.saveChecklistNRefresh();

		System.assert(null != ctrl.lstOrderFacilitatorChkLst && ctrl.lstOrderFacilitatorChkLst.size() > 0, 'List should have more than 0 items.');

		//Insert feed Data
		FeedItem feeItem = new FeedItem();
		feeItem.ParentId = ctrl.lstOrderFacilitatorChkLst[0].id;
		feeItem.body = System.UserInfo.getUserName();
		FeedItemTriggerHelper.skipTrigger = true;
		insert feeItem;

		User facilitator = [SELECT Id FROM USer WHERE Profile.Name = 'Direct Sales User' AND isActive = TRUE LIMIT 1];
		System.runAs(facilitator) {
			FeedComment feedCom = new FeedComment(
				FeedItemId = feeItem.id,
				CommentType = 'TextComment',
				CommentBody = System.UserInfo.getFirstName() + ' ' + System.UserInfo.getLastName()
			);
			FeedCommentTriggerHelper.skipTrigger = true;
			insert feedCom;

			FeedItem fItem = new FeedItem();
			fItem.ParentId = ctrl.lstOrderFacilitatorChkLst[1].id;
			fItem.body = 'Feed Item by Facilitator';
			FeedItemTriggerHelper.skipTrigger = true;
			insert fItem;
		}

		ctrl.loadFeedItems();

		System.assert(ctrl.lstOrderChklstWrapper != null, 'lstOrderChklstWrapper should not be null.');
		System.assert(ctrl.lstOrderChklstWrapper.size() > 0, 'Size of lstOrderChklstWrapper should be greater than 0.');
		System.assert(ctrl.lstOrderChklstWrapper[0].strLastAdvocateComment != '', 'strLastAdvocateComment should not be empty string.');

		test.stopTest();
	}

	@isTest
	private static void testChecklistOperations() {
		List<Order> lstOrder = [SELECT Id FROM Order WHERE RecordType.Name = 'Company Migration' LIMIT 1];
		Order objOrder = lstOrder != null ? lstOrder[0] : null;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
		System.assert(null != ctrl.lstOrderChklstWrapper && ctrl.lstOrderChklstWrapper.size() > 0, 'lstOrderChklstWrapper should have more than 0 items.');

		//select checklists
		ctrl.lstOrderChklstWrapper[0].objOrderChkLst.Is_Checked__c = true;
		ctrl.lstOrderChklstWrapper[1].objOrderChkLst.Is_Checked__c = true;

		ctrl.saveChecklists();
		//run as facilitator
		User facilitator = [SELECT Id FROM USer WHERE Profile.Name = 'Direct Sales User' AND isActive = TRUE LIMIT 1];
		System.runAs(facilitator) {
			ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);

			//set as Complete
			ctrl.intWrapIndex = 0;
			ctrl.lstOrderChklstWrapper[0].objOrderChkLst.Is_Completed__c = true;
			ctrl.strFieldName = 'Completed';
			ctrl.toggleComplete();
			ctrl.saveChecklists();

			//set as blocked
			ctrl.intWrapIndex = 0;
			ctrl.lstOrderChklstWrapper[0].objOrderChkLst.Is_Blocked__c = true;
			ctrl.strFieldName = 'Blocked';

			ctrl.toggleComplete();
			ctrl.saveChecklists();
			System.assert(!ctrl.lstOrderChklstWrapper[0].objOrderChkLst.Is_Completed__c, 'Is Completed should be false.');
		}
		//add new checklist
		ctrl.addNewCheckList();
		ctrl.lstNewOrderChk[0].objOrderChkLst.Checklist_Name__c = 'New Checklist';

		//ctrl.saveChecklists();
		ctrl.selectAllchecklists();
		//remove checklist
		ctrl.intIndxToBeRemoved = 0;
		ctrl.bool_IsNewChkToBeRemoved = false;
		ctrl.removeChecklist();

		ctrl.intIndxToBeRemoved = 0;
		ctrl.bool_IsNewChkToBeRemoved = true;
		ctrl.removeChecklist();

		test.stopTest();
	}

	@isTest
	private static void testCopyChecklists() {
		List<Order> lstOrder = [SELECT Id FROM Order WHERE RecordType.Name = 'Company Migration' LIMIT 1];
		Order objOrder = lstOrder != null ? lstOrder[0] : null;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
		System.assert(null != ctrl.lstOrderChklstWrapper && ctrl.lstOrderChklstWrapper.size() > 0, 'lstOrderChklstWrapper should have more than 0 items.');

		//select checklists
		ctrl.lstOrderChklstWrapper[0].objOrderChkLst.Is_Checked__c = true;
		ctrl.lstOrderChklstWrapper[1].objOrderChkLst.Is_Checked__c = true;

		ctrl.saveAndCopychecklists();

		System.assert([SELECT COUNT() FROM Order_Facilitator_Checklist__c] > 3, 'Count should be more than 3.');
		test.stopTest();
	}

	@isTest
	private static void testSaveChecklists() {
		List<Order> lstOrder = [
			SELECT Id, Data_Entry_Assist__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration'
			LIMIT 1
		];
		Order objOrder = lstOrder != null ? lstOrder[0] : null;
		OrderTriggerHelper.skipTrigger = true;
		objOrder.Data_Entry_Assist__c = UserInfo.getUserId();
		update objOrder;
		OrderTriggerHelper.skipTrigger = false;
		Analytics_Time_Tracker__c objTracker = new Analytics_Time_Tracker__c(
			Order__c = objOrder.Id,
			Start_Date__c = DateTime.now()
		);
		insert objTracker;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);
		test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl ctrl = new CreateEditOrderFacilitatorChecklistCtrl(stdCtrl);
		System.assert(null != ctrl.lstOrderChklstWrapper && ctrl.lstOrderChklstWrapper.size() > 0, 'lstOrderChklstWrapper should have more than 0 items.');
		ctrl.saveChecklists();
		ctrl.selectAll = true;
		for (CreateEditOrderFacilitatorChecklistCtrl.OrderChecklistWrapper objWrap : ctrl.lstOrderChklstWrapper) {
			objWrap.objOrderChkLst.Is_Completed__c = true;
		}
		ctrl.saveChecklists();
		test.stopTest();
	}

	
    /**
     * @Author      : Sanjay Paryani
     * @Description : Tests if on entering Blocked Reason, the due date is allowed to be today and order is saved succesfully
     * @Parm        : NA
     * @Return      : NA
    **/
	@isTest
	private static void test_BlockedReasonEntered() {
		List<Order> list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration'
			LIMIT 1
		];
		Order objOrder = list_Orders != null ? list_Orders[0] : null;
		OrderTriggerHelper.skipTrigger = true;
		objOrder.Data_Entry_Assist__c = UserInfo.getUserId();
		update objOrder;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		Test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl objChecklistController = new CreateEditOrderFacilitatorChecklistCtrl(
			stdCtrl
		);
		System.assert(
			objChecklistController.lstOrderChklstWrapper != null &&
			objChecklistController.lstOrderChklstWrapper.size() > 0,
			'lstOrderChklstWrapper should have more than 0 items.'
		);

		objChecklistController.selectAll = false;

		objChecklistController.objFollowUpOrder.Facilitator_Follow_Up_Date__c = Date.today();
		objChecklistController.objFollowUpOrder.Facilitator_Follow_Up_Date_Reason__c = 'Other';
		objChecklistController.objFollowUpOrder.Blocked_Reason__c = 'Pausing this account for urgent 2FA access elsewhere';

		objChecklistController.saveChecklists();

		list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration' AND Blocked_Reason__c != NULL
		];

		Test.stopTest();

		System.assert(list_Orders.size() > 0, 'There should be more than 0 orders.');
		System.assertEquals(
			'Pausing this account for urgent 2FA access elsewhere',
			list_Orders.get(0).Blocked_Reason__c,
			'Blocked reason should match.'
		);
	}

	
	/**
     * @Author      : Sanjay Paryani
     * @Description : Tests if on entering Blocked Reason, but no follow up date reason order still saves without error.
     * @Parm        : NA
     * @Return      : NA
    **/
	@isTest
	private static void test_FollowUpDateReasonNullForToday() {
		List<Order> list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration'
			LIMIT 1
		];
		Order objOrder = list_Orders != null ? list_Orders[0] : null;
		OrderTriggerHelper.skipTrigger = true;
		objOrder.Data_Entry_Assist__c = UserInfo.getUserId();
		update objOrder;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		Test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl objChecklistController = new CreateEditOrderFacilitatorChecklistCtrl(
			stdCtrl
		);
		System.assert(
			objChecklistController.lstOrderChklstWrapper != null &&
			objChecklistController.lstOrderChklstWrapper.size() > 0,
			'lstOrderChklstWrapper should have more than 0 items.'
		);

		objChecklistController.selectAll = true;

		objChecklistController.objFollowUpOrder.Facilitator_Follow_Up_Date__c = Date.today();
		objChecklistController.objFollowUpOrder.Blocked_Reason__c = 'Pausing this account for urgent 2FA access elsewhere';

		objChecklistController.saveChecklists();

		list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration' AND Blocked_Reason__c != NULL
		];

		Test.stopTest();

		System.assert(list_Orders.size() > 0, 'There should be more than 0 orders.');
		System.assert(!objChecklistController.missingRequiredField(), 'No required field should be missing.');
	}

	/**
     * @Author      : Sanjay Paryani
     * @Description : Tests if for future follow up date, but no follow up date reason order fails with error.
     * @Parm        : NA
     * @Return      : NA
    **/
	@isTest
	private static void test_FollowUpDateReasonNullForFutureDate() {
		List<Order> list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration'
			LIMIT 1
		];
		Order objOrder = list_Orders != null ? list_Orders[0] : null;
		OrderTriggerHelper.skipTrigger = true;
		objOrder.Data_Entry_Assist__c = UserInfo.getUserId();
		update objOrder;

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objOrder);

		Test.startTest();
		CreateEditOrderFacilitatorChecklistCtrl objChecklistController = new CreateEditOrderFacilitatorChecklistCtrl(
			stdCtrl
		);
		System.assert(
			objChecklistController.lstOrderChklstWrapper != null &&
			objChecklistController.lstOrderChklstWrapper.size() > 0,
			'lstOrderChklstWrapper should have more than 0 items.'
		);

		objChecklistController.selectAll = true;

		objChecklistController.objFollowUpOrder.Facilitator_Follow_Up_Date__c = Date.today().addDays(2);

		objChecklistController.saveChecklists();

		list_Orders = [
			SELECT Id, Data_Entry_Assist__c, Blocked_Reason__c
			FROM Order
			WHERE RecordType.Name = 'Company Migration' AND Blocked_Reason__c != NULL
		];

		Test.stopTest();

		System.assert(list_Orders.size() == 0, 'There should be 0 orders.');
		System.assert(objChecklistController.missingRequiredField(), 'Required field should be missing.');
	}	
}