unpackaged/main/default/objects/Account/fields/Previous_Payroll_Provider__c.field-meta.xml
<CustomField>
    <fullName>Previous_Payroll_Provider__c</fullName>
    <label>Previous Payroll Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex</fullName>
            </value>
            <value>
                <fullName>Intuit or Quickbooks</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
            <value>
                <fullName>Paylocity</fullName>
            </value>
            <value>
                <fullName>JustWorks</fullName>
            </value>
            <value>
                <fullName>Trinet</fullName>
                <label>TriNet</label>
            </value>
            <value>
                <fullName>We do it ourselves manually</fullName>
            </value>
            <value>
                <fullName>We use a local provider</fullName>
            </value>
            <value>
                <fullName>An accountant/CPA</fullName>
            </value>
            <value>
                <fullName>I don&apos;t know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pricebook2__c.field-meta.xml
<CustomField>
    <fullName>Pricebook2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Previous_Payroll_Provider__c.field-meta.xml
<CustomField>
    <fullName>Previous_Payroll_Provider__c</fullName>
    <label>Previous Payroll Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Paychex</fullName>
            </value>
            <value>
                <fullName>Intuit or Quickbooks</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
            <value>
                <fullName>Paylocity</fullName>
            </value>
            <value>
                <fullName>JustWorks</fullName>
            </value>
            <value>
                <fullName>Trinet</fullName>
            </value>
            <value>
                <fullName>We do it ourselves manually</fullName>
            </value>
            <value>
                <fullName>We use a local provider</fullName>
            </value>
            <value>
                <fullName>An accountant/CPA</fullName>
            </value>
            <value>
                <fullName>I don&apos;t know</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Order/fields/Previous_Payroll_Provider__c.field-meta.xml
<CustomField>
    <fullName>Previous_Payroll_Provider__c</fullName>
    <label>Previous Payroll Provider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADP Run</fullName>
            </value>
            <value>
                <fullName>ADP Resource</fullName>
            </value>
            <value>
                <fullName>ADP Total Source</fullName>
            </value>
            <value>
                <fullName>ADP Workforce Now</fullName>
            </value>
            <value>
                <fullName>BenefitMall</fullName>
            </value>
            <value>
                <fullName>Bank of America</fullName>
            </value>
            <value>
                <fullName>Heartland Payroll</fullName>
            </value>
            <value>
                <fullName>Intuit Online Payroll</fullName>
            </value>
            <value>
                <fullName>iSolved</fullName>
            </value>
            <value>
                <fullName>JustWorks</fullName>
            </value>
            <value>
                <fullName>Namely</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Offline (manual)</fullName>
            </value>
            <value>
                <fullName>Offline (downloaded reports)</fullName>
            </value>
            <value>
                <fullName>Patriot Software</fullName>
            </value>
            <value>
                <fullName>Paychex</fullName>
            </value>
            <value>
                <fullName>Paycom</fullName>
            </value>
            <value>
                <fullName>Paycor</fullName>
            </value>
            <value>
                <fullName>Paychex Preview</fullName>
            </value>
            <value>
                <fullName>Paylocity</fullName>
            </value>
            <value>
                <fullName>PEO / Full Service Backend Provider</fullName>
            </value>
            <value>
                <fullName>QuickBooks Desktop</fullName>
            </value>
            <value>
                <fullName>QuickBooks Online</fullName>
            </value>
            <value>
                <fullName>Sage</fullName>
            </value>
            <value>
                <fullName>Square</fullName>
            </value>
            <value>
                <fullName>SurePayroll</fullName>
            </value>
            <value>
                <fullName>Thomson Reuters</fullName>
            </value>
            <value>
                <fullName>Trinet</fullName>
            </value>
            <value>
                <fullName>Zenefits</fullName>
            </value>
            <value>
                <fullName>BambooHR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Maintain__c.field-meta.xml
<CustomField>
    <fullName>Maintain__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if a product is automatically added when a record is generated.</description>
    <label>Maintain</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Program.cls
/**
 * Created by brent.johnson on 11/24/16.
 */

public without sharing virtual class Program {
	public static Map<Id, Pricebook2> pricebook2s {
		get {
			if (pricebook2s == null) {
				pricebook2s = new Map<Id, Pricebook2>([SELECT Id, Name, IsActive FROM Pricebook2]);
			}
			return pricebook2s;
		}
		private set;
	}

	public static Map<Id, Product2> product2s {
		get {
			if (product2s == null) {
				product2s = new Map<Id, Product2>([SELECT Id, Name, IsActive FROM Product2]);
			}
			return product2s;
		}
		private set;
	}

	public static Map<Id, PricebookEntry> pricebookEntries {
		get {
			if (pricebookEntries == null) {
				pricebookEntries = new Map<Id, PricebookEntry>([SELECT Id, Pricebook2Id, Product2Id, IsActive, Maintain__c, UnitPrice, Pricebook2.Name, Product2.Name FROM PricebookEntry]);
			}
			return pricebookEntries;
		}
		private set;
	}

	static Map<Schema.SObjectType, Map<Id, SObject>> ProgramCache = new Map<Schema.SObjectType, Map<Id, SObject>>();

	public static void loadAccounts(Set<Id> accountIds) {
		load(
			[
				SELECT
					Id,
					Previous_Payroll_Provider__c,
					BillingStreet,
					BillingPostalCode,
					BillingCity,
					BillingState,
					BillingStateCode,
					BillingCountry,
					BillingCountryCode,
					ShippingStreet,
					ShippingPostalCode,
					ShippingCity,
					ShippingState,
					ShippingStateCode,
					ShippingCountry,
					ShippingCountryCode,
					Pricebook2__c
				FROM Account
				WHERE Id IN :accountIds
			]
		);
	}

	public static void loadOpportunities(Set<Id> opportunityIds) {
		load([SELECT Id, Pricebook2Id FROM Opportunity WHERE Id IN :opportunityIds]);
	}

	public static void loadOrdersWithOrderItems(Set<Id> orderIds) {
		load([SELECT Id, (SELECT Id, PricebookEntryId FROM OrderItems) FROM Order WHERE Id IN :orderIds]);
	}

	public static Account getAccount(Id accountId) {
		return (Account) getSObject(Schema.Account.SObjectType, accountId);
	}

	public static Order getOrderWithOrderItems(Id orderId) {
		return (Order) getSObject(Schema.Order.SObjectType, orderId);
	}

	public static Opportunity getOpportunity(Id opportunityId) {
		return (Opportunity) getSObject(Schema.Opportunity.SObjectType, opportunityId);
	}

	static SObject getSObject(Schema.SObjectType sObjType, Id sObjId) {
		SObject sObj = null;
		if (ProgramCache.containsKey(sObjType)) {
			Map<Id, SObject> sObjMap = ProgramCache.get(sObjType);
			if (sObjMap.containsKey(sObjId)) {
				sObj = sObjMap.get(sObjId);
			}
		}
		return sObj;
	}

	static void load(List<SObject> sObjs) {
		load(sObjs.getSObjectType(), sObjs);
	}

	static void load(Schema.SObjectType sObjType, List<SObject> sObjs) {
		if (!ProgramCache.containsKey(sObjType))
			ProgramCache.put(sObjType, new Map<Id, SObject>());
		ProgramCache.get(sObjType).putAll(sObjs);
	}
}