unpackaged/main/default/objects/Account/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Referred By)</relationshipLabel>
    <relationshipName>AccountsReferredBy</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sold_By__c.field-meta.xml
<CustomField>
    <fullName>Sold_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sold Accounts</relationshipLabel>
    <relationshipName>SoldByAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>true</active>
    <description>Used to identify entities that help sell Gusto to other companies or their own clients. Generally associated with the Accountants segment, though not all Resellers are truly Accountants/CPAs</description>
    <label>Reseller</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/Referred_By__c.field-meta.xml
<CustomField>
    <fullName>Referred_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referred By</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Referred By)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Send_Slack_to_Reseller__c.field-meta.xml
<CustomField>
    <fullName>Send_Slack_to_Reseller__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Based on this flag - message will be send to Partner slack channel when Client opportunity is getting Sold By/Referred by - within 30 days after opportunity is Closed Won.</description>
    <label>Send Slack to Reseller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sold_By__c.field-meta.xml
<CustomField>
    <fullName>Sold_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Reseller</value>
        </filterItems>
        <infoMessage>Displaying Partner Accounts</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Sold By)</relationshipLabel>
    <relationshipName>Opportunities_As_Reseller</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Reseller.recordType-meta.xml
<RecordType>
    <fullName>Reseller</fullName>
    <active>false</active>
    <businessProcess>Sales Process Redesign</businessProcess>
    <description>Inactive - previously used to track firm sign up and onboarding of the Accountant</description>
    <label>Reseller</label>
</RecordType>

force-app/main/default/classes/SendSlackNotForOppResellerScheduler.cls
/**
 * @author Yogesh Kherajani
 * @since 09/18/2024
 * @description This class will be used to Send Slack Notification To Opportunity Reseller.
 * Test class: SendSlackNotForOppResellerSchedulerTest
 **/
public class SendSlackNotForOppResellerScheduler implements Schedulable{
    public void execute(SchedulableContext SC) {
        List<SendSlackNotForOppResellerWrapper> lst_SendSlakcNotification = new List<SendSlackNotForOppResellerWrapper>();
        
        for(Opportunity objOppRec : [
            SELECT Id, Sold_By__c, Sold_By__r.Name, Sold_By__r.Owner_Slack_Id__c, Referred_By__c, Send_Slack_to_Reseller__c,
            Referred_By__r.Name, Referred_By__r.Owner_Slack_Id__c
            FROM Opportunity 
            WHERE Send_Slack_to_Reseller__c = TRUE
        ]){
            SendSlackNotForOppResellerWrapper objSendSlakcNotification = new SendSlackNotForOppResellerWrapper();
            objSendSlakcNotification.strOpportunityId = objOppRec.Id;
            
            if(objOppRec.Sold_By__c != NULL){
                objSendSlakcNotification.strSoldBy = objOppRec.Sold_By__c;
            	objSendSlakcNotification.strSoldByName = objOppRec.Sold_By__r.Name;
                objSendSlakcNotification.strSoldByOwnerSlackId = objOppRec.Sold_By__r.Owner_Slack_Id__c;
            }
            
            if(objOppRec.Referred_By__c != NULL){
                objSendSlakcNotification.strReferredBy = objOppRec.Sold_By__c;
            	objSendSlakcNotification.strReferredByName = objOppRec.Sold_By__r.Name;
                objSendSlakcNotification.strReferredByOwnerSlackId = objOppRec.Referred_By__r.Owner_Slack_Id__c;
            }
            
            lst_SendSlakcNotification.add(objSendSlakcNotification);
        }
        
        if(!lst_SendSlakcNotification.isEmpty()){
            Map<String, Object> map_SendSlackNotification = new Map<String, Object>();
            map_SendSlackNotification.put('lst_SendSlackRecords', lst_SendSlakcNotification);
            
            // Instantiate and start the Flow
            Flow.Interview.Send_Slack_notificaiotn_to_partner_for_new_client_add_within_30_days_of_CW objFlow = new Flow.Interview.Send_Slack_notificaiotn_to_partner_for_new_client_add_within_30_days_of_CW(map_SendSlackNotification);
            objFlow.start();    
        }
    }
}