force-app/main/default/objects/Role__c/Role__c.object-meta.xml
<CustomObject>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Role__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Used in Flexforce module</description>
    <label>Skill Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <displayFormat>SL-{00000}</displayFormat>
        <label>Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Skill__c/fields/Payroll_Transfer_Skills__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Transfer_Skills__c</fullName>
    <label>Payroll Transfer Skills</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bulk Order</fullName>
            </value>
            <value>
                <fullName>Direct Order</fullName>
            </value>
            <value>
                <fullName>BigDesk Order</fullName>
            </value>
            <value>
                <fullName>Externals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Role</label>
    <referenceTo>Role__c</referenceTo>
    <relationshipLabel>User Roles</relationshipLabel>
    <relationshipName>User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gustie_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_Skill__c/User_Skill__c.object-meta.xml
<CustomObject>
    <label>User Skill</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User_Skill__c/fields/Payroll_Transfer_Skills__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Transfer_Skills__c</fullName>
    <formula>TEXT(Skill__r.Payroll_Transfer_Skills__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payroll Transfer Skills</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>User Skills</relationshipLabel>
    <relationshipName>Skill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User_Skill__c/fields/Skill_Role_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Role_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Skill Role Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User_Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Used in Workforce Manage user Module</description>
    <formula>TEXT(Skill__r.Role__r.Skill_Type__c)</formula>
    <label>Skill Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Skill__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Role</label>
    <referenceTo>User_Role__c</referenceTo>
    <relationshipLabel>User Skills</relationshipLabel>
    <relationshipName>User_Role</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdvocateTabCompCtrlTest.cls
/********************************************************************
* Info : AdvocateTabCompCtrlTest is used to cover AdvocateTabCompCtrl
*       * 
* Created by : Lirik on 11/17/2020
***********************************************************************/ 

@isTest
public class AdvocateTabCompCtrlTest {
	static testMethod void testAdvocateTabCompCtrl() {
        //Create Role
        Role__c ptaRole = new Role__c(Name = 'Payroll Transfer Advocate');
        ptaRole.Skill_Type__c='Core';
        insert ptaRole;        
        
        //Create Skill
        List<Skill__c> lstSkill = new List<Skill__c>();
        lstSkill.add(new Skill__c(Payroll_Transfer_Skills__c ='Bulk',Role__c = ptaRole.Id));
        lstSkill.add(new Skill__c(Payroll_Transfer_Skills__c ='Direct',Role__c = ptaRole.Id));
        insert lstSkill;
        //Create user Role
        User_Role__c userRoleObj = new User_Role__c();
        userRoleObj.User__c = userinfo.getUserId();
        insert userRoleObj;
        
        //Create User Skill
        User_Skill__c userSkillObj = new User_Skill__c();
        userSkillObj.Skill__c = lstSkill[0].id;
        userSkillObj.User_Role__c = userRoleObj.Id;  
        userSkillObj.Skill_role_name__c = 'Payroll Transfer Advocate';
        insert userSkillObj;
        
        AdvocateTabCompCtrl objAdvTab=new AdvocateTabCompCtrl();	
    }
}