force-app/main/default/objects/Research_Project_Detail__c/Research_Project_Detail__c.object-meta.xml
<CustomObject>
    <label>Research Project Detail</label>
    <nameField>
        <displayFormat>RPD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Project Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Research_Project_Detail__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Research Project Details</relationshipLabel>
    <relationshipName>Research_Project_Details</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Research_Project_Detail__c/fields/Incentive__c.field-meta.xml
<CustomField>
    <fullName>Incentive__c</fullName>
    <label>Incentive</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Research_Project_Detail__c/fields/Proposed_Incentive__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Incentive__c</fullName>
    <inlineHelpText>If Applicable for Incentive = true and Gift card/swag sent = true then &quot;Proposed Incentive&quot; value assign to &quot;Incentive&quot; field.</inlineHelpText>
    <label>Proposed Incentive</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Research_Project_Detail__c/fields/Research_Participant_Status__c.field-meta.xml
<CustomField>
    <fullName>Research_Participant_Status__c</fullName>
    <label>Research Participant Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>No Show</fullName>
            </value>
            <value>
                <fullName>Replied</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Contact Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Research_Project_Detail__c/fields/Research_Project_Master__c.field-meta.xml
<CustomField>
    <fullName>Research_Project_Master__c</fullName>
    <label>Research Project Master</label>
    <referenceTo>Research_Project_Master__c</referenceTo>
    <relationshipLabel>Research Project Details</relationshipLabel>
    <relationshipName>Research_Project_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Project_Master__c/Research_Project_Master__c.object-meta.xml
<CustomObject>
    <label>UXR Scout</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UXR Scout</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Research_Project_Master__c/fields/Closed_Schedule_Email_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Closed_Schedule_Email_Error_Message__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Closed Schedule Email Error Message</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Research_Schedule_Email__c/Research_Schedule_Email__c.object-meta.xml
<CustomObject>
    <label>Research Schedule Email</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>Research Schedule Email Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Schedule Emails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Schedule_Email__c/fields/Schedule_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Email_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedule Email Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Research_Schedule_Email__c/fields/Schedule_Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Email_Template_Id__c</fullName>
    <label>Schedule Email Template Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Research_Schedule_Email__c/fields/Schedule_Email_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Email_Time__c</fullName>
    <label>Schedule Email Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>01:00 AM</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>02:00 AM</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>03:00 AM</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>04:00 AM</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>05:00 AM</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>06:00 AM</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>07:00 AM</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>08:00 AM</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>09:00 AM</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10:00 AM</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>11:00 AM</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12:00 PM</label>
            </value>
            <value>
                <fullName>13</fullName>
                <label>01:00 PM</label>
            </value>
            <value>
                <fullName>14</fullName>
                <label>02:00 PM</label>
            </value>
            <value>
                <fullName>15</fullName>
                <label>03:00 PM</label>
            </value>
            <value>
                <fullName>16</fullName>
                <label>04:00 PM</label>
            </value>
            <value>
                <fullName>17</fullName>
                <label>05:00 PM</label>
            </value>
            <value>
                <fullName>18</fullName>
                <label>06:00 PM</label>
            </value>
            <value>
                <fullName>19</fullName>
                <label>07:00 PM</label>
            </value>
            <value>
                <fullName>20</fullName>
                <label>08:00 PM</label>
            </value>
            <value>
                <fullName>21</fullName>
                <label>09:00 PM</label>
            </value>
            <value>
                <fullName>22</fullName>
                <label>10:00 PM</label>
            </value>
            <value>
                <fullName>23</fullName>
                <label>11:00 PM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Research_Schedule_Email__c/fields/UXR_Scout__c.field-meta.xml
<CustomField>
    <fullName>UXR_Scout__c</fullName>
    <label>UXR Scout</label>
    <referenceTo>Research_Project_Master__c</referenceTo>
    <relationshipLabel>Research Schedule Emails</relationshipLabel>
    <relationshipName>Research_Schedule_Emails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Research_Schedule_Email_Participant__c/Research_Schedule_Email_Participant__c.object-meta.xml
<CustomObject>
    <label>Research Schedule Email Participant</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Research Schedule Email Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Schedule Email Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Research_Schedule_Email_Participant__c/fields/Research_Project_Detail__c.field-meta.xml
<CustomField>
    <fullName>Research_Project_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Research Project Detail</label>
    <referenceTo>Research_Project_Detail__c</referenceTo>
    <relationshipLabel>Research Schedule Email Participants</relationshipLabel>
    <relationshipName>Research_Schedule_Email_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Research_Schedule_Email_Participant__c/fields/Research_Schedule_Email__c.field-meta.xml
<CustomField>
    <fullName>Research_Schedule_Email__c</fullName>
    <label>Research Schedule Email</label>
    <referenceTo>Research_Schedule_Email__c</referenceTo>
    <relationshipLabel>Research Schedule Email Participants</relationshipLabel>
    <relationshipName>Research_Schedule_Email_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Schedule_Email_Participant__c/fields/Schedule_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Email_Status__c</fullName>
    <label>Schedule Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Schedule</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UR_ScheduleEmail.cls
public class UR_ScheduleEmail implements Database.Batchable<sObject>, Schedulable {
	public void execute(SchedulableContext sc) {
		UR_ScheduleEmail scheduleBatchObj = new UR_ScheduleEmail();
		Database.executeBatch(scheduleBatchObj, 1);

		System.abortJob(sc.getTriggerId());
	}

	public Database.QueryLocator start(Database.BatchableContext BC) {
		Date dateObj = Date.today();
		String timeObj = DateTime.now().hour() + '';
		String query = 'select id, Research_Schedule_Email__r.UXR_Scout__c, Research_Project_Detail__r.Contact__c, Research_Project_Detail__c, Schedule_Email_Status__c, Research_Schedule_Email__r.Schedule_Email_Type__c, Research_Schedule_Email__r.Schedule_Email_Template_Id__c from Research_Schedule_Email_Participant__c where Research_Schedule_Email__r.Schedule_Email_Date__c=:dateObj and Research_Schedule_Email__r.Schedule_Email_Time__c=:timeObj and Schedule_Email_Status__c = \'Schedule\' ';
		if (Test.isRunningTest()) {
			query = 'select id, Research_Schedule_Email__r.UXR_Scout__c, Research_Project_Detail__r.Contact__c, Research_Project_Detail__c, Schedule_Email_Status__c, Research_Schedule_Email__r.Schedule_Email_Template_Id__c from Research_Schedule_Email_Participant__c limit 1';
		}
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<Research_Schedule_Email_Participant__c> scope) {
		if (scope.size() > 0) {
			try {
				sendEmail(scope[0]);
				scope[0].put('Schedule_Email_Status__c', 'Success');
				scope[0].put('Error_Message__c', '');
				update scope[0];

				Research_Schedule_Email_Participant__c scheduleObj = scope[0];

				List<Research_Project_Detail__c> lstProjectDetail = [
					SELECT id, Research_Participant_Status__c, Incentive__c, Proposed_Incentive__c
					FROM Research_Project_Detail__c
					WHERE id = :scheduleObj.Research_Project_Detail__c
				];
				if (lstProjectDetail.size() > 0) {
					// "Research Participant Status" should not be changed, if participant is Attended and some incentive amount is given to it.
					if (lstProjectDetail[0].Research_Participant_Status__c != 'Attended' || Test.isRunningTest()) {
						String strPartStatus = scheduleObj.Research_Schedule_Email__r.Schedule_Email_Type__c;
						if (String.isNotBlank(strPartStatus)) {
							String finalStatus = UR_UtilityCtrl.emailStatusMap.get(strPartStatus);
							if (String.isNotBlank(finalStatus)) {
								Research_Project_Detail__c objUpdate = new Research_Project_Detail__c(id = scheduleObj.Research_Project_Detail__c);
								objUpdate.Research_Participant_Status__c = finalStatus;
								update objUpdate;
							}
						}
					}
				}
			} catch (Exception ex) {
				updateProjectMaster(scope, ex.getMessage());
			}
		}
	}

	public void finish(Database.BatchableContext BC) {
	}

	public void updateProjectMaster(List<Research_Schedule_Email_Participant__c> scope, String errorMsg) {
		scope[0].put('Schedule_Email_Status__c', 'Fail');
		scope[0].put('Error_Message__c', errorMsg);
		update scope[0];

		if (scope[0].Research_Schedule_Email__r.UXR_Scout__c != null) {
			UR_ProjectMasterTriggerHelper.skipTrigger = true;
			Research_Project_Master__c obj = new Research_Project_Master__c();
			obj.Id = scope[0].Research_Schedule_Email__r.UXR_Scout__c;
			obj.Closed_Schedule_Email_Error_Message__c = false;
			update obj;
			UR_ProjectMasterTriggerHelper.skipTrigger = false;
		}
	}

	public void sendEmail(sObject sObj) {
		Research_Schedule_Email_Participant__c scheduleEmail = (Research_Schedule_Email_Participant__c) sObj;
		List<Messaging.SingleEmailMessage> mail = new List<Messaging.SingleEmailMessage>();
		Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
		msg.setWhatId(scheduleEmail.Research_Project_Detail__c);
		msg.setTargetObjectId(scheduleEmail.Research_Project_Detail__r.Contact__c);
		if (string.isNotBlank(UR_UtilityCtrl.strReplyEmail)) {
			msg.setReplyTo(UR_UtilityCtrl.strReplyEmail);
		}

		if (String.isNotBlank(scheduleEmail.Research_Schedule_Email__r.Schedule_Email_Template_Id__c)) {
			msg.setTemplateId(scheduleEmail.Research_Schedule_Email__r.Schedule_Email_Template_Id__c);
		} else {
			msg.setHtmlBody('emailBody');
			msg.setSubject('strSubject');
		}
		msg.setSaveAsActivity(true);

		if (UR_UtilityCtrl.orgWideEmail_NoReply != null) {
			msg.setOrgWideEmailAddressId(UR_UtilityCtrl.orgWideEmail_NoReply);
		}
		mail.add(msg);
		if (mail.size() > 0) {
			skipTrigger(true);
			EmailMessageTriggerHelper.skipTrigger = true;
			Messaging.sendEmail(mail);
			EmailMessageTriggerHelper.skipTrigger = false;
			skipTrigger(false);
		}
	}
	public void skipTrigger(Boolean flag) {
		ContactTriggerHelper.skipTrigger = flag;
		AccountTriggerHelper.skipTrigger = flag;
	}
}