unpackaged/main/default/objects/Case/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
            </value>
            <value>
                <fullName>Gusto</fullName>
            </value>
            <value>
                <fullName>Other/Unknown</fullName>
            </value>
            <value>
                <fullName>Dependent</fullName>
            </value>
            <value>
                <fullName>Dismissed Employee</fullName>
            </value>
            <value>
                <fullName>BASIC</fullName>
            </value>
            <value>
                <fullName>Administrator</fullName>
            </value>
            <value>
                <fullName>CPA/Partner</fullName>
            </value>
            <value>
                <fullName>Suspended Company</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Non-User</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Closed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Closed_Reason__c</fullName>
    <description>Closed Reason</description>
    <label>Closed Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Merged Duplicate</fullName>
            </value>
            <value>
                <fullName>Termination Cancelled</fullName>
            </value>
            <value>
                <fullName>Merged Follow up Case</fullName>
            </value>
            <value>
                <fullName>Abandoned Call</fullName>
            </value>
            <value>
                <fullName>Merged Previously Answered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Confirm_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Case_Reason__c</fullName>
    <label>Confirm Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>100k Liability</fullName>
            </value>
            <value>
                <fullName>1099 Adjustment</fullName>
            </value>
            <value>
                <fullName>2 Day Bank Balance Response</fullName>
            </value>
            <value>
                <fullName>2 Day Details</fullName>
            </value>
            <value>
                <fullName>2 Day Payroll Blocked</fullName>
                <label>2 Day Payroll Blocked RC</label>
            </value>
            <value>
                <fullName>2 Day Payroll Error</fullName>
            </value>
            <value>
                <fullName>2 Day Re Approval</fullName>
            </value>
            <value>
                <fullName>2 Day Reject Explanation</fullName>
            </value>
            <value>
                <fullName>2 Day RFI Complete Approval Request</fullName>
            </value>
            <value>
                <fullName>2 Day RFI Inquiry</fullName>
            </value>
            <value>
                <fullName>2 Day Suspension Explanation</fullName>
            </value>
            <value>
                <fullName>2 Day to 4 Day</fullName>
            </value>
            <value>
                <fullName>Abandoned/Unresponsive Chat</fullName>
            </value>
            <value>
                <fullName>Account Closed/Inactive</fullName>
            </value>
            <value>
                <fullName>Account ID Update</fullName>
            </value>
            <value>
                <fullName>Account Locked Explanation</fullName>
            </value>
            <value>
                <fullName>Account Rejected</fullName>
            </value>
            <value>
                <fullName>Agency: Correspondence</fullName>
            </value>
            <value>
                <fullName>Agency: Informational</fullName>
            </value>
            <value>
                <fullName>Agency/Gusto relationship</fullName>
            </value>
            <value>
                <fullName>ATO Claim Negative</fullName>
            </value>
            <value>
                <fullName>ATO Claim Positive</fullName>
            </value>
            <value>
                <fullName>Audit</fullName>
            </value>
            <value>
                <fullName>Audit Blocked</fullName>
            </value>
            <value>
                <fullName>Audit Error</fullName>
            </value>
            <value>
                <fullName>Bank Verification</fullName>
            </value>
            <value>
                <fullName>Benefit Adjustment</fullName>
                <label>benefit adjustment</label>
            </value>
            <value>
                <fullName>Benefits Adjustment</fullName>
                <label>benefits adjustment</label>
            </value>
            <value>
                <fullName>Business Name Change Request</fullName>
            </value>
            <value>
                <fullName>Calendly Appointments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoCloseCasesBatch.cls
global class AutoCloseCasesBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id FROM Case WHERE Confirm_Case_Reason__c IN (\'No Action\', \'Wrong Email\') AND Audience__c IN (\'Other\', \'Unknown\')';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Case> scope) {
        List<Case> casesToUpdate = new List<Case>();

        for (Case c : scope) {
            c.Status = 'Closed';
            //c.Closed_Reason__c = '';
            casesToUpdate.add(c);
        }

        if (!casesToUpdate.isEmpty()) {
            update casesToUpdate;
        }
    }

    global void finish(Database.BatchableContext bc) {
        // Optional
    }
}