unpackaged/main/default/objects/Case/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Class 1</fullName>
            </value>
            <value>
                <fullName>Class 2</fullName>
            </value>
            <value>
                <fullName>Class 3</fullName>
            </value>
            <value>
                <fullName>Class 4</fullName>
            </value>
            <value>
                <fullName>Class 0</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Classification_formula__c.field-meta.xml
<CustomField>
    <fullName>Classification_formula__c</fullName>
    <formula>TExt(Routing_Case_Reason_Classification__r.Class__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Classification formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Routing_Case_Reason__c.field-meta.xml
<CustomField>
    <fullName>Routing_Case_Reason__c</fullName>
    <label>Routing Case Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1099 Adjustment</fullName>
            </value>
            <value>
                <fullName>Response to NPS Survey</fullName>
            </value>
            <value>
                <fullName>Deduction or Garnishment</fullName>
            </value>
            <value>
                <fullName>Benefit Reversal</fullName>
            </value>
            <value>
                <fullName>Soft Suspend</fullName>
                <label>soft suspend</label>
            </value>
            <value>
                <fullName>Time Tracking ER</fullName>
            </value>
            <value>
                <fullName>Time Tracking EE</fullName>
                <label>time tracking EE</label>
            </value>
            <value>
                <fullName>Destroy or Delete Account (not cancel)</fullName>
            </value>
            <value>
                <fullName>EFTPS Question</fullName>
            </value>
            <value>
                <fullName>IRS/State Notice</fullName>
            </value>
            <value>
                <fullName>Unsupported State - Workers Comp&apos;</fullName>
            </value>
            <value>
                <fullName>Gusto Giving</fullName>
            </value>
            <value>
                <fullName>Cancel Account</fullName>
            </value>
            <value>
                <fullName>PTO Policy</fullName>
            </value>
            <value>
                <fullName>External Workers&apos; Comp</fullName>
            </value>
            <value>
                <fullName>EoY Spot Check Squad Action Required</fullName>
            </value>
            <value>
                <fullName>Benefits Adjustment</fullName>
                <label>benefits adjustment</label>
            </value>
            <value>
                <fullName>POA Responses</fullName>
            </value>
            <value>
                <fullName>Onboarding Audit</fullName>
            </value>
            <value>
                <fullName>Benefit Adjustment</fullName>
                <label>benefit adjustment</label>
            </value>
            <value>
                <fullName>External Covid Reporting</fullName>
            </value>
            <value>
                <fullName>QSEHRA</fullName>
            </value>
            <value>
                <fullName>Route to FSC</fullName>
            </value>
            <value>
                <fullName>Route to PRC</fullName>
            </value>
            <value>
                <fullName>Route to Modern Bank</fullName>
            </value>
            <value>
                <fullName>Route to Risk</fullName>
            </value>
            <value>
                <fullName>Route to Sales</fullName>
            </value>
            <value>
                <fullName>Route to Tax Ops</fullName>
            </value>
            <value>
                <fullName>Route to Tax Res</fullName>
            </value>
            <value>
                <fullName>Route to Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Total_Number_of_Touchpoints__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_of_Touchpoints__c</fullName>
    <label>Total Number of Touchpoints</label>
    <summarizedField>Case_Audit_Log__c.Touchpoint__c</summarizedField>
    <summaryForeignKey>Case_Audit_Log__c.Case__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/WorkInProgressCasesController.cls
public with sharing class WorkInProgressCasesController {
    public class WorkInProgressCaseResponse {
        @AuraEnabled
        public List<Case> list_Cases;

        @AuraEnabled
        public Boolean blnIsSuccess;

        @AuraEnabled
        public String strMessage;

        @AuraEnabled
        public Case objCase;

        public WorkInProgressCaseResponse(
            List<Case> list_Cases,
            Case objCase,
            Boolean blnIsSuccess,
            String strMessage
        ) {
            this.list_Cases = list_Cases;
            this.objCase = objCase;
            this.blnIsSuccess = blnIsSuccess;
            this.strMessage = strMessage;
        }
    }
    // This method returns similar work in progress cases for caseId's contact
    @AuraEnabled
    public static WorkInProgressCaseResponse returnWorkInProgressCases(Id idCase) {
        // Check if the call comes from LiveChatTranscript page or Chat Page
        // If LiveChatTranscript, fetch parent case
        String strObjectType = idCase.getSObjectType().getDescribe().getName();
        if (strObjectType.equals('LiveChatTranscript')) {
            idCase = [SELECT Id, CaseId FROM LiveChatTranscript WHERE Id = :idCase].CaseId;
        }

        Id idNpUservey = null;
        // list of work in cases to return
        List<Case> list_Cases = new List<Case>();
        List<String> list_GroupNames = new List<String>{ 'Mass Email Cases' };
        List<String> list_RecordTypeName = new List<String>{
            'Payroll Care',
            'Payroll Care - Read Only',
            'Benefits Care - Read Only',
            'Tax Res',
            'Tax Res - Read Only',
            'GEP CX',
            'Modern Bank',
            'Modern Bank - Read Only'
        };

        Case objCase = new Case();
        try {
            List<Case> list_ExistingCases = [
                SELECT Id, ContactId, RecordTypeId, Record_Type_Name__c, Contact.Name
                FROM Case
                WHERE Id = :idCase
            ];

            if (!list_ExistingCases.isEmpty()) {
                objCase = list_ExistingCases[0];

                for (Case objCaseRec : [
                    SELECT
                        Id,
                        Subject,
                        OwnerId,
                        Owner.Name,
                        CreatedDate,
                        Total_Number_of_Touchpoints__c,
                        CaseNumber,
                        Class__c,
                        Classification_formula__c,
                        Status,
                        Origin,
                        Priority,
                        Record_Type_Name__c,
                        Routing_Case_Reason__c,
                        Type
                    FROM Case
                    WHERE
                        ContactId = :objCase.ContactId
                        AND RecordTypeId = :objCase.RecordTypeId
                        AND Id != :objCase.Id
                        AND (Owner.Type = 'User'
                        OR (Owner.Type = 'Queue'
                        AND Owner.Name IN :list_GroupNames))
                        AND Status != 'Closed'
                        AND Status != 'Solved'
                        AND RecordType.Name IN :list_RecordTypeName
                        AND Origin != 'Phone'
                        AND Origin != 'Chat'
                ]) {
                    list_Cases.add(objCaseRec);
                }
            }
        } catch (Exception objException) {
            ExceptionLogUtil.logException(
                'WorkInProgressCasesController',
                'returnWorkInProgressCases',
                objException.getMessage(),
                objException.getStackTraceString()
            );

            return new WorkInProgressCaseResponse(null, objCase, false, objException.getMessage());
        }

        return new WorkInProgressCaseResponse(list_Cases, objCase, true, null);
    }
}