unpackaged/main/default/objects/Case/fields/Status_Detail__c.field-meta.xml
<CustomField>
    <fullName>Status_Detail__c</fullName>
    <label>Status Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group Termed for Non-Payment</fullName>
            </value>
            <value>
                <fullName>SSN Verification</fullName>
            </value>
            <value>
                <fullName>Name Verification</fullName>
            </value>
            <value>
                <fullName>Birthday Verification</fullName>
            </value>
            <value>
                <fullName>Cross-Team Escalation</fullName>
            </value>
            <value>
                <fullName>Pending Due to Carrier</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>No Group ID</fullName>
            </value>
            <value>
                <fullName>RFI</fullName>
            </value>
            <value>
                <fullName>Researching</fullName>
            </value>
            <value>
                <fullName>Contacting Agency</fullName>
            </value>
            <value>
                <fullName>Processing Corrections</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Agency</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Gusto</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Client</fullName>
            </value>
            <value>
                <fullName>Waiting/Need Info Bank</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>Awaiting Info</fullName>
            </value>
            <value>
                <fullName>Inactionable Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Zendesk_Id__c.field-meta.xml
<CustomField>
    <fullName>Zendesk_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Zendesk Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AcceptCaseExtension.cls
public class AcceptCaseExtension {
	public Case theCase { get; private set; }

	public AcceptCaseExtension(ApexPages.StandardController controller) {
		theCase = (Case) controller.getRecord();
		theCase = [
			SELECT Id, OwnerId, Subject, Description, Reason, Status, Status_Detail__c, Requires_Action__c, Zendesk_Id__c
			FROM Case
			WHERE Id = :theCase.Id
			FOR UPDATE
		];
	}

	public pageReference backToCase() {
		PageReference pgref = new PageReference('/' + theCase.id);
		return pgref;
	}

	public pageReference acceptCase() {
		String caseOwnerId = theCase.OwnerId;
		if (caseOwnerId.indexOf('00G') < 0) {
			apexPages.addMessage(new apexPages.Message(ApexPages.Severity.ERROR, 'Case is not owned by a queue'));
			return null;
		}
		theCase.OwnerId = UserInfo.getUserId();
		Database.SaveResult result = Database.update(theCase);
		if (result.success) {
			PageReference pgref = new PageReference('/' + theCase.id);
			return pgref;
		} else {
			PageReference pgref = new PageReference('/apex/AcceptCaseViewPage?id=' + theCase.id + '&refreshPage=true');
			return pgref;
		}
	}
}