force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Lowercase concatenation of carrier name with state. Hyphen delimitated.</description>
    <externalId>true</externalId>
    <label>HI Carrier Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

force-app/main/default/objects/HI_HSA_Benefit__c/HI_HSA_Benefit__c.object-meta.xml
<CustomObject>
    <label>HI HSA Benefit</label>
    <nameField>
        <displayFormat>HIHSA-{0000000000}</displayFormat>
        <label>HI HSA Benefit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI HSA Benefit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_HSA_Benefit__c/fields/Provider_Key__c.field-meta.xml
<CustomField>
    <fullName>Provider_Key__c</fullName>
    <description>This value is passed by HI and used to distinguish which TAdA provider the HSA benefit is associated to</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Provider Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HI_HSA_Benefit__c/fields/Source_Id__c.field-meta.xml
<CustomField>
    <fullName>Source_Id__c</fullName>
    <label>Source Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>A benefits Policy</description>
    <label>Policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Benefit_Type__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Type__c</fullName>
    <label>Benefit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Life</fullName>
            </value>
            <value>
                <fullName>Long Term Disability</fullName>
            </value>
            <value>
                <fullName>Short Term Disability</fullName>
            </value>
            <value>
                <fullName>Flexible Spending Account - Medical</fullName>
            </value>
            <value>
                <fullName>Flexible Spending Account - Dependent Care</fullName>
            </value>
            <value>
                <fullName>HSA</fullName>
            </value>
            <value>
                <fullName>Commuter</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
                <isActive>false</isActive>
                <label>Disability</label>
            </value>
            <value>
                <fullName>Life / Disability</fullName>
                <isActive>false</isActive>
                <label>Life / Disability</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Policy__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Policies must be related to an benefits opportunity. Please select an eligible benefits opportunity.</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change, Benefits BoR</value>
        </filterItems>
        <infoMessage>Displaying benefits opportunities only.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Policy__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Name</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Unique state abbreviation used for external lookups and relationships.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HI State Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HIHSABenefitTriggerHelperTest.cls
/**
 * @name         HIHSABenefitTriggerHelperTest
 * @author       Bhagat Singh
 * @date         30 May 2023
 * @description  Test class for HIHSABenefitTriggerHelper class.
 **/
@istest
private class HIHSABenefitTriggerHelperTest {
    /**
     * @Author      : Bhagat Singh
     * @Description : Test Class setup method
     **/
    @testSetup
    static void setupData() {
        Utils.skipTrigger(true);
        Account objAccount = new TestDataFactory.AccountBuilder().setRecordTypeId('Company').setZPCompanyID('7757616923607181').setName('Gusto HINewPlanApplication').build();
        
        Pricebook2 objPriceBook = new TestDataFactory.PriceBookBuilder().setName('Benefits 2017').setActive().build();
        insert objPriceBook;
        
        Product2 objProduct = new TestDataFactory.ProductBuilder().setName('HSA').setFamily('HSA').build();
        insert objProduct;
        
        List<PricebookEntry> list_PriceBookEntry = new List<PricebookEntry>();
        list_PriceBookEntry.add(new TestDataFactory.PricebookEntryBuilder().setProductId(objProduct.Id).setUnitPrice(5).setPriceBookId(Test.getStandardPriceBookId()).setIsActive(true).build());
        list_PriceBookEntry.add(new TestDataFactory.PricebookEntryBuilder().setProductId(objProduct.Id).setUnitPrice(5).setPriceBookId(objPriceBook.Id).setIsActive(true).build());
        insert list_PriceBookEntry;
        
        State__c objState = new TestDataFactory.StateBuilder().setName('California').setId('12').setAbbreviation('CA').build();
        insert objState;
        
        List<Carrier__c> list_Carriers = New List<Carrier__c>();
        Carrier__c objCarrier1 = new TestDataFactory.CarrierBuilder().setName('Alegeus').setUniqueName('Alegeus').setId('Alegeus001').setState('AK').setKey('Alegeus').build();
        list_Carriers.add(objCarrier1);
        
        Carrier__c objCarrier2 = new TestDataFactory.CarrierBuilder().setName('elevate').setUniqueName('elevate').setId('elevate001').setState('AK').setKey('elevate').build();
        list_Carriers.add(objCarrier2);
        
        insert list_Carriers;
        
        List<Opportunity> list_Opportunity = new List<Opportunity>();
        list_Opportunity.add(
            new TestDataFactory.OpportunityBuilder()
            .setRecordTypeId(OpportunityUtil.BENEFITS_NEW_PLAN_OPPTY_RT_ID)
            .setName('Benefits New Plan')
            .setAccountId(objAccount.Id)
            .setNumberOfEE(5)
            .setBenefitsState('CA')
            .setStage('SAL')
            .setCloseDate(System.today().addDays(30))
            .setSourceID('hawaiian_ice-new_plans_application-321')
            .setPriceBookId(objPriceBook.Id)
            .build()
            );
        list_Opportunity.add(
            new TestDataFactory.OpportunityBuilder()
            .setRecordTypeId(OpportunityUtil.BENEFITS_RENEWAL_OPPTY_RT_ID)
            .setName('Benefits New Plan')
            .setAccountId(objAccount.Id)
            .setNumberOfEE(5)
            .setBenefitsState('CA')
            .setStage('SAL')
            .setCloseDate(System.today().addDays(30))
            .setSourceID('hawaiian_ice-renewal-322')
            .setPriceBookId(objPriceBook.Id)
            .build()
            );
        insert list_Opportunity;
        
        Utils.skipTrigger(false);
    }
    
    /**
     * @Author      : Bhagat Singh
     * @Description : Validate Source Type & Source Id
     **/
    @isTest
    static void validateRequiredFields() {
        Test.startTest();
        HIHSABenefitTriggerHelper.queue = true;
        HI_HSA_Benefit__c objHSA = new TestDataFactory.HIHSABenefitBuilder()
            .setId('101')
            .setCompanyId('7757616923607181')
            .setExternalKey('hawaiian_ice-hsa-101')
            .setCreatedAt(System.Now())
            .setSourceId('321')
            .build();
        insert objHSA;
        
        Test.stopTest();
        
        objHSA = [SELECT Id, Message__c, Processing_State__c FROM HI_HSA_Benefit__c WHERE Id = :objHSA.Id];
        System.assertEquals(IntegrationUtils.ERROR_STATE, objHSA.Processing_State__c, 'Invalid Source Id');
        System.assert(objHSA.Message__c.contains(HIHSABenefitTriggerHelper.strRequiredSourceId), 'Invalid Source Id');
    }
    
    /**
     * @Author      : Bhagat Singh
     * @Description : Create Alegeus Policy with respect to NewPlanApplication Opportunity
     **/
    @isTest
    static void HINewPlanApplicationHSA() {
        Test.startTest();
        HIHSABenefitTriggerHelper.queue = true;
        HIHSABenefitTriggerHelper.skipTrigger = true;
        HI_HSA_Benefit__c objHSA = new TestDataFactory.HIHSABenefitBuilder()
            .setId('101')
            .setCompanyId('7757616923607181')
            .setExternalKey('hawaiian_ice-hsa-101')
            .setCreatedAt(System.Now())
            .setSourceId('321')
            .setSourceType('NewPlansApplication')
            .build();
        insert objHSA;
        objHSA.Provider_Key__c = 'Alegeus';
        HIHSABenefitTriggerHelper.skipTrigger = false;
        update objHSA;
        
        Test.stopTest();
        //Added for BBO-1967
        Carrier__c AlegeusCarrier = [select Id from Carrier__c where Key__c = 'Alegeus'];
        Policy__c objPolicy = [SELECT Id, Carrier__c, Benefit_Type__c FROM Policy__c WHERE Opportunity__r.Source_Id__c = 'hawaiian_ice-new_plans_application-321'];
        System.assertEquals('HSA', objPolicy.Benefit_Type__c, 'No Policy exist with respect to HSA Benefit Type');
        //Modified for BBO-1967
        System.assertEquals(AlegeusCarrier.Id, objPolicy.Carrier__c, 'No Policy exist with respect to Alegeus carrier');
    }
    
    /**
     * @Author      : Bhagat Singh
     * @Description : Create Alegeus Policy with respect to Renewal Opportunity
     **/
    @isTest
    static void HIRenewalApplicationHSA() {
        Test.startTest();
        HIHSABenefitTriggerHelper.queue = true;
        HI_HSA_Benefit__c objHSA = new TestDataFactory.HIHSABenefitBuilder()
            .setId('101')
            .setCompanyId('7757616923607181')
            .setExternalKey('hawaiian_ice-hsa-101')
            .setCreatedAt(System.Now())
            .setSourceId('322')
            .setSourceType('Renewal')
            .build();
        objHSA.Provider_Key__c = 'elevate';
        insert objHSA;
        
        Test.stopTest();
        //Added for BBO-1967
        Carrier__c elevateCarrier = [select Id from Carrier__c where Key__c = 'elevate'];
        Policy__c objPolicy = [SELECT Id, Carrier__c, Benefit_Type__c FROM Policy__c WHERE Opportunity__r.Source_Id__c = 'hawaiian_ice-renewal-322'];
        System.assertEquals('HSA', objPolicy.Benefit_Type__c, 'No Policy exist with respect to HSA Benefit Type');
        //Modified for BBO-1967
        System.assertEquals(elevateCarrier.Id, objPolicy.Carrier__c, 'No Policy exist with respect to Alegeus carrier');
    }
}