force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Ardius_Configuration__c/Ardius_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings used for Ardius Implementation</description>
    <label>Ardius Configuration</label>
</CustomObject>

unpackaged/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used for tracking any exceptions logged from Apex code</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>This field will hold the class from which the error was logged.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field will hold the class from which the error was logged.</inlineHelpText>
    <label>Class Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>Ticket-{00000000}</displayFormat>
        <label>Action Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ticket__c/fields/Lost_Detail2__c.field-meta.xml
<CustomField>
    <fullName>Lost_Detail2__c</fullName>
    <label>Lost Detail 2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lost_Detail__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>$100 fee</fullName>
            </value>
            <value>
                <fullName>Abandon</fullName>
            </value>
            <value>
                <fullName>Accountant/Tax Preparer already calc&apos;ed</fullName>
            </value>
            <value>
                <fullName>Accountant advised against Gusto</fullName>
                <isActive>false</isActive>
                <label>Accountant advised against Gusto</label>
            </value>
            <value>
                <fullName>Accountant advised against R&amp;D Credit</fullName>
                <isActive>false</isActive>
                <label>Accountant advised against R&amp;D Credit</label>
            </value>
            <value>
                <fullName>Accountant doesn&apos;t believe they qualify</fullName>
            </value>
            <value>
                <fullName>Accountant doesn&apos;t trust our numbers</fullName>
            </value>
            <value>
                <fullName>Accountant resistant to sec 174</fullName>
            </value>
            <value>
                <fullName>Accountant won&apos;t use any R&amp;D firm</fullName>
            </value>
            <value>
                <fullName>Already claimed credits (and we aren’t allowing further maximization)</fullName>
            </value>
            <value>
                <fullName>Asked to be removed from outreach</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>boast.AI</fullName>
            </value>
            <value>
                <fullName>Clarus</fullName>
            </value>
            <value>
                <fullName>Credit not high enough</fullName>
            </value>
            <value>
                <fullName>Credit size insufficient</fullName>
            </value>
            <value>
                <fullName>Customer doesn’t believe they qualify</fullName>
            </value>
            <value>
                <fullName>Customer engaged and then became unresponsive</fullName>
                <isActive>false</isActive>
                <label>Customer engaged and then became unresponsive</label>
            </value>
            <value>
                <fullName>Customer not willing to supersede</fullName>
            </value>
            <value>
                <fullName>Customer was never responsive</fullName>
                <isActive>false</isActive>
                <label>Customer was never responsive</label>
            </value>
            <value>
                <fullName>Didn&apos;t know they would have to pay</fullName>
            </value>
            <value>
                <fullName>Did not complete in tax year</fullName>
            </value>
            <value>
                <fullName>Didn’t know they’d signed TOS and aren’t interested</fullName>
            </value>
            <value>
                <fullName>Doesn&apos;t trust ML based calculation</fullName>
            </value>
            <value>
                <fullName>ER going to DIY</fullName>
            </value>
            <value>
                <fullName>Fear of getting audited</fullName>
            </value>
            <value>
                <fullName>Fraud (cannot do study)</fullName>
                <isActive>false</isActive>
                <label>Fraud (cannot do study)</label>
            </value>
            <value>
                <fullName>Hasn’t yet claimed, but doesn’t want to switch</fullName>
            </value>
            <value>
                <fullName>Just looking, no intention to buy</fullName>
            </value>
            <value>
                <fullName>Looking for payroll tax credit redemption</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Lost_Detail__c.field-meta.xml
<CustomField>
    <fullName>Lost_Detail__c</fullName>
    <label>Lost Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accountant intervention</fullName>
            </value>
            <value>
                <fullName>Account flagged / suspended in Panda</fullName>
            </value>
            <value>
                <fullName>Account suspended</fullName>
            </value>
            <value>
                <fullName>Already working with a competitor</fullName>
            </value>
            <value>
                <fullName>Company went out of business</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Customer confusion</fullName>
            </value>
            <value>
                <fullName>Disqualified by CSM</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Not interested</fullName>
            </value>
            <value>
                <fullName>Not pursuing credits this year</fullName>
            </value>
            <value>
                <fullName>Out of business</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Redemption only</fullName>
            </value>
            <value>
                <fullName>Tax related concern</fullName>
            </value>
            <value>
                <fullName>Unable to file this year</fullName>
            </value>
            <value>
                <fullName>Unknown / Customer unresponsive</fullName>
                <isActive>false</isActive>
                <label>Unknown / Customer unresponsive</label>
            </value>
            <value>
                <fullName>Value prop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>SALY</fullName>
            </value>
            <value>
                <fullName>New - Onboarding</fullName>
            </value>
            <value>
                <fullName>Verification Needed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Account Provisioned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New / QRE Review</fullName>
            </value>
            <value>
                <fullName>Finalize Portal</fullName>
            </value>
            <value>
                <fullName>Four Part Pending</fullName>
            </value>
            <value>
                <fullName>Onboard Review</fullName>
            </value>
            <value>
                <fullName>Data Load</fullName>
            </value>
            <value>
                <fullName>Report Creation</fullName>
            </value>
            <value>
                <fullName>Calc Approval Pending</fullName>
            </value>
            <value>
                <fullName>Customer Survey Pending</fullName>
            </value>
            <value>
                <fullName>Ready for Additional Qualitative</fullName>
            </value>
            <value>
                <fullName>Credit Determination</fullName>
            </value>
            <value>
                <fullName>Filed Tax Return Needed</fullName>
            </value>
            <value>
                <fullName>Tax Return - Needs Quant Team Review</fullName>
            </value>
            <value>
                <fullName>Load Credits</fullName>
            </value>
            <value>
                <fullName>Gusto Real Time Billing</fullName>
            </value>
            <value>
                <fullName>Payroll Billing (non-Gusto)</fullName>
            </value>
            <value>
                <fullName>Liability Billing - Annually</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Carryforward Credits</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Unresponsive__c.field-meta.xml
<CustomField>
    <fullName>Unresponsive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Represent the user is un-responsive for several days.</description>
    <label>Unresponsive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ArdiusIntegrationHelperTest.cls
/**
 * @description Ardius Integration Helper Test class
 * @author      Ajay Krishna P U
 * @since       2024-01-03
 */
@isTest
public with sharing class ArdiusIntegrationHelperTest {
	final static String DEBUG_LOG = 'DEBUG_LOG';
	final static String EXCEPTION_LOG = 'EXCEPTION_LOG';

	/**
	 * @description To setup initial Test data setup
	 */
	@TestSetup
	static void setupData() {
		AccountTriggerHelper.skipTrigger = true;
		OpportunityTriggerHelper.skipTrigger = true;
		TicketTriggerHelper.skipTrigger = true;

		Ardius_Configuration__c objArdiusConfig = new TestDataFactory.ArdiusConfigurationBuilder()
			.setActivateTicketIntegration(true)
			.setIntegrationInDebugMode(true)
			.build();
		insert objArdiusConfig;

		Account objAccount = new TestDataFactory.AccountBuilder()
			.setName('Test Demo AccountName 1')
			.setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID)
			.setBillingStreet('Testing Avenue 1')
			.setBillingPostalCode('123456')
			.setPhone('19992344444')
			.setCompanyTradeName('Company trade name 1')
			.setShippingStreet('Testing Avenue 1')
			.setShippingPostalCode('123455')
			.build();
		insert objAccount;

		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(OpportunityUtil.R_D_TAX_CREDITS_OPPTY_RT_ID)
			.setAccountId(objAccount.Id)
			.setName('Test Ardius Opportunity')
			.setStage(OpportunityUtil.NEW_STAGE)
			.setCloseDate(System.today())
			.build();
		insert objOpportunity;

		Ticket__c objTicket = new TestDataFactory.TicketBuilder()
			.setOppId(objOpportunity.Id)
			.setAccountId(objAccount.Id)
			.setStatus(TicketUtil.TICKET_STATUS_NEW)
			.setDescription('Test Ardius')
			.setOwnerId(UserInfo.getUserId())
			.setRecordTypeId(TicketUtil.ARDIUS_TICKET_RT_ID)
			.build();
		insert objTicket;

		AccountTriggerHelper.skipTrigger = false;
		OpportunityTriggerHelper.skipTrigger = false;
		TicketTriggerHelper.skipTrigger = false;
	}

	/**
	 * @description Test Un Responsive API
	 * triggered when Unresponsive__c = true
	 */
	@isTest
	static void testUnResponsive() {
		Test.setMock(HttpCalloutMock.class, new GeneralSuccessCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		Test.startTest();
		objTicket.Unresponsive__c = true;
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - Unresponsive, success log did not generated');
		System.assertEquals(0, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - Unresponsive, exception log generated');
	}

	/**
	 * @description Test Un Responsive API
	 * triggered when Unresponsive__c = false
	 */
	@isTest
	static void testResponsive() {
		Test.setMock(HttpCalloutMock.class, new GeneralSuccessCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		//Skip trigger ==> skip integration
		TicketTriggerHelper.skipTrigger = true;
		objTicket.Unresponsive__c = true;
		update objTicket;
		TicketTriggerHelper.skipTrigger = false;

		Test.startTest();
		objTicket.Unresponsive__c = false;
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - Responsive, success log did not generated');
		System.assertEquals(0, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - Responsive, exception log generated');
	}

	/**
	 * @description Test Lost API
	 * triggered when Status__c = Lost
	 */
	@isTest
	static void testLost() {
		Test.setMock(HttpCalloutMock.class, new GeneralSuccessCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		Test.startTest();
		objTicket.Status__c = TicketUtil.TICKET_STATUS_LOST;
		objTicket.Lost_Detail__c = 'Price';
		objTicket.Lost_Detail2__c = 'Other';
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - Lost, success log did not generated');
		System.assertEquals(0, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - Lost, exception log generated');
	}

	/**
	 * @description Test UnLost API
	 * triggered when Status__c Changed from Lost to other
	 */
	@isTest
	static void testUnLost() {
		Test.setMock(HttpCalloutMock.class, new GeneralSuccessCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		//Skip trigger ==> skip integration
		TicketTriggerHelper.skipTrigger = true;
		objTicket.Status__c = TicketUtil.TICKET_STATUS_LOST;
		objTicket.Lost_Detail__c = 'Price';
		objTicket.Lost_Detail2__c = 'Other';
		update objTicket;
		TicketTriggerHelper.skipTrigger = false;

		Test.startTest();
		objTicket.Status__c = TicketUtil.TICKET_STATUS_NEW;
		objTicket.Lost_Detail__c = null;
		objTicket.Lost_Detail2__c = null;
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - UnLost, success log did not generated');
		System.assertEquals(0, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - UnLost, exception log generated');
	}

	/**
	 * @description Test UnResponsive API Failure
	 */
	@isTest
	static void testUnResponsiveFailure() {
		Test.setMock(HttpCalloutMock.class, new GeneralFailureCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		Test.startTest();
		objTicket.Unresponsive__c = true;
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - UnResponsive, log did not generated');
		System.assertEquals(1, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - UnResponsive, exception log did not generated');
	}

	/**
	 * @description Test Lost API Failure
	 */
	@isTest
	static void testLostFailure() {
		Test.setMock(HttpCalloutMock.class, new GeneralFailureCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		Test.startTest();
		objTicket.Status__c = TicketUtil.TICKET_STATUS_LOST;
		objTicket.Lost_Detail__c = 'Price';
		objTicket.Lost_Detail2__c = 'Other';
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - Lost,  log did not generated');
		System.assertEquals(1, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - Lost, exception log did not generated');
	}

	/**
	 * @description Test UnLost API Failure
	 */
	@isTest
	static void testUnLostFailure() {
		Test.setMock(HttpCalloutMock.class, new GeneralFailureCalloutMock());

		List<Ticket__c> list_Tickets = [SELECT Id FROM Ticket__c WHERE RecordTypeId = :TicketUtil.ARDIUS_TICKET_RT_ID LIMIT 1];
		System.assertEquals(1, list_Tickets.size(), 'Test data Ticket unavailable');
		Ticket__c objTicket = list_Tickets[0];

		//Skip trigger ==> skip integration
		TicketTriggerHelper.skipTrigger = true;
		objTicket.Status__c = TicketUtil.TICKET_STATUS_LOST;
		objTicket.Lost_Detail__c = 'Price';
		objTicket.Lost_Detail2__c = 'Other';
		update objTicket;
		TicketTriggerHelper.skipTrigger = false;

		Test.startTest();
		objTicket.Status__c = TicketUtil.TICKET_STATUS_NEW;
		objTicket.Lost_Detail__c = null;
		objTicket.Lost_Detail2__c = null;
		update objTicket;
		Test.stopTest();

		Map<String, List<Exception_Log__c>> map_TypeToLogs = getIntegrationLogs();
		System.assertEquals(1, map_TypeToLogs.get(DEBUG_LOG).size(), 'Failed - UnLost,  log did not generated');
		System.assertEquals(1, map_TypeToLogs.get(EXCEPTION_LOG).size(), 'Failed - UnLost, exception log did not generated');
	}

	/**
	 * @description Utility method to get the Integration status
	 * @return      `Map<String, List<Exception_Log__c>>`
	 */
	static Map<String, List<Exception_Log__c>> getIntegrationLogs() {
		Map<String, List<Exception_Log__c>> map_TypeToLogs = new Map<String, List<Exception_Log__c>>{ EXCEPTION_LOG => new List<Exception_Log__c>(), DEBUG_LOG => new List<Exception_Log__c>() };

		for (Exception_Log__c objLog : [SELECT Id, Class_Name__c FROM Exception_Log__c WHERE Class_Name__c LIKE 'ArdiusIntegrationHelper%']) {
			if (objLog.Class_Name__c.contains(' Debug')) {
				map_TypeToLogs.get(DEBUG_LOG).add(objLog);
			} else {
				map_TypeToLogs.get(EXCEPTION_LOG).add(objLog);
			}
		}

		return map_TypeToLogs;
	}

	/**
	 * Mock Response - Success
	 */
	public class GeneralSuccessCalloutMock implements HttpCalloutMock {
		public HTTPResponse respond(HTTPRequest request) {
			HttpResponse objResponse = new HttpResponse();
			objResponse.setHeader('Content-Type', 'application/json');
			objResponse.setBody('{"status": "SUCCESS"}');
			objResponse.setStatusCode(200);
			return objResponse;
		}
	}

	/**
	 * Mock Response - Failure
	 */
	public class GeneralFailureCalloutMock implements HttpCalloutMock {
		public HTTPResponse respond(HTTPRequest request) {
			HttpResponse objResponse = new HttpResponse();
			objResponse.setHeader('Content-Type', 'application/json');
			objResponse.setBody('{"status":"FAILURE","event_id":"0","response":"failed: bad request (400)"}');
			objResponse.setStatusCode(400);
			return objResponse;
		}
	}
}