force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/AI_Interaction_Detail__c/AI_Interaction_Detail__c.object-meta.xml
<CustomObject>
    <description>Object captures interaction with AI.
Data provided, related case, response received, if any errors.</description>
    <label>AI Interaction Detail</label>
    <nameField>
        <displayFormat>AID-{00000000}</displayFormat>
        <label>AI Interaction Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AI Interaction Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/AI_Response__c.field-meta.xml
<CustomField>
    <fullName>AI_Response__c</fullName>
    <description>Captures response received by AI.</description>
    <label>AI Response</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will be used to link AI Interaction details with chat transcript to display chat history.</description>
    <label>Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>AI Interaction Details</relationshipLabel>
    <relationshipName>AI_Interaction_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AI_Interaction_Detail__c/fields/User_Question__c.field-meta.xml
<CustomField>
    <fullName>User_Question__c</fullName>
    <description>Captures user typed question.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/LiveChatTranscript/recordTypes/Internal.recordType-meta.xml
<RecordType>
    <fullName>Internal</fullName>
    <active>true</active>
    <label>Internal</label>
</RecordType>

force-app/main/default/objects/Tier_Config__c/Tier_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration used to store names of old tiers and plans</description>
    <label>Tier Config</label>
</CustomObject>

force-app/main/default/objects/Tier_Config__c/fields/New_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>New_Tier_2__c</fullName>
    <description>Name of new Tier 2 - Typically it is called Plus</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Tier 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChimaAISupportAuraCtrlTest.cls
/**
 * @name         : ChimaAISupportAuraCtrlTest
 * @author       : Yogesh Kherajani
 * @date         : 24/04/2024
 * @description  : This class has test methods for ChimaAISupportAuraCtrl
 **/
@isTest
public class ChimaAISupportAuraCtrlTest {
    /**
	 * @Author      : Yogesh Kherajani
	 * @Description : This method creates all the test data.
	 **/
	@testSetup
    private static void setupData(){
        // insert org default tier config settings
		Tier_Config__c objTierConfig = new TestDataFactory.TierConfigBuilder().build();
		insert objTierConfig;

		//Account creation
		Account objAccount = new TestDataFactory.AccountBuilder()
			.setName('TestAccount')
			.setZPCompanyId('12312321')
			.setZPFirmId('12312321')
			.setConciergeGroupId('test')
			.setConciergeGroup('test')
			.setTier(objTierConfig.New_Tier_2__c)
			.setAMTier('Gold')
			.setRecordTypeId('Company')
			.build();
		AccountTriggerHelper.skipTrigger = true;
		insert objAccount;

		//Contact creation
		Contact objContact = new TestDataFactory.ContactBuilder()
            .setAccountId(objAccount.Id)
            .setLastName('TestContact')
            .setRecordTypeId('Company')
            .setZPUserId('12312321')
            .build();
		ContactTriggerHelper.skipTrigger = true;
		insert objContact;

		//Case creation
		Case objCase = new TestDataFactory.CaseBuilder()
			.setSubject('Om Test')
			.setStatus('New')
			.setOrigin('Email')
			.setSuppliedEmail('test@gmail.com')
			.setRecordTypeId('Payroll Care')
			.setAccountId(objAccount.Id)
			.setContactId(objContact.Id)
			.build();
		CaseTriggerHelper.skipTrigger = true;
		insert objCase;
        
        LiveChatVisitor objLiveChatVisitor = new LiveChatVisitor();
		insert objLiveChatVisitor;
        
        LiveChatTranscript objLiveChatTranscript = new TestDataFactory.LiveChatTranscriptBuilder()
            .setRecordTypeId('Internal')
            .setCaseId(objCase.Id)
            .setChatVisitor(objLiveChatVisitor.Id)
            .setChatKey('123')
            .build();
		insert objLiveChatTranscript;
    }
    
    /**
	 * @Author      : Yogesh Kherajani
	 * @Description : To test the handleUpdateLiveChatTranscriptOnAIInteraction method.
	 **/
    @isTest
    private static void handleUpdateLiveChatTranscriptOnAIInteractionUnitTest(){
        Case objCase = [
            SELECT Id
            FROM Case
            LIMIT 1
        ];
        
        AI_Interaction_Detail__c objAIInteractionDetail = new AI_Interaction_Detail__c();
        objAIInteractionDetail.User_Question__c = 'How to add an employee?';
        objAIInteractionDetail.AI_Response__c = 'Here is the article';
        
        INSERT objAIInteractionDetail;
        
        ChimaAISupportAuraCtrl.handleUpdateLiveChatTranscriptOnAIInteraction('123', new List<String>{objAIInteractionDetail.Id});
        
        LiveChatTranscript objLiveChatTranscript = [
            SELECT Id 
            FROM LiveChatTranscript
            WHERE CaseId = :objCase.Id 
            ORDER BY CreatedDate 
            DESC 
            LIMIT 1
        ];
        
        List<AI_Interaction_Detail__c> lst_AIInteractionDetail = [
            SELECT Id 
            FROM AI_Interaction_Detail__c 
            WHERE Chat_Transcript__c = :objLiveChatTranscript.Id
        ];
        
        System.assertEquals(lst_AIInteractionDetail.isEmpty(), false, 'AI Interaction Record should linked with Chat Transcript.');
    }
    
    /**
	 * @Author      : Yogesh Kherajani
	 * @Description : To test the updateAgentFeedback method.
	 **/
    @isTest
    private static void updateAgentFeedbackUnitTest(){
        ChimaAISupportAuraCtrl.updateAgentFeedback('123', 'Feedback', '1');
        
        List<AI_Interaction_Detail__c> lst_AIInteractionDetail = [
            SELECT Id 
            FROM AI_Interaction_Detail__c
        ];
        
        System.assertEquals(lst_AIInteractionDetail.isEmpty(), false, 'AI Interaction Record should be created');
    }
    
    /**
	 * @Author      : Yogesh Kherajani
	 * @Description : To test the getLiveChatTranscriptDetail method.
	 **/
    @isTest
    private static void getLiveChatTranscriptDetailUnitTest(){
        List<LiveChatTranscript> lst_LiveChatTranscript = ChimaAISupportAuraCtrl.getLiveChatTranscriptDetail('123');
        
        System.assertEquals(lst_LiveChatTranscript.isEmpty(), false, 'Live Chat Transcript Record should not be empty.');
    }
}