force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Primary_Call_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Call_Reason__c</fullName>
    <description>This is prepopulated from task Contact Reason field</description>
    <label>Contact Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
                <label>Transfer / Other Team Responsibility</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Secondary_Call_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Call_Reason__c</fullName>
    <description>This is mostly prepopuated from task sub-contact reason field</description>
    <label>Sub-Contact Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Primary_Call_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Company’s Address</fullName>
            </value>
            <value>
                <fullName>Add accountant</fullName>
            </value>
            <value>
                <fullName>Explore Benefits</fullName>
            </value>
            <value>
                <fullName>Add Employees | Add Contractors</fullName>
            </value>
            <value>
                <fullName>Set Up Federal Taxes</fullName>
            </value>
            <value>
                <fullName>Set Up State Taxes</fullName>
            </value>
            <value>
                <fullName>Bank Account | Verify Bank Account</fullName>
            </value>
            <value>
                <fullName>Select A Payroll Schedule</fullName>
            </value>
            <value>
                <fullName>Report Previous Paystubs</fullName>
            </value>
            <value>
                <fullName>Sign Documents | Add Signatory</fullName>
            </value>
            <value>
                <fullName>Unpaid Tax Liabilities</fullName>
            </value>
            <value>
                <fullName>Workers Compensation</fullName>
            </value>
            <value>
                <fullName>R&amp;D Tax Credit</fullName>
            </value>
            <value>
                <fullName>Discover App, Integration, or Partner</fullName>
            </value>
            <value>
                <fullName>Choose A Plan</fullName>
            </value>
            <value>
                <fullName>RFI / Assurance</fullName>
            </value>
            <value>
                <fullName>Run Payroll</fullName>
            </value>
            <value>
                <fullName>After Payroll / Not transferred</fullName>
            </value>
            <value>
                <fullName>JIRA - please post link in notes</fullName>
            </value>
            <value>
                <fullName>Sold | Notate APD</fullName>
            </value>
            <value>
                <fullName>Running it by decision maker</fullName>
            </value>
            <value>
                <fullName>25+ Employees | Pass To Another Team</fullName>
            </value>
            <value>
                <fullName>Not Sold | Determine Closed Lost</fullName>
            </value>
            <value>
                <fullName>Bad Transfer from Care (not an FEIN change)</fullName>
            </value>
            <value>
                <fullName>Transfer to Care</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <description>Used to log emails sent from users who are not MM or Partner. &quot;Type&quot; is used to differentiate between automated and personal emails.</description>
    <label>Email</label>
</RecordType>

force-app/main/default/classes/SalesCaseEmailHelperTest.cls
/**
 * @author Lalitha kasturi
 * @date June 29, 2022
 * @description  Test class for SalesCaseEmailHelper
 */
@isTest
public class SalesCaseEmailHelperTest {
	public static Integer generateRandomId() {
		return Integer.valueOf(10000000 + Math.rint(Math.random() * 90000000));
	}

	@testSetup
	static void setUp() {
		TriggerHandler.bypass('AccountTriggerHandler');
		TriggerHandler.bypass('ContactTriggerHanlder');
		OpportunityTriggerHelper.skipTrigger = true;

		Account objAccount = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setName('Test Company Account').build();
		insert objAccount;

		Contact objContact = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
			.setAccountId(objAccount.Id)
			.setFirstName('TEST CONTACT')
			.setLastName('CONTACT')
			.setPhone('1234567890')
			.setEmail('test.contact@gusto.com')
			.setZPUserId(String.valueOf(generateRandomId()))
			.build();

		insert objContact;

		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setAccountId(objAccount.Id)
			.setName('Test Sales Opportunity')
			.setCloseDate(System.today())
			.setRecordTypeId(OpportunityUtil.BENEFITS_CHANGE_OPPTY_RT_ID)
			.setSourceID('343434')
			.setStage('SAL')
			.build();
		insert objOpportunity;

		OpportunityContactRole objContactRole = new TestDataFactory.OpportunityContactRoleBuilder().setOpportunityId(objOpportunity.Id).setContactId(objContact.Id).build();

		insert objContactRole;

		Task objTask = new TestDataFactory.TaskBuilder()
			.setRecordTypeId(TaskUtil.TASK_CALL_RT_ID)
			.setWhatId(objOpportunity.Id)
			.setSubject('Subject')
			.setStatus(TaskUtil.TASK_STATUS_IN_PROGRESS)
			.setContactReason('Onboarding')	
			.setSubContactReason('Add Accountant')
			.build();
		insert objTask;
	}

	@isTest
	private static void SendFollowUpEmailTest() {
		Task objTask = [SELECT Id, WhatId, Case__c FROM Task LIMIT 1];

		SalesCaseEmailHelper.Requests objReqInput = new SalesCaseEmailHelper.Requests();
		objReqInput.strTaskRecordInputId = objTask.Id;
		List<SalesCaseEmailHelper.Requests> list_Requests = new List<SalesCaseEmailHelper.Requests>();
		list_Requests.add(objReqInput);

		Test.startTest();
		List<SalesCaseEmailHelper.Results> list_Results = SalesCaseEmailHelper.CreateCaseForFollowUpEmail(list_Requests);
		Test.stopTest();

		Case objCase = [SELECT Id, CaseNumber, RecordTypeId, Primary_Call_Reason__c, Secondary_Call_Reason__c FROM Case WHERE Id = :list_Results[0].strCaseId LIMIT 1];
		Task objTaskResult = [SELECT Id, Case__c, Primary_Call_Reason__c, Secondary_Call_Reason__c FROM Task WHERE Id = :objTask.Id LIMIT 1];

		System.assert(list_Results[0].strCaseId != null);
		System.assertEquals(objCase.RecordTypeId, CaseUtils.RECTYPE_SALES_CASES);
		System.assert(objTaskResult.Case__c == objCase.Id);
		System.assertEquals(objCase.Primary_Call_Reason__c.toLowerCase(), objTaskResult.Primary_Call_Reason__c.toLowerCase());
		System.assertEquals(objCase.Secondary_Call_Reason__c.toLowerCase(), objTaskResult.Secondary_Call_Reason__c.toLowerCase());

		EmailMessage objMessage = new TestDataFactory.EmailMessageBuilder()
			.setParentId(objCase.Id)
			.setFromAddress('supporttest@gustotest.com')
			.setToAddress('test.contact@gusto.com')
			.setSubject('test outbound email to auto close')
			.setIncoming(false)
			.setTextBody('Sending test email outbound to auto close sales case')
			.build();
		insert objMessage;
		Case objCaseUpdated = [SELECT Id, Status FROM Case WHERE Id = :list_Results[0].strCaseId LIMIT 1];
		System.assertEquals(objCaseUpdated.Status, CaseUtils.STATUS_CLOSED);
	}
}