force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HI Carrier Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>Lowercase concatenation of carrier name with state. Hyphen delimitated.</description>
    <externalId>true</externalId>
    <label>HI Carrier Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Configuration_Settings__c/fields/Active_TAdA_Provider__c.field-meta.xml
<CustomField>
    <fullName>Active_TAdA_Provider__c</fullName>
    <description>This Stores the Carrier Key value of the TAdA Provider Gusto currently partners with</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This Stores the Carrier Key value of the TAdA Provider Gusto currently partners with</inlineHelpText>
    <label>Active TAdA Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ZenPayroll or Hawaiian Ice External Id
Prefixed with model name for uniqueness.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HIUpsellInformationUtil.cls
/***
    Created by : Swati Arya
    Created Date : 03/24/2023
    Description: Hi Upsell Information related Utilities for reuse
**/
public class HIUpsellInformationUtil {
	public static final String COMPANY_ID_EMPTY = 'Company Id is empty.';
	public static final String EXTERNAL_KEY_EMPTY = 'External key is empty.';
	public static final String BENEFIT_TYPE_EMPTY = 'Benefit type is empty.';
	public static final String COMPANY_NOT_EXIST = 'Company does not exist.';
	public static final String OPPTY_DONT_EXIST = 'Opportunity does not exist.';
	public static final String UPSELL_TYPE_NEW_TADA = 'New TAdA Plan';
	public static final String UPSELL_TYPE_TRANSFER_TADA = 'Transfer TAdA Plan';
	public static final String STR_NEW_BENEFIT = 'new_benefit';
	public static final String STR_TRANSFER_BENEFIT = 'transfer_benefit';
	public static final String STR_FSA = 'fsa';
	public static final String STR_DCA = 'dca';
	public static final String STR_HSA = 'HSA';
	public static final String STR_COMMUTER = 'Commuter';
	public static final String STR_FSA_MEDICAL = 'Flexible Spending Account - Medical';
	public static final String STR_FSA_DEPENDENT = 'Flexible Spending Account - Dependent Care';
	public static final String STR_HI_BENEFIT_INTEREST = 'HIBENEFITINTEREST';
	public static final String STR_CHANGE = 'Change';
	public static final String STR_MODE_NORMAL = 'Normal';
	public static final String DUPLICATE_VALUE_ERROR_MSG = 'duplicate value found: Id__c duplicates value on record with id:';

	public static final List<String> POLICY_BENEFIT_TYPES = new List<String>{ STR_FSA_MEDICAL, STR_FSA_DEPENDENT, STR_HSA, STR_COMMUTER };

	/**
	 * @author      Deepika
	 * @description Get Carrier which is saved in the Configuration setting
	 * @param       N/A
	 * @return      Carrier__c
	 **/
	public static Carrier__c getActiveTadaCarrier() {
		Configuration_Settings__c objConfig = Configuration_Settings__c.getOrgDefaults();
		Carrier__c objCarrier = new Carrier__c();

		if (objConfig != null && objConfig.Active_TAdA_Provider__c != null) {
			String strCOTadaKey = String.valueOf(objConfig.Active_TAdA_Provider__c);
			objCarrier = [SELECT Id, Key__c, Name FROM Carrier__c WHERE Key__c = :strCOTadaKey LIMIT 1];
		}
		return objCarrier;
	}
}