force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Customer_Health__c/Customer_Health__c.object-meta.xml
<CustomObject>
    <description>Custom Object to primarily store churn prevention data of companies.</description>
    <label>Customer Health</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Customer Health Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Health</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Customer_Health__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to account matching company Id</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Health</relationshipLabel>
    <relationshipName>Customer_Health</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpenCustomerHealthScoreControllerTest.cls
/**
 * @description  Test Class for OpenCustomerHealthScoreController
 * @author       Debasmita Rawooth
 * @date         03-12-2024
 **/
@isTest
public with sharing class OpenCustomerHealthScoreControllerTest {
	@isTest
	public static void testOpenCHSPositive() {
		Account objCompAccount = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setName('Company Account CHS').setZPCompanyId('1111111111').build();
		insert objCompAccount;

		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(OpportunityUtil.CUSTOMER_SUCCESS_RT_ID)
			.setName('CS Opp')
			.setAccountId(objCompAccount.Id)
			.setStage('New')
			.setCloseDate(System.today())
			.build();
		insert objOpportunity;

		Customer_Health__c objCustHealth = new TestDataFactory.CustomerHealthBuilder()
			.setCompanyId('1111111111')
			.setUpgradePropensity('medium upgrade propensity')
			.setHINPRank(0.5)
			.setChurnScore(0.2)
			.build();

		insert objCustHealth;

		Test.startTest();
		Id idCHSRecId = OpenCustomerHealthScoreController.getCHSRecordId(objOpportunity.Id);
		Customer_Health__c objCHSAssert = [SELECT Id, Name, Account__c FROM Customer_Health__c WHERE Id = :idCHSRecId];
		Test.stopTest();

		System.assertEquals(objOpportunity.AccountId, objCHSAssert.Account__c, 'CHS record Id is not fetched correctly.');
	}
	@isTest
	public static void testOpenCHSNegative() {
		Account objCompAccount = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setName('Company Account CHS').setZPCompanyId('1111111111').build();
		insert objCompAccount;

		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(OpportunityUtil.CUSTOMER_SUCCESS_RT_ID)
			.setName('CS Opp')
			.setAccountId(objCompAccount.Id)
			.setStage('New')
			.setCloseDate(System.today())
			.build();
		insert objOpportunity;

		Test.startTest();
		Id idCHSRecId;
		try {
			idCHSRecId = OpenCustomerHealthScoreController.getCHSRecordId(objOpportunity.Id);
		} catch (Exception objEx) {
			//Testing exception scenario
		}
		Test.stopTest();

		System.assertEquals(idCHSRecId, null, 'Exception Handling did not work correctly');
	}
}