force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Action_Necessary_Notes__c.field-meta.xml
<CustomField>
    <fullName>Action_Necessary_Notes__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <label>Action Necessary Notes</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/External_Deductions__c.field-meta.xml
<CustomField>
    <fullName>External_Deductions__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <label>External Deductions</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/External_Deductions_for_LiDi__c.field-meta.xml
<CustomField>
    <fullName>External_Deductions_for_LiDi__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <label>External Deductions for LiDi</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/GDrive_Link__c.field-meta.xml
<CustomField>
    <fullName>GDrive_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>GDrive Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Is_Multi_EIN__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_EIN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used by Benefit Transfer team</description>
    <label>Is Multi-EIN</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Number_Of_Collected_Documents__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Collected_Documents__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Used by Benefit Transfer team</description>
    <label>Number Of Collected Documents</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Qualification_Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Follow_Up_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Qualification Follow Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Qualification_Follow_Up_Notes__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Follow_Up_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Qualification Follow Up Notes</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Useful_docs_in_attachments__c.field-meta.xml
<CustomField>
    <fullName>Useful_docs_in_attachments__c</fullName>
    <description>Used by Benefit Transfer team</description>
    <label>Useful docs in attachments?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/UW_Owner__c.field-meta.xml
<CustomField>
    <fullName>UW_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Qualification Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Benefit_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/GDrive_Link__c.field-meta.xml
<CustomField>
    <fullName>GDrive_Link__c</fullName>
    <description>Benefit Transfer - Used in Facilitator Module</description>
    <formula>Benefit_Order__r.GDrive_Link__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDrive Link</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/Is_Multi_EIN__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_EIN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Benefit Transfer - This field we are using to identify whether it is multi EIN or not.</description>
    <label>Is Multi-EIN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Number_Of_Collected_Documents__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Collected_Documents__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Benefit Transfer - To get the number of collected checklist document</description>
    <label>Number Of Collected Documents</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GDrive_Link__c.field-meta.xml
<CustomField>
    <fullName>GDrive_Link__c</fullName>
    <description>Google Drive Link - GEP Opportunity Info</description>
    <label>GDrive Link</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Is_Multi_EIN__c.field-meta.xml
<CustomField>
    <fullName>Is_Multi_EIN__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used this field in Advising Email Automation</description>
    <label>Is Multi-EIN</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>Ticket-{00000000}</displayFormat>
        <label>Action Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>SALY</fullName>
            </value>
            <value>
                <fullName>New - Onboarding</fullName>
            </value>
            <value>
                <fullName>Verification Needed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Account Provisioned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New / QRE Review</fullName>
            </value>
            <value>
                <fullName>Finalize Portal</fullName>
            </value>
            <value>
                <fullName>Four Part Pending</fullName>
            </value>
            <value>
                <fullName>Onboard Review</fullName>
            </value>
            <value>
                <fullName>Data Load</fullName>
            </value>
            <value>
                <fullName>Report Creation</fullName>
            </value>
            <value>
                <fullName>Calc Approval Pending</fullName>
            </value>
            <value>
                <fullName>Customer Survey Pending</fullName>
            </value>
            <value>
                <fullName>Ready for Additional Qualitative</fullName>
            </value>
            <value>
                <fullName>Credit Determination</fullName>
            </value>
            <value>
                <fullName>Filed Tax Return Needed</fullName>
            </value>
            <value>
                <fullName>Tax Return - Needs Quant Team Review</fullName>
            </value>
            <value>
                <fullName>Load Credits</fullName>
            </value>
            <value>
                <fullName>Gusto Real Time Billing</fullName>
            </value>
            <value>
                <fullName>Payroll Billing (non-Gusto)</fullName>
            </value>
            <value>
                <fullName>Liability Billing - Annually</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Carryforward Credits</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BTBOSideViewCtrlTest.cls
/**
* @name         BTBOSideViewCtrlTest
* @author       Vinay 
* @date         27-02-2020
* @description  Test class for BTBOSideViewCtrl class . VF page - BTBOSideView
**/
@isTest
public class BTBOSideViewCtrlTest {

    static testmethod void  testBTBOSideViewCtrl(){
       OpportunityTriggerHelper.skipTrigger=true;
	   AccountTriggerHelper.skipTrigger=true;
       BenefitOrderHelper.skipTrigger=true;
	   BenefitOrderHelper.skipTaskCreation=true;
        
        account acc1 = TestUtility.CompanyAccount();
        
        Opportunity opp1 = TestUtility.BenefitsNewPlanOpportunity();
  
       Benefit_Order__c boRec = TestUtility.createTestBenefitOrder('New Plan', opp1.Id, 'Test Benefit Order', true); 
       borec.Qualification_Follow_Up_Date__c=Date.newInstance(2016, 12, 9);
       borec.Qualification_Follow_Up_Notes__c	='test data';
       borec.UW_Owner__c = NULL; 
       borec.External_Deductions_for_LiDi__c='yes';
       borec.External_Deductions__c = 'yes';
       borec.Useful_docs_in_attachments__c	='yes';
       borec.Order_Status__c = 'Qualification';
       borec.GDrive_Link__c = 'http://Link';
       borec.Number_Of_Collected_Documents__c=11;
       borec.Action_Necessary_Notes__c='test';
       borec.Is_Multi_EIN__c=true;
       borec.Letters_sent_to_all_carriers__c=true;
       borec.Order_Status__c = 'Ready for Qualification';
       update borec;
        
       
       Benefit_Order__c boRecChild = TestUtility.createTestBenefitOrder('New Plan', opp1.Id, 'Test Benefit Order', true); 
       boRecChild.Qualification_Follow_Up_Date__c=Date.newInstance(2016, 12, 9);
       boRecChild.Qualification_Follow_Up_Notes__c	='test data';
       boRecChild.UW_Owner__c = NULL; 
       boRecChild.External_Deductions_for_LiDi__c='yes';
       boRecChild.External_Deductions__c = 'yes';
       boRecChild.Useful_docs_in_attachments__c	='yes';
       boRecChild.Order_Status__c = 'Qualification';
       boRecChild.GDrive_Link__c = 'http://Link';
       boRecChild.Number_Of_Collected_Documents__c=11;
       boRecChild.Action_Necessary_Notes__c='test';
       boRecChild.Is_Multi_EIN__c=true;
       boRecChild.Letters_sent_to_all_carriers__c=true;
       boRecChild.Order_Status__c = 'Ready for Qualification';
       boRecChild.Parent_Benefit_Order__c=borec.id;
       update boRecChild;
        
       Case cse = new Case();
        cse.RecordTypeId = cache.getRecordTypeId('Case', 'Benefits BoR');
        cse.AccountId = acc1.Id;
        cse.Benefit_Order__c=borec.id;
        cse.Subject='Test';
        cse.Description='Test';
        cse.Type='QLE';
        cse.Origin='Email';
        insert cse;
              
       Carrier__c objCarrier = TestUtility.createTestCarrier('Alegeus','NY' ,true);
       
       Carrier_Order__c obj_CarrierOrder = TestUtility.createTestCarrierOrder(objCarrier.id, 'CarrierORderHandlerTest', boRec.id, true); 
       obj_CarrierOrder.Implementation_Stage__c= 'Ready for Document Collection';	
       Id rectype = Schema.SObjectType.Carrier_Order__c.getRecordTypeInfosByName().get('Benefits BoR').getRecordTypeId();
       obj_CarrierOrder.RecordTypeId=rectype;
       obj_CarrierOrder.Is_Multi_EIN__c=true;
       obj_CarrierOrder.Benefit_Types__c = 'Medical';
       update obj_CarrierOrder;
         
        
       /* Ticket__c t1 = new Ticket__c();
        t1.Carrier_Order__c= obj_CarrierOrder.id;
        t1.Status__c ='new';
        insert t1;
        */
       ApexPages.currentPage().getParameters().put('IdOwner',boRec.id);
       ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(boRec);
       BTBOSideViewCtrl obj1 = new BTBOSideViewCtrl(sc);
       
        
       obj1.UpdateStage();
       obj1.qualifyOrder();
       System.assertEquals(obj1.blnShowQualifyButton, false, 'Qualify button is visible');
       
       obj1.blnCustomerSignedApp=true;
       obj1.blnIsADV=true;
       obj1.blnShowTADASection=true;
        
       obj1.saveBO();
       obj1.MarkTADAComplete();
       obj1.acceptOrder();
       System.assertEquals(obj1.blnShowAcceptOrderButton, false, 'Accept Order button is visible');
    }
    
   
}