force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Benefit_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change</value>
        </filterItems>
        <infoMessage>Displaying new plan, change, and renewal opportunities only.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <description>A mid-term changes to an existing benefits package.</description>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/BoR_Transfer__c/BoR_Transfer__c.object-meta.xml
<CustomObject>
    <description>https://github.com/Gusto/hawaiian-ice/blob/development/app/models/bor_transfer.rb</description>
    <label>BoR Transfer</label>
    <nameField>
        <displayFormat>BOR{000000000}</displayFormat>
        <label>BoR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BoR Transfers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/BOR_Transfer_Email_List__c.field-meta.xml
<CustomField>
    <fullName>BOR_Transfer_Email_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter in the format
&lt;Description&gt;::&lt;Email&gt;
&lt;Description&gt;::&lt;Email&gt;</inlineHelpText>
    <label>BOR Transfer Email List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/New_Plan_Email_List__c.field-meta.xml
<CustomField>
    <fullName>New_Plan_Email_List__c</fullName>
    <inlineHelpText>Enter email in the format
&lt;Description&gt;::&lt;Email&gt;
&lt;Description&gt;::&lt;Email&gt;</inlineHelpText>
    <label>New Plan Email List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/Renewal_Email_List__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Email_List__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter in the format
&lt;Description&gt;::&lt;Email&gt;
&lt;Description&gt;::&lt;Email&gt;</inlineHelpText>
    <label>Renewal Email List</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/BoR_Transfer__c.field-meta.xml
<CustomField>
    <fullName>BoR_Transfer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BoR Transfer</label>
    <referenceTo>BoR_Transfer__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Federal</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>A benefits Policy</description>
    <label>Policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Policy__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Policy__c/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Carrier Order Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Policies must be related to an benefits opportunity. Please select an eligible benefits opportunity.</errorMessage>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change, Benefits BoR</value>
        </filterItems>
        <infoMessage>Displaying benefits opportunities only.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Policy__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State Name</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EmailCarrierListCaseExtension.cls
public without sharing class EmailCarrierListCaseExtension {

    public Case theCase {get; private set;}
    public String email {get; set;}
    public String fromEmail {get; set;}
    public String carrierId {get; set;}
    public List<SelectOption> carrierOptions {get; private set;}
    public List<SelectOption> emailOptions {get; private set;}

        
    public EmailCarrierListCaseExtension(ApexPages.StandardController controller) {

        
        theCase = (Case) controller.getRecord();
        theCase = [Select Id, Opportunity__c,Benefit_Order__c,RecordType.Name from Case where Id=:theCase.id];
        email='';
        carrierId='';
        if(theCase.RecordType.Name.indexOf('Renewal')>-1 || theCase.RecordType.Name.indexOf('Change')>-1){
            fromEmail = Label.RenewalCaseCarrierEmail;
        }else if(theCase.RecordType.Name.indexOf('New Plan')>-1){
            fromEmail = Label.NewPlanCaseCarrierEmail;
        }else if(theCase.RecordType.Name.indexOf('Benefits BoR')>-1){
            fromEmail = Label.BORTransferCaseCarrierEmail;
        }
        carrierOptions = new List<SelectOption>();
        SelectOption optn = new SelectOption('','');
        carrierOptions.add(optn);
    
    //Lirik - Not in USE - Migration for BOR to BO -- Start ---
       // if(theCase.Opportunity__c != null || thecase.BoR_Transfer__c!= null){
       //Lirik - Not in USE - Migration for BOR to BO -- End ---
        if(theCase.Opportunity__c != null || thecase.Benefit_Order__c!= null){
            Set<id> carrierIdSet = new Set<id>();
            if(theCase.Opportunity__c != null && theCase.RecordType.Name.indexOf('Benefits BoR') < 0){
              for(Policy__c policy : [Select Id, Carrier__c,Carrier__r.Name, Carrier__r.State__c from Policy__c where Is_Selected__c=true and Opportunity__c=:theCase.Opportunity__c]){
                  if(carrierIdSet.contains(policy.Carrier__c)){
                      continue;
                  }
                  optn = new SelectOption(''+policy.Carrier__c,policy.Carrier__r.Name+' - '+policy.Carrier__r.State__c+' (Policy) ');
                  carrierOptions.add(optn);
                  carrierIdSet.add(policy.Carrier__c);
              }
              
            }else if(thecase.Benefit_Order__c!= null && theCase.RecordType.Name.indexOf('Benefits BoR') > -1) {
              for(Carrier_Order__c carrierInfo : [Select Id, Carrier__c,Carrier__r.Name, Carrier__r.State__c from Carrier_Order__c where Benefit_Order__c=:theCase.Benefit_Order__c]){
                  if(carrierIdSet.contains(carrierInfo.Carrier__c)){
                      continue;
                  }
                  optn = new SelectOption(''+carrierInfo.Carrier__c,carrierInfo.Carrier__r.Name+' - '+carrierInfo.Carrier__r.State__c+' (Carrier) ');
                  carrierOptions.add(optn);
                  carrierIdSet.add(carrierInfo.Carrier__c);
              }
            }
            //Lirik - Not in USE - Migration for BOR to BO -- Start ---
            /*}else if(thecase.BoR_Transfer__c!= null && theCase.RecordType.Name.indexOf('Benefits BoR') > -1) {
              for(Carrier_Information__c carrierInfo : [Select Id, Carrier__c,Carrier__r.Name, Carrier__r.State__c from Carrier_Information__c where BoR_Transfer_Id__c=:theCase.BoR_Transfer__c]){
                  if(carrierIdSet.contains(carrierInfo.Carrier__c)){
                      continue;
                  }
                  optn = new SelectOption(''+carrierInfo.Carrier__c,carrierInfo.Carrier__r.Name+' - '+carrierInfo.Carrier__r.State__c+' (Carrier) ');
                  carrierOptions.add(optn);
                  carrierIdSet.add(carrierInfo.Carrier__c);
              }
            }*/
            //Lirik - Not in USE - Migration for BOR to BO -- End ---
            
            
            for(Carrier__c carrier : [Select Id, Name, State__c,Renewal_Email_List__c,New_Plan_Email_List__c,BOR_Transfer_Email_List__c from Carrier__c]){
                if(theCase.RecordType.Name.indexOf('Benefits BoR') < 0){
                  if(carrier.Renewal_Email_List__c==null && carrier.New_Plan_Email_List__c==null){
                      continue;
                  }
                  if(carrierIdSet.contains(carrier.Id)){
                      continue;
                  }
                  optn = new SelectOption(''+carrier.Id,carrier.Name+' - '+carrier.State__c);
                  carrierOptions.add(optn);
                  carrierIdSet.add(carrier.Id);
                }else if(theCase.RecordType.Name.indexOf('Benefits BoR') > -1){
                  if(carrier.BOR_Transfer_Email_List__c==null ){
                      continue;
                  }
                  if(carrierIdSet.contains(carrier.Id)){
                      continue;
                  }
                  optn = new SelectOption(''+carrier.Id,carrier.Name+' - '+carrier.State__c);
                  carrierOptions.add(optn);
                  carrierIdSet.add(carrier.Id);
                  
                }
            }
        }
    }
    
    public PageReference renderEmailDetails(){
    email='';
        emailOptions = new List<SelectOption>();
        SelectOption optn = new SelectOption('','');
        emailOptions.add(optn);
        
        if(carrierId!=null && carrierId!=''){
            Carrier__c carrier = [Select Id, Renewal_Email_List__c,New_Plan_Email_List__c,BOR_Transfer_Email_List__c from Carrier__c where id=:carrierId];
            if(carrier.Renewal_Email_List__c!=null && carrier.Renewal_Email_List__c!=''){
                for(String emailInfo : carrier.Renewal_Email_List__c.split('\n')){
                    if(emailInfo.indexOf('::')>-1){

                        emailOptions.add(new SelectOption(emailInfo.split('::')[1].trim(),'Renewal - '+emailInfo.split('::')[0]));
                    }
                }
            }
            if(carrier.New_Plan_Email_List__c!=null && carrier.New_Plan_Email_List__c!=''){
                for(String emailInfo : carrier.New_Plan_Email_List__c.split('\n')){
                    if(emailInfo.indexOf('::')>-1){

                        emailOptions.add(new SelectOption(emailInfo.split('::')[1].trim(),'New Plan - '+emailInfo.split('::')[0]));
                    }
                }
            }
            if(carrier.BOR_Transfer_Email_List__c!=null && carrier.BOR_Transfer_Email_List__c!=''){
                for(String emailInfo : carrier.BOR_Transfer_Email_List__c.split('\n')){
                    if(emailInfo.indexOf('::')>-1){

                        emailOptions.add(new SelectOption(emailInfo.split('::')[1].trim(),'BoR Transfer - '+emailInfo.split('::')[0]));
                    }
                }
            }
        }
        
        return null;
    }
    
    public PageReference assignEmail(){
        /*
        if(carrierId!=null && carrierId!=''){
            Carrier__c carrier = [Select Id, Group_Benefits_and_Renewals_Email__c from Carrier__c where id=:carrierId];
            if(carrier.Group_Benefits_and_Renewals_Email__c!=null && carrier.Group_Benefits_and_Renewals_Email__c!=''){
                email = carrier.Group_Benefits_and_Renewals_Email__c;
            }
        }
        */
        return null;
    }
    

}