force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Submission_Deadline_Days__c.field-meta.xml
<CustomField>
    <fullName>Submission_Deadline_Days__c</fullName>
    <formula>Submission_Deadline__c - TODAY()</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Submission Deadline Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal Alignment</fullName>
            </value>
            <value>
                <fullName>New to Gusto</fullName>
            </value>
            <value>
                <fullName>Same carrier, plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Same carrier, NO plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Carrier switch</fullName>
            </value>
            <value>
                <fullName>New Line of Coverage</fullName>
            </value>
            <value>
                <fullName>TAdA: Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>TAdA: No Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>BOR + TAdA</fullName>
            </value>
            <value>
                <fullName>BOR</fullName>
            </value>
            <value>
                <fullName>BOR TAdA Only</fullName>
            </value>
            <value>
                <fullName>New to BYB - No OE</fullName>
            </value>
            <value>
                <fullName>New to BYB - OE</fullName>
            </value>
            <value>
                <fullName>Gusto to BYB - Renewal</fullName>
            </value>
            <value>
                <fullName>Gusto to BYB - Midyear</fullName>
            </value>
            <value>
                <fullName>BYB Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Order_Generated__c.field-meta.xml
<CustomField>
    <fullName>Order_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Condition that if true then an order has already been generated for this Opportunity.</description>
    <label>Order Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Policy__c/Policy__c.object-meta.xml
<CustomObject>
    <description>A benefits Policy</description>
    <label>Policy</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Policies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Policy__c/fields/Benefit_Type__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Type__c</fullName>
    <label>Benefit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Dental</fullName>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Life</fullName>
            </value>
            <value>
                <fullName>Long Term Disability</fullName>
            </value>
            <value>
                <fullName>Short Term Disability</fullName>
            </value>
            <value>
                <fullName>Flexible Spending Account - Medical</fullName>
            </value>
            <value>
                <fullName>Flexible Spending Account - Dependent Care</fullName>
            </value>
            <value>
                <fullName>HSA</fullName>
            </value>
            <value>
                <fullName>Commuter</fullName>
            </value>
            <value>
                <fullName>Disability</fullName>
                <isActive>false</isActive>
                <label>Disability</label>
            </value>
            <value>
                <fullName>Life / Disability</fullName>
                <isActive>false</isActive>
                <label>Life / Disability</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Policy__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Policies</relationshipLabel>
    <relationshipName>Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Policy__c/fields/Is_Selected__c.field-meta.xml
<CustomField>
    <fullName>Is_Selected__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduleToCreateCOAgainstBOTest.cls
@isTest
public class ScheduleToCreateCOAgainstBOTest {
	static testMethod void testAsyncMethods() {
		AccounttriggerHelper.skipTrigger = true;
		OpportunitytriggerHelper.skipTrigger = true;
		CarrierOrderTriggerHelper.skipTrigger = true;
		BenefitOrderHelper.skipTrigger = true;
		PolicyHelper.skipTrigger = true;

		Opportunity opp1 = TestUtility.BenefitsNewPlanOpportunity();
		opp1.StageName = 'Pending PR';
		opp1.Order_Generated__c = true;
		update opp1;

		Benefit_Order__c benefitOrdr1 = TestUtility.createTestBenefitOrder('New Plan', opp1.Id, 'Test Benefit Order', false);
		benefitOrdr1.Type__c = 'New to Gusto';
		insert benefitOrdr1;

		Carrier__c carrier1 = TestUtility.Carrier();

		Policy__c pol1 = TestUtility.createTestPolicy(opp1.Id, carrier1.Id, true, 'Test Policy1', null, false);
		pol1.Benefit_Type__c = 'Dental';
		pol1.Is_Selected__c = true;
		insert pol1;

		//insert new Configuration_Settings__c(Submission_Deadline_Days__c = 5);BBO-1937

		test.startTest();
		ScheduleToCreateCarrierOrderAgainstBO objCreateCarrierOrder = new ScheduleToCreateCarrierOrderAgainstBO();
		objCreateCarrierOrder.execute(null);
		test.stopTest();
	}
}