force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Requires_Action__c.field-meta.xml
<CustomField>
    <fullName>Requires_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <description>A mid-term changes to an existing benefits package.</description>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Stage__c</fullName>
    <description>The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.

The Previous Implementation Stage and Implementation stage should be in sync. This status is mapped to previous implementation stage and OB message is sent to app using Kafka.</description>
    <label>Implementation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>Ready For Qualification</fullName>
                <default>true</default>
                <label>Ready For Qualification</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>OE Extended</fullName>
            </value>
            <value>
                <fullName>OE Verification/Checking Participation</fullName>
            </value>
            <value>
                <fullName>Ready for Submission Prep</fullName>
            </value>
            <value>
                <fullName>Submission Prep</fullName>
            </value>
            <value>
                <fullName>Ready for Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Item</fullName>
            </value>
            <value>
                <fullName>Approved Pending EE Audit</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Benefit_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order_Status__c</fullName>
    <formula>Text(Benefit_Order__r.Order_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Benefit Order Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <formula>Carrier__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Carrier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <description>Used this field in Advising Email Automation</description>
    <formula>CASE(MONTH(Opportunity__r.HI_Effective_Date__c),1,&apos;January&apos;,2,&apos;February&apos;,3,&apos;March&apos;,4,&apos;April&apos;,5,&apos;May&apos;,6,&apos;June&apos;,7,&apos;July&apos;,8,&apos;August&apos;,9,&apos;September&apos;,10,&apos;October&apos;,11, &apos;November&apos;,12, &apos;December&apos;,&apos;None&apos;) &amp; &quot; &quot; &amp; Text(Day(Opportunity__r.HI_Effective_Date__c)) &amp;IF(AND(DAY(Opportunity__r.HI_Effective_Date__c) &gt;= 11, DAY(Opportunity__r.HI_Effective_Date__c) &lt;= 13),&quot;th&quot;,
IF(MOD(DAY(Opportunity__r.HI_Effective_Date__c),10) = 1,&quot;st&quot;,
IF(MOD(DAY(Opportunity__r.HI_Effective_Date__c),10) = 2,&quot;nd&quot;,
IF(MOD(DAY(Opportunity__r.HI_Effective_Date__c),10) = 3,&quot;rd&quot;,&quot;th&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Coverage Effective Date</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related cases</description>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Cases (Related_Cases)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Requires_Action__c.field-meta.xml
<CustomField>
    <fullName>Requires_Action__c</fullName>
    <formula>Case__r.Requires_Action__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requires Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>false</active>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/User_Preference__c/User_Preference__c.object-meta.xml
<CustomObject>
    <label>User Preference</label>
    <nameField>
        <displayFormat>UP-{00000000}</displayFormat>
        <label>User Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Preference__c/fields/Benefit_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Benefit Order Status</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Preference__c/fields/Carrier_Name__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Preference__c/fields/Carrier_Order_Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order_Implementation_Stage__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Order Implementation Stage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User_Preference__c/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/User_Preference__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Preferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BenefitCarrierTableExtension.cls
public with sharing class BenefitCarrierTableExtension {
	public Integer size { get; set; }
	public String loggedInUser { get; set; }
	public Integer noOfRecords { get; set; }
	public List<SelectOption> paginationSizeOptions { get; set; }
	public User_Preference__c userRecord { get; set; }
	public List<User_Preference__c> userList = new List<User_Preference__c>();

	public list<selectOption> benefitOrderStatus { get; set; }
	public list<selectOption> carrierOrderStatus { get; set; }

	public list<selectOption> selectedBenefitOrderStatus { get; set; }
	public list<selectOption> selectedCarrierOrderStatus { get; set; }

	public String benefitOrderSortOrder { get; set; }
	public string sortDirection { get; set; }
	private string sortOrderField { get; set; }

	boolean isCarrierOrderFilterApplied = false;

	public BenefitCarrierTableExtension(ApexPages.StandardController controller) {
		//benefitOrderSortOrder = 'Order_Status__c';
		sortDirection = 'ASC';
		benefitOrderStatus = new List<SelectOption>();
		carrierOrderStatus = new List<SelectOption>();
		selectedBenefitOrderStatus = new List<SelectOption>();
		selectedCarrierOrderStatus = new List<SelectOption>();
		paginationSizeOptions = new List<SelectOption>();
		paginationSizeOptions.add(new SelectOption('5', '5'));
		paginationSizeOptions.add(new SelectOption('10', '10'));
		paginationSizeOptions.add(new SelectOption('20', '20'));
		paginationSizeOptions.add(new SelectOption('50', '50'));
		paginationSizeOptions.add(new SelectOption('100', '100'));
		userList = [
			SELECT Id, Coverage_Effective_Date__c, User__c, Carrier_Name__c, Benefit_Order_Status__c, Carrier_Order_Implementation_Stage__c
			FROM User_Preference__c
			WHERE User__c = :UserInfo.getUserId()
		];
		if (userList.size() > 0) {
			userRecord = userList[0];

			if (userRecord.Benefit_Order_Status__c != null && userRecord.Benefit_Order_Status__c.length() > 0) {
				for (string status : userRecord.Benefit_Order_Status__c.split(',')) {
					selectedBenefitOrderStatus.add(new selectOption(status.trim(), status.trim()));
				}
			}

			if (userRecord.Carrier_Order_Implementation_Stage__c != null && userRecord.Carrier_Order_Implementation_Stage__c.length() > 0) {
				for (string stage : userRecord.Carrier_Order_Implementation_Stage__c.split(',')) {
					selectedCarrierOrderStatus.add(new selectOption(stage.trim(), stage.trim()));
				}
			}
		} else {
			userRecord = new User_Preference__c();
			userRecord.User__c = UserInfo.getUserId();
		}

		benefitOrderStatus = getPicklistOptions(new Benefit_Order__c(), 'Order_Status__c', userRecord.Benefit_Order_Status__c);
		carrierOrderStatus = getPicklistOptions(new Carrier_Order__c(), 'Implementation_Stage__c', userRecord.Carrier_Order_Implementation_Stage__c);
	}

	private list<SelectOption> getPicklistOptions(Sobject Obj, String PicklistFieldName, string toExcludeValueString) {
		Schema.sObjectType sobject_type = Obj.getSObjectType();
		Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe();
		Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap();

		List<Schema.PicklistEntry> pick_list_values = field_map.get(PicklistFieldName).getDescribe().getPickListValues();
		List<selectOption> options = new List<selectOption>();

		for (Schema.PicklistEntry a : pick_list_values) {
			if (toExcludeValueString != null && toExcludeValueString.length() > 0) {
				if (toExcludeValueString.contains(a.getValue())) {
					continue;
				}
			}
			SelectOption so = new selectOption(a.getLabel(), a.getValue());
			options.add(so);
		}

		return options;
	}

	public ApexPages.StandardSetController setCon {
		get {
			if (Test.isRunningTest()) {
				setCon = null;
			}
			if (setCon == null) {
				size = 20;
				String query = 'SELECT ';
				loggedInUser = userinfo.getUserId();
				for (Schema.FieldSetMember field : this.getBenefitOrderFields()) {
					query += field.getFieldPath() + ', ';
				}
				query += '(SELECT ID, CaseNumber, Requires_Action__c from Cases__r where RecordType.name in (\'Benefits Renewal Case\',\'Benefits New Plan Case\',\'Benefits Change Case\')), ';
				query += '(SELECT ';
				for (Schema.FieldSetMember field : this.getCarrierOrderFields()) {
					query += field.getFieldPath() + ', ';
				}

				query += 'Id, Name from Carrier_Orders__r';

				boolean isWhereApplied = false;
				if (userRecord.Carrier_Name__c != null && userRecord.Carrier_Name__c.length() > 0) {
					string tempName = userRecord.Carrier_Name__c;
					query += ' where Carrier__r.Name =\'' + tempName + '\' ';
					isWhereApplied = true;
					isCarrierOrderFilterApplied = true;
				}

				if (userRecord.Carrier_Order_Implementation_Stage__c != null && userRecord.Carrier_Order_Implementation_Stage__c.trim().length() > 0) {
					string tempStageString = '(';
					for (String rec : userRecord.Carrier_Order_Implementation_Stage__c.split(',')) {
						if (rec != null && rec.trim().length() > 0) {
							tempStageString += '\'' + rec.trim() + '\',';
						}
					}

					tempStageString = tempStageString.trim().removeEnd(',') + ')';

					if (tempStageString != null && tempStageString.length() > 0) {
						if (isWhereApplied) {
							query += ' and 	Implementation_Stage__c IN ' + tempStageString;
						} else {
							query += ' where  Implementation_Stage__c IN ' + tempStageString;
						}
						isCarrierOrderFilterApplied = true;
					}
				}

				query += '), Id, Name from Benefit_Order__c ';

				// if(!Test.isRunningTest()){
				query += 'where (OwnerId=:loggedInUser OR UW_Owner__c=:loggedInUser) and Order_Status__c not in (\'Canceled\',\'Closed Lost\',\'Closed Admin\')';

				if (userRecord.Coverage_Effective_Date__c != null) {
					Date tempDate = userRecord.Coverage_Effective_Date__c;
					query += ' and Coverage_Effective_Date__c = :tempDate';
				}

				if (userRecord.Benefit_Order_Status__c != null && userRecord.Benefit_Order_Status__c.length() > 0) {
					string tempStatusstring = '(';
					for (string rec : userRecord.Benefit_Order_Status__c.split(',')) {
						if (rec != null && rec.trim().length() > 0) {
							tempStatusString += '\'' + rec.trim() + '\',';
						}
					}
					tempStatusString = tempStatusString.trim().removeEnd(',') + ')';
					if (tempStatusString != null && tempStatusString.length() > 0) {
						query += ' and Order_Status__c IN ' + tempStatusString;
					}
				}

				if (benefitOrderSortOrder != null && benefitOrderSortOrder.length() > 0) {
					query += ' Order By ' + benefitOrderSortOrder + ' ' + sortDirection;
				}
				// }

				list<Benefit_Order__c> tempBenefitList = Database.query(query);

				if (isCarrierOrderFilterApplied) {
					setCon = new ApexPages.StandardSetController(filterOutBenefitOrderWithoutChildRecords(tempBenefitList));
				} else {
					setCon = new ApexPages.StandardSetController(tempBenefitList);
				}
				setCon.setPageSize(size);
				noOfRecords = setCon.getResultSize();
			}
			return setCon;
		}
		set;
	}

	public list<Benefit_Order__c> filterOutBenefitOrderWithoutChildRecords(list<Benefit_Order__c> originalBOList) {
		list<Benefit_Order__c> benefitOrderList = new List<Benefit_Order__c>();

		if (originalBOList == null || !(originalBOList.size() > 0)) {
			return originalBOList;
		}

		for (Benefit_Order__c rec : originalBOList) {
			if (rec.Carrier_Orders__r == null || !(rec.Carrier_Orders__r.size() > 0)) {
				continue;
			}
			benefitOrderList.add(rec);
		}

		isCarrierOrderFilterApplied = false;
		return benefitOrderList;
	}

	//refresh orders
	public PageReference refreshOrders() {
		queryRecords();

		return null;
	}

	//Save the edited orders
	public PageReference saveMe() {
		List<Benefit_Order__c> benefitOrderList = new List<Benefit_Order__c>();
		List<Carrier_Order__c> carrierOrderList = new List<Carrier_Order__c>();

		for (Benefit_Order__c benefitOrd : (List<Benefit_Order__c>) setCon.getRecords()) {
			benefitOrderList.add(benefitOrd);
			if (benefitOrd.Carrier_Orders__r.size() > 0) {
				for (Carrier_Order__c carrierOrd : benefitOrd.Carrier_Orders__r) {
					carrierOrderList.add(carrierOrd);
				}
			}
		}
		try {
			if (benefitOrderList.size() > 0) {
				update benefitOrderList;
			}
			if (carrierOrderList.size() > 0) {
				update carrierOrderList;
			}
			queryRecords();
		} catch (Exception e) {
			ApexPages.addMessages(e);
		}
		return null;
	}

	//Refresh page size
	public PageReference refreshPageSize() {
		try {
			queryRecords();
		} catch (Exception e) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Modified rows exist in the records.'));
		}
		return null;
	}

	public void queryRecords() {
		String query = 'SELECT ';
		loggedInUser = userinfo.getUserId();
		for (Schema.FieldSetMember field : this.getBenefitOrderFields()) {
			query += field.getFieldPath() + ', ';
		}
		query += '(SELECT ID, CaseNumber, Requires_Action__c from Cases__r where RecordType.name in (\'Benefits Renewal Case\',\'Benefits New Plan Case\',\'Benefits Change Case\')), ';
		query += '(SELECT ';
		for (Schema.FieldSetMember field : this.getCarrierOrderFields()) {
			query += field.getFieldPath() + ', ';
		}
		query += 'Id, Name from Carrier_Orders__r';

		boolean isWhereApplied = false;
		if (userRecord.Carrier_Name__c != null && userRecord.Carrier_Name__c.length() > 0) {
			string tempName = userRecord.Carrier_Name__c;
			query += ' where Carrier__r.Name =\'' + tempName + '\' ';
			isWhereApplied = true;
			isCarrierOrderFilterApplied = true;
		}

		if (selectedCarrierOrderStatus != null && selectedCarrierOrderStatus.size() > 0) {
			string tempStageString;
			string tempCarrierOrderStage;

			for (selectOption rec : selectedCarrierOrderStatus) {
				string stage = rec.getValue();
				if (stage != null && stage.trim().length() > 0) {
					if (tempStageString == null || tempStageString.length() == 0) {
						tempStageString = '(';
					}
					tempStageString += '\'' + stage.trim() + '\',';
					tempCarrierOrderStage = stage.trim() + ',';
				}
			}

			if (tempStageString != null && tempStageString.length() > 0) {
				tempStageString = tempStageString.trim().removeEnd(',') + ')';
			}

			if (tempCarrierOrderStage != null && tempCarrierOrderStage.length() > 0) {
				tempCarrierOrderStage = tempCarrierOrderStage.trim().removeEnd(',');
				userRecord.Carrier_Order_Implementation_Stage__c = tempCarrierOrderStage;
			}

			if (tempStageString != null && tempStageString.length() > 0) {
				if (isWhereApplied) {
					query += ' and 	Implementation_Stage__c IN ' + tempStageString;
				} else {
					query += ' where  Implementation_Stage__c IN ' + tempStageString;
				}
				isCarrierOrderFilterApplied = true;
			}
		} else {
			userRecord.Carrier_Order_Implementation_Stage__c = '';
		}

		query += '), Id, Name from Benefit_Order__c ';
		//if(!Test.isRunningTest()){
		query += 'where (OwnerId=:loggedInUser OR UW_Owner__c=:loggedInUser) and Order_Status__c not in (\'Canceled\',\'Closed Lost\',\'Closed Admin\')';

		if (userRecord.Coverage_Effective_Date__c != null) {
			Date tempDate = userRecord.Coverage_Effective_Date__c;
			query += ' and Coverage_Effective_Date__c = :tempDate';
		}

		if (selectedBenefitOrderStatus != null && selectedBenefitOrderStatus.size() > 0) {
			string tempStatusString;
			string tempCarrierOrderStage;
			//userRecord.Benefit_Order_Status__c = userRecord.Benefit_Order_Status__c.replace('[','').replace(']','');
			for (selectOption rec : selectedBenefitOrderStatus) {
				string stage = rec.getValue();
				if (stage != null && stage.trim().length() > 0) {
					if (tempStatusString == null || tempStatusString.length() == 0) {
						tempStatusString = '(';
					}
					tempStatusString += '\'' + stage.trim() + '\',';
					tempCarrierOrderStage = stage + ',';
				}
			}

			if (tempStatusString != null && tempStatusString.length() > 0) {
				tempStatusString = tempStatusString.trim().removeEnd(',') + ')';
			}

			if (tempCarrierOrderStage != null && tempCarrierOrderStage.trim().length() > 0) {
				userRecord.Benefit_Order_Status__c = tempCarrierOrderStage.trim().removeEnd(',');
			}

			if (tempStatusString != null && tempStatusString.length() > 0) {
				query += ' and Order_Status__c IN ' + tempStatusString;
			}
		} else {
			userRecord.Benefit_Order_Status__c = '';
		}

		if (benefitOrderSortOrder != null && benefitOrderSortOrder.length() > 0) {
			query += ' order by ' + benefitOrderSortOrder + ' ' + sortDirection;
		}

		list<Benefit_Order__c> tempBenefitList = Database.query(query);
		if (isCarrierOrderFilterApplied) {
			setCon = new ApexPages.StandardSetController(filterOutBenefitOrderWithoutChildRecords(tempBenefitList));
		} else {
			setCon = new ApexPages.StandardSetController(tempBenefitList);
		}
		setCon.setPageSize(size);
		noOfRecords = setCon.getResultSize();
		//if(userRecord.Coverage_Effective_Date__c!=null){
		upsert userRecord;
		//}
	}

	public void sortbyBenefitOrderField() {
		//this.benefitOrderSortOrder = 'Name';
		if (sortOrderField == benefitOrderSortOrder) {
			sortDirection = (sortDirection == 'ASC' ? 'DESC' : 'ASC');
		} else {
			sortDirection = 'ASC';
		}

		sortOrderField = benefitOrderSortOrder;
		refreshOrders();
	}

	//Redirect to benefit order page
	public PageReference benefitOrderView() {
		Schema.DescribeSObjectResult result = Benefit_Order__c.SObjectType.getDescribe();
		PageReference pageRef = new PageReference('/' + result.getKeyPrefix());
		//PageReference pageRef = new PageReference('/apex/BenefitsTab');
		pageRef.setRedirect(true);
		return pageRef;
	}

	public List<Benefit_Order__c> getBenefitOrders() {
		List<Benefit_Order__c> benefitOrderList = new List<Benefit_Order__c>();
		for (Benefit_Order__c benefitOrd : (List<Benefit_Order__c>) setCon.getRecords()) {
			benefitOrderList.add(benefitOrd);
		}
		return benefitOrderList;
	}

	public List<Schema.FieldSetMember> getBenefitOrderFields() {
		return SObjectType.Benefit_Order__c.FieldSets.BenefitCarrierTableReq.getFields();
	}

	public List<Schema.FieldSetMember> getCarrierOrderFields() {
		return SObjectType.Carrier_Order__c.FieldSets.BenefitCarrierTableReq.getFields();
	}
}