force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Push_Rate_Reason__c.field-meta.xml
<CustomField>
    <fullName>Push_Rate_Reason__c</fullName>
    <label>Push Rate Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not enough EE enrolled</fullName>
            </value>
            <value>
                <fullName>Only owner(s) enrolled</fullName>
            </value>
            <value>
                <fullName>Too expensive/need more time to think about plans</fullName>
            </value>
            <value>
                <fullName>Not enough payroll history</fullName>
            </value>
            <value>
                <fullName>Unresponsive ER</fullName>
            </value>
            <value>
                <fullName>ER decided they’re not ready yet</fullName>
            </value>
            <value>
                <fullName>Problem with coverage area?/OOS EE</fullName>
            </value>
            <value>
                <fullName>Didn’t complete OE on time</fullName>
            </value>
            <value>
                <fullName>Want to make changes to selections</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Covid-19</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Stage__c</fullName>
    <description>The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.

The Previous Implementation Stage and Implementation stage should be in sync. This status is mapped to previous implementation stage and OB message is sent to app using Kafka.</description>
    <label>Implementation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>Ready For Qualification</fullName>
                <default>true</default>
                <label>Ready For Qualification</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>OE Extended</fullName>
            </value>
            <value>
                <fullName>OE Verification/Checking Participation</fullName>
            </value>
            <value>
                <fullName>Ready for Submission Prep</fullName>
            </value>
            <value>
                <fullName>Submission Prep</fullName>
            </value>
            <value>
                <fullName>Ready for Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Item</fullName>
            </value>
            <value>
                <fullName>Approved Pending EE Audit</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Open_Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Open_Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_Start_Date__c</fullName>
    <label>Open Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Carrier Switch</fullName>
            </value>
            <value>
                <fullName>New to Gusto</fullName>
            </value>
            <value>
                <fullName>New line of Coverage</fullName>
            </value>
            <value>
                <fullName>Same carrier, plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Same Carrier, NO Plan/Group Level Changes</fullName>
            </value>
            <value>
                <fullName>TAdA: No Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>TAdA: Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>Terminated Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarrierOrderApproveAuditControllerTest.cls
/*
 * Description: Test Class for CarrierOrderApproveAuditController
 * Author: Omar Benitez
 * Date: 05/05/2024
 */
@isTest
public class CarrierOrderApproveAuditControllerTest {
	@testSetup
	static void setUp() {
		AccounttriggerHelper.skipTrigger = true;
		OpportunitytriggerHelper.skipTrigger = true;
		CarrierOrderTriggerHelper.skipTrigger = true;
		BenefitOrderHelper.skipTrigger = true;
		Opportunity objOpp1 = TestUtility.BenefitsNewPlanOpportunity();

		Benefit_Order__c objBenefitOrdr1 = TestUtility.createTestBenefitOrder('New Plan', objOpp1.Id, 'Test Benefit Order', true);

		objBenefitOrdr1.Order_Status__c = 'OE';
		objBenefitOrdr1.Coverage_Effective_Date__c = System.today();
		objBenefitOrdr1.Open_Enrollment_Start_Date__c = System.today();
		objBenefitOrdr1.Open_Enrollment_End_Date__c = System.today();
		objBenefitOrdr1.Push_Rate_Reason__c = 'Not enough EE enrolled';
		update objBenefitOrdr1;

		Carrier__c objTestCarrier = TestUtility.Carrier();

		List<Carrier_Order__c> lst_CarrierOrder = new List<Carrier_Order__c>();
		Carrier_Order__c objCarOrder = (Carrier_Order__c) Carrier_Order__c.SObjectType.newSObject();
		objCarOrder.Name = 'TEST CARRIER ORDER';
		objCarOrder.Carrier__c = objTestCarrier.Id;
		objCarOrder.Benefit_Order__c = objBenefitOrdr1.Id;
		objCarOrder.Implementation_Stage__c = 'With Advising';
		objCarOrder.Order_Type__c = 'TAdA: Pre OE Setup';
		objCarOrder.Stage_Detail__c = 'TAdA Setup Complete';
		lst_CarrierOrder.add(objCarOrder);

		Carrier_Order__c objCarOrder1 = (Carrier_Order__c) Carrier_Order__c.SObjectType.newSObject();
		objCarOrder1.Name = 'TEST CARRIER ORDER 1';
		objCarOrder1.Carrier__c = objTestCarrier.Id;
		objCarOrder1.Benefit_Order__c = objBenefitOrdr1.Id;
		objCarOrder1.Implementation_Stage__c = 'Approved';
		objCarOrder1.OwnerId = UserInfo.getUserId();
		objCarOrder1.Stage_Detail__c = 'TAdA Setup Complete';
		lst_CarrierOrder.add(objCarOrder1);

		Carrier_Order__c objCarOrder2 = (Carrier_Order__c) Carrier_Order__c.SObjectType.newSObject();
		objCarOrder2.Name = 'TEST CARRIER ORDER 2';
		objCarOrder2.Carrier__c = objTestCarrier.Id;
		objCarOrder2.Benefit_Order__c = objBenefitOrdr1.Id;
		objCarOrder2.Implementation_Stage__c = 'Approved';
		objCarOrder2.OwnerId = UserInfo.getUserId();
		objCarOrder2.Stage_Detail__c = 'TAdA Setup Complete';
		lst_CarrierOrder.add(objCarOrder2);
		insert lst_CarrierOrder;

		objCarOrder2.Parent_Carrier_Order__c = lst_CarrierOrder[1].Id;
		update objCarOrder2;
	}
	/*
	 * Description: Test Method for getOptions
	 * Author: Omar Benitez
	 * Date: 05/05/2024
	 */
	@isTest
	static void testGetOptions() {
		Carrier_Order__c objCarrierOrder = [SELECT Id FROM Carrier_Order__c WHERE Name = 'TEST CARRIER ORDER' LIMIT 1];
		Test.startTest();
		Map<String, Object> map_response = CarrierOrderApproveAuditController.getOptions(objCarrierOrder.Id);
		Test.stopTest();
		Map<String, String> map_ImplementationStage = (Map<String, String>) map_response.get('implementationStageOptions');
		Map<String, String> map_implementationStageDetailOptions = (Map<String, String>) map_response.get('implementationStageDetailOptions');
		String strImplementationStage = (String) map_response.get('implementationStage');
		Carrier_Order__c objCarrierOrderRes = (Carrier_Order__c) map_response.get('objCarrierOrder');
		Boolean blnHasTadaOrder = (Boolean) map_response.get('blnHasTadaOrder');
		System.assertNotEquals(0, map_ImplementationStage.size(), 'Options should not be empty');
		System.assertNotEquals(0, map_implementationStageDetailOptions.size(), 'Options should not be empty');
		System.assertEquals('Approved', strImplementationStage, 'It should be Approved');
		System.assertNotEquals(null, objCarrierOrderRes, 'CO should not be null');
		System.assertEquals(true, blnHasTadaOrder, 'tada should be true');
	}

	/*
	 * Description: Test Method for getOptions with TAdA Selected
	 * Author: Omar Benitez
	 * Date: 05/05/2024
	 */
	@isTest
	static void testGetOptionsNotTAdA() {
		Carrier_Order__c objCarrierOrder = [SELECT Id FROM Carrier_Order__c WHERE Name = 'TEST CARRIER ORDER 1' LIMIT 1];
		Test.startTest();
		Map<String, Object> map_response = CarrierOrderApproveAuditController.getOptions(objCarrierOrder.Id);
		Test.stopTest();
		Map<String, String> map_ImplementationStage = (Map<String, String>) map_response.get('implementationStageOptions');
		Map<String, String> map_implementationStageDetailOptions = (Map<String, String>) map_response.get('implementationStageDetailOptions');
		String strImplementationStage = (String) map_response.get('implementationStage');
		Carrier_Order__c objCarrierOrderRes = (Carrier_Order__c) map_response.get('objCarrierOrder');
		Boolean blnHasTadaOrder = (Boolean) map_response.get('blnHasTadaOrder');
		System.assertNotEquals(0, map_ImplementationStage.size(), 'Options should not be empty');
		System.assertNotEquals(0, map_implementationStageDetailOptions.size(), 'Options should not be empty');
		System.assertEquals('Approved', strImplementationStage, 'It should be Approved');
		System.assertNotEquals(null, objCarrierOrderRes, 'CO should not be null');
		System.assertEquals(false, blnHasTadaOrder, 'tada should be false');
	}

	/*
	 * Description: Test Method for save order
	 * Author: Omar Benitez
	 * Date: 05/05/2024
	 */
	@isTest
	static void testSaveOrder() {
		Carrier_Order__c objCarrierOrder = [
			SELECT Id, Implementation_Stage__c, Stage_Detail__c, Order_Type__c, Approval_Notes__c, Approval_Method__c, Benefit_Order__c, RecordTypeId
			FROM Carrier_Order__c
			WHERE Name = 'TEST CARRIER ORDER 1'
			LIMIT 1
		];
		objCarrierOrder.Implementation_Stage__c = 'Approved';
		objCarrierOrder.Approval_Notes__c = 'The note';
		Test.startTest();
		Object response = CarrierOrderApproveAuditController.saveOrder(objCarrierOrder);
		objCarrierOrder = [
			SELECT Id, Implementation_Stage__c, Stage_Detail__c, Order_Type__c, Approval_Notes__c, Approval_Method__c, Benefit_Order__c, RecordTypeId
			FROM Carrier_Order__c
			WHERE Name = 'TEST CARRIER ORDER 1'
			LIMIT 1
		];
		Test.stopTest();
		System.assertEquals(null, response, 'Response should be null');
		System.assertEquals('Approved', objCarrierOrder.Implementation_Stage__c, 'Implementation Stage should be approved');
		System.assertEquals('The note', objCarrierOrder.Approval_Notes__c, 'Approved Notes should be the note');
	}

	/*
	 * Description: Test Method for save order with TAdA selected
	 * Author: Omar Benitez
	 * Date: 05/05/2024
	 */
	@isTest
	static void testSaveOrderTAdA() {
		Carrier_Order__c objCarrierOrder = [
			SELECT Id, Implementation_Stage__c, Stage_Detail__c, Order_Type__c, Approval_Notes__c, Approval_Method__c, Benefit_Order__c, RecordTypeId
			FROM Carrier_Order__c
			WHERE Name = 'TEST CARRIER ORDER'
			LIMIT 1
		];
		objCarrierOrder.Implementation_Stage__c = 'Approved';
		objCarrierOrder.Approval_Notes__c = 'The note';
		Test.startTest();
		Object saveOrderResponse = CarrierOrderApproveAuditController.saveOrder(objCarrierOrder);
		objCarrierOrder = [
			SELECT Id, Implementation_Stage__c, Stage_Detail__c, Order_Type__c, Approval_Notes__c, Approval_Method__c, Benefit_Order__c, RecordTypeId
			FROM Carrier_Order__c
			WHERE Name = 'TEST CARRIER ORDER'
			LIMIT 1
		];
		Test.stopTest();
		System.assertEquals(null, saveOrderResponse, 'Response should be null');
		System.assertEquals('Approved', objCarrierOrder.Implementation_Stage__c, 'Implementation Stage should be approved');
		System.assertEquals('The note', objCarrierOrder.Approval_Notes__c, 'Approved Notes should be the note');
	}
}