force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <description>A mid-term changes to an existing benefits package.</description>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/Benefit_Change.recordType-meta.xml
<RecordType>
    <fullName>Benefit_Change</fullName>
    <active>false</active>
    <label>Benefit Change</label>
</RecordType>

force-app/main/default/objects/Order/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>false</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>Ticket-{00000000}</displayFormat>
        <label>Action Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>SALY</fullName>
            </value>
            <value>
                <fullName>New - Onboarding</fullName>
            </value>
            <value>
                <fullName>Verification Needed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Account Provisioned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New / QRE Review</fullName>
            </value>
            <value>
                <fullName>Finalize Portal</fullName>
            </value>
            <value>
                <fullName>Four Part Pending</fullName>
            </value>
            <value>
                <fullName>Onboard Review</fullName>
            </value>
            <value>
                <fullName>Data Load</fullName>
            </value>
            <value>
                <fullName>Report Creation</fullName>
            </value>
            <value>
                <fullName>Calc Approval Pending</fullName>
            </value>
            <value>
                <fullName>Customer Survey Pending</fullName>
            </value>
            <value>
                <fullName>Ready for Additional Qualitative</fullName>
            </value>
            <value>
                <fullName>Credit Determination</fullName>
            </value>
            <value>
                <fullName>Filed Tax Return Needed</fullName>
            </value>
            <value>
                <fullName>Tax Return - Needs Quant Team Review</fullName>
            </value>
            <value>
                <fullName>Load Credits</fullName>
            </value>
            <value>
                <fullName>Gusto Real Time Billing</fullName>
            </value>
            <value>
                <fullName>Payroll Billing (non-Gusto)</fullName>
            </value>
            <value>
                <fullName>Liability Billing - Annually</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Carryforward Credits</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tier_Config__c/Tier_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration used to store names of old tiers and plans</description>
    <label>Tier Config</label>
</CustomObject>

force-app/main/default/objects/Tier_Config__c/fields/New_Tier_1__c.field-meta.xml
<CustomField>
    <fullName>New_Tier_1__c</fullName>
    <description>Name of the new Tier - Typically it is called Simple</description>
    <label>New Tier 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tier_Config__c/fields/New_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>New_Tier_2__c</fullName>
    <description>Name of new Tier 2 - Typically it is called Plus</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Tier 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tier_Config__c/fields/Old_Tier_1__c.field-meta.xml
<CustomField>
    <fullName>Old_Tier_1__c</fullName>
    <description>Name of Old Tier 1 - Core</description>
    <label>Old Tier 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tier_Config__c/fields/Old_Tier_2__c.field-meta.xml
<CustomField>
    <fullName>Old_Tier_2__c</fullName>
    <description>Name of Old Tier 2 - Typically Complete</description>
    <label>Old Tier 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tier_Config__c/fields/Old_Tier_3__c.field-meta.xml
<CustomField>
    <fullName>Old_Tier_3__c</fullName>
    <description>Name of Old Tier 3 - Typically Concierge</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Old Tier 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BenefitOrderUtil.cls
/**
    Created by : Praveen Sethu
    Created Date : 10/28/2020
    Description: Benefit Order related Utilities for reuse
**/
public class BenefitOrderUtil {
	public static final String STATUS_APPROVED = 'Approved';
	public static final String STATUS_APPROVED_PENDING_EE_AUDIT = 'Approved Pending EE Audit';
	public static final String STATUS_FULFILLED = 'Fulfilled';
	public static final String STATUS_CLOSED_ADMIN = 'Closed Admin';
	public static final String STATUS_CANCELLED = 'Canceled';
	public static final String STATUS_CLOSED_LOST = 'Closed Lost';
	public static final String STATUS_DENIED = 'Denied';
	public static final String STATUS_ALIGNEMENT_DENIED = 'Alignment Denied';
	public static final String STATUS_ALIGNEMENT_APPROVED_POST_RENEWAL = 'Alignment Approved Post Renewal';
	public static final String STATUS_ALIGNEMENT_APPROVED = 'Alignment Approved';
	public static final String STATUS_BLOCKED = 'Blocked';
	public static final String STATUS_QUALIFICATION = 'Qualification';
	public static final String STATUS_READY_FOR_QUALIFICATION = 'Ready for Qualification';
	public static final String STATUS_READY_FOR_OE_PREP = 'Ready for OE Prep';
	public static final String ORDER_TYPE_TERMINATED_ORDER = 'Terminated Order';
	public static final String BO_STAGE_DETAIL_READY_FOR_TADA_SETUP = 'Ready for TAdA Setup';
	public static final String STATUS_PENDING_ER_SIGNATURE = 'Pending ER Signature';

	public static final String OPPTY_BENEFITS_SETUP_AWAIT_OFFERINGS_STEP = 'Awaiting Offerings';
	public static final List<String> COMPLETED_ORDER_STATUSES = new List<String>{
		STATUS_FULFILLED,
		STATUS_CANCELLED,
		STATUS_CLOSED_LOST,
		STATUS_CLOSED_ADMIN
	};

	public static Set<String> set_ClosedOrderStatusForBOAndAlignementBO = new Set<String>{
		STATUS_DENIED,
		STATUS_CANCELLED,
		STATUS_CLOSED_ADMIN,
		STATUS_ALIGNEMENT_APPROVED,
		STATUS_ALIGNEMENT_DENIED,
		STATUS_ALIGNEMENT_APPROVED_POST_RENEWAL
	};

	public static Set<String> set_ClosedOrderStatusForBO = new Set<String>{
		STATUS_CANCELLED,
		STATUS_CLOSED_ADMIN,
		STATUS_CLOSED_LOST
	};

	public static Set<String> set_ClosedOrderStatusForBOToShowData = new Set<String>{
		STATUS_BLOCKED,
		STATUS_APPROVED,
		STATUS_CLOSED_LOST,
		STATUS_FULFILLED,
		STATUS_CLOSED_ADMIN,
		STATUS_CANCELLED
	};
	// Record Type Ids
	public static final Id RENEWAL_ALIGNMENT_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId(
		'Benefit_Order__c',
		'Renewal Alignment'
	);
	public static final Id RENEWAL_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId('Benefit_Order__c', 'Renewal');
	public static final Id CHANGE_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId('Benefit_Order__c', 'Change');
	public static final Id BOR_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId('Benefit_Order__c', 'Benefits BoR');
	public static final Id NEW_PLAN_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId('Benefit_Order__c', 'New Plan');
	public static final Id BYB_BENEFIT_ORDER_RT_ID = Cache.getRecordTypeId('Benefit_Order__c', 'Benefits BYB');

	public static final String RENEWAL_QA_SHEET_RT_NAME = 'Benefit_Renewal';
	public static final String NEW_PLAN_QA_SHEET_RT_NAME = 'Benefit_New_Plan';
	public static final String CHANGE_QA_SHEET_RT_NAME = 'Benefit_Change';

	public static final String BENEFIT_ORDER_RT_NEW_PLAN = 'New Plan';
	public static final String BENEFIT_ORDER_RT_RENEWAL = 'Renewal';
	public static final String BENEFIT_ORDER_RT_CHANGE = 'Change';
	public static final String BENEFIT_ORDER_RT_BENEFITS_BOR = 'Benefits BoR';
	public static final String BENEFIT_ORDER_RT_RENEWAL_ALIGNMENT = 'Renewal Alignment';

	public static final String MSQ_CLOSE_OPEN_TICKET_FIRST = 'There is an open ticket associated to this order. Please ensure all tickets are closed before Fulfilling/Canceling order';
	public final static String QUEUE_PREFIX = '00G';
	public static final Id LOGGED_IN_USER_ID = UserInfo.getUserId();
	public static final String  BYB_RENEWAL = 'BYB Renewal';
	public static final String STATUS_READY_FOR_INTRO = 'Ready for Intro';
	public static final String PRIORITY_REASON_EFFECTIVE_DATE = 'Upcoming Effective Date';

	//Tiers
	public static Tier_Config__c objTierConfig = Tier_Config__c.getOrgDefaults();
	public static String strCORE =  objTierConfig.Old_Tier_1__c;
	public static String strCOMPLETE =  objTierConfig.Old_Tier_2__c;
	public static String strCONCIERAGE = objTierConfig.Old_Tier_3__c;
	public static String strSIMPLE = objTierConfig.New_Tier_1__c;
	public static String strPLUS = objTierConfig.New_Tier_2__c;
	public static String strPLUS_AND_SUPPORT_PRIOR = 'Plus & Priority Support';
	public static final String BO_ORDER_TYPE_BOR = 'BOR';
	public static final String BO_ORDER_TYPE_BOR_AND_TADA = 'BOR + TAdA';
	public static final String BO_ORDER_TYPE_BOR_TADA_ONLY = 'BOR TAdA Only';

    //Integration ID for BO Cases
    public static final String BO_CASE_INTEGRATION_ID_BYB = 'hippo-Benefits_BYB-';


	/**
	 * @Author      : Deepika Saini
	 * @Description : fetch the open Tickets related to BenefitOrder
	 * @Parm        : set_BenefitOrdersId : set of Benefit Orders Id
	 * @Return      : list of ticket
	 **/
	public static Map<Id, Ticket__c> fetchOpenTicketsRelatedToBO(Set<Id> set_BenefitOrdersId) {
		Map<Id, Ticket__c> map_OpenTicketsWithBO = new Map<Id, Ticket__c>();
		String strTicketQuery = '';

		if (!set_BenefitOrdersId.isEmpty()) {
			for (Ticket__c objTicket : [
				SELECT Id, Benefit_Order__c
				FROM Ticket__c
				WHERE
					Benefit_Order__c != NULL
					AND Status__c != NULL
					AND Benefit_Order__c IN :set_BenefitOrdersId
					AND Status__c != :TicketUtil.TICKET_STATUS_CLOSED
					AND RecordTypeId IN :TicketUtil.set_BenefitsOnboardingRelatedTickets
			]) {
				if (
					!map_OpenTicketsWithBO.isEmpty() &&
					map_OpenTicketsWithBO.containsKey(objTicket.Benefit_Order__c)
				) {
					continue;
				}
				map_OpenTicketsWithBO.put(objTicket.Benefit_Order__c, objTicket);
			}
		}

		return map_OpenTicketsWithBO;
	}
}