force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/QA_Sheet__c.field-meta.xml
<CustomField>
    <fullName>QA_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populate QA Sheet lookup from opportunity record</description>
    <label>QA Sheet</label>
    <referenceTo>QA_Sheet__c</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QA_Sheet__c/QA_Sheet__c.object-meta.xml
<CustomObject>
    <label>QA Sheet</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>QA Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Sheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QA_Sheet__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>QA Sheet</relationshipLabel>
    <relationshipName>QA_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_Sheet__c/fields/Benefits_Point_of_Contact_Name_SFDC__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Point_of_Contact_Name_SFDC__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Benefits Point of Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QA_Sheet__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Mailing Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/QAButtonOnBODetailExt.cls
public class QAButtonOnBODetailExt {
    string currentRecordId;
    public QA_Sheet__c QAObj{get;set;}
    public QAButtonOnBODetailExt(ApexPages.StandardController sc){
        currentRecordId = ApexPages.CurrentPage().getparameters().get('id');
        List<QA_Sheet__c> qaList = [select id,name,Benefits_Point_of_Contact_Name_SFDC__c,Mailing_Address__c,Effective_Date__c from QA_Sheet__c where Benefit_Order__c =:currentRecordId]; 
        if(qaList!=Null && qaList.size()>0){
            QAObj = qaList[0];
        }
    }

    public PageReference DisplayQARecord(){
        if(QAObj!=Null){
            PageReference pageRef = new PageReference('/'+QAObj.id);
            return pageRef;
        }else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'There is no QA Sheet is not available for this Benefit Order'));
    		return null;
        }
       /* list<QA_Sheet__c> qalist = [select id from QA_Sheet__c where Benefit_Order__c =:currentRecordId];
        if(qalist.size()>0){
        PageReference pageRef = new PageReference('/apex/NPRU_DisplayEditQASheet?id='+qalist[0].id);
        return pageRef;
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'There is no QA Sheet is not available for this Benefit Order'));
    		return null;
        }*/
    }
}