force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Benefit_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change</value>
        </filterItems>
        <infoMessage>Displaying new plan, change, and renewal opportunities only.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Transition_to_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Transition_to_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transition to Fulfillment</label>
    <referenceTo>Transition_to_Fulfillment__c</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Change.recordType-meta.xml
<RecordType>
    <fullName>Change</fullName>
    <active>true</active>
    <description>A mid-term changes to an existing benefits package.</description>
    <label>Change</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Contacts associated with Carriers</description>
    <label>Carrier</label>
</RecordType>

unpackaged/main/default/objects/Order/fields/Transition_to_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Transition_to_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transition to Fulfillment</label>
    <referenceTo>Transition_to_Fulfillment__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>false</active>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Transition_to_Fulfillment__c/Transition_to_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Transition to Fulfillment</label>
    <nameField>
        <displayFormat>TF-{00000}</displayFormat>
        <label>Transition to Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transition to Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Transition_to_Fulfillment__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Transition to Fulfillments</relationshipLabel>
    <relationshipName>Transition_to_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transition_to_Fulfillment__c/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Transition to Fulfillments</relationshipLabel>
    <relationshipName>Transition_to_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transition_to_Fulfillment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefits Point of Contact 1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transition to Fulfillments</relationshipLabel>
    <relationshipName>Transition_to_Fulfillments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Transition_to_Fulfillment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Transition to Fulfillments</relationshipLabel>
    <relationshipName>NP_Complexity_Scorings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateTransitionToConfirmationExt.cls
/** 
  * Description     :   On Carrier order,for creating/updating transition to fulfillment records based on record types-
  *                     Confirmation New Plan,Confirmation Renewal/Change with respective page layout
  *                     Buttons:Transition to Confirmation.
  *
  * Visualforce page:   NPRU_CreateTransitionToConfirmation

  * Created By      :   Syam Nukilla 
  *                
  * Created Date    :   10/03/2019
  **/
public class CreateTransitionToConfirmationExt {
    public String currentRecordId;
    public List<Transition_to_Fulfillment__c> lstTtfRec;
    public Carrier_Order__c coObj;
    public id  newrecordtypeid;
    public id renewalrecordtypeid;
    public String urlStr;
    public id carriernewrectypeid;
    public id fullfillrecordtypeid;
    public String contactId;
    public String ContactName;
    public List<Transition_to_Fulfillment__c> ttfRecCon;
    public CreateTransitionToConfirmationExt(ApexPages.StandardController standardController){
        lstTtfRec = new List<Transition_to_Fulfillment__c>();
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        urlStr = null;
        carriernewrectypeid =cache.getRecordTypeId('Carrier_Order__c', 'New Plan');
    }
    // transition to Confirmation
    public PageReference initconfirmation(){
        newrecordtypeid = cache.getRecordTypeId('Transition_to_Fulfillment__c', 'Confirmation New Plan');
        renewalrecordtypeid = cache.getRecordTypeId('Transition_to_Fulfillment__c', 'Confirmation Renewal/Change');
        
        List<Carrier_Order__c> coList= [select id,name,Benefit_Order__c,Benefit_Order__r.name,
                                        Benefit_Order__r.Opportunity__c,Benefit_Order__r.Opportunity__r.name,
                                        Benefit_Order__r.Opportunity__r.Account.id,Benefit_Order__r.Opportunity__r.Account.name,recordtypeid 
                                        from Carrier_Order__c where id =:currentRecordId Limit 1];
        if(coList!=Null){
            coObj = coList[0];
            if(coObj.recordtypeid == carriernewrectypeid){
            fullfillrecordtypeid = newrecordtypeid;
            }
            else{
            fullfillrecordtypeid = renewalrecordtypeid;
            }
            ttfRecCon = [SELECT Id,Contact__r.id,Contact__r.name FROM Transition_to_Fulfillment__c WHERE Opportunity__c =:coObj.Benefit_Order__r.Opportunity__c];
            if(ttfRecCon.size()>0 && ttfRecCon!= Null){
                ContactName = ttfRecCon[0].Contact__r.name;
                ContactId = ttfRecCon[0].Contact__r.id;
            }
        }
        String prefix = Transition_to_Fulfillment__c.sobjectType.getDescribe().getkeyPrefix();
        lstTtfRec = [select id,name,Opportunity__c,Carrier_Order__c from Transition_to_Fulfillment__c where Benefit_Order__c=:coObj.Benefit_Order__c and (recordtypeid=:newrecordtypeid or recordtypeid=:renewalrecordtypeid)];
        if(lstTtfRec.size()==0){
            urlStr = '/'+prefix+'/e?retURL=%2F'+currentRecordId+'&RecordType='+fullfillrecordtypeid+'&ent=Transition_to_Fulfillment__c&CF00N3D000004yWa5='+coObj.name+'&CF00N3D000004yWa5_lkid='+coObj.id+'&CF00N1M00000FE19l='+coObj.Benefit_Order__r.name+'&CF00N1M00000FE19l_lkid='+coObj.Benefit_Order__c+'&CF00N1600000FDl7b_lkid='+coObj.Benefit_Order__r.Opportunity__c+'&CF00N1600000FDl7b='+coObj.Benefit_Order__r.Opportunity__r.name+'&CF00N1600000FDl7J_lkid='+coObj.Benefit_Order__r.Opportunity__r.Account.id+'&CF00N1600000FDl7J='+coObj.Benefit_Order__r.Opportunity__r.Account.name+'&CF00N3D000004jtw5_lkid='+ContactId+'&CF00N3D000004jtw5='+ContactName+'&nooverride=1';
        }
        else{
            urlStr = '/'+lstTtfRec[0].id+'/e?retURL=%2F'+coObj.id+'&RecordType='+fullfillrecordtypeid+'&ent=Transition_to_Fulfillment__c&nooverride=1';
        }
        PageReference pg = new PageReference(urlStr);
        pg.setRedirect(true);
        return pg;
    }
    // end of transition to Confirmation
}