force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Benefit_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change</value>
        </filterItems>
        <infoMessage>Displaying new plan, change, and renewal opportunities only.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/QA_Sheet__c.field-meta.xml
<CustomField>
    <fullName>QA_Sheet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Populate QA Sheet lookup from opportunity record</description>
    <label>QA Sheet</label>
    <referenceTo>QA_Sheet__c</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Stage__c</fullName>
    <description>The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.

The Previous Implementation Stage and Implementation stage should be in sync. This status is mapped to previous implementation stage and OB message is sent to app using Kafka.</description>
    <label>Implementation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>Ready For Qualification</fullName>
                <default>true</default>
                <label>Ready For Qualification</label>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>OE Extended</fullName>
            </value>
            <value>
                <fullName>OE Verification/Checking Participation</fullName>
            </value>
            <value>
                <fullName>Ready for Submission Prep</fullName>
            </value>
            <value>
                <fullName>Submission Prep</fullName>
            </value>
            <value>
                <fullName>Ready for Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Pending Item</fullName>
            </value>
            <value>
                <fullName>Approved Pending EE Audit</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Benefits_New_Plan.recordType-meta.xml
<RecordType>
    <fullName>Benefits_New_Plan</fullName>
    <active>true</active>
    <businessProcess>Benefits New Plan Sales Process</businessProcess>
    <description>Used to track a potential sale for new HI Benefits where the customer does not currently provide HI</description>
    <label>Benefits New Plan</label>
</RecordType>

unpackaged/main/default/objects/QA_Lines_Of_Coverage__c/QA_Lines_Of_Coverage__c.object-meta.xml
<CustomObject>
    <label>QA Lines Of Coverage</label>
    <nameField>
        <displayFormat>QA-L-{0000}</displayFormat>
        <label>QA Lines Of Coverage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Lines Of Coverage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QA_Lines_Of_Coverage__c/fields/Benefits_selected_Carrier__c.field-meta.xml
<CustomField>
    <fullName>Benefits_selected_Carrier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>QA Lines Of Coverage</relationshipLabel>
    <relationshipName>QA_Lines_Of_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_Lines_Of_Coverage__c/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>QA Lines Of Coverage</relationshipLabel>
    <relationshipName>QA_Lines_Of_Coverage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_Lines_Of_Coverage__c/fields/QA_Sheet__c.field-meta.xml
<CustomField>
    <fullName>QA_Sheet__c</fullName>
    <label>QA Sheet</label>
    <referenceTo>QA_Sheet__c</referenceTo>
    <relationshipLabel>QA Lines Of Coverage</relationshipLabel>
    <relationshipName>QA_Lines_Of_Coverage_del</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QA_Sheet__c/QA_Sheet__c.object-meta.xml
<CustomObject>
    <label>QA Sheet</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>QA Sheet Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QA Sheet</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QA_Sheet__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>QA Sheet</relationshipLabel>
    <relationshipName>QA_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_Sheet__c/fields/Carrier_Order__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carrier Order</label>
    <referenceTo>Carrier_Order__c</referenceTo>
    <relationshipLabel>QA Sheet</relationshipLabel>
    <relationshipName>QA_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QA_Sheet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to company&apos;s opportunity based on company ID and application id</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>QA Sheet</relationshipLabel>
    <relationshipName>QA_Sheet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateWarningMessagesLwcTest.cls
/*
 * @name			CreateWarningMessagesLwcTest
 * @author			Deepika Saini
 * @date			28/02/2025
 * @description		Test Confitmation Coverage Email Warning Messages.
 */

@isTest
public class CreateWarningMessagesLwcTest {
	/**
	 * @Author      : Deepika Saini
	 * @Description : Create the Setup of Test Data
	 * @Parm        : null
	 * @Return      : null
	 **/
	@testSetup
	static void setup() {
		createBenefitNewPlanCaseRecord();
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Creating a new Instance of Account, Opportunity, Contact, Benefit_Order__c..
	 * @Parm        : null
	 * @Return      : null
	 **/
	public static void createBenefitNewPlanCaseRecord() {
		//Create new Account
		CreateWarningMessagesLwcTest.skipTrigger(true);
		Account objAcc = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setName('test acc1').setZPCompanyId('100989011').build();
		insert objAcc;

		//Create Benefits New Plan Opportunity.
		Opportunity objOpp = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(OpportunityUtil.BENEFITS_NEW_PLAN_OPPTY_RT_ID)
			.setName('Test New Plan Opportunity')
			.setAccountId(objAcc.Id)
			.setStage('SAL')
			.setCloseDate(System.today())
			.build();
		insert objOpp;

		//Create Contact.
		ContactTriggerHelper.skipTrigger = true;
		List<Contact> list_Contact = new List<Contact>();
		list_Contact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
				.setAccountId(objOpp.AccountId)
				.setFirstName('Neha 1')
				.setLastName('Test August 6 ')
				.setEmail('neha.dabastest+1@lirik.io')
				.build()
		);
		insert list_Contact;

		//Create New Contact records
		List<Contact> list_NewContact = new List<Contact>();
		list_NewContact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
				.setAccountId(objOpp.AccountId)
				.setFirstName('Test')
				.setLastName('User01')
				.setEmail('testuser01@gusto.com')
				.setZPUserId('75001')
				.build()
		);
		list_NewContact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
				.setAccountId(objOpp.AccountId)
				.setFirstName('Test')
				.setLastName('User02')
				.setEmail('testuser02@gusto.com')
				.setZPUserId('75002')
				.build()
		);
		list_NewContact.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
				.setAccountId(objOpp.AccountId)
				.setFirstName('Test')
				.setLastName('User03')
				.setEmail('testuser03@gusto.com')
				.setZPUserId('75003')
				.build()
		);
		insert list_NewContact;

		ContactTriggerHelper.skipTrigger = false;

		//Create Benefit Order
		Benefit_Order__c objBONewPlan = new TestDataFactory.BenefitOrderBuilder()
			.setRecordType(BenefitOrderUtil.NEW_PLAN_BENEFIT_ORDER_RT_ID)
			.setName('Test Benefit Order')
			.setAccount(objOpp.AccountId)
			.setOpp(objOpp.Id)
			.setOpenEnrollmentStartDate(System.today().addDays(-3))
			.setOpenEnrollmentEndDate(System.today().addDays(-1))
			.setFinalExtensionDate(System.today())
			.setCoverageEffectiveDate(System.today())
			.setSubmissionDeadline(System.today())
			.setOwnerID(UserInfo.getUserId())
			.setStatus('Ready for Qualification')
			.build();
		insert objBONewPlan;

		//Create Carrier record
		List<Carrier__c> list_Carrier = new List<Carrier__c>();
		list_Carrier.add(new TestDataFactory.CarrierBuilder().setName('Test Carrier').setUniqueName('Test Carrier').setId('4536').build());
		list_Carrier.add(new TestDataFactory.CarrierBuilder().setName('Alegeus').setUniqueName('Alegeus').setPartnerType('TAdA').build());
		list_Carrier.add(new TestDataFactory.CarrierBuilder().setName('Test Carrier 1').setUniqueName('Test Carrier 1').setId('4537').build());
		insert list_Carrier;

		//Create Carrier Order
		List<Carrier_Order__c> list_CO = new List<Carrier_Order__c>();
		list_CO.add(
			new TestDataFactory.CarrierOrderBuilder()
				.setRecordTypeId(CarrierOrderUtil.RECTYPE_NEW_PLAN)
				.setOrderAssignment('Carrier Switch')
				.setBenefitOrder(objBONewPlan.Id)
				.setImplementationStage('Ready For Qualification')
				.setGroupNumber('1234')
				.setCarrier(list_Carrier[0].Id)
				.build()
		);

		list_CO.add(
			new TestDataFactory.CarrierOrderBuilder()
				.setRecordTypeId(CarrierOrderUtil.RECTYPE_NEW_PLAN)
				.setOrderAssignment('Carrier Switch')
				.setBenefitOrder(objBONewPlan.Id)
				.setImplementationStage('Ready For Qualification')
				.setGroupNumber('3432')
				.setCarrier(list_Carrier[1].Id)
				.setBenefitTypes('HSA;FSA')
				.build()
		);

		list_CO.add(
			new TestDataFactory.CarrierOrderBuilder()
				.setRecordTypeId(CarrierOrderUtil.RECTYPE_NEW_PLAN)
				.setOrderAssignment('Carrier Switch')
				.setBenefitOrder(objBONewPlan.Id)
				.setImplementationStage('Ready For Qualification')
				.setGroupNumber('1235')
				.setCarrier(list_Carrier[2].Id)
				.build()
		);

		insert list_CO;

		//Create QA Sheet Test records
		QA_Sheet__c objQASheet = new TestDataFactory.QASheetBuilder()
			.setBenefitOrderId(objBONewPlan.Id)
			.setFederalCobraState('Federal')
			.setSICCodeSupportedByAllCarriers('Yes')
			.setSICCode('test')
			.setBAASigned('Yes')
			.setBAASignedBy('test')
			.setBSASigned('Yes')
			.setBSASignedBy('test')
			.setRecordTypeId(QASheetHelper.QAS_BEN_NP_RT_ID)
			.build();
		insert objQASheet;

		//Create QA Lines Of Coverage Test records
		QA_Lines_Of_Coverage__c objQALine = new TestDataFactory.QALineOfCoverageBuilder()
			.setQASheetId(objQASheet.Id)
			.setLinesOfCoverage('Medical')
			.setColorCode('Benefits_selected_Carrier__c')
			.setSNO(0)
			.build();
		insert objQALine;

		CreateWarningMessagesLwcTest.skipTrigger(false);
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Test Benefis Order Confitmation Coverage Email Warning Messages.
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testBOWarningMessages() {
		List<Benefit_Order__c> list_BO = [SELECT Id, Opportunity__c, Opportunity__r.AccountId FROM Benefit_Order__c WHERE Opportunity__r.Name = 'Test New Plan Opportunity'];
		List<Contact> list_Contact = [SELECT Id, AccountId FROM Contact LIMIT 1];

		//Update BO order status
		CreateWarningMessagesLwcTest.skipTrigger(true);

		list_BO[0].Order_Status__c = BenefitOrderUtil.STATUS_APPROVED;
		update list_BO[0];

		//Update Carrier Order
		List<Carrier_Order__c> list_CO = [SELECT Id, Implementation_Stage__c FROM Carrier_Order__c WHERE Benefit_Order__c = :list_BO[0].Id];
		for (Carrier_Order__c objCO : list_CO) {
			objCO.Implementation_Stage__c = BenefitOrderUtil.STATUS_APPROVED;
		}
		update list_CO;
		CreateWarningMessagesLwcTest.skipTrigger(false);

		//Create new case record having record type as : Benefits Renewal Case
		Id idRenewal = CaseUtils.RECTYPE_RENEWAL;
		Case objCase = new Case(
			Subject = 'Test Case 1',
			ContactId = list_Contact[0].Id,
			AccountId = list_Contact[0].AccountId,
			RecordTypeId = idRenewal,
			Priority = 'Medium',
			Direction__c = 'Inbound',
			Origin = 'Email',
			Benefit_Order__c = list_BO[0].Id,
			Integration_Id__c = 'hippo-Benefits_New_Plan-' + list_BO[0].Opportunity__c,
			Opportunity__c = list_BO[0].Opportunity__c
		);

		insert objCase;

		objCase.Carrier_Order__c = null;
		update objCase;

		List<Case> list_Case = [SELECT Id, Renewal_Survey_URL__c, NP_Survey_URL__c FROM Case WHERE Id = :objCase.Id];
		if (OrganizationUtilities.canSendEmails()) {
			System.assert(list_Case.size() > 0);
		}

		test.startTest();
		CreateWarningMessagesLwc.WarningMessagesWrapper objWrapper = CreateWarningMessagesLwc.showEmailWarningMessages(list_BO[0].Id, BenefitOrderUtil.Benefit_Order);
		System.assertEquals(objWrapper.blnIsSuccess, true);

		Id idRenewalRecord = BenefitOrderUtil.RENEWAL_BENEFIT_ORDER_RT_ID;
		list_BO[0].RecordTypeId = idRenewalRecord;
		list_BO[0].Order_Status__c = BenefitOrderUtil.STATUS_APPROVED;
		update list_BO[0];

		CreateWarningMessagesLwc.WarningMessagesWrapper objWrapper1 = CreateWarningMessagesLwc.showEmailWarningMessages(list_BO[0].Id, BenefitOrderUtil.Benefit_Order);
		System.assertEquals(objWrapper1.blnIsSuccess, true);

		Id idBO = null;
		CreateWarningMessagesLwc.WarningMessagesWrapper objWrapper2 = CreateWarningMessagesLwc.showEmailWarningMessages(idBO, BenefitOrderUtil.Benefit_Order);
		System.assertEquals(objWrapper2.blnIsSuccess, false);

		test.stopTest();
	}

	/**
	 * @Author      : Deepika Saini
	 * @Description : Skip Trigger to avoid DML Exception
	 * @Parm        : Boolean Flag
	 * @Return      : null
	 **/
	public static void skipTrigger(Boolean blnFlag) {
		ContactTriggerHelper.skipTrigger = blnFlag;
		AccountTriggerHelper.skipTrigger = blnFlag;
		OpportunityTriggerHelper.skipTrigger = blnFlag;
		CaseTriggerHelper.skipTrigger = blnFlag;
		BenefitOrderHelper.skipTrigger = blnFlag;
		CarrierOrderTriggerHelper.skipTrigger = blnFlag;
	}
}