force-app/main/default/objects/Bulk_Migration_Request__c/Bulk_Migration_Request__c.object-meta.xml
<CustomObject>
    <label>Bulk Migration Request</label>
    <nameField>
        <displayFormat>BMR-{0000}</displayFormat>
        <label>Bulk Migration Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Migration Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Bulk_Migration_Owner__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bulk_Migration_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Bulk_Migration_Status__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration_Status__c</fullName>
    <label>Bulk Migration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Final_Check_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Check_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Primary_Point_of_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Point_of_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Point of Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bulk Migration Requests</relationshipLabel>
    <relationshipName>Bulk_Migration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Bulk_Migration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Requested_First_Check_Date__c.field-meta.xml
<CustomField>
    <fullName>Requested_First_Check_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Requested First Check Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Reseller_Account__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bulk Migration Requests</relationshipLabel>
    <relationshipName>Bulk_Migration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Migration_Request__c/fields/Transition_To_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Transition_To_Fulfillment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transition To Fulfillment</label>
    <referenceTo>Transition_to_Fulfillment__c</referenceTo>
    <relationshipLabel>Bulk Migration Requests</relationshipLabel>
    <relationshipName>Bulk_Migration_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bulk_Migration_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bulk Migration</fullName>
            </value>
            <value>
                <fullName>Multi-EIN</fullName>
            </value>
            <value>
                <fullName>Same Login</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bulk_Order_CSV_Columns__c/Bulk_Order_CSV_Columns__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Bulk Order CSV Columns</label>
</CustomObject>

force-app/main/default/objects/Bulk_Order_CSV_Columns__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Order_CSV_Columns__c/fields/Field_Values__c.field-meta.xml
<CustomField>
    <fullName>Field_Values__c</fullName>
    <label>Field Values</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Order_CSV_Data__c/Bulk_Order_CSV_Data__c.object-meta.xml
<CustomObject>
    <description>Temporary objects that will hold records from csv, will be used by Batch to process Orders</description>
    <label>Bulk Order CSV Data</label>
    <nameField>
        <displayFormat>CSV-{0000}</displayFormat>
        <label>CSV For Orders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bulk Order CSV Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bulk_Order_CSV_Data__c/fields/Bulk_Migration_Request__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Migration_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bulk Migration Request</label>
    <referenceTo>Bulk_Migration_Request__c</referenceTo>
    <relationshipName>CSV_For_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bulk_Order_CSV_Data__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bulk_Order_CSV_Data__c/fields/First_Pay_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Pay_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>First Pay Date</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Transition_to_Fulfillment__c/Transition_to_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>Transition to Fulfillment</label>
    <nameField>
        <displayFormat>TF-{00000}</displayFormat>
        <label>Transition to Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transition to Fulfillments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BulkOrderUploadController.cls
public with sharing class BulkOrderUploadController {
	public Boolean readSuccess { get; set; }
	public Set<String> setFieldNames { get; set; }
	public Map<String, String> fieldNamesMap { get; set; }
	public Bulk_Migration_Request__c BMRRecord { get; set; }
	public string testCSVData { get; set; }
	public List<Bulk_Order_CSV_Data__c> lstCSVRecords { get; set; }
	public List<Bulk_Order_CSV_Data__c> lstCSVRecordsFinal { get; set; }

	public Set<string> companyIdSet = new Set<string>();
	public Blob fileData { get; set; }
	String CSVDataAsString;
	String fieldValue;
	Integer fieldNumber;
	string message = '';
	Map<String, Integer> fieldNumberMap = new Map<String, Integer>();
	Map<String, string> fieldsCustSettingsMap = new Map<String, string>();
	Id bulkMigrationId { get; set; }

	public BulkOrderUploadController() {
		lstCSVRecordsFinal = new List<Bulk_Order_CSV_Data__c>();
		setFieldNames = new Set<string>();
		readSuccess = false;

		Map<String, Bulk_Order_CSV_Columns__c> uploadSetting = Bulk_Order_CSV_Columns__c.getAll();
		for (Bulk_Order_CSV_Columns__c temp : uploadSetting.Values()) {
			string sfieldName = temp.Field_Values__c.replaceAll('[^a-zA-Z0-9]', '').trim();
			fieldsCustSettingsMap.put(sfieldName, String.valueOf(temp.Field_API_Name__c));
		}
		bulkMigrationId = ApexPages.currentPage().getParameters().get('id');

		if (!String.isEmpty(bulkMigrationId)) {
			populateBulMigrationFields(bulkMigrationId);
		} else {
			BMRRecord = new Bulk_Migration_Request__c();
		}
	}
	public void populateBulMigrationFields(Id bulMigId) {
		List<Bulk_Migration_Request__c> bulkMigRequestList = [
			SELECT
				Id,
				Requested_By__c,
				Bulk_Migration_Owner__c,
				Bulk_Migration_Status__c,
				Requested_First_Check_Date__c,
				Primary_Point_of_Contact__c,
				Final_Check_Date__c,
				Transition_To_Fulfillment__c,
				Reseller_Account__c,
				OwnerId
			FROM Bulk_Migration_Request__c
			WHERE ID = :bulMigId
		];

		if (bulkMigRequestList != null && bulkMigRequestList.size() > 0) {
			BMRRecord = bulkMigRequestList[0];
		}
	}

	List<List<String>> allData;
	private List<List<String>> parseCSV(string contents) {
		try {
			String freshString = '';
			List<String> lines = new List<String>();
			lines.addAll(contents.split('\r\n'));
			callDataParsing(lines);
		} catch (Exception ex) {
			System.debug(LoggingLevel.ERROR, ex.getMessage());
		}
		return allData;
	}
	public void callDataParsing(List<string> lines) {
		allData = new List<List<String>>();
		for (String line : lines) {
			if (line.replaceAll(',', '').trim().length() == 0) {
				break;
			}

			List<String> cleanFields = new List<String>();
			String compositeField;
			Boolean makeCompositeField = false;

			for (String field : line.split(',')) {
				if (!'#EOL#'.equalsIgnoreCase(field)) {
					if (field.trim().startsWith('"') && field.trim().endsWith('"')) {
						cleanFields.add(field.replaceAll(',"""', ',""').replaceAll('""",', '"",').replaceAll('""', '"').trim());
					} else if (field.trim().startsWith('"')) {
						makeCompositeField = true;
						compositeField = field.trim();
					} else if (field.trim().endsWith('"')) {
						compositeField += ',' + field.trim();
						cleanFields.add(compositeField.replaceAll(',"""', ',""').replaceAll('""",', '"",').replaceAll('""', '"').trim());
						makeCompositeField = false;
					} else if (makeCompositeField) {
						compositeField += ',' + field.trim();
					} else {
						cleanFields.add(field.replaceAll(',"""', ',""').replaceAll('""",', '"",').replaceAll('""', '"').trim());
					}
				}
			}
			allData.add(cleanFields);
		}
	}
	public void readCSVFile(List<List<String>> allData) {
		Set<string> bulkOrderCSVDataObjFieldsSet = getCSVObjectFields();
		//lstCSVRecords.clear();
		lstCSVRecordsFinal.clear();
		fieldNamesMap = new Map<String, String>();
		List<Bulk_Order_CSV_Data__c> lstCSVRecords = new List<Bulk_Order_CSV_Data__c>();
		string[] csvFieldNames = allData[0];
		for (Integer i = 0; i < csvFieldNames.size(); i++) {
			fieldNumberMap.put(csvFieldNames[i], i);

			String apiName = getFieldMapping(csvFieldNames[i].trim());
			if (apiName != null) {
				if (bulkOrderCSVDataObjFieldsSet.contains(apiName)) {
					fieldNamesMap.put(csvFieldNames[i].trim(), apiName);
					setFieldNames.add(csvFieldNames[i].trim());
				}
			}
		}
		for (Integer i = 1; i < allData.size(); i++) {
			Bulk_Order_CSV_Data__c oppObj = new Bulk_Order_CSV_Data__c();
			String[] csvRecordData = allData[i];
			if (csvRecordData.size() > 0) {
				for (String fieldName : csvFieldNames) {
					fieldNumber = fieldNumberMap.get(fieldName);
					if (csvRecordData.size() - 1 >= fieldNumber) {
						fieldValue = csvRecordData[fieldNumber];
					} else {
						fieldValue = '';
					}
					String apiName = fieldNamesMap.get(fieldName.trim());
					if (apiName != null) {
						if (bulkOrderCSVDataObjFieldsSet.contains(apiName)) {
							oppObj.put(apiName, fieldValue.trim());
						}
					}
				}

				lstCSVRecords.add(oppObj);
			}
		}
		if (lstCSVRecords.size() > 0) {
			// Remove duplicate records
			companyIdSet.clear();
			for (Bulk_Order_CSV_Data__c obj : lstCSVRecords) {
				if (!companyIdSet.contains(obj.Company_ID__c)) {
					obj.OwnerId = UserInfo.getUserId();
					lstCSVRecordsFinal.add(obj);
					companyIdSet.add(obj.Company_ID__c);
				}
			}
			if (lstCSVRecordsFinal.size() > 0) {
				readSuccess = true;
			} else {
				readSuccess = false;
				message = 'CSV cannot be recognized. Please upload correct CSV';
				displayErrorMessage(message);
			}
		} else {
			readSuccess = false;
			message = 'CSV does not have any data rows. Please update your file and try again.';
			displayErrorMessage(message);
		}
	}
	public void readFromFile() {
		try {
			if (!Test.isRunningTest()) {
				CSVDataAsString = fileData.toString();
			} else {
				CSVDataAsString = testCSVData;
			}

			List<List<String>> cleanData = parseCSV(CSVDataAsString);
			if (cleanData.size() > 0) {
				readCSVFile(cleanData);
			} else {
				readSuccess = false;
				message = 'Invalid csv file. Please upload correct csv file.';
				displayErrorMessage(message);
			}
		} catch (exception e) {
			readSuccess = false;
			if (e.getMessage() == 'Argument cannot be null.') {
				message = 'Please Select and Upload CSV File';
			} else if (e.getMessage() == 'BLOB is not a valid UTF-8 string') {
				message = 'Only CSV file is allowed';
			} else {
				message = 'Invalid csv /Error reading csv file' + '<Br/>' + 'Exception === ' + e.getMessage() + ' ' + e.getStackTraceString();
			}
			displayErrorMessage(message);
		}
	}
	public String getFieldMapping(String fieldName) {
		String fieldAPIName;
		string sFiledName = fieldName.replaceAll('[^a-zA-Z0-9]', '').trim();
		if (fieldsCustSettingsMap.containsKey(sFiledName)) {
			fieldAPIName = fieldsCustSettingsMap.get(sFiledName);
		}
		return fieldAPIName;
	}
	public void discard() {
		lstCSVRecordsFinal.clear();
		readSuccess = false;
		ApexPages.getMessages().clear();
	}
	public PageReference confirm() {
		Boolean isValidDate = validateDate(lstCSVRecordsFinal);
		if (!isValidDate) {
			return null;
		}

		bulkMigrationId = ApexPages.currentPage().getParameters().get('id');
		Id bmrId;
		Savepoint sp = Database.setSavepoint();
		if (String.IsEmpty(bulkMigrationId)) {
			// Insert scenario
			BMRRecord.Bulk_Migration_Status__c = 'New';
			BMRRecord.Type__c = 'Bulk Migration';

			Database.SaveResult srList = Database.insert(BMRRecord, false);
			if (!srList.isSuccess()) {
				for (Database.Error error : srList.getErrors()) {
					message += error.getMessage() + ';';
				}
				Database.rollback(sp);
				displayErrorMessage(message);
				return null;
			} else {
				bmrId = srList.getId();
			}
		} else {
			// Update scenario
			bmrId = bulkMigrationId; // recieved as a page parameter
			BMRRecord.Bulk_Migration_Status__c = 'In Progress';
			update BMRRecord;
		}

		for (Bulk_Order_CSV_Data__c temp : lstCSVRecordsFinal) {
			temp.Bulk_Migration_Request__c = bmrId;
		}
		Database.SaveResult[] orderList = Database.insert(lstCSVRecordsFinal, false);
		// Iterate through each returned result
		for (Database.SaveResult sr : orderList) {
			if (sr.isSuccess()) {
				PageReference orderPage = new PageReference('/apex/BulkOrderUploadStatus?id=' + bmrId);
				orderPage.setRedirect(true);
				return orderPage;
			} else {
				for (Database.Error error : sr.getErrors()) {
					message += error.getMessage() + ';';
				}
				Database.rollback(sp);
				displayErrorMessage(message);
			}
		}

		return null;
	}

	public Set<String> getCSVObjectFields() {
		Set<string> fieldsSet = new Set<String>();
		Schema.DescribeSObjectResult a_desc = Bulk_Order_CSV_Data__c.sObjectType.getDescribe();
		Map<String, Schema.SObjectField> a_fields = a_desc.fields.getMap();
		for (Schema.sObjectField fld : a_fields.values()) {
			fieldsSet.add(String.valueOf(fld));
		}
		return fieldsSet;
	}

	public boolean validateDate(List<Bulk_Order_CSV_Data__c> bulkOrderCSVDataList) {
		integer i = 0;
		for (Bulk_Order_CSV_Data__c obj : bulkOrderCSVDataList) {
			try {
				i++;
				if (!String.isBlank(obj.First_Pay_Date__c)) {
					Date d = date.ValueOf(obj.First_Pay_Date__c);
				}
			} catch (Exception e) {
				message = 'Invalid date format : ' + obj.First_Pay_Date__c + ' (at row no. ' + i + ')';
				displayErrorMessage(message);
				return false;
			}
		}
		return true;
	}

	public void displayErrorMessage(string message) {
		if (!String.isBlank(message)) {
			ApexPages.getMessages().clear();
			ApexPages.Message errorMessage;
			errorMessage = new ApexPages.Message(ApexPages.Severity.ERROR, message);
			ApexPages.addMessage(errorMessage);
		}
	}
}