force-app/main/default/objects/Account/fields/Apply_to_all_clients__c.field-meta.xml
<CustomField>
    <fullName>Apply_to_all_clients__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Captures if Benefits Out Out apples to all clients (From &quot;Reseller&quot; account down to &quot;Company&quot; Accounts).</description>
    <label>Apply to all clients</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Benefit_Opt_Out_Sync__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Opt_Out_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set Benefits Opt Out Sync if Benefits Opt Out changes on reseller account.
Will be picked by batch job and processed to direct opportunities.</description>
    <label>Benefit Opt Out Sync</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Benefits_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Email_Opt_Out__c</fullName>
    <inlineHelpText>Select the Benefit the lead does not want to be contacted about HI  / 401k / Workers comp</inlineHelpText>
    <label>Benefits Opt Out</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Health Insurance</fullName>
            </value>
            <value>
                <fullName>401k</fullName>
            </value>
            <value>
                <fullName>Workers Comp</fullName>
            </value>
            <value>
                <fullName>P&amp;C Insurance</fullName>
            </value>
            <value>
                <fullName>CorpNet</fullName>
            </value>
            <value>
                <fullName>BD/Tech-Enabled Partners</fullName>
            </value>
            <value>
                <fullName>No Marketing</fullName>
            </value>
            <value>
                <fullName>R&amp;D Tax Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Upsell_Opp_Open__c.field-meta.xml
<CustomField>
    <fullName>Upsell_Opp_Open__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upsell Opp Open</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

unpackaged/main/default/objects/Configuration_Settings__c/fields/CL_Tier_Upsell_Age__c.field-meta.xml
<CustomField>
    <fullName>CL_Tier_Upsell_Age__c</fullName>
    <defaultValue>45</defaultValue>
    <label>CL Tier Upsell Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Benefits_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Benefits_Opt_Out__c</fullName>
    <description>Benefits Opt Out - reflects same field from Sold By Account.</description>
    <label>Benefits Opt Out</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Health Insurance</fullName>
            </value>
            <value>
                <fullName>401k</fullName>
            </value>
            <value>
                <fullName>Workers Comp</fullName>
            </value>
            <value>
                <fullName>P&amp;C Insurance</fullName>
            </value>
            <value>
                <fullName>CorpNet</fullName>
            </value>
            <value>
                <fullName>BD/Tech-Enabled Partners</fullName>
            </value>
            <value>
                <fullName>No Marketing</fullName>
            </value>
            <value>
                <fullName>R&amp;D Tax Credits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_Tier__c.field-meta.xml
<CustomField>
    <fullName>Current_Tier__c</fullName>
    <description>This is the Tier of the Company Account at the time of the Tier Upsell Opportunity Creation. This field, once populated, does not update after creation.</description>
    <inlineHelpText>This is the Tier of the Company Account at the time of the Tier Upsell Opportunity Creation. This field, once populated, does not update after creation.</inlineHelpText>
    <label>Current Tier</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Concierge</fullName>
            </value>
            <value>
                <fullName>Legacy Premium</fullName>
            </value>
            <value>
                <fullName>Premium CRB</fullName>
            </value>
            <value>
                <fullName>Premium Multi-EIN</fullName>
            </value>
            <value>
                <fullName>Contractor Only</fullName>
            </value>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>Plus</fullName>
            </value>
            <value>
                <fullName>Premium</fullName>
            </value>
            <value>
                <fullName>contractor_only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Detail__c.field-meta.xml
<CustomField>
    <fullName>Stage_Detail__c</fullName>
    <label>Stage Detail</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>[Benefits] BoR&apos;ed Away - At Renewal</fullName>
            </value>
            <value>
                <fullName>[Benefits] BoR&apos;ed Away - Before Renewal Cycle</fullName>
            </value>
            <value>
                <fullName>[Benefits] Canceling HI Coverage</fullName>
            </value>
            <value>
                <fullName>[Benefits] Carrier Won&apos;t Allow Change</fullName>
            </value>
            <value>
                <fullName>[Benefits] Chose Competitor</fullName>
            </value>
            <value>
                <fullName>[Benefits] Employees Not Eligible</fullName>
            </value>
            <value>
                <fullName>[Benefits] Not eligible</fullName>
            </value>
            <value>
                <fullName>[Benefits] Post-Signature Cancel - Customer Cancel</fullName>
            </value>
            <value>
                <fullName>[Benefits] Route to NP</fullName>
            </value>
            <value>
                <fullName>[Benefits] Switching to PEO</fullName>
            </value>
            <value>
                <fullName>[Logistics] Disruption to Workforce</fullName>
            </value>
            <value>
                <fullName>[Logistics] Not offering medical (cost)</fullName>
            </value>
            <value>
                <fullName>[Logistics] Not offering medical (participation)</fullName>
            </value>
            <value>
                <fullName>[Logistics] RFI Complication</fullName>
            </value>
            <value>
                <fullName>[Logistics] Special Enrollment Period Expired</fullName>
            </value>
            <value>
                <fullName>[Logistics] Too Expensive</fullName>
            </value>
            <value>
                <fullName>[Logistics] Too Labor-Intensive</fullName>
            </value>
            <value>
                <fullName>[Logistics] Unsupported: Not/No Longer Gusto Payroll Customer</fullName>
            </value>
            <value>
                <fullName>[Logistics] Upcoming/Active Renewal</fullName>
            </value>
            <value>
                <fullName>[Logistics] Workers Comp Unsupported</fullName>
            </value>
            <value>
                <fullName>[Other] Duplicate Opportunity</fullName>
            </value>
            <value>
                <fullName>[Other] Migrations Capacity</fullName>
            </value>
            <value>
                <fullName>[Other] Non Product</fullName>
            </value>
            <value>
                <fullName>[Other] Other</fullName>
            </value>
            <value>
                <fullName>[Other] Renewal Aligned</fullName>
            </value>
            <value>
                <fullName>[Partner] Partner Incentives</fullName>
            </value>
            <value>
                <fullName>[Payroll] Blocked by Benefits Oppty</fullName>
            </value>
            <value>
                <fullName>[Product] 401(k) Functionality</fullName>
            </value>
            <value>
                <fullName>[Product] ACH Window</fullName>
            </value>
            <value>
                <fullName>[Product] Agricultural Employees</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Timing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tier_Config__c/Tier_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration used to store names of old tiers and plans</description>
    <label>Tier Config</label>
</CustomObject>

force-app/main/default/objects/Tier_Config__c/fields/New_Price_1__c.field-meta.xml
<CustomField>
    <fullName>New_Price_1__c</fullName>
    <description>Price of the new Simple Tier - Typically $40 Base, $6: 1+</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Price 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tier_Config__c/fields/New_Price_2__c.field-meta.xml
<CustomField>
    <fullName>New_Price_2__c</fullName>
    <description>Price of the new Plus Tier - Typically $80 Base, $12: 1+</description>
    <encryptionScheme>None</encryptionScheme>
    <label>New Price 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityJobsTest.cls
/**
 * @name         : OpportunityJobsTest
 * @author       : Prashant Bhatt
 * @date         : 03-17-2021
 * @description  : Test class for OpportunityJobs
 **/

@isTest
public class OpportunityJobsTest {
	@isTest
	public static void testBenefitsOptOutSyncOnOpportunityPositive() {
		List<Account> list_Accounts = new List<Account>();

		Account objCompanyAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId('Company')
			 .setZPCompanyId('1234567890')
			 .build(); 
		list_Accounts.add(objCompanyAccount);

		Account objResellerAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId(AccountUtil.RESELLER_ACCOUNT_RT_ID)
			 .setZPFirmId('7777789')
			 .setBenefitsEmailOptOut('Health Insurance')
			 .build();
		list_Accounts.add(objResellerAccount);

		AccountTriggerHelper.skipTrigger = true;
		insert list_Accounts;
		AccountTriggerHelper.skipTrigger = false;

		Opportunity objCompanyOpp = new TestDataFactory.OpportunityBuilder()
			 .setAccountId(objCompanyAccount.Id)
			 .setRecordTypeId(OpportunityUtil.COMPANY_OPPTY_RT_ID)
			 .setName('GUSTO-TESTOPP')
			 .setStage('Qualified')
			 .setCloseDate(System.today())
			 .setSoldBy(objResellerAccount.Id)
			 .build();
		OpportunityTriggerHelper.skipTrigger = true;
		insert objCompanyOpp;

		Test.startTest();
		objResellerAccount.Apply_to_all_clients__c = true;
		objResellerAccount.Benefits_Email_Opt_Out__c = 'Health Insurance;Workers Comp';
		update objResellerAccount;

		Database.executeBatch(new OpportunityJobs(''));
		Test.stopTest();

		objCompanyOpp = [SELECT Id, Benefits_Opt_Out__c FROM Opportunity WHERE Id = :objCompanyOpp.Id];
		System.assertEquals(objCompanyOpp.Benefits_Opt_Out__c, 'Health Insurance;Workers Comp');

		objResellerAccount = [SELECT Id, Benefit_Opt_Out_Sync__c FROM Account WHERE Id = :objResellerAccount.Id];
		System.assertEquals(objResellerAccount.Benefit_Opt_Out_Sync__c, false);
	}

	@isTest
	public static void testBenefitsOptOutSyncOnOpportunityNegative() {
		List<Account> list_Accounts = new List<Account>();

		Account objCompanyAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId('Company')
			 .setZPCompanyId('1234567890')
			 .build();
		list_Accounts.add(objCompanyAccount);

		Account objResellerAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId(AccountUtil.RESELLER_ACCOUNT_RT_ID)
			 .setZPFirmId('7777789')
			 .setBenefitsEmailOptOut('Health Insurance')
			 .build();
		list_Accounts.add(objResellerAccount);

		AccountTriggerHelper.skipTrigger = true;
		insert list_Accounts;
		AccountTriggerHelper.skipTrigger = false;

		Opportunity objCompanyOpp = new TestDataFactory.OpportunityBuilder()
			 .setAccountId(objCompanyAccount.Id)
			 .setRecordTypeId(OpportunityUtil.COMPANY_OPPTY_RT_ID)
			 .setName('GUSTO-TESTOPP')
			 .setStage('Qualified')
			 .setCloseDate(System.today())
			 .setSoldBy(objResellerAccount.Id)
			 .build();
		OpportunityTriggerHelper.skipTrigger = true;
		insert objCompanyOpp;

		Test.startTest();
		objResellerAccount.Apply_to_all_clients__c = true;
		update objResellerAccount;

		Database.executeBatch(new OpportunityJobs(''));
		Test.stopTest();

		objCompanyOpp = [SELECT Id, Benefits_Opt_Out__c FROM Opportunity WHERE Id = :objCompanyOpp.Id];
		System.assertEquals(objCompanyOpp.Benefits_Opt_Out__c, null);

		objResellerAccount = [SELECT Id, Benefit_Opt_Out_Sync__c FROM Account WHERE Id = :objResellerAccount.Id];
		System.assertEquals(objResellerAccount.Benefit_Opt_Out_Sync__c, false);
	}

	@isTest
	static void testBenefitsOptOutSyncOnOpportunityPositiveScheduled() {
		List<Account> list_Accounts = new List<Account>();

		Account objCompanyAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId('Company')
			 .setZPCompanyId('1234567890')
			 .build();
		list_Accounts.add(objCompanyAccount);

		Account objResellerAccount = new TestDataFactory.AccountBuilder()
			 .setName('name')
			 .setRecordTypeId(AccountUtil.RESELLER_ACCOUNT_RT_ID)
			 .setZPFirmId('7777789')
			 .setBenefitsEmailOptOut('Health Insurance')
			 .build();
		list_Accounts.add(objResellerAccount);

		AccountTriggerHelper.skipTrigger = true;
		insert list_Accounts;
		AccountTriggerHelper.skipTrigger = false;

		Opportunity objCompanyOpp = new TestDataFactory.OpportunityBuilder()
			 .setAccountId(objCompanyAccount.Id)
			 .setRecordTypeId(OpportunityUtil.COMPANY_OPPTY_RT_ID)
			 .setName('GUSTO-TESTOPP')
			 .setStage('Qualified')
			 .setCloseDate(System.today())
			 .setSoldBy(objResellerAccount.Id)
			 .build();
		OpportunityTriggerHelper.skipTrigger = true;
		insert objCompanyOpp;

		Test.startTest();
		objResellerAccount.Apply_to_all_clients__c = true;
		objResellerAccount.Benefits_Email_Opt_Out__c = 'Health Insurance;Workers Comp';
		update objResellerAccount;

		// Dynamically scheduling jobs for next year
		Integer intNextYear = Date.today().year() + 1;
		String strCronExp = '0 0 0 15 3 ? ' + intNextYear;
		OpportunityJobsScheduler objScheduler = new OpportunityJobsScheduler();
		String jobId = System.schedule('Test Benefits Opt Out Sync Scheduler', strCronExp, objScheduler);
		// Directly call Scheduler's execute method
		objScheduler.execute(null);
		Test.stopTest();

		objCompanyOpp = [SELECT Id, Benefits_Opt_Out__c FROM Opportunity WHERE Id = :objCompanyOpp.Id];
		System.assertEquals(objResellerAccount.Benefits_Email_Opt_Out__c, objCompanyOpp.Benefits_Opt_Out__c);

		objResellerAccount = [SELECT Id, Benefit_Opt_Out_Sync__c FROM Account WHERE Id = :objResellerAccount.Id];
		System.assertEquals(objResellerAccount.Benefit_Opt_Out_Sync__c, false);
	}

	@isTest
	static void testTierUpsellClosedLostScheduled() {
		// insert org default tier config settings
		Tier_Config__c objTierConfig = new TestDataFactory.TierConfigBuilder().build();
		insert objTierConfig;
		objTierConfig = Tier_Config__c.getOrgDefaults();
		setUpNewPrices(objTierConfig.New_Price_2__c, false);
		setUpNewPrices(objTierConfig.New_Price_1__c, false);
		Configuration_Settings__c objConfigSettings = new TestDataFactory.ConfigurationSettingsBuilder().setTierUpsellTimingSize(45).build();
		Integer intAge = objConfigSettings.CL_Tier_Upsell_Age__c != null && objConfigSettings.CL_Tier_Upsell_Age__c != 0 ? objConfigSettings.CL_Tier_Upsell_Age__c.intValue() : 45;
		TriggerHandler.bypass('AccountTriggerHandler');
		Account objAccount = new TestDataFactory.AccountBuilder()
			.setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID)
			.setName('Company Account OHI')
			.setZPCompanyId('11123334')
			.setPricing(AccountUtil.SIMPLE_PAYMENT_PLAN)
			.setTier(AccountUtil.SIMPLE_TIER)
			.setNumberOfActiveEEs(8)
			.build();
		insert objAccount;
		TriggerHandler.clearAllBypasses();
		Opportunity objOpportunity = new TestDataFactory.OpportunityBuilder()
			.setRecordTypeId(OpportunityUtil.TIER_UPSELL_OPPTY_RT_ID)
			.setName('APD Upsell Opportunity')
			.setAccountId(objAccount.Id)
			.setUpsellTier(AccountUtil.PLUS_TIER)
			.setStage('Qualified')
			.setType('Upsell')
			.build();
		objOpportunity.Current_Tier__c = AccountUtil.SIMPLE_TIER;
		insert objOpportunity;
		DateTime dtCLTime = Datetime.now().addDays(-47);
		Test.setCreatedDate(objOpportunity.Id, dtCLTime);
		Account objAssertAcc = [SELECT Id, Upsell_Opp_Open__c FROM Account WHERE Id = :objAccount.Id];
		System.assertEquals(objAssertAcc.Upsell_Opp_Open__c, true);

		Test.startTest();
		Database.executeBatch(new OpportunityJobs(''));
		Test.stopTest();

		Opportunity objAssertOpp = [SELECT Id, CloseDate, StageName, Stage_Detail__c FROM Opportunity WHERE Id = :objOpportunity.Id];
		objAssertAcc = [SELECT Id, Upsell_Opp_Open__c FROM Account WHERE Id = :objAccount.Id];
		System.assertEquals(objAssertOpp.StageName, 'Closed Lost');
		System.assertEquals(objAssertOpp.Stage_Detail__c, 'Timing');
		System.assertEquals(objAssertOpp.CloseDate, Date.today());
		System.assertEquals(objAssertAcc.Upsell_Opp_Open__c, false);
	}

	/**
	 * @description Setting up test data for creating pricebook and pricebook entries
	 * @author      Praveen Sethu
	 * @param       NA
	 * @return      NA
	 **/
	public static void setUpNewPrices(String strPriceName, Boolean blnPrioritySupport) {
		// Start setting up data and create pricebook and pricebook entries
		// Create a new pricebook
		Pricebook2 objPriceBookOne = new TestDataFactory.PriceBookBuilder().setName(strPriceName).setActive().build();
		insert objPriceBookOne;

		// Create new products
		List<Product2> list_Products = new List<Product2>();
		list_Products.add(TestUtility.createTestProduct('Company', 'Company', false));
		list_Products.add(TestUtility.createTestProduct('Active Employee', 'Employee', false));
		list_Products.add(TestUtility.createTestProduct('Contractor', 'Payroll', false));
		if (blnPrioritySupport) {
			list_Products.add(TestUtility.createTestProduct(OpportunityUtil.PRIORITY_SUPPORT_EMPLOYEE, 'Payroll', false));
			list_Products.add(TestUtility.createTestProduct(OpportunityUtil.PRIORITY_SUPPORT_CONTRACTOR, 'Payroll', false));
		}
		insert list_Products;

		// Create pricebook entries
		List<PricebookEntry> list_Entries = new List<PricebookEntry>();
		// create standard pricebook entries before creating custom ones
		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[0].Id, 5, Test.getStandardPriceBookId(), false));
		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[1].Id, 5, Test.getStandardPriceBookId(), false));
		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[2].Id, 5, Test.getStandardPriceBookId(), false));
		if (blnPrioritySupport) {
			list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[3].Id, 5, Test.getStandardPriceBookId(), false));
			list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[4].Id, 5, Test.getStandardPriceBookId(), false));
		}

		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[0].Id, 5, objPriceBookOne.id, false));
		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[1].Id, 5, objPriceBookOne.id, false));
		list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[2].Id, 5, objPriceBookOne.id, false));
		if (blnPrioritySupport) {
			list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[3].Id, 5, objPriceBookOne.id, false));
			list_Entries.add(TestUtility.createTestPriceBookEntry(list_Products[4].Id, 5, objPriceBookOne.id, false));
		}

		insert list_Entries;
	}
}