force-app/main/default/objects/Account/fields/Company_Trade_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Trade_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Trade Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <label>FEIN</label>
    <length>175</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Tax_Ops_Failed_Record__c/Tax_Ops_Failed_Record__c.object-meta.xml
<CustomObject>
    <label>Tax Ops Failed Record</label>
    <nameField>
        <displayFormat>F-{0000000}</displayFormat>
        <label>Tax Ops Failure File Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Ops Failed Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tax Ops Failed Records</relationshipLabel>
    <relationshipName>Tax_Ops_Failed_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Amount_Held__c.field-meta.xml
<CustomField>
    <fullName>Amount_Held__c</fullName>
    <label>Amount Held</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>FEIN</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Filing_Successful__c.field-meta.xml
<CustomField>
    <fullName>Filing_Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filing Successful?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <formula>Tax_Ops_Task__r.Tax_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Failed_Record__c/fields/Tax_Ops_Task__c.field-meta.xml
<CustomField>
    <fullName>Tax_Ops_Task__c</fullName>
    <label>Tax Ops Task</label>
    <referenceTo>Tax_Ops_Task__c</referenceTo>
    <relationshipLabel>Tax Ops Failed Records</relationshipLabel>
    <relationshipName>Tax_Ops_Failed_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Tax_Ops_Failed_Record__c/fields/Uploaded_to_Koala__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_Koala__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded to Koala</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Tax_Ops_Task__c/Tax_Ops_Task__c.object-meta.xml
<CustomObject>
    <label>Tax Ops Task</label>
    <nameField>
        <displayFormat>Tx-{0000000}</displayFormat>
        <label>Task Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Ops Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Tax_Ops_Task__c/fields/Payments_Completed__c.field-meta.xml
<CustomField>
    <fullName>Payments_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payments Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Task__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/Tax_Ops_Tasks_Csv_Data__c.object-meta.xml
<CustomObject>
    <description>This Object is created for Field Mapping with CSV Data</description>
    <label>Tax Ops Tasks Csv Data</label>
    <nameField>
        <displayFormat>TaxOps-{00000}</displayFormat>
        <label>TaxOpsTasksCsvData Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Ops Tasks Csv Data</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Account Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Amount_Held__c.field-meta.xml
<CustomField>
    <fullName>Amount_Held__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Amount Held</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <label>FEIN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Filing_Successful__c.field-meta.xml
<CustomField>
    <fullName>Filing_Successful__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Filing Successful</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Optional, short description of the processing result when an error or warning is encountered.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Processed_At__c.field-meta.xml
<CustomField>
    <fullName>Processed_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Processed At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <description>The current processing state for this record. Only values in Queued are processed.</description>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Tax_Ops_Task__c.field-meta.xml
<CustomField>
    <fullName>Tax_Ops_Task__c</fullName>
    <label>Tax Ops Task</label>
    <referenceTo>Tax_Ops_Task__c</referenceTo>
    <relationshipLabel>Tax Ops Tasks Csv Data</relationshipLabel>
    <relationshipName>Tax_Ops_Tasks_Csv_Data</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Data__c/fields/Uploaded_to_Koala__c.field-meta.xml
<CustomField>
    <fullName>Uploaded_to_Koala__c</fullName>
    <label>Uploaded to Koala</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Field_Mapping__c/Tax_Ops_Tasks_Csv_Field_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Tax Ops Tasks Field Mapping with Csv Data</description>
    <label>Tax Ops Tasks Csv Field Mapping</label>
</CustomObject>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Field_Mapping__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Ops_Tasks_Csv_Field_Mapping__c/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Field Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/ZP_Company_Tax_Code_EIN__c.object-meta.xml
<CustomObject>
    <label>ZP Company Tax Code EIN</label>
    <nameField>
        <displayFormat>TCE-{0000000}</displayFormat>
        <label>ZP Company Tax Code EIN Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Company Tax Code EINs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>FEIN</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/fields/Reference_Ein__c.field-meta.xml
<CustomField>
    <fullName>Reference_Ein__c</fullName>
    <label>Reference_Ein</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Tax Code</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Tax_Code_EIN__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP Company ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Processing_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Queued</fullName>
        <default>true</default>
        <label>Queued</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Dead</fullName>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Retry</fullName>
    </customValue>
    <customValue>
        <fullName>Manually Enqueued</fullName>
    </customValue>
    <description>Processing state for integration</description>
    <masterLabel>Integration Processing States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TaxOpsTaskCSVDataTriggerHelperTest.cls
@isTest
public class TaxOpsTaskCSVDataTriggerHelperTest {
    @testSetup
    static void setup(){
        
        Tax_Ops_Task__c taxOpsTask=new Tax_Ops_Task__c();
        	taxOpsTask.Payments_Completed__c=true;
             taxOpsTask.Tax_Code__c='OH000-001';
        insert taxOpsTask;
        
        Id accId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Company').getRecordTypeId();
        Account account=new Account();
        account.Name = 'Test Demo AccountName 1';
        account.BillingStreet = 'Testing Avenue 1';
        account.BillingPostalCode = '123456';
        account.Company_Trade_Name__c = 'Company trade name 1';
        account.Phone = '19992344444';
        account.ShippingStreet = 'Testing Avenue 1';
        account.ShippingPostalCode = '123455';
        account.ZP_Company_ID__c = '5464365436434';
        account.RecordTypeId=accId;
        insert account;
        
        Blob key = EncryptionUtils.generateKey('Master');
        ZP_Company_Tax_Code_EIN__c obj = new ZP_Company_Tax_Code_EIN__c();
        obj.Account_Number__c = '127483';
        obj.FEIN__c = '758373';
        obj.Reference_Ein__c = '1234112';
        obj.Tax_Code__c = 'OH000-001';
        obj.ZP_Company_ID__c = '5464365436434';
        insert obj;
        
        Id failedRecId=Schema.SObjectType.Tax_Ops_Failed_Record__c.getRecordTypeInfosByName().get('Failed Filing').getRecordTypeId();

        list<Tax_Ops_Tasks_Csv_Field_Mapping__c> lst_mappingObj = new list<Tax_Ops_Tasks_Csv_Field_Mapping__c>();

        Tax_Ops_Tasks_Csv_Field_Mapping__c temCSVObj1 = new Tax_Ops_Tasks_Csv_Field_Mapping__c();
        temCSVObj1.API_Name__c = 'FEIN__c';
        temCSVObj1.Field_Label__c = 'FEIN__c';
        temCSVObj1.Name='FEIN__c';
        lst_mappingObj.add(temCSVObj1);

        Tax_Ops_Tasks_Csv_Field_Mapping__c temCSVObj2 = new Tax_Ops_Tasks_Csv_Field_Mapping__c();
        temCSVObj2.API_Name__c = 'Amount_Held__c';
        temCSVObj2.Field_Label__c = 'Amount_Held__c';
        temCSVObj2.Name='Amount_Held__c';
        lst_mappingObj.add(temCSVObj2);

        Tax_Ops_Tasks_Csv_Field_Mapping__c temCSVObj3 = new Tax_Ops_Tasks_Csv_Field_Mapping__c();
        temCSVObj3.API_Name__c = 'Uploaded_to_Koala__c';
        temCSVObj3.Field_Label__c = 'Uploaded_to_Koala__c';
        temCSVObj3.Name='Uploaded_to_Koala__c';
        lst_mappingObj.add(temCSVObj3);

        Tax_Ops_Tasks_Csv_Field_Mapping__c temCSVObj4 = new Tax_Ops_Tasks_Csv_Field_Mapping__c();
        temCSVObj4.API_Name__c = 'Account_Number__c';
        temCSVObj4.Field_Label__c = 'Account_Number__c';
        temCSVObj4.Name='Account_Number__c';
        lst_mappingObj.add(temCSVObj4);

        insert lst_mappingObj;
        
    }
    
    @isTest
    static void testTriggerEvents(){
        Tax_Ops_Task__c taskObj = [SELECT id FROM Tax_Ops_Task__c];
        Test.startTest();

            List<Tax_Ops_Tasks_Csv_Data__c> lst_CSVData=new List<Tax_Ops_Tasks_Csv_Data__c>();
            for(Integer i=0;i<10;i++){
                Tax_Ops_Tasks_Csv_Data__c tempCsvObj = new Tax_Ops_Tasks_Csv_Data__c(
                                                            Account__c='TestAcc'+i, 
                                                            Account_Number__c='127483',
                                                            FEIN__c='758373',
                                                            Processing_Status__c='Queued',
                                                            Message__c='This is Test Message',
                                                            Amount_Held__c='1000',
                                                            Uploaded_to_Koala__c='Test',
                                                            Filing_Successful__c='InProgress',
                                                            Processed_At__c=System.now(),
                                                            Tax_Ops_Task__c=taskObj.Id);
                
                if(i <= 5){
                    tempCsvObj.Record_Type__c = cache.getRecordTypeId('Tax_Ops_Failed_Record__c', 'Failed Filing');
                }
                else{
                    tempCsvObj.Record_Type__c = cache.getRecordTypeId('Tax_Ops_Failed_Record__c', 'Failed Payment');
                }

                lst_CSVData.add(tempCsvObj);
            }
            insert lst_CSVData;

            UPDATE lst_CSVData;

            DELETE lst_CSVData;
            UNDELETE lst_CSVData;

        Test.stopTest();
    }
    
    


    
}