force-app/main/default/objects/Account/fields/Concierge_Group__c.field-meta.xml
<CustomField>
    <fullName>Concierge_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Concierge Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Concierge_Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Concierge_Group_Id__c</fullName>
    <label>Concierge Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Tier_Update_Status__c.field-meta.xml
<CustomField>
    <fullName>Tier_Update_Status__c</fullName>
    <label>Tier Update Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/AccountContactRelation/fields/Concierge_Group__c.field-meta.xml
<CustomField>
    <fullName>Concierge_Group__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Concierge Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountContactRelation/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Concierge_Account__c.field-meta.xml
<CustomField>
    <fullName>Concierge_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Concierge Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ZP User Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines user types - Integration, Admin, UXR Manager, etc. It can be used in flows and trigger logic for customization and automation.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>UX Researcher Mng</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZP_Company__c/ZP_Company__c.object-meta.xml
<CustomObject>
    <label>ZP Company</label>
    <nameField>
        <displayFormat>COMPANY-{000000000}</displayFormat>
        <label>ZP Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Company__c/fields/Company_Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Lead_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>The external record ID from the source system, company.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source Model ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ZP_User__c/ZP_User__c.object-meta.xml
<CustomObject>
    <label>ZP User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Last_Sign_In_At__c.field-meta.xml
<CustomField>
    <fullName>Last_Sign_In_At__c</fullName>
    <label>Last Sign In At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>ZP User Roles</relationshipLabel>
    <relationshipName>ZP_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConciergeAccountBatchTest.cls
@isTest
private class ConciergeAccountBatchTest {
	@testSetup
	static void createRecords() {
		List<Account> accList = new List<Account>();
		List<Contact> conList = new List<Contact>();
		List<AccountContactRelation> relationList = new List<AccountContactRelation>();

		Account Company1 = new Account();
		company1.recordTypeId = Cache.getRecordTypeId('Account', 'Company');
		company1.Name = 'Concierge Company 1';
		company1.Concierge_Group__c = 'Tier 1';
		company1.Concierge_Group_Id__c = 'Tier';
		company1.ZP_Company_Id__c = '11111111111111';
		company1.Tier_Update_Status__c = 'Not Processed';
		accList.add(company1);

		insert accList;

		ZP_Company__c zpCompany = new TestDataFactory.ZPCompanyBuilder()
			.setZPCompanyId('11111111111111')
			.setName('Test Company')
			.setProcessingState('Queued')
			.setPartnerProgramCompanyDataId('PPCD1')
			.setPartnerBilling(ZPCompanyUtil.BILLING_PARTNER_BILLED)
			.build();
		zpCompany.Company_Lead_Id__c = '222222222222';
		zpCompany.Created_At__c = System.today();
		insert zpCompany;

		ZP_User__c user = new ZP_User__c();
		user.Id__c = '777777777777777';
		user.email__c = 'testuserConciergeTest@gusto.com';
		user.Last_Sign_In_At__c = System.now();
		user.Created_At__c = System.now();
		user.Updated_At__c = System.now();
		insert user;

		List<ZP_User_Role__c> userRoleList = new List<ZP_User_Role__c>();

		ZP_User_Role__c userRole = new ZP_User_Role__c();
		userRole.User_Id__c = '777777777777777';
		userRole.Id__c = '2222222222233';
		userRole.Company_Id__c = '11111111111111';
		userRole.Created_At__c = System.now();
		userRole.Updated_At__c = System.now();
		userRole.Type__c = 'Role::PayrollAdmin';
		userRoleList.add(userRole);

		insert userRoleList;

		Contact contact1 = new Contact();
		contact1.RecordTypeId = Cache.getRecordTypeId('Contact', 'Company');
		Contact1.LastName = 'conciergeMainContact';
		contact1.AccountId = company1.Id;
		contact1.ZP_User_Id__c = '777777777777777';
		conList.add(contact1);

		insert conList;
	}

	@isTest
	static void testBatchMethod() {
		Test.startTest();
		ConciergeAccountBatch controller = new ConciergeAccountBatch();
		Database.executeBatch(controller);
		Test.stopTest();

		List<Contact> conList = [SELECT Id, Concierge_Account__c FROM Contact];
		System.assert(conList.size() > 0, 'List should not be empty');
	}
}