force-app/main/default/objects/Account/fields/CX_Experiment__c.field-meta.xml
<CustomField>
    <fullName>CX_Experiment__c</fullName>
    <label>CX Experiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CX_Experiment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Technical_Account_Manager__c.field-meta.xml
<CustomField>
    <fullName>Technical_Account_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A field to indicate the assigned TAM on an account</description>
    <label>Technical Account Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Case/fields/Case_In_Route__c.field-meta.xml
<CustomField>
    <fullName>Case_In_Route__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indication of the case being routed by captains.</description>
    <label>Case In Route</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>IF(   ISPICKVAL(Origin, &apos;Phone&apos;) &amp;&amp; Source__c == &apos;C2CB&apos;,
      &apos;Phone&apos;,
      IF( ISPICKVAL(Origin, &apos;Gusto&apos;) &amp;&amp; NOT(ISBLANK(Integration_Id__c)) &amp;&amp; ISBLANK(IVR_Routing_Log__c),
      &apos;Email&apos;, 
      IF( First_Level__c = &apos;wallet_chatbot&apos; &amp;&amp; ISPICKVAL(Origin, &apos;Gusto&apos;), &apos;Wallet Chatbot&apos;, 
IF( NOT(ISBLANK(First_Level__c)) &amp;&amp; ISPICKVAL(Origin, &apos;Gusto&apos;), &apos;Chat&apos;,
IF( ISPICKVAL(Origin, &apos;Gusto Wallet&apos;) &amp;&amp; ISBLANK(Integration_Id__c), &apos;Chat&apos;,
IF( ISPICKVAL(Origin, &apos;Gusto Wallet&apos;) &amp;&amp; NOT(ISBLANK(Integration_Id__c)), &apos;Email&apos;,
IF( IVR_Type__c=&apos;Voicemail&apos; &amp;&amp; OR(IVR_Queue_Name__c=&apos;Dedicated TAM&apos;, IVR_Queue_Name__c=&apos;Tax Filing Compliance&apos;, IVR_Queue_Name__c=&apos;Tax Operations&apos;), &apos;Voicemail&apos;,null))) 
))
)
)</formula>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/CX_Experiment__c.field-meta.xml
<CustomField>
    <fullName>CX_Experiment__c</fullName>
    <label>CX Experiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CX_Experiment</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Engagement_Alert__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Alert__c</fullName>
    <description>This will be used to identify skillset related to Engagement Alerts</description>
    <label>Engagement Alert</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Engagement_Alert</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Internal_Support_Requested_From__c.field-meta.xml
<CustomField>
    <fullName>Internal_Support_Requested_From__c</fullName>
    <label>Internal Support Requested From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Benefits Advising - EQ</fullName>
            </value>
            <value>
                <fullName>Benefits Advising - MYBC (mid-year benefit change)</fullName>
            </value>
            <value>
                <fullName>Benefits Transfers</fullName>
            </value>
            <value>
                <fullName>BYB</fullName>
            </value>
            <value>
                <fullName>Captain/SME</fullName>
            </value>
            <value>
                <fullName>Carrier I&amp;O</fullName>
            </value>
            <value>
                <fullName>Carrier Operations (COps)</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Engagement - Parked</fullName>
            </value>
            <value>
                <fullName>EPD</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Fulfillment Advising</fullName>
            </value>
            <value>
                <fullName>Member Ops</fullName>
            </value>
            <value>
                <fullName>New Fulfillment</fullName>
            </value>
            <value>
                <fullName>Partnerships</fullName>
            </value>
            <value>
                <fullName>Payments</fullName>
            </value>
            <value>
                <fullName>Payroll Transfers</fullName>
            </value>
            <value>
                <fullName>PPIO</fullName>
            </value>
            <value>
                <fullName>Renewed Fulfillment</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>TaxOps</fullName>
            </value>
            <value>
                <fullName>Tax Resolution</fullName>
            </value>
            <value>
                <fullName>TPO</fullName>
            </value>
            <value>
                <fullName>New Plans</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
            <value>
                <fullName>Member Processing</fullName>
            </value>
            <value>
                <fullName>New Plan Sales</fullName>
            </value>
            <value>
                <fullName>Benefits Care</fullName>
            </value>
            <value>
                <fullName>Full Stack Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Persona__c.field-meta.xml
<CustomField>
    <fullName>Persona__c</fullName>
    <description>Customer Persona used for Omni Channel routing..</description>
    <inlineHelpText>This field shows a customers persona on a case.</inlineHelpText>
    <label>Persona</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Persona</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Benefits_Care.recordType-meta.xml
<RecordType>
    <fullName>Benefits_Care</fullName>
    <active>true</active>
    <businessProcess>Care</businessProcess>
    <description>Benefits Care</description>
    <label>Benefits Care</label>
</RecordType>

force-app/main/default/objects/Case_Reason_Classification__c/Case_Reason_Classification__c.object-meta.xml
<CustomObject>
    <label>Case Reason Classification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Reason Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Contact/fields/CX_Experiment__c.field-meta.xml
<CustomField>
    <fullName>CX_Experiment__c</fullName>
    <formula>TEXT( Account.CX_Experiment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CX Experiment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Engagement_Flow_Configuration__c/Engagement_Flow_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to be used for Engagement team flow metadata.</description>
    <label>Engagement Flow Configuration</label>
</CustomObject>

unpackaged/main/default/objects/User/fields/CX_Experiment__c.field-meta.xml
<CustomField>
    <fullName>CX_Experiment__c</fullName>
    <label>CX Experiment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CX_Experiment</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/CX_Experiment.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Seamless Service Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Seamless Service Control</fullName>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
    </customValue>
    <customValue>
        <fullName>Tier Upsell</fullName>
    </customValue>
    <customValue>
        <fullName>Q3 2020 EOQ Spot Check</fullName>
    </customValue>
    <customValue>
        <fullName>Good Outcomes</fullName>
    </customValue>
    <customValue>
        <fullName>Treatment</fullName>
    </customValue>
    <customValue>
        <fullName>Control</fullName>
    </customValue>
    <customValue>
        <fullName>EOY Guided Experience</fullName>
    </customValue>
    <customValue>
        <fullName>Accountant Care Pilot</fullName>
    </customValue>
    <customValue>
        <fullName>Embedded Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Regular Rate of Pay</fullName>
    </customValue>
    <customValue>
        <fullName>TAM</fullName>
    </customValue>
    <customValue>
        <fullName>Project-GHR</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
        <isActive>false</isActive>
        <label>Kiosk</label>
    </customValue>
    <masterLabel>CX Experiment</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Engagement_Alert.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>General Alert</fullName>
    </customValue>
    <description>This will be used in case of any alerts</description>
    <masterLabel>Engagement Alert</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Persona.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Admin</fullName>
    </customValue>
    <customValue>
        <fullName>Member</fullName>
    </customValue>
    <customValue>
        <fullName>Accountant</fullName>
    </customValue>
    <description>Customer Personas...</description>
    <masterLabel>Persona</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OmniOwnerRoutingTest.cls
/*
* Description: This test class contains test methods to test varios scenarios in the Omni Owner Routing flow.
* Author: Aslam Juneid 
* Date: 16/08/2024
*/

@isTest
public class OmniOwnerRoutingTest {
    
    /**
    * @description Setup method to set data
    * @author		Aslam Juneid
    */
    @testSetup
    static void setUp() {
        AccountTriggerHelper.skipTrigger = true;
        ContactTriggerHelper.skipTrigger = true;
        List<Account> list_Accounts = new List<Account>();
        List<Case_Reason_Classification__c> list_CaseReasons = new List<Case_Reason_Classification__c>();
        List<Case> list_Cases = new List<Case>();
        
        System.runAs(new user(ID = UserInfo.getUserID())){
            userInsert();
        }
        Account objAccount = new TestDataFactory.AccountBuilder()
            .setName('Test Gusto Global Account')
            .setRecordTypeId('Company')
            .setHelpJourneyRouting('Gusto Global')
            .build();
        list_Accounts.add(objAccount);
        
        Account objAccount2 = new TestDataFactory.AccountBuilder()
            .setName('Test Account')
            .setRecordTypeId('Company')
            .build();
        list_Accounts.add(objAccount2);
        insert list_Accounts;
        
        List<Contact> list_Contacts = new List<Contact>();
        Contact objContact = new TestDataFactory.ContactBuilder()
            .setRecordTypeId('Company')
            .setAccountId(objAccount.Id)
            .setFirstName('Test')
            .setLastName('Contact')
            .setEmail('test.contact@gusto.com')
            .build();
        list_Contacts.add(objContact);
        
        Contact objContact2 = new TestDataFactory.ContactBuilder()
            .setRecordTypeId('Company')
            .setAccountId(objAccount2.Id)
            .setFirstName('Test')
            .setLastName('Contact 2')
            .setEmail('testcontact@gusto.com')
            .build();
        list_Contacts.add(objContact2);
        
        insert list_Contacts;
        AccountTriggerHelper.skipTrigger = false;
        ContactTriggerHelper.skipTrigger = false;
        
              
        Map<String, QueueRoutingConfig> map_RoutingConfigByName = new Map<String, QueueRoutingConfig>();
        Map<String, Group> map_QueueByName = new Map<String, Group>();
        
        for (Group objGroup : [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND Name IN ('Engagement - Auto First Response Queue', 'Engagement Cases')]) {
            map_QueueByName.put(objGroup.Name, objGroup);
        }
        
        for (QueueRoutingConfig objRoutingConfig : [SELECT Id, DeveloperName FROM QueueRoutingConfig]) {
            map_RoutingConfigByName.put(objRoutingConfig.DeveloperName, objRoutingConfig);
        }
        
        Engagement_Flow_Configuration__c objFlowConfiguration = new TestDataFactory.FlowConfigurationBuilder()
            .setOwnerId(UserInfo.getOrganizationId())
            .setAcceptedValues('Payroll,Benefits,TAdA,Taxes,Gusto Global,Cancel,Cobra,Workers Comp,Retirement')
            .setFirstResponseQueueId(map_QueueByName.get('Engagement - Auto First Response Queue').Id)
            .setEngagementQueueId(map_QueueByName.get('Engagement Cases').Id)
            .setOmniRecordTypes('Engagement,Payroll_Care,Benefits_Care')
            .setIneligibleOrigins('Phone,Chat')
            .setEngagementRecordTypeId(CaseUtils.RECTYPE_ENGAGEMENT)
            .setEngagementRoutingConfigId(map_RoutingConfigByName.get('Engagement_Case').Id)
            .setOfflineRoutingConfigId(map_RoutingConfigByName.get('Engagement_Case_Offline_Re_Route').Id)
            .setPriorAgentRoutingConfigId(map_RoutingConfigByName.get('Engagement_Case_Route_Prior_Agent').Id)
            .setGustoGlobalId(map_RoutingConfigByName.get('Engagement_Gusto_Global').Id)
            .setEngagementAlertId(map_RoutingConfigByName.get('Engagement_Alert_Cases').Id)
            .setOfflineId(map_RoutingConfigByName.get('Engagement_Case_Offline').Id)
            .setManualOwnerChangeId(map_RoutingConfigByName.get('Engagement_Manual_Owner_Change').Id)
            .build();
        
        insert objFlowConfiguration;
        
        Case objCase1 = new TestDataFactory.CaseBuilder()
            .setAccountId(objContact2.AccountId)
            .setContactId(objContact2.Id)
            .setRecordTypeId(CaseUtils.TYPE_ENGAGEMENT)
            .setOrigin(CaseUtils.ORIGIN_EMAIL)
            .setSubject('Test agatha prediction 1')
            .setStatus(CaseUtils.STATUS_OPEN)
            .setSuppliedEmail('testagatha@gusto.com')
            .setDescription('Test agatha prediction 1')
            .setSolveProcessedFlag('No')
            .setInternalAIProcessedFlag('No')
            .build();
        list_Cases.add(objCase1);
        
        Case objCase2 = new TestDataFactory.CaseBuilder()
            .setAccountId(objContact2.AccountId)
            .setContactId(objContact2.Id)
            .setRecordTypeId(CaseUtils.TYPE_ENGAGEMENT)
            .setOrigin(CaseUtils.ORIGIN_EMAIL)
            .setSubject('Test agatha prediction 2')
            .setStatus(CaseUtils.STATUS_OPEN)
            .setSuppliedEmail('testagatha2@gusto.com')
            .setDescription('Test agatha prediction 2')
            .setSolveProcessedFlag('No')
            .setInternalAIProcessedFlag('No')
            .build();
        list_Cases.add(objCase2);
        
        insert list_Cases;
    }
    
     /**
    * @description Testing TAM User scnerio for Omni Routing
    * @author		Aslam Juneid
    */
    @isTest
    private static void testTAMUser(){
        User tamUser = [SELECT Id FROM User LIMIT 1];
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,AccountId,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        
        Case objCase = list_Case[0];

        //Assert Check for Initial Values
        Assert.isTrue(objCase.Recordtype.Developername == 'Engagement');
        Assert.isTrue(objCase.Origin == 'Email');
        Assert.isTrue(objCase.Persona__c == 'Admin');
        Assert.isTrue(objCase.AccountId != null);
        Assert.isTrue(objCase.Account.Technical_Account_Manager__c == null);
        Assert.isTrue(objCase.status == 'Open');
        
        //Update TAM on Account
        Account objAccount = new Account();
        objAccount.Id = objCase.AccountId;
        objAccount.Technical_Account_Manager__c = tamUser.Id;
        update objAccount;
        Assert.isTrue(Account.Technical_Account_Manager__c != null);

        //Case Update
        objCase.status = 'Awaiting Response';
        update objCase;
        
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check PendingServiceRouting not created to make sure OmniOwnerRouting flow didnt invoked
        Assert.isTrue(list_PSR.isEmpty());
    }
    
    /**
    * @description To test  Case Update  with P0 is when the agent goes offline
    * @author		Aslam Juneid
    */
    @isTest
    private static void caseAgentOfflineTest(){
        
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Assert Check for Initial Values
        Assert.isTrue(objCase.Recordtype.Developername == 'Engagement');
        Assert.isTrue(objCase.Origin == 'Email');
        Assert.isTrue(objCase.Persona__c == 'Admin');
        
        
        //Case Update since we can't simulate the agent offline behavior directly, we are updating the status of the case to Open. 
        objCase.status = 'In Progress';
        update  objCase;
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'In Progress');
        
        objCase.status = 'Open';
        Test.startTest();
        update  objCase;
        Test.stopTest();
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'Open');
        Assert.isTrue(!list_PSR.isEmpty());
        Assert.isTrue(list_PSR[0].RoutingPriority == 0);
        List<SkillRequirement> list_Skills = [SELECT Id, RelatedRecordId, SkillId FROM SkillRequirement WHERE RelatedRecordId = :list_PSR[0].Id];
        Assert.isTrue(list_Skills.isEmpty());
    }
    /**
    * @description To test  Case Update  for Record Type Change Scnerio
    * @author		Aslam Juneid
    */
    @isTest
    private static void recordTypeChangeTest(){
        
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,recordtype.Name,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Assert Check for Initial Values
        Assert.isTrue(objCase.Recordtype.Developername == 'Engagement');
        Assert.isTrue(objCase.Origin == 'Email');
        Assert.isTrue(objCase.Persona__c == 'Admin');
        
       
        //Case Update since we can't simulate the agent offline behavior directly, we are updating the status of the case to Open. 
         objCase.recordtypeId = CaseUtils.RECTYPE_BYB;
        objCase.status = 'In Progress';
        update  objCase;
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'In Progress');
        
        objCase.status = 'Open';
        Test.startTest();
        update  objCase;
        Test.stopTest();
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'Open');
        Assert.isTrue(list_PSR.isEmpty());
    }
    
    /**
    * @description To test  Case Update for assign the "Engagement Alert Cases" routing 
    * @author		Aslam Juneid
    */
    @isTest
    private static void engagementAlertTest(){
        
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Internal_Support_Requested_From__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Assert Check for Initial Values
        Assert.isTrue(objCase.Recordtype.Developername == 'Engagement');
        Assert.isTrue(objCase.Origin == 'Email');
        Assert.isTrue(objCase.Persona__c == 'Admin');
        
        //Case Update
        objCase.Engagement_Alert__c ='General Alert';
        objCase.Internal_Support_Requested_From__c = 'Risk';
        objCase.status = 'Awaiting Internal Support';
        update  objCase;
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.Internal_Support_Requested_From__c == 'Risk');
        Assert.isTrue(objCase.Engagement_Alert__c == 'General Alert');
        Assert.isTrue(objCase.status == 'Awaiting Internal Support');
        
        //Case Update
        objCase.status = 'In Progress';
        update  objCase;
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status ==  'In Progress');
        Assert.isTrue(!list_PSR.isEmpty());
        Assert.isTrue(list_PSR[0].RoutingPriority == 0);
        List<SkillRequirement> list_Skills = [SELECT Id, RelatedRecordId, SkillId FROM SkillRequirement WHERE RelatedRecordId = :list_PSR[0].Id];
        Assert.isTrue(list_Skills.isEmpty());
    }
    
    /**
    * @description To test Case Update for Assign the "Engagement Case Offline" routing 
    * @author		Aslam Juneid
    */
    @isTest
    private static void manualOwnerChangeTest(){
        
        User objUser = [SELECT id,Name FROM User WHERE UserName = 'testinactiveuser@gusto.com'];
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Internal_Support_Requested_From__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Case Update
        objCase.status = 'Awaiting Response';
        update  objCase;
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'Awaiting Response');
        
        //Case Update
        Id idOldOwner = objCase.OwnerId;
        objCase.OwnerId = objUser.Id;
        objCase.status = 'In Progress';
        update  objCase;
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'In Progress');
        Assert.isTrue( objCase.OwnerId != idOldOwner);
        Assert.isTrue((String.valueOf(objCase.OwnerId).startswith('005')) );
        Assert.isTrue(!list_PSR.isEmpty());
        Assert.isTrue(list_PSR[0].RoutingPriority == 0);
        List<SkillRequirement> list_Skills = [SELECT Id, RelatedRecordId, SkillId FROM SkillRequirement WHERE RelatedRecordId = :list_PSR[0].Id];
        Assert.isTrue(list_Skills.isEmpty());
    }
    
    /**
    * @description To test Case Update route to Queue
    * @author		Aslam Juneid
    */
    @isTest
    private static void routeCaseToQueueTest(){
        
        Group objGroup = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND Name IN ('Engagement - Auto First Response Queue', 'Engagement Cases') limit 1];
        
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Internal_Support_Requested_From__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Case Update
        objCase.Status = 'Awaiting Response';
        objCase.Type = 'Payroll';
        update  objCase;
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'Awaiting Response');
        
        //Case Update
        Id idOldOwner = objCase.OwnerId;
        objCase.OwnerId = objGroup.Id;
        
        objCase.status = 'In Progress';
        update  objCase;
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'In Progress');
        Assert.isTrue(idOldOwner != objCase.OwnerId);
        Assert.isTrue(!(String.valueOf(objCase.OwnerId).startswith('005')) );
        Assert.isTrue(!list_PSR.isEmpty());
        Assert.isTrue(list_PSR[0].RoutingPriority == 1);
        List<SkillRequirement> list_Skills = [SELECT Id, RelatedRecordId, SkillId FROM SkillRequirement WHERE RelatedRecordId = :list_PSR[0].Id];
        Assert.isTrue(!list_Skills.isEmpty());

    }
    
    /**
    * @description To test Case Update route to Queue
    * @author		Aslam Juneid
    */
    @isTest
    private static void routCaseToUserTest(){
        
        List<Case> list_Case = [SELECT id,Engagement_Alert__c,Internal_Support_Requested_From__c,Channel__c,Case_In_Route__c,OwnerId,Status,Origin,recordtype.DeveloperName,Persona__c,Account.Technical_Account_Manager__c,Account.CX_Experiment__c FROM Case];
        Case objCase = list_Case[0];
        
        //Case Update
        objCase.status = 'Awaiting Response';
        update  objCase;
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'Awaiting Response');
        
        //Case Update
        objCase.status = 'In Progress';
        update  objCase;
        
        List<PendingServiceRouting> list_PSR = [SELECT Id, WorkItemId, RoutingPriority FROM PendingServiceRouting WHERE WorkItemId = :objCase.Id];
        
        //Assert Check for Updated Values
        Assert.isTrue(objCase.status == 'In Progress');
        Assert.isTrue((String.valueOf(objCase.OwnerId).startswith('005')) );
        Assert.isTrue(!list_PSR.isEmpty());
        Assert.isTrue(list_PSR[0].RoutingPriority == 1);
        List<SkillRequirement> list_Skills = [SELECT Id, RelatedRecordId, SkillId FROM SkillRequirement WHERE RelatedRecordId = :list_PSR[0].Id];
        Assert.isTrue(list_Skills.isEmpty());
        
    }
    
    /**
    * @description 	Method to insert the users
    * @author		Aslam Juneid
    */
    
    public static void userInsert(){
        
        Profile objProfile = [SELECT Id FROM Profile WHERE Name = 'ZP System Administrator'];
        List<User> list_Users = new List<User>();
        User objUser = new TestDataFactory.UserBuilder()
            .setUserName('testinactiveuser@gusto.com')
            .setFirstName('')
            .setLastName('Test Inactive User')
            .setEmail('testinactiveuser@gusto.com')
            .setProfileId(objProfile.Id)
            .setTimeZoneSidKey('America/Denver')
            .setLocaleSidKey('en_US')
            .setLanguageLocaleKey('en_US')
            .setEmailEncoding('ISO-8859-1')
            .setAlias('test')
            .setIsActive(true)
            .build();
        list_Users.add(objUser);
        
        insert list_Users;
    }
    
}