force-app/main/default/objects/Account/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>External unique key identifier.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Order/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ID of company migration record in Zen Payroll</description>
    <externalId>true</externalId>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order/fields/Zp_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Zp_Company_ID__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <label>Zp Company ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_Nacha_Entry_Returns__c/ZP_Nacha_Entry_Returns__c.object-meta.xml
<CustomObject>
    <description>GFS passes Failed Expedite Nacha Entries here, to enrich recovery case data</description>
    <label>ZP Nacha Entry Return</label>
    <nameField>
        <displayFormat>Nacha-Entry-Return-{0000000000}</displayFormat>
        <label>ZP Nacha Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Nacha Entry Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>External concatenation, lowercase, no spaces, hyphen delimited  

database - model name - record id

e.g. zp-user_role-23123111</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZPNachaEntryReturnsQueueTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ZPNachaEntryReturnsQueueTest {
	@testsetup
	static void dataMethod() {
		ZP_User_Role__c roleRec = new ZP_User_Role__c();
		roleRec.User_Id__c = '0000999900001';
		roleRec.Company_Id__c = '00009999000011';
		roleRec.Type__c = 'Role:Signatory';
		insert roleRec;

		Account acc = TestUtility.CompanyAccount();
		acc.ZP_Company_ID__c = '0000999900001';
		update acc;

		Contact objContact = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Contact', 'Company'))
			.setPhone('999999124')
			.setFirstName('Test Contact')
			.setLastName('ZPNachaEntryQueue')
			.setAccountId(acc.id)
			.setEmail('ZPNachaEntry1@gusto.com')
			.setZPUserId('0000999900001')
			.build();

		insert objContact;
	}

	@isTest
	static void createNachaCaseRecTest() {
		Test.startTest();
		ZP_Nacha_Entry_Returns__c ZPRec = new ZP_Nacha_Entry_Returns__c();
		ZPRec.Event_Id__c = '3334445556';
		ZPRec.Event_Type__c = 'Payroll';
		ZPRec.Id__c = '9991110001';
		ZPRec.External_Key__c = 'zenpayroll-nacha_entry_return-9991110001';
		ZPRec.Error_Code__c = 'R011';
		ZPRec.Company_Id__c = '0000999900001';
		ZPRec.Amount__c = 110;
		insert ZPRec;
		ZPRec = [SELECT Id, External_Key__c FROM ZP_Nacha_Entry_Returns__c];
		System.assertEquals(
			ZPRec.External_Key__c,
			'zenpayroll-nacha_entry_return-9991110001',
			'The External_Key__c of ZP_Nacha_Entry_Returns__c records should be zenpayroll-nacha_entry_return-9991110001.'
		);
		test.stopTest();
	}
}