force-app/main/default/objects/Account/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>External unique key identifier.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Event_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>ContractorPayment</fullName>
                <label>Contractor Payment</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>AgentPayment</fullName>
                <label>Agent Payment</label>
            </value>
            <value>
                <fullName>HistoricalCompany</fullName>
                <label>Historical Company</label>
            </value>
            <value>
                <fullName>PenaltyCase</fullName>
                <label>Penalty Case</label>
            </value>
            <value>
                <fullName>Payroll Care Email</fullName>
            </value>
            <value>
                <fullName>InternationalContractorPayments::Db::InternationalContractorPayment</fullName>
            </value>
            <value>
                <fullName>InternationalEmployeePayroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Key__c.field-meta.xml
<CustomField>
    <fullName>Integration_Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Integration Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ZP_Nacha_Entry_Returns__c/ZP_Nacha_Entry_Returns__c.object-meta.xml
<CustomObject>
    <description>GFS passes Failed Expedite Nacha Entries here, to enrich recovery case data</description>
    <label>ZP Nacha Entry Return</label>
    <nameField>
        <displayFormat>Nacha-Entry-Return-{0000000000}</displayFormat>
        <label>ZP Nacha Entries Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Nacha Entry Returns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Event Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_Nacha_Entry_Returns__c/fields/Processing_Status__c.field-meta.xml
<CustomField>
    <fullName>Processing_Status__c</fullName>
    <label>Processing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/External_Key__c.field-meta.xml
<CustomField>
    <fullName>External_Key__c</fullName>
    <description>External concatenation, lowercase, no spaces, hyphen delimited  

database - model name - record id

e.g. zp-user_role-23123111</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>External Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Processing_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Queued</fullName>
        <default>true</default>
        <label>Queued</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Dead</fullName>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Retry</fullName>
    </customValue>
    <customValue>
        <fullName>Manually Enqueued</fullName>
    </customValue>
    <description>Processing state for integration</description>
    <masterLabel>Integration Processing States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NachaEntryReturnBatchSchedulerTest.cls
@isTest
private class NachaEntryReturnBatchSchedulerTest {

    @testsetup
    static void dataMethod(){
        
        ZP_User_Role__c roleRec = new ZP_User_Role__c();
        roleRec.User_Id__c = '00009999000011';
        roleRec.Company_Id__c = '000099990000111';
        roleRec.Type__c = 'Role:Signatory';
        insert roleRec;
        
        Account acc = TestUtility.CompanyAccount();
        acc.ZP_Company_ID__c = '000099990000111';
        update acc;
        
        Contact objContact = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
			.setAccountId(acc.Id)
			.setFirstName('Test Contact')
			.setLastName('BatchSchedulerZPNachaEntry')
			.setEmail('BatchZPNachaEntry@gusto.com')
			.setPhone('9999971234')
			.setZPUserId('00009999000011')
			.build();
        
        insert objContact;
        
        Case cse = new Case();
        cse.RecordTypeId = cache.getRecordTypeId('Case', 'Recovery Cases');
        cse.AccountId = acc.Id;
        cse.Subject='Test';
        cse.Description='Test';
        cse.Type='Recovery';
        cse.Origin='Panda';
        cse.Event_Type__c = 'Payroll';
        cse.Integration_Key__c = 'zenpayroll-payroll-01010101010101';        
        insert cse;
    }
    
    @isTest
    static void batchRunTest() {
        
        list<ZP_Nacha_Entry_Returns__c> zpList = new list<ZP_Nacha_Entry_Returns__c>();
        
        ZP_Nacha_Entry_Returns__c ZPRec = new ZP_Nacha_Entry_Returns__c();
        ZPRec.Event_Id__c = '333444555';
        ZPRec.Event_Type__c = 'Payroll';
        ZPRec.Id__c = '9991110003';
        ZPRec.External_Key__c = 'zenpayroll-nacha_entry_return-9991110003';
        ZPRec.Error_Code__c = 'R01';
        ZPRec.Company_Id__c = '000099990000111';
        ZPRec.Amount__c = 110;
        ZPRec.Processing_Status__c = 'Error';
        zpList.add(ZPRec);
        
        ZP_Nacha_Entry_Returns__c ZPRec2 = new ZP_Nacha_Entry_Returns__c();
        ZPRec2.Event_Id__c = '01010101010101';
        ZPRec2.Event_Type__c = 'Payroll';
        ZPRec2.Id__c = '9991110004';
        ZPRec2.External_Key__c = 'zenpayroll-nacha_entry_return-9991110004';
        ZPRec2.Error_Code__c = 'R01';
        ZPRec2.Company_Id__c = '000099990000111';
        ZPRec2.Amount__c = 110;
        ZPRec2.Processing_Status__c = 'Error';
        zpList.add(ZPRec2);
        
        ZPNachaEntryReturnsTriggerHelper.skipTrigger = true;        
        insert zpList;
        ZPNachaEntryReturnsTriggerHelper.skipTrigger = false;
        
        test.startTest(); 
            String CRON_EXP = '0 0 * * * ?';
            NachaEntryReturnBatchScheduler sch = new NachaEntryReturnBatchScheduler();
            system.schedule('Hourly Example Batch Schedule job', CRON_EXP, sch); 
        test.stopTest();
       
        
    }
}