force-app/main/default/objects/Account/fields/Joined_Date_Panda__c.field-meta.xml
<CustomField>
    <fullName>Joined_Date_Panda__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Joined Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Agency_Information__c/Agency_Information__c.object-meta.xml
<CustomObject>
    <label>Agency Information</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Agency_Information__c.field-meta.xml
<CustomField>
    <fullName>Agency_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure the agency you have selected is active.</errorMessage>
        <filterItems>
            <field>Agency_Information__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Agency_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Auto_Indexing_Status__c.field-meta.xml
<CustomField>
    <fullName>Auto_Indexing_Status__c</fullName>
    <description>This is used for showing the Indexing status after OCR is complete.</description>
    <label>Auto Indexing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partially Indexed</fullName>
            </value>
            <value>
                <fullName>Fully Indexed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Failed: Untrained Document</fullName>
            </value>
            <value>
                <fullName>Failed: No Valid Document</fullName>
            </value>
            <value>
                <fullName>Failed: System Issue</fullName>
            </value>
            <value>
                <fullName>Failed: No Attachment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OCR_Message__c.field-meta.xml
<CustomField>
    <fullName>OCR_Message__c</fullName>
    <description>This will be used by OCR (via Instabase)</description>
    <label>IDP Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OCR_Status__c.field-meta.xml
<CustomField>
    <fullName>OCR_Status__c</fullName>
    <description>This will be used by OCR (Instabase)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>OCR Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/Tax_Notice_Index__c/Tax_Notice_Index__c.object-meta.xml
<CustomObject>
    <label>Tax Notice Index</label>
    <nameField>
        <displayFormat>TNI-{000000000}</displayFormat>
        <label>Tax Notice Index Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Notice Indexs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Notice_Index__c/fields/Agency_Information__c.field-meta.xml
<CustomField>
    <fullName>Agency_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NAME OF AGENCY THAT ISSUED TAX NOTICE</description>
    <label>Agency Information</label>
    <referenceTo>Agency_Information__c</referenceTo>
    <relationshipLabel>Tax Notice Indexs</relationshipLabel>
    <relationshipName>Tax_Notice_Indexs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tax_Notice_Index__c/fields/Manual_Review_Required__c.field-meta.xml
<CustomField>
    <fullName>Manual_Review_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be set by OCR automation tool if manual review is needed.</description>
    <label>Manual Review Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Notice_Index__c/fields/MRR_Reason__c.field-meta.xml
<CustomField>
    <fullName>MRR_Reason__c</fullName>
    <description>This is used to store the Manual Review Required Reason from integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>MRR Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Notice_Index__c/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <description>It is used to store the Company Id for the Account.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP Company Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Notice_Index__c/recordTypes/OCR.recordType-meta.xml
<RecordType>
    <fullName>OCR</fullName>
    <active>true</active>
    <description>This will be used by IDP Indexing</description>
    <label>IDP Indexing</label>
</RecordType>

unpackaged/main/default/objects/Tax_Res_TNDC_Confidence_Score_Setting__mdt/Tax_Res_TNDC_Confidence_Score_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This is used to store the Confidence Score Thresholds for TNDC fields received from Integration.</description>
    <label>Tax Res TNDC Confidence Score Setting</label>
    <pluralLabel>Tax Res TNDC Confidence Score Settings</pluralLabel>
</CustomObject>

force-app/main/default/classes/TaxResIDPNoticeControllerTest.cls
/**
 * @name         TaxResIDPNoticeControllerTest
 * @author       Shyam Nasare
 * @date         10/09/2024
 * @description  Test class for 'TaxResIDPNoticeController'
 **/

@IsTest
public with sharing class TaxResIDPNoticeControllerTest {
	@testSetup
	static void setUp() {
		AccountTriggerHelper.skipTrigger = true;
		CaseTriggerHelper.skipTrigger = true;
		ContactTriggerHelper.skipTrigger = true;

		List<Tax_Notice_Index__c> list_TNDC = new List<Tax_Notice_Index__c>();

		// Creating new company account
		Account objAccount = new TestDataFactory.AccountBuilder().setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setName('Test Company Account').build();
		objAccount.Joined_Date_Panda__c = System.today();
		objAccount.ZP_Company_ID__c = 'ZPCOMPANY123';
		insert objAccount;

		//Creating Company Contact
		Contact objContact = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
			.setAccountId(objAccount.Id)
			.setFirstName('Test First\' Name1')
			.setLastName('Test Last\' Name1')
			.setEmail('newmember1@campaign.com')
			.setNormalizedPhone('1876543211')
			.build();
		insert objContact;

		//Create tax Res
		Agency_Information__c objAgency = TestDataFactory.CreateOneAgencyInforation('Internal Revenue Service');

		Case objCase = new TestDataFactory.CaseBuilder()
			.setAccountId(objAccount.Id)
			.setContactId(objContact.Id)
			.setRecordTypeId('Tax Res')
			.setType('Tax Res')
			.setSubject('Test Subject')
			.setOrigin('Email')
			.setDirection('Inbound')
			.setStatus(CaseUtils.CASE_STATUS_READY_FOR_OCR_CAPTURE)
			.setSuppliedEmail('test@gusto.com')
			.setDescription('Amended W-2 for 2019 needed')
			.setAgencyInformation(objAgency.Id)
			.build();
		insert objCase;

		Tax_Notice_Index__c objTaxNotice = new TestDataFactory.TaxNoticeIndexBuilder()
			.setCaseId(objCase.Id)
			.setRecordTypeId(Cache.getRecordTypeId('Tax_Notice_Index__c', 'IDP Indexing'))
			.setAgencyInformation(objAgency.Id)
			.build();
		objTaxNotice.Manual_Review_Required__c = true;
		objTaxNotice.MRR_Reason__c = 'Failed: Untrained Document';
		list_TNDC.add(objTaxNotice);

		insert list_TNDC;
	}

	/**
	 * @Author      : Shyam Nasare
	 * @Description : Test method to check After OCR Capture Complete status updates
	 **/
	@IsTest
	static void testAfterOCRCaptureCompleteUpdates() {
		Test.startTest();
		Case objCase = [SELECT Id, Status, OCR_Message__c, OCR_Status__c FROM Case LIMIT 1];
		objCase.Status = CaseUtils.CASE_STATUS_OCR_CAPTURE_COMPLETE;
		update objCase;
		Test.stopTest();

		objCase = [SELECT Id, Status, OCR_Message__c, OCR_Status__c, Auto_Indexing_Status__c FROM Case LIMIT 1];

		System.assertEquals(TaxResIDPNoticeController.AUTO_INDEX_STATUS_PARTIALLY_INDEXED, objCase.Auto_Indexing_Status__c, 'Auto Indexing Status is not Partially Indexed');
	}

	/**
	 * @Author      : Shyam Nasare
	 * @Description : Test method to check Custom MetaData for TNDC Confidence Score setting
	 **/
	@IsTest
	static void testCustomMetadata() {
		Test.startTest();
		Case objCase = [SELECT Id, Status, OCR_Message__c, OCR_Status__c FROM Case LIMIT 1];
		List<Tax_Res_TNDC_Confidence_Score_Setting__mdt> list_customMetadata = TaxResIDPNoticeController.getTNDCConfidenceScoreSetting(objCase.Id);
		Test.stopTest();
		System.assert(list_customMetadata != null, 'Custom Metadata not found');
	}
}