force-app/main/default/objects/Account/fields/No_of_EEs_in_HI_State__c.field-meta.xml
<CustomField>
    <fullName>No_of_EEs_in_HI_State__c</fullName>
    <description>Total number of active employees that are in an HI-eligible state</description>
    <inlineHelpText>Total number of active employees that are in an HI-eligible state</inlineHelpText>
    <label>No. of EEs in HI State</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/No_Of_Employees_Filling_State__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Employees_Filling_State__c</fullName>
    <description>Total number of active employees in the company&apos;s filing state</description>
    <inlineHelpText>Total number of active employees in the company&apos;s filing state</inlineHelpText>
    <label># Of Employees - Filing State</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Resident_States__c.field-meta.xml
<CustomField>
    <fullName>Resident_States__c</fullName>
    <label>Resident State(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State_Abbreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Employee Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Residence_State__c.field-meta.xml
<CustomField>
    <fullName>Residence_State__c</fullName>
    <label>Residence State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/HI_Opportunity_Router_State__c/HI_Opportunity_Router_State__c.object-meta.xml
<CustomObject>
    <label>HI Opportunity Router State</label>
    <nameField>
        <displayFormat>HIRS-{000000}</displayFormat>
        <label>HI Opportunity Router Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI Opportunity Router States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Opportunity_Router_State__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Name_to_abbreviations_Mapping__c/State_Name_to_abbreviations_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to map all state names to abbreviations</description>
    <label>State Name to abbreviations Mapping</label>
</CustomObject>

force-app/main/default/objects/State_Name_to_abbreviations_Mapping__c/fields/HI_Active__c.field-meta.xml
<CustomField>
    <fullName>HI_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HI_Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/State_Name_to_abbreviations_Mapping__c/fields/State_Abbreviation__c.field-meta.xml
<CustomField>
    <fullName>State_Abbreviation__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State Abbreviation</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Name_to_abbreviations_Mapping__c/fields/State_Name__c.field-meta.xml
<CustomField>
    <fullName>State_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_Employee__c/ZP_Employee__c.object-meta.xml
<CustomObject>
    <label>ZP Employee</label>
    <nameField>
        <displayFormat>ZPE-{000000000}</displayFormat>
        <label>ZP Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Employee__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Employee__c/fields/Residence_State__c.field-meta.xml
<CustomField>
    <fullName>Residence_State__c</fullName>
    <label>Residence State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/State_Abbreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>State Abbreviations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ZPEmployeeTriggerHelperTest.cls
/**
 * @name		:ZPEmployeeTriggerHelperTest
 * @author
 * @date
 * @description :Unit tests for ZPEmployeeTriggerHelper, ZPEmployeeTriggerHandler, ZPEmployeeTrigger
 * @class		:ZPEmployeeTriggerHelper, ZPEmployeeTriggerHandler, ZPEmployeeTrigger
 * @revisions   :August 23, 2021 ------------ Neha ------------ Added test scenarios for processing Residence State
 **/
@isTest
public class ZPEmployeeTriggerHelperTest {
	/**
	 * @Author      : Neha Dabas
	 * @Description : Create Test Data
	 * @Parm        : null
	 * @Return      : null
	 **/
	@TestSetup
	static void makeData() {
		List<State_Name_to_abbreviations_Mapping__c> list_StateName = new List<State_Name_to_abbreviations_Mapping__c>();

		list_StateName.add(new State_Name_to_abbreviations_Mapping__c(Name = 'Missouri', State_Abbreviation__c = 'MO', State_Name__c = 'MO', HI_Active__c = true));

		insert list_StateName;

		List<HI_Opportunity_Router_State__c> list_HiStates = new List<HI_Opportunity_Router_State__c>();

		list_HiStates.add(new TestDataFactory.HIOpportunityRouterStateBuilder().setStateName('Missouri').setState('MO').setPriority('1').build());

		insert list_HiStates;

		List<Account> list_Accounts = new List<Account>();
		list_Accounts.add(
			new TestDataFactory.AccountBuilder()
				.setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID)
				.setName('Test Accountant - 1')
				.setOnboardingFlow('In-App')
				.setZPCompanyId('11119999')
				.setBillingState('Missouri')
				.setBillingCountry('United States')
				.build()
		);
		insert list_Accounts;

		List<Contact> list_Contacts = new List<Contact>();
		list_Contacts.add(
			new TestDataFactory.ContactBuilder()
				.setRecordTypeId('Company')
				.setAccountId(list_Accounts[0].Id)
				.setFirstName('Funnybones')
				.setLastName('Testing C')
				.setEmail('funnybone1@secondcontact.com')
				.setEmployeeId('5453255')
				.build()
		);
		insert list_Contacts;
	}

	/**
	 * @Author      :
	 * @Description : Test Employee Insertion
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testAfterInsertRecords() {
		Test.startTest();
		ZPEmployeeTriggerHandler.resetSkipTriggerFlags();

		ZP_Employee__c objEmployee = new TestDataFactory.ZPEmployeeBuilder().setCompanyId('11119999').setProcessingState('Queued').build();

		insert objEmployee;

		objEmployee.Processing_State__c = 'Processed';
		update objEmployee;

		Test.stopTest();

		Account objAccountRec = [SELECT Id, ZP_Company_id__c, No_Of_Employees_Filling_State__c, No_of_EEs_in_HI_State__c, BillingState FROM Account];

		System.assertEquals(0, objAccountRec.No_Of_Employees_Filling_State__c, 'Number of EE Filling State should be 0');
		System.assertEquals(0, objAccountRec.No_of_EEs_in_HI_State__c, 'Number of EE in HI State should be 0');
	}

	/**
	 * @Author      :
	 * @Description : Test Skip trigger functionality
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testSkipTrigger() {
		ZPEmployeeTriggerHelper.skipTrigger = true;

		ZP_Employee__c objEmployee = new ZP_Employee__c();
		objEmployee.Processing_State__c = 'Queued';
		objEmployee.Company_Id__c = '11119999';
		insert objEmployee;
	}

	/**
	 * @Author      : Neha Dabas
	 * @Description : Test Residence State Update on Employee Insert
	 * @Parm        : null
	 * @Return      : null
	 **/
	static testMethod void testResidenceStateUpdateAtInsert() {
		Test.startTest();
		ZPEmployeeTriggerHandler.resetSkipTriggerFlags();

		ZP_Employee__c objEmployee = new TestDataFactory.ZPEmployeeBuilder().setEmployeeId('5453255').setCompanyId('11119999').setProcessingState('Queued').setResidenceState('CA').build();
		insert objEmployee;

		Test.stopTest();

		Contact objContact = [SELECT Residence_State__c, Account.Resident_States__c FROM Contact WHERE Employee_Id__c = '5453255' LIMIT 1];

		System.assert(objContact.Account.Resident_States__c != null && objContact.Account.Resident_States__c.contains('CA'), 'Resident State is incorrect on account.');
		System.assertEquals(objContact.Residence_State__c, 'CA', 'Residence State should be set to CA.');
	}

	/**
	 * @Author      : Neha Dabas
	 * @Description : Test Residence State Update on Employee Update
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testResidenceStateUpdateAtUpdate() {
		Test.startTest();
		ZPEmployeeTriggerHandler.resetSkipTriggerFlags();

		ZP_Employee__c objEmployee = new TestDataFactory.ZPEmployeeBuilder().setEmployeeId('5453255').setCompanyId('11119999').setProcessingState('Queued').build();
		insert objEmployee;

		objEmployee.Residence_State__c = 'CA';
		update objEmployee;

		Test.stopTest();

		Contact objContact = [SELECT Residence_State__c, Account.Resident_States__c FROM Contact WHERE Employee_Id__c = '5453255' LIMIT 1];

		System.assert(objContact.Account.Resident_States__c != null && objContact.Account.Resident_States__c.contains('CA'));
		System.assertEquals(objContact.Residence_State__c, 'CA', 'Residence State should be set to CA.');
	}

	/**
	 * @Author      : Neha Dabas
	 * @Description : Test Residence State Update on Employee Delete
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testResidenceStateUpdateOnDelete() {
		Test.startTest();
		ZPEmployeeTriggerHandler.resetSkipTriggerFlags();

		ZP_Employee__c objEmployee = new TestDataFactory.ZPEmployeeBuilder().setEmployeeId('5453255').setCompanyId('11119999').setProcessingState('Queued').setResidenceState('CA').build();
		insert objEmployee;

		objEmployee.Deleted_At__c = System.now();
		update objEmployee;

		Test.stopTest();

		Contact objContact = [SELECT Residence_State__c, Account.Resident_States__c FROM Contact WHERE Employee_Id__c = '5453255' LIMIT 1];

		System.assert(String.isBlank(objContact.Account.Resident_States__c), 'Account Resident State should be blank');
		System.assert(String.isBlank(objContact.Residence_State__c), 'Contact Resident State should be blank');
	}

	/**
	 * @Author      : Neha Dabas
	 * @Description : Test Residence State Update Without company id and employee id
	 * @Parm        : null
	 * @Return      : null
	 **/
	@isTest
	static void testResidenceStateUpdateNegative() {
		Test.startTest();
		ZPEmployeeTriggerHandler.resetSkipTriggerFlags();

		ZP_Employee__c objEmployee = new TestDataFactory.ZPEmployeeBuilder().setProcessingState('Queued').setResidenceState('CA').build();
		insert objEmployee;

		Test.stopTest();

		Contact objContact = [SELECT Residence_State__c, Account.Resident_States__c FROM Contact WHERE Employee_Id__c = '5453255' LIMIT 1];

		System.assert(String.isBlank(objContact.Account.Resident_States__c), 'Account Resident State should be blank');
		System.assert(String.isBlank(objContact.Residence_State__c), 'Contact Resident State should be blank');
	}
}