force-app/main/default/objects/Account/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Large_Scale_Issue__c.field-meta.xml
<CustomField>
    <fullName>Large_Scale_Issue__c</fullName>
    <label>Large Scale Issue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TaxOps</fullName>
            </value>
            <value>
                <fullName>Pufferfish</fullName>
            </value>
            <value>
                <fullName>MasterTax</fullName>
            </value>
            <value>
                <fullName>EPD</fullName>
            </value>
            <value>
                <fullName>Agency Error</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>No LSI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Reason_Classification__c/Case_Reason_Classification__c.object-meta.xml
<CustomObject>
    <label>Case Reason Classification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Reason Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Reason_Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The field determines the type for the case reason.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Care</fullName>
            </value>
            <value>
                <fullName>Benefits Care</fullName>
            </value>
            <value>
                <fullName>Tax Res</fullName>
            </value>
            <value>
                <fullName>Tax Ops</fullName>
            </value>
            <value>
                <fullName>Risk Assurance</fullName>
            </value>
            <value>
                <fullName>Modern Bank</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>PayrollOps Audit</fullName>
            </value>
            <value>
                <fullName>GEP CX</fullName>
            </value>
            <value>
                <fullName>R&amp;D Tax Credits</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Benefits Care - Read Only</fullName>
                <isActive>false</isActive>
                <label>Benefits Care - Read Only</label>
            </value>
            <value>
                <fullName>Modern Bank - Read Only</fullName>
                <isActive>false</isActive>
                <label>Modern Bank - Read Only</label>
            </value>
            <value>
                <fullName>Payroll Care - Read Only</fullName>
                <isActive>false</isActive>
                <label>Payroll Care - Read Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Configuration_Settings__c/Configuration_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Configuration Settings</label>
</CustomObject>

force-app/main/default/objects/Configuration_Settings__c/fields/TaxRes_Agatha_Sync_Time_Gap_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>TaxRes_Agatha_Sync_Time_Gap_in_Minutes__c</fullName>
    <description>This field is used to calculate the time difference needed to query Cases where &quot;Agency Info Agatha&quot; is not synced properly.</description>
    <inlineHelpText>This field is used to calculate the time difference needed to query Cases where &quot;Agency Info Agatha&quot; is not synced properly.</inlineHelpText>
    <label>TaxRes Agatha Sync Time Gap in Minutes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Email_Subject_AutoClosed__c/Email_Subject_AutoClosed__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Email subject match will auto Closed Case and assign to TaxOps Auto Closed Queue and update Confirm Case Reason to No Action Required</description>
    <label>Auto Closed Cases</label>
</CustomObject>

force-app/main/default/objects/Email_Subject_AutoClosed__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>TaxOps auto closed Case by email Subject</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Email Subject</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Email_Subject_AutoClosed__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/add_addresses_started_at__c.field-meta.xml
<CustomField>
    <fullName>add_addresses_started_at__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>add addresses started at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/add_employees_started_at__c.field-meta.xml
<CustomField>
    <fullName>add_employees_started_at__c</fullName>
    <label>add employees started at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ZenPayroll or Hawaiian Ice External Id
Prefixed with model name for uniqueness.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NumberOfEmployees__c.field-meta.xml
<CustomField>
    <fullName>NumberOfEmployees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Employees</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Onboarding_Funnel__c/ZP_Company_Onboarding_Funnel__c.object-meta.xml
<CustomObject>
    <label>ZP Company Onboarding Funnel</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP Company Onboarding Funnel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Company Onboarding Funnel</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ZP_Company_Onboarding_Funnel__c/fields/Add_Addresses_Completed__c.field-meta.xml
<CustomField>
    <fullName>Add_Addresses_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Addresses Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Onboarding_Funnel__c/fields/add_addresses_completed_at__c.field-meta.xml
<CustomField>
    <fullName>add_addresses_completed_at__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Add addresses completed at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Onboarding_Funnel__c/fields/add_addresses_started_at__c.field-meta.xml
<CustomField>
    <fullName>add_addresses_started_at__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>add addresses started at</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Onboarding_Funnel__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <externalId>true</externalId>
    <label>Source Model ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ZP_Company_Onboarding_Funnel__c/fields/Sign__c.field-meta.xml
<CustomField>
    <fullName>Sign__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Sign Up Step</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/ZP_User__c.object-meta.xml
<CustomObject>
    <label>ZP User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Last_Sign_In_At__c.field-meta.xml
<CustomField>
    <fullName>Last_Sign_In_At__c</fullName>
    <label>Last Sign In At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>ZP User Roles</relationshipLabel>
    <relationshipName>ZP_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TaxResCaseAgencyInfoAgathaSyncBatchTest.cls
@isTest
public with sharing class TaxResCaseAgencyInfoAgathaSyncBatchTest {
	@TestSetup
	static void TestDataSetup() {
		AccountTriggerHelper.skipTrigger = true;
		contactTriggerHelper.skipTrigger = true;
		OpportunityTriggerHelper.skipTrigger = true;

		Configuration_Settings__c objSetting = new Configuration_Settings__c();
		objSetting.TaxRes_Agatha_Sync_Time_Gap_in_Minutes__c = 45.0;
		insert objSetting;

		Account objAcc = TestUtility.CompanyAccount();
		objAcc.ZP_Company_id__c = '11111111111111TaxRes';
		update objAcc;

		Email_Subject_AutoClosed__c emailAutoClosed = new Email_Subject_AutoClosed__c();
		emailAutoClosed.Record_Type__c = 'Sales Cases';
		emailAutoClosed.Email_Subject__c = 'Test';
		emailAutoClosed.Name = 'Test';
		insert emailAutoClosed;

		Contact objCon = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(ContactUtil.COMPANY_CONTACT_RT_ID)
			.setAccountId(objAcc.Id)
			.setFirstName('Test Contact')
			.setLastName('Test')
			.setEmail('taxResCase@gusto1.com')
			.setPhone('1234567809')
			.setZPUserId('43243Gusto1')
			.build();
		insert objCon;

		Opportunity opp1 = new Opportunity();
		opp1.AccountId = objAcc.id;
		opp1.RecordTypeId = cache.getRecordTypeId('Opportunity', 'Benefits Renewal');
		opp1.name = 'Test';
		opp1.StageName = 'SAL';
		opp1.closedate = System.today();
		opp1.NumberOfEmployees__c = 12;
		insert opp1;

		Large_Scale_Issue__c largeScaleIssues = new Large_Scale_Issue__c();
		largeScaleIssues.name = 'Test LSI';
		insert largeScaleIssues;

		Case_Reason_Classification__c cseReason = new Case_Reason_Classification__c();
		cseReason.name = 'Test Reason';
		cseReason.Type__c = 'Tax Res';
		cseReason.Active__c = true;
		insert cseReason;

		ZP_User__c zpUser = new ZP_User__c();
		zpUser.Email__c = 'taxResCase@gusto1.com';
		zpUser.Created_At__c = Date.newInstance(2016, 11, 9);
		zpUser.Updated_At__c = Date.newInstance(2016, 12, 9);
		zpUser.Last_Sign_In_At__c = Date.newInstance(2018, 1, 1);
		zpUser.Id__c = '43243Gusto1';
		insert zpUser;

		ZP_User_Role__c zpUserRole = new ZP_User_Role__c();
		zpUserRole.User_Id__c = '43243Gusto1';
		zpUserRole.Phone__c = '1234567809';
		insert zpUserRole;

		Entitlement ent = new Entitlement(Name = 'Testing', AccountId = objAcc.Id, StartDate = Date.valueof(System.now()), EndDate = Date.valueof(System.now().addYears(2)));
		ent.type = 'Engagement - First Response';
		insert ent;

		ZPCompanyOnboardingFunnelTriggerHelper.skipTrigger = true;
		ZP_Company_Onboarding_Funnel__c funnel = new ZP_Company_Onboarding_Funnel__c();
		funnel.company_id__c = '11111111111111TaxRes';
		funnel.add_addresses_completed__c = true;
		funnel.Sign__c = 'Test';
		funnel.add_addresses_started_at__c = System.now().addDays(2);
		funnel.add_addresses_completed_at__c = System.now().addDays(-1);
		funnel.add_employees_started_at__c = System.now().addDays(2);
		funnel.Add_employees_completed_at__c = System.now().addDays(-1);
		funnel.state_setup_started_at__c = System.now().addDays(2);
		funnel.State_setup_completed_at__c = System.now().addDays(-1);
		funnel.add_bank_info_started_at__c = System.now().addDays(2);
		funnel.add_bank_info_completed_at__c = System.now().addDays(-1);
		funnel.payroll_schedule_started_at__c = System.now().addDays(2);
		funnel.payroll_schedule_completed_at__c = System.now().addDays(-1);
		funnel.previous_paystubs_started_at__c = System.now().addDays(2);
		funnel.previous_paystubs_completed_at__c = System.now().addDays(-1);
		funnel.add_signatory_started_at__c = System.now().addDays(2);
		funnel.add_signatory_started_at__c = System.now().addDays(2);
		funnel.sign_all_forms_started_at__c = System.now().addDays(2);
		funnel.Sign_all_forms_completed_at__c = System.now().addDays(-1);
		funnel.verify_bank_info_started_at__c = System.now().addDays(2);
		funnel.verify_bank_info_completed_at__c = System.now().addDays(-1);
		funnel.historical_liabilities_started_at__c = System.now().addDays(2);
		funnel.historical_liabilities_completed_at__c = System.now().addDays(-1);
		insert funnel;
		ZPCompanyOnboardingFunnelTriggerHelper.skipTrigger = false;
	}

	@isTest
	static void testBatchExecution() {
		CaseTriggerHelper.skipTrigger = true;
		list<Account> list_accRec = [SELECT Id FROM Account LIMIT 1];
		Case cse = new Case();
		cse.RecordTypeId = cache.getRecordTypeId('Case', 'Tax Res');
		cse.AccountId = list_accRec.get(0).Id;
		cse.Subject = 'Test';
		cse.Description = 'Test';
		cse.Type = 'QLE';
		cse.Origin = 'Email';
		cse.SuppliedEmail = 'taxResCase@gusto1.com';
		cse.Authorized_User__c = 'No';
		cse.Formating_Status__c = 'Pending';
		cse.TaxRes_OBMsg_Trigger__c = true;
		insert cse;

		test.startTest();
		TaxResCaseAgencyInfoAgathaSyncBatch batchController = new TaxResCaseAgencyInfoAgathaSyncBatch();
		Database.executeBatch(batchController, 1);
		test.stopTest();
		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void testBatchScheduler() {
		test.starttest();
		TaxResCaseScheduler schedulerClass = new TaxResCaseScheduler();
		String chron = '0 0 23 * * ?';
		System.schedule('Test Sched', chron, schedulerClass);
		test.stopTest();
		System.assert(true, 'Fixing Apex PMD issue.');
	}
}