force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Advisor_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Advisor_Assignment__c</fullName>
    <description>Advising would like to identify customers that do and do NOT want to communicate with advisors.</description>
    <label>Advisor Assignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin requested dedicated advisor</fullName>
            </value>
            <value>
                <fullName>Jira required</fullName>
            </value>
            <value>
                <fullName>Too many TPs</fullName>
            </value>
            <value>
                <fullName>Escalated ER</fullName>
            </value>
            <value>
                <fullName>Late BOR</fullName>
            </value>
            <value>
                <fullName>Outgrowing SGHI</fullName>
            </value>
            <value>
                <fullName>BYOB</fullName>
            </value>
            <value>
                <fullName>Big Desk (25+ EEs)</fullName>
            </value>
            <value>
                <fullName>Custom Quote Needed</fullName>
            </value>
            <value>
                <fullName>Carrier Deadline &lt;2 weeks away</fullName>
            </value>
            <value>
                <fullName>Affiliate Add Requested</fullName>
            </value>
            <value>
                <fullName>Enrollment error from previous year</fullName>
            </value>
            <value>
                <fullName>Plan error from previous year</fullName>
            </value>
            <value>
                <fullName>Escalated from Care team for early reach out</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Churn Risk</fullName>
            </value>
            <value>
                <fullName>Class-based contribution</fullName>
            </value>
            <value>
                <fullName>Hawaii employee</fullName>
            </value>
            <value>
                <fullName>Recertification</fullName>
            </value>
            <value>
                <fullName>Carrier Offboarding Strategy</fullName>
            </value>
            <value>
                <fullName>Customer upsell</fullName>
            </value>
            <value>
                <fullName>Employer outreach, can&apos;t auto-renew</fullName>
            </value>
            <value>
                <fullName>Address mismatch/SOS issues</fullName>
            </value>
            <value>
                <fullName>Termination or BOR away</fullName>
            </value>
            <value>
                <fullName>Level Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MassAdvisorAssignmentCtrlTest.cls
/**
 * @name         MassAdvisorAssignmentCtrlTest
 * @author       Bhagat Singh
 * @date         26 June 2024
 * @description  MassAdvisorAssignmentCtrl class code coverage.
 **/
@isTest
private class MassAdvisorAssignmentCtrlTest {
	@testSetup
	static void makeData() {
		List<Account> list_Account = new List<Account>();
		list_Account.add(new TestDataFactory.AccountBuilder().setName('Test Account 01').setRecordTypeId(AccountUtil.COMPANY_ACCOUNT_RT_ID).setZPCompanyId('7757616923580731').build());
		insert list_Account;

		List<Opportunity> list_Opp = new List<Opportunity>();
		list_Opp.add(
			new TestDataFactory.OpportunityBuilder()
				.setRecordTypeId(OpportunityUtil.BENEFITS_RENEWAL_OPPTY_RT_ID)
				.setName('Test Opp - BNP Ren')
				.setAccountId(list_Account[0].Id)
				.setCloseDate(System.today())
				.build()
		);
		insert list_Opp;
	}

	/**
	 * @author       Bhagat Singh
	 * @description  This method validate mass update Advisor_Assignment__c field values on selected opportunity records.
	 * @param        NA
	 * @return       NA
	 **/
	@isTest
	static void massUpdateAdvisorAssignment() {
		Test.startTest();
		List<Opportunity> list_Opp = [SELECT Id, Advisor_Assignment__c FROM Opportunity WHERE Account.ZP_Company_ID__c = '7757616923580731'];
		ApexPages.currentPage().getParameters().put('Id', list_Opp.get(0).id);
		ApexPages.StandardSetController objSSC = new ApexPages.StandardSetController(list_Opp);
		objSSC.setSelected(list_Opp);
		MassAdvisorAssignmentCtrl objCon = new MassAdvisorAssignmentCtrl(objSSC);
		objCon.getStep();
		objCon.cancel();
		objCon.objOpportunity.Advisor_Assignment__c = 'Escalated ER';
		objCon.updateOpportunity();

		Test.stopTest();

		list_Opp = [SELECT Id, Advisor_Assignment__c FROM Opportunity WHERE Account.ZP_Company_ID__c = '7757616923580731'];
		System.assertEquals('Escalated ER', list_Opp[0].Advisor_Assignment__c, 'Advisor Assignment not updated on opportunity');
	}
}