force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_Firm_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Firm_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Accounting Firm ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/Authorized_User__c.field-meta.xml
<CustomField>
    <fullName>Authorized_User__c</fullName>
    <description>Check if user is authorized based on Email on ZP User and Contact</description>
    <label>Authorized User</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Related_Company__c.field-meta.xml
<CustomField>
    <fullName>Related_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZP_User_id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP User id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ZP User Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Inapp_Email_Log__c/Inapp_Email_Log__c.object-meta.xml
<CustomObject>
    <label>Inapp Email Log</label>
    <nameField>
        <displayFormat>IEL-{000000000}</displayFormat>
        <label>Inapp Email Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inapp Email Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Inapp_Email_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Inapp Email Logs</relationshipLabel>
    <relationshipName>Inapp_Email_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inapp_Email_Log__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Exception</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inapp_Email_Log__c/fields/HTML_Body__c.field-meta.xml
<CustomField>
    <fullName>HTML_Body__c</fullName>
    <label>HTML Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Inapp_Email_Log__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inapp_Email_Log__c/fields/Plain_Text_Body__c.field-meta.xml
<CustomField>
    <fullName>Plain_Text_Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Plain Text Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NanorepInboundEmailService.cls
global class NanorepInboundEmailService implements Messaging.InboundEmailHandler {
	private static String companyId = '';
	private static String firmId = '';
	private static String userId = '';
	private static String emailAddress = '';
	private static String userName = '';
	private static String subject = '';

	global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
		String body = '';

		if (email.htmlBody != null) {
			body = email.htmlBody;
		} else if (email.plainTextBody != null) {
			body = email.plainTextBody;
		}

		try {
			Case c = new Case();

			c = createCase(email);

			EmailMessage msg = new EmailMessage();
			String ccaddr = '';

			if (email.ccAddresses != null) {
				for (String str : email.ccAddresses) {
					if (ccaddr != '') {
						ccaddr += '; ';
					}
					ccaddr += str;
				}
			}

			msg.CcAddress = ccaddr;
			msg.FromAddress = emailAddress;
			msg.FromName = userName;
			msg.Headers = '' + email.headers;
			msg.TextBody = getParsedText(body);
			msg.Subject = subject;
			if (c != null && c.Id != null) {
				msg.ParentId = c.Id;
			}
			String toaddr = '';
			if (email.toAddresses != null) {
				for (String str : email.toAddresses) {
					if (toaddr != '') {
						toaddr += '; ';
					}
					toaddr += str;
				}
			}

			msg.Incoming = true;
			insert msg;
			List<Attachment> attachmentList = new List<Attachment>();
			if (email.binaryAttachments != null) {
				for (Messaging.InboundEmail.BinaryAttachment atch : email.binaryAttachments) {
					if (isExeFile(atch, null)) {
						continue;
					}
					Attachment attch = new Attachment();
					attch.Body = atch.body;
					attch.Name = atch.fileName;
					attch.ContentType = atch.mimeTypeSubType;
					attch.ParentId = msg.Id;
					attachmentList.add(attch);
				}
			}
			if (email.textAttachments != null) {
				for (Messaging.InboundEmail.TextAttachment atch : email.textAttachments) {
					if (isExeFile(null, atch)) {
						continue;
					}
					Attachment attch = new Attachment();
					attch.Body = Blob.valueOf(atch.body);
					attch.Name = atch.fileName;
					attch.ContentType = atch.mimeTypeSubType;
					attch.ParentId = msg.Id;
					attachmentList.add(attch);
				}
			}
			if (attachmentList.size() > 0) {
				insert attachmentList;
			}
			createLog(email, c.id, 'Success', '');
		} catch (Exception ex) {
			createLog(email, null, 'Failed', ex.getMessage());
		}

		Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
		return result;
	}

	private void createLog(Messaging.InboundEmail email, String caseId, String status, String errorMessage) {
		Inapp_Email_Log__c log = new Inapp_Email_Log__c();
		log.Case__c = caseId;
		log.Exception__c = errorMessage;
		log.HTML_Body__c = email.htmlBody;
		log.Plain_Text_Body__c = email.plainTextBody;
		log.Status__c = status;
		log.message_id__c = 'Email-' + email.messageId;
		insert log;
	}

	public String getParsedText(String body) {
		String responseBody = body.split('-----------------------------------------------<br/>')[2];
		responseBody = responseBody.replaceAll('<br/>', '\n');
		responseBody = responseBody.replaceAll('<BR/>', '\n');
		responseBody = responseBody.replaceAll('</FONT>', '');
		responseBody = responseBody.replaceAll('<FONT size=1 face=Arial>', '');
		responseBody = responseBody.replaceAll('</P>', '');
		responseBody = responseBody.replaceAll('</DIV>', '');
		responseBody = responseBody.replaceAll('</BODY>', '');
		responseBody = responseBody.replaceAll('</HTML>', '');
		return responseBody;
	}

	public boolean isExeFile(Messaging.InboundEmail.BinaryAttachment binaryAttchmentRec, Messaging.InboundEmail.TextAttachment textAttachmentRec) {
		boolean isExeFile = false;
		List<Messaging.InboundEmail.Header> headerList = new List<Messaging.InboundEmail.Header>();

		if (binaryAttchmentRec != null) {
			headerList = binaryAttchmentRec.headers;
		} else if (textAttachmentRec != null) {
			headerList = textAttachmentRec.headers;
		}

		if (headerList != null && headerList.size() > 0) {
			for (Messaging.InboundEmail.Header headerRec : headerList) {
				if (headerRec.Name.equalsIgnoreCase('Content-Type') && headerRec.Value.equalsIgnoreCase('exe')) {
					isExeFile = true;
					break;
				}
			}
		}

		return isExeFile;
	}

	public static Case createCase(Messaging.InboundEmail email) {
		Database.DMLOptions dmo = new Database.DMLOptions();
		dmo.assignmentRuleHeader.useDefaultRule = true;

		Case cse = new Case();
		cse.setOptions(dmo);

		if (email.plainTextBody != null) {
			cse.Description = email.plainTextBody;
		} else if (email.htmlBody != null) {
			cse.Description = email.htmlBody;
		}

		cse.Origin = 'Gusto';
		cse.RecordTypeId = cache.getRecordTypeId('Case', 'Payroll Care');
		cse.Source__c = 'Support Bot';
		cse = setCaseAttributes(email.plainTextBody, cse);

		insert cse;

		return cse;
	}

	private static Case setCaseAttributes(String emailBody, Case cse) {
		cse.Authorized_User__c = 'Yes';

		if (emailBody.indexOf('-----------------------------------------------') > -1) {
			String metaData = '';
			String[] bodyArr = emailBody.split('-----------------------------------------------');
			if (bodyArr.size() > 2) {
				metaData = bodyArr[1];
			}

			String[] lineArray = metaData.split('\n');
			for (String line : lineArray) {
				if (line.indexOf('CompanyID : ') > -1) {
					companyId = line.replace('CompanyID : ', '');
				}
				if (line.indexOf('FirmID : ') > -1) {
					firmId = line.replace('FirmID : ', '');
				}
				if (line.indexOf('UserID : ') > -1) {
					userId = line.replace('UserID : ', '');
				}
				if (line.indexOf('Email : ') > -1) {
					emailAddress = line.replace('Email : ', '');
					if (emailAddress.indexOf(' <') > -1) {
						emailAddress = emailAddress.split(' <')[0];
					}
					emailAddress = emailAddress.trim();
				}
				if (line.indexOf('UserName : ') > -1) {
					userName = line.replace('UserName : ', '');
				}
				if (line.indexOf('subject :') > -1) {
					subject = line.replace('subject :', '');
				}
			}

			List<Account> companyAccounts = new List<Account>([SELECT Id FROM Account WHERE ZP_Company_id__c = :companyId AND ZP_Company_id__c != NULL]);
			List<Account> firmAccounts = new List<Account>([SELECT Id FROM Account WHERE ZP_Firm_id__c = :firmId AND ZP_Firm_id__c != NULL]);
			List<Contact> contactList = new List<Contact>([SELECT Id FROM contact WHERE zp_user_id__c = :userId AND zp_user_id__c != NULL]);
			List<Contact> contactEailList = new List<Contact>([SELECT Id FROM contact WHERE Email = :emailAddress AND Email != NULL]);
			if (firmId != '') {
				if (firmAccounts.size() > 0) {
					cse.AccountId = firmAccounts[0].id;
				}
				if (companyAccounts.size() > 0) {
					cse.Related_Company__c = companyAccounts[0].id;
				}
			} else if (companyId != '') {
				if (companyAccounts.size() > 0) {
					cse.AccountId = companyAccounts[0].id;
				}
			}
			if (userId != '') {
				if (contactList.size() > 0) {
					cse.ContactId = contactList[0].id;
				}
				cse.ZP_User_id__c = userId;
			}
			if (emailAddress != '') {
				cse.SuppliedEmail = emailAddress;
				if (contactList.size() < 1 && contactEailList.size() > 0) {
					cse.ContactId = contactEailList[0].id;
				}
			}
			if (userName != '') {
				cse.SuppliedName = userName;
			}
			if (subject != '') {
				cse.Subject = subject.left(80);
			}
		}
		return cse;
	}
}