force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Final_Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Extension_Date__c</fullName>
    <label>Final Extension Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/OE_Complete__c.field-meta.xml
<CustomField>
    <fullName>OE_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OE Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change</value>
        </filterItems>
        <infoMessage>Displaying new plan, change, and renewal opportunities only.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <formula>Opportunity__r.Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/HI_Fulfillment__c/HI_Fulfillment__c.object-meta.xml
<CustomObject>
    <label>HI Fulfillment</label>
    <nameField>
        <displayFormat>FUL-{0000}</displayFormat>
        <label>HI Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hi Fulfillments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Fulfillment__c/fields/Fulfillable_Id__c.field-meta.xml
<CustomField>
    <fullName>Fulfillable_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfillable Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Fulfillment__c/fields/Fulfillable_Type__c.field-meta.xml
<CustomField>
    <fullName>Fulfillable_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Fulfillable Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Fulfillment__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HI_Fulfillment__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HI_Open_Enrollment_Window__c/HI_Open_Enrollment_Window__c.object-meta.xml
<CustomObject>
    <label>HI Open Enrollment Window</label>
    <nameField>
        <displayFormat>OEW-{0000}</displayFormat>
        <label>Open Enrollment Windows Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI Open Enrollment Windows</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Final_Extension_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Extension_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Final Extension Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Fulfillment_Id__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Id__c</fullName>
    <label>Fulfillment Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/OE_Complete__c.field-meta.xml
<CustomField>
    <fullName>OE_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OE Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Window_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Window_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Window End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HI_Open_Enrollment_Window__c/fields/Window_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Window_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Window Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ZenPayroll or Hawaiian Ice External Id
Prefixed with model name for uniqueness.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Source_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_ID__c</fullName>
    <externalId>true</externalId>
    <label>Source ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ID of company migration record in Zen Payroll</description>
    <externalId>true</externalId>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Order/fields/Zp_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Zp_Company_ID__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <label>Zp Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>false</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/classes/HIOpenEnrollmentWindowTriggerHelper.cls
/*
 *   By : Akash Sharma
 *   Created Date : March 7, 2019
 *
 */

public with sharing class HIOpenEnrollmentWindowTriggerHelper {
	public static boolean skipTrigger = false;
	private static integer counter = 0;
	public static boolean queue = false;

	public void OnBeforeInsert(List<HI_Open_Enrollment_Window__c> openEnrollmentWindowList) {
		counter++;
		if (queue == true) {
			processInformation(openEnrollmentWindowList);
		} else {
			for (HI_Open_Enrollment_Window__c state : openEnrollmentWindowList) {
				state.Processing_State__c = IntegrationUtils.QUEUED_STATE;
			}
		}
	}

	public void OnAfterInsert(Map<ID, HI_Open_Enrollment_Window__c> openEnrollmentWindowMap) {
		if (queue == false) {
			HIOpenEnrollmentWindowQueue updateJob = new HIOpenEnrollmentWindowQueue(openEnrollmentWindowMap.values());
			ID jobID = System.enqueueJob(updateJob);
		}
	}

	@future
	public static void OnAfterInsertAsync(Set<ID> insertedopenEnrollmentWindowIDs) {
	}

	public void OnBeforeUpdate(Map<ID, HI_Open_Enrollment_Window__c> oldopenEnrollmentWindowMap, Map<ID, HI_Open_Enrollment_Window__c> newOpenEnrollmentWindowMap) {
		counter++;
		if (queue == true) {
			processInformation(newOpenEnrollmentWindowMap.values());
		} else {
			for (HI_Open_Enrollment_Window__c enrollRec : newOpenEnrollmentWindowMap.values()) {
				HI_Open_Enrollment_Window__c oldRewObj = oldopenEnrollmentWindowMap.get(enrollRec.Id);
				enrollRec.Processing_State__c = IntegrationUtils.QUEUED_STATE;
			}
		}
	}

	public void OnAfterUpdate(Map<ID, HI_Open_Enrollment_Window__c> oldopenEnrollmentWindowMap, Map<ID, HI_Open_Enrollment_Window__c> newOpenEnrollmentWindowMap) {
		if (queue == false) {
			HIOpenEnrollmentWindowQueue updateJob = new HIOpenEnrollmentWindowQueue(newOpenEnrollmentWindowMap.values());
			ID jobID = System.enqueueJob(updateJob);
		}
	}

	@future
	public static void OnAfterUpdateAsync(Set<ID> updatedCompantIDs) {
	}

	public void OnBeforeDelete(HI_Open_Enrollment_Window__c[] openEnrollmentWindowToDelete, Map<ID, HI_Open_Enrollment_Window__c> oldOpenEnrollmentWindowMap) {
		counter++;
	}

	public void OnAfterDelete(HI_Open_Enrollment_Window__c[] deletedOpenEnrollmentWindow, Map<ID, HI_Open_Enrollment_Window__c> oldOpenEnrollmentWindowMap) {
		counter++;
	}

	@future
	public static void OnAfterDeleteAsync(Set<ID> deletedCompanyIDs) {
	}

	public void OnUndelete(HI_Open_Enrollment_Window__c[] restoredOpenEnrollmentWindow) {
		counter++;
	}

	private void processInformation(List<HI_Open_Enrollment_Window__c> openEnrollmentWindowList) {
		Map<String, String> dmlUpsertErrorsMap = new Map<String, String>();
		List<Benefit_Order__c> boToUpdate = new List<Benefit_Order__c>();
		Set<String> companyIdSet = new Set<String>();
		Map<String, HI_Open_Enrollment_Window__c> enrollmentFulFillmentIdMap = new Map<String, HI_Open_Enrollment_Window__c>();
		Map<String, String> fulFillmentRecMap;

		for (HI_Open_Enrollment_Window__c openEnrollRec : openEnrollmentWindowList) {
			if (openEnrollRec.Company_Id__c != null) {
				companyIdSet.add(string.valueof(openEnrollRec.Company_Id__c));
				enrollmentFulFillmentIdMap.put(openEnrollRec.Fulfillment_Id__c, openEnrollRec);
			}
		}

		//Fetching the Hi_Fulfillment records based on the FulfillmentIds on HI_Open_Enrollment_Window__c
		if (enrollmentFulFillmentIdMap != null && enrollmentFulFillmentIdMap.keySet().size() > 0) {
			fulFillmentRecMap = new Map<String, String>();
			for (HI_Fulfillment__c fulfillmentRec : [
				SELECT Id__c, Fulfillable_Id__c, Fulfillable_Type__c
				FROM HI_Fulfillment__c
				WHERE Id__c IN :enrollmentFulFillmentIdMap.keySet() AND Created_At__c != NULL
			]) {
				if (fulfillmentRec.Fulfillable_Type__c == 'NewPlansApplication') {
					fulFillmentRecMap.put('hawaiian_ice-new_plans_application-' + fulfillmentRec.Fulfillable_Id__c, fulfillmentRec.Id__c);
				} else if (fulfillmentRec.Fulfillable_Type__c == 'BenefitChangeApplication') {
					fulFillmentRecMap.put('hawaiian_ice-benefit_change_application-' + fulfillmentRec.Fulfillable_Id__c, fulfillmentRec.Id__c);
				} else if (fulfillmentRec.Fulfillable_Type__c == 'Renewal') {
					fulFillmentRecMap.put('hawaiian_ice-renewal-' + fulfillmentRec.Fulfillable_Id__c, fulfillmentRec.Id__c);
				}
			}
		}

		if (fulFillmentRecMap != null && companyIdSet != null && fulFillmentRecMap.size() > 0 && companyIdSet.size() > 0) {
			for (Benefit_Order__c boRec : [
				SELECT Final_Extension_Date__c, OE_Complete__c, Open_Enrollment_End_Date__c, Open_Enrollment_Start_Date__c, Opportunity__r.Account.ZP_Company_ID__c, Opportunity__r.Source_ID__c
				FROM Benefit_Order__c
				WHERE
					Opportunity__r.Source_ID__c IN :fulFillmentRecMap.keySet()
					AND Opportunity__r.Account.ZP_Company_ID__c IN :companyIdSet
					AND Opportunity__c != NULL
					AND Opportunity__r.Source_ID__c != NULL
					AND Opportunity__r.AccountId != NULL
					AND Opportunity__r.Account.ZP_Company_ID__c != NULL
			]) {
				if (
					enrollmentFulFillmentIdMap != null &&
					enrollmentFulFillmentIdMap.keyset().size() > 0 &&
					fulFillmentRecMap.containsKey(boRec.Opportunity__r.Source_ID__c) &&
					enrollmentFulFillmentIdMap.containsKey(fulFillmentRecMap.get(boRec.Opportunity__r.Source_ID__c))
				) {
					HI_Open_Enrollment_Window__c relatedWindowRec = enrollmentFulFillmentIdMap.get(fulFillmentRecMap.get(boRec.Opportunity__r.Source_ID__c));
					boRec.Open_Enrollment_Start_Date__c = relatedWindowRec.Window_Start_Date__c;
					boRec.Open_Enrollment_End_Date__c = relatedWindowRec.Window_End_Date__c;
					boRec.Final_Extension_Date__c = relatedWindowRec.Final_Extension_Date__c;
					boRec.OE_Complete__c = relatedWindowRec.OE_Complete__c;
					boToUpdate.add(boRec);
				}
			}
		}

		Map<String, String> dmlUpdateErrorsMap = new Map<String, String>();

		if (boToUpdate != null && boToUpdate.size() > 0) {
			//Update benefit order records
			Boolean benefitOrderTriggerFlag = BenefitOrderHelper.skipTrigger;
			BenefitOrderHelper.skipTrigger = true;
			update boToUpdate;
			BenefitOrderHelper.skipTrigger = benefitOrderTriggerFlag;
			for (HI_Open_Enrollment_Window__c openEnrollmentRec : openEnrollmentWindowList) {
				openEnrollmentRec.Processing_State__c = 'Processed';
			}
		}
	}
	private HI_Open_Enrollment_Window__c setProcessingState(String ProcessingState, String message, HI_Open_Enrollment_Window__c hiOpenEnrollmentWindow) {
		hiOpenEnrollmentWindow.Processing_State__c = ProcessingState;
		hiOpenEnrollmentWindow.Message__c = message;
        
		return hiOpenEnrollmentWindow;
	}
}