force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <formula>Opportunity__r.Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <label>Carrier</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carriers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/recordTypes/Carrier.recordType-meta.xml
<RecordType>
    <fullName>Carrier</fullName>
    <active>true</active>
    <description>Medical Carrier</description>
    <label>Carrier</label>
</RecordType>

force-app/main/default/objects/Carrier_Order__c/Carrier_Order__c.object-meta.xml
<CustomObject>
    <label>Carrier Order</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Carrier_Order__c/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order Name</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier__c.field-meta.xml
<CustomField>
    <fullName>Carrier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carrier Name</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Carrier Orders</relationshipLabel>
    <relationshipName>Carrier_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/Carrier_Group_Number__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Group_Number__c</fullName>
    <description>This will be auto-populated via RPA (Automation bot)</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Group Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Order__c/fields/HI_Carrier_Id__c.field-meta.xml
<CustomField>
    <fullName>HI_Carrier_Id__c</fullName>
    <formula>Carrier__r.Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>HI Carrier Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Benefit_Order__r.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CarrierOrderGroupNumberKafkaCalloutTest.cls
/**
 * @name         CarrierOrderGroupNumberKafkaCalloutTest
 * @author       Ajay Kumar Vijay
 * @date         08/24/2023
 * @description  Test class for CarrierOrderGroupNumberKafkaCallout
 **/
@isTest
public class CarrierOrderGroupNumberKafkaCalloutTest {
    @isTest
    private static void testSendGroupNumber() {
        try {
            Account objAccount = new TestDataFactory.AccountBuilder()
                .setRecordTypeId('Company')
                .setName('Test Account1')
                .setZPCompanyId('123456789')
                .build();
            insert objAccount;
            
            Opportunity objOpp = new TestDataFactory.OpportunityBuilder()
                .setRecordTypeId(OpportunityUtil.BENEFITS_RENEWAL_OPPTY_RT_ID)
                .setAccountId(objAccount.Id)
                .setName('TEST OPPORTUNITY')
                .setStage('Open')
                .setCloseDate(System.Today())
                .build();
            insert objOpp;

            Benefit_Order__c objBO = new TestDataFactory.BenefitOrderBuilder()
                .setRecordType(Cache.getRecordTypeId('Benefit_Order__c', 'Renewal'))
                .setOpp(objOpp.Id)
                .setStatus('Ready for Qualification')
                .setOwnerID(UserInfo.getUserId())
                .build();

            Carrier__c objCarrierRec = new TestDataFactory.CarrierBuilder()
                .setName('Test123')
                .setKey('test123')
                .setId('test123')
                .setCarrierId('28272728')
                .build();
            insert objCarrierRec;

            Carrier_Order__c objCarrierOrder = new TestDataFactory.CarrierOrderBuilder()
                .setName('TestCarrierOrder')
                .setRecordTypeId(Cache.getRecordTypeId('Carrier_Order__c', 'Renewal'))
                .setCarrier(objCarrierRec.Id)
                .setOwnerID(UserInfo.getUserId())
                .setBenefitOrder(objBO.Id)
                .setOrderType('Carrier Switch')
                .setStartDate(System.today() - 50)
                .setImplementationStage('Ready For Qualification')
                .setCarrierGroupNumber('1234567890')
                .build();
            insert objCarrierOrder;

            Test.startTest();
            CarrierOrderGroupNumberKafkaCallout.sendGroupNumber(
                new List<CarrierOrderGroupNumberKafkaCallout.Request> {
                    new CarrierOrderGroupNumberKafkaCallout.Request(
                        objCarrierOrder.Carrier_Group_Number__c,
                        objCarrierOrder.HI_Carrier_Id__c,
                        objCarrierOrder.ZP_Company_Id__c
                    )
                }
            );
            Test.stopTest();
        } catch(Exception e) {
            System.assert(false, e.getMessage());
        }
    }
}