force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Benefit_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Unable to find an eligible company account.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Company, Embedded Company</value>
        </filterItems>
        <infoMessage>Displaying company accounts ONLY.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <formula>SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(Opportunity__r.Source_ID__c,&quot;hawaiian_ice-renewal-&quot;, &quot;&quot;) ,&quot;hawaiian_ice-new_plans_application-&quot;, &quot;&quot;),&quot;hawaiian_ice-commuter_benefit-&quot;, &quot;&quot;),&quot;hawaiian_ice-benefit_change_application-&quot;,&quot;&quot;),&quot;hawaiian_ice-account_benefit_interest-&quot;,&quot;&quot;),&quot;hawaiian_ice-BYB-&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Application_Type__c.field-meta.xml
<CustomField>
    <fullName>Application_Type__c</fullName>
    <formula>IF(RecordType.Name=&apos;Change&apos;, &apos;Change&apos;, IF(RecordType.Name=&apos;New Plan&apos;, &apos;New Plan&apos;, IF(RecordType.Name=&apos;Renewal&apos;, &apos;Renewal&apos;, &apos;&apos;) ) )</formula>
    <label>Application Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Coverage_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Coverage_Effective_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Coverage Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Documents_Status__c.field-meta.xml
<CustomField>
    <fullName>Documents_Status__c</fullName>
    <description>This will hold &apos;rejected&apos;, &apos;all_uploaded&apos;, &apos;all_completed&apos; as the possible values. We get this value from HI platform</description>
    <label>Documents Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>all_uploaded</fullName>
                <label>All uploaded</label>
            </value>
            <value>
                <fullName>all_completed</fullName>
                <label>All completed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>in_progress</fullName>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renewal Alignment</fullName>
            </value>
            <value>
                <fullName>New to Gusto</fullName>
            </value>
            <value>
                <fullName>Same carrier, plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Same carrier, NO plan/group level changes</fullName>
            </value>
            <value>
                <fullName>Carrier switch</fullName>
            </value>
            <value>
                <fullName>New Line of Coverage</fullName>
            </value>
            <value>
                <fullName>TAdA: Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>TAdA: No Pre OE Setup</fullName>
            </value>
            <value>
                <fullName>BOR + TAdA</fullName>
            </value>
            <value>
                <fullName>BOR</fullName>
            </value>
            <value>
                <fullName>BOR TAdA Only</fullName>
            </value>
            <value>
                <fullName>New to BYB - No OE</fullName>
            </value>
            <value>
                <fullName>New to BYB - OE</fullName>
            </value>
            <value>
                <fullName>Gusto to BYB - Renewal</fullName>
            </value>
            <value>
                <fullName>Gusto to BYB - Midyear</fullName>
            </value>
            <value>
                <fullName>BYB Renewal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <formula>Opportunity__r.Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/HIGroupEvent__c/HIGroupEvent__c.object-meta.xml
<CustomObject>
    <description>HI event table to handle all order/TTQ related events,</description>
    <label>HIGroupEvent</label>
    <nameField>
        <label>HIGroupEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HIGroupEvents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HIGroupEvent__c/fields/Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Application_Id__c</fullName>
    <description>Will contain application/Carrier Id, present in the json</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Application Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/fields/Application_type__c.field-meta.xml
<CustomField>
    <fullName>Application_type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Application type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/fields/Company_Id__c.field-meta.xml
<CustomField>
    <fullName>Company_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/fields/Documents_Status__c.field-meta.xml
<CustomField>
    <fullName>Documents_Status__c</fullName>
    <description>This will hold &apos;rejected&apos;, &apos;all_uploaded&apos;, &apos;all_completed&apos; as the possible values. We get this value from HI platform and stamp it onto the appropriate BO record</description>
    <label>Documents Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HIGroupEvent__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Event Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HIGroupEvent__c/fields/Event_Info__c.field-meta.xml
<CustomField>
    <fullName>Event_Info__c</fullName>
    <label>Event Info</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/HIGroupEvent__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
                <default>true</default>
                <label>Queued</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Dead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HIGroupEventDocCollectionStatus.cls
/**
 * @name         HIGroupEventDocCollectionStatus
 * @author       Deepika Saini
 * @Date         02/09/2021
 * @description  This class handles the messages sent to kafka topic document_collection via Workato and writes it to the HIGroupEvent__c object
 * @test class   HIGroupEventDocCollectionStatusTest.cls
 **/
public class HIGroupEventDocCollectionStatus {
	/*
	 * Process HIGroupEvents and copy information to Benefit Orders
	 */
	public static void processEvents(List<HIGroupEvent__c> list_Events) {
		Set<String> set_ApplicationIds = new Set<String>();
		Set<String> set_CompanyIds = new Set<String>();
		Set<String> set_ApplicationType = new Set<String>();
		Map<String, HIGroupEvent__c> map_EventIdHIGrpEvent = new Map<String, HIGroupEvent__c>();
		Map<String, BenefitOrderInfoWrapper> map_BenefitOrderInfoWrap = new Map<String, BenefitOrderInfoWrapper>();

		if (list_Events == null || list_Events.isEmpty()) {
			return;
		}

		for (HIGroupEvent__c objEvent : list_Events) {
			if (String.isBlank(objEvent.Event_Info__c)) {
				HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.ERROR_EVENT_INFO_MISSING, objEvent);
				continue;
			}

			try {
				HIGroupEventDocCollectionJSON objEventInfoJSON = (HIGroupEventDocCollectionJSON) JSON.deserialize(objEvent.Event_Info__c, HIGroupEventDocCollectionJSON.class);
				if (String.isBlank(objEvent.Application_Id__c)) {
					if (String.isBlank(objEventInfoJSON.application_id)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.ERROR_APPLICATION_ID_MISSING, objEvent);
						continue;
					}

					objEvent.Application_Id__c = objEventInfoJSON.application_id;
				}

				if (String.isBlank(objEvent.Application_type__c)) {
					if (String.isBlank(objEventInfoJSON.application_type)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.ERROR_APPLICATION_TYPE_MISSING, objEvent);
						continue;
					}

					objEvent.Application_type__c = objEventInfoJSON.application_type;
				}

				if (String.isBlank(objEvent.Company_Id__c)) {
					if (String.isBlank(objEventInfoJSON.company_id)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.ERROR_COMPANY_ID_MISSING, objEvent);
						continue;
					}

					objEvent.Company_Id__c = objEventInfoJSON.company_id;
				}

				if (String.isBlank(objEvent.Documents_Status__c)) {
					if (String.isBlank(objEventInfoJSON.documents_status)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.ERROR_DOC_COLLECTION_STATUS_MISSING, objEvent);
						continue;
					}

					objEvent.Documents_Status__c = objEventInfoJSON.documents_status;
				}

				set_ApplicationIds.add(objEvent.Application_Id__c);
				set_CompanyIds.add(objEvent.Company_Id__c);
				set_ApplicationType.add(objEvent.Application_type__c);

				String strKey = objEvent.Company_Id__c + '-' + objEvent.Application_Id__c + '-' + objEvent.Application_type__c;

				map_EventIdHIGrpEvent.put(objEvent.Event_Id__c, objEvent);
				BenefitOrderInfoWrapper objBOWrap = new BenefitOrderInfoWrapper(objEventInfoJSON.documents_status, objEvent.Event_Id__c);
				map_BenefitOrderInfoWrap.put(strKey, objBOWrap);
			} catch (Exception objEx) {
				HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, 'Error while parsing Event Info: ' + objEx.getMessage(), objEvent);
			}
		}

		try {
			if (map_EventIdHIGrpEvent.isEmpty() || set_ApplicationIds.isEmpty() || set_CompanyIds.isEmpty() || set_ApplicationType.isEmpty()) {
				return;
			}

			updateBenefitOrders(map_EventIdHIGrpEvent, map_BenefitOrderInfoWrap, set_ApplicationIds, set_CompanyIds, set_ApplicationType);
		} catch (Exception objEx) {
			ExceptionLogUtil.logException('HIGroupEventDocCollectionStatus', 'processEvents', objEx);
		}
	}

	/**Update Document Collection Status on Benefit Orders */
	static void updateBenefitOrders(
		Map<String, HIGroupEvent__c> map_EventIdHIGrpEvent,
		Map<String, BenefitOrderInfoWrapper> map_BenefitOrderInfoWrap,
		Set<String> set_ApplicationIds,
		Set<String> set_CompanyIds,
		Set<String> set_ApplicationType
	) {
		Map<String, String> map_EventIdToBenefitOrder = new Map<String, String>();
		List<Benefit_Order__c> list_BOToUpdate = new List<Benefit_Order__c>();

		for (Benefit_Order__c objBO : [
			SELECT Application_Id__c, RecordType.Name, Account__r.ZP_Company_Id__c, Type__c, Order_Status__c, Coverage_Effective_Date__c
			FROM Benefit_Order__c
			WHERE
				Account__c != NULL
				AND Account__r.ZP_Company_Id__c != NULL
				AND Account__r.ZP_Company_Id__c IN :set_CompanyIds
				AND Application_Id__c != NULL
				AND Application_Id__c IN :set_ApplicationIds
				AND RecordType.Name IN :set_applicationType
			FOR UPDATE
		]) {
			String strKey = objBO.Account__r.ZP_Company_Id__c + '-' + objBO.Application_Id__c + '-' + objBO.RecordType.Name;
			if (map_BenefitOrderInfoWrap.containsKey(strKey)) {
				BenefitOrderInfoWrapper objBOWrapper = map_BenefitOrderInfoWrap.get(strKey);

				map_EventIdToBenefitOrder.put(objBOWrapper.strEventId, objBO.Id);
				if (String.isNotBlank(objBOWrapper.strDocCollectionStatus)) {
					objBO.Documents_Status__c = objBOWrapper.strDocCollectionStatus;
					list_BOToUpdate.add(objBO);
				}
			}
		}
		
		if (!list_BOToUpdate.isEmpty()) {
			try {
				Database.SaveResult[] objResults = Database.update(list_BOToUpdate, false);

				Map<String, String> map_BOUpdateErrors = new Map<String, String>();
				map_BOUpdateErrors = Utils.processSaveRecords(objResults, list_BOToUpdate, 'Id', true, 'HIGroupEventDocCollectionStatus', 'updateBenefitOrders');

				for (HIGroupEvent__c objEvent : map_EventIdHIGrpEvent.values()) {
					String strBenefitOrderId;

					if (objEvent.Processing_State__c == IntegrationUtils.DEAD_STATE || objEvent.Processing_State__c == IntegrationUtils.ERROR_STATE) {
						continue;
					}

					if (!map_EventIdToBenefitOrder.containsKey(objEvent.Event_Id__c)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, HIGroupEventUtil.DOC_COLLECTION_ERROR_UNPROCESSED_EVENT, objEvent);
						continue;
					}

					strBenefitOrderId = map_EventIdToBenefitOrder.get(objEvent.Event_Id__c);

					if (map_BOUpdateErrors.containsKey(strBenefitOrderId)) {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.ERROR_STATE, map_BOUpdateErrors.get(strBenefitOrderId), objEvent);
						continue;
					} else {
						HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.PROCESSED_STATE, HIGroupEventUtil.DOC_COLLECTION_PROCESSED_MESSAGE, objEvent);
					}
				}
			} catch (Exception objEx) {
				ExceptionLogUtil.logException('HIGroupEventDocCollectionStatus', 'updateBenefitOrders', objEx);
			}
		} else {
			for (String strEventId : map_EventIdHIGrpEvent.keySet()) {
				if (map_EventIdHIGrpEvent.containsKey(strEventId) == false) {
					continue;
				}

				HIGroupEventTriggerHelper.setProcessingState(IntegrationUtils.DEAD_STATE, HIGroupEventUtil.DOC_COLLECTION_DEAD_UNPROCESSED_EVENT, map_EventIdHIGrpEvent.get(strEventId));
			}
		}
	}

	class BenefitOrderInfoWrapper {
		String strDocCollectionStatus;
		String strEventId;
		BenefitOrderInfoWrapper(String strStatus, String strEvent) {
			strDocCollectionStatus = strStatus;
			strEventId = strEvent;
		}
	}
}