force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Analytics_Time_Tracker__c/Analytics_Time_Tracker__c.object-meta.xml
<CustomObject>
    <description>To hold timestamp for different events on which reporting is to be done</description>
    <label>Analytics Time Tracker</label>
    <nameField>
        <displayFormat>ATT-{000000}</displayFormat>
        <label>Analytics Time Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Analytics Time Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Analytics_Time_Tracker__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Analytics Time Trackers</relationshipLabel>
    <relationshipName>Analytics_Time_Trackers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Order/fields/Data_Entry_Assist__c.field-meta.xml
<CustomField>
    <fullName>Data_Entry_Assist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[User].Is_Migration_Specialist__c must be true.</description>
    <label>Facilitator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Specialist_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Facilitator_Work_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Facilitator_Work_Start_DateTime__c</fullName>
    <description>Set for the first time when facilitator views the checklists</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Facilitator Work Start DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Order/fields/Zp_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Zp_Company_ID__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <label>Zp Company ID</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/Order_Facilitator_Checklist__c.object-meta.xml
<CustomObject>
    <description>Checklists related to Order</description>
    <label>Order Facilitator Checklist</label>
    <nameField>
        <displayFormat>OFC{000000}</displayFormat>
        <label>Order Facilitator Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Facilitator Checklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Checklist_Name__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Name__c</fullName>
    <description>Name of checklist, copied over fom BOR Master Checklist</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Checklist Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Facilitator_Checklist__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Lookup to Order object to Identify which checklists apply to a particular order</description>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Facilitator Checklists</relationshipLabel>
    <relationshipName>Order_Facilitator_Checklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Order_Facilitator_Checklist__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Order in which checklists are displayed</description>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PayrollTransferTimeTrackingBatchTest.cls
@isTest
public class PayrollTransferTimeTrackingBatchTest {
	@testsetup
	private static void setupTestData() {
		//Create a user who will be the facilitator
		Profile p = [SELECT Id FROM Profile WHERE Name = 'Direct Sales User'];

		User facilitator = new TestDataFactory.UserBuilder()
			.setEmail('testfacilitator@testorg.com')
			.setFirstName('Implementation')
			.setLastName('facilitator')
			.setProfileId(p.Id)
			.setUserName('Implementation.facilitator@test.Implementation')
			.setIsActive(true)
			.build();
		insert facilitator;
		//Insert Account
		Account account = new Account();
		account.RecordTypeId = Cache.getRecordTypeId('Account', 'Company');
		account.ZP_Company_Id__c = 'TestChkLst241019';
		account.Name = 'TestAccountChecklist';

		AccountTriggerHelper.skiptrigger = true;
		insert new List<Account>{ account };

		//Contact
		Contact objContact1 = new TestDataFactory.ContactBuilder()
			.setRecordTypeId('Company')
			.setAccountId(account.Id)
			.setFirstName('fName1')
			.setLastName('lName1')
			.setEmail('testAddress1@domain.com')
			.build();
		insert objContact1;

		//Order
		Order objOrder = new TestDataFactory.OrderBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Order', 'Company Migration'))
			.setAccountId(account.Id)
			.setStatus('Drafted')
			.setPayrollRunDate(Date.today())
			.setEffectiveDate(Date.today())
			.build();

		Order objOrder1 = new TestDataFactory.OrderBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Order', 'Company Migration'))
			.setAccountId(account.Id)
			.setStatus('Drafted')
			.setPayrollRunDate(Date.valueOf('2019-11-11'))
			.setEffectiveDate(Date.today())
			.build();

		Order objOrder2 = new TestDataFactory.OrderBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Order', 'Company Migration'))
			.setAccountId(account.Id)
			.setStatus('Onboarding Steps 1 - 6')
			.setPayrollRunDate(Date.valueOf('2019-11-11'))
			.setEffectiveDate(Date.today())
			.build();

		insert new List<Order>{ objOrder, objOrder1, objOrder2 };

		//Insert checklists
		List<Order_Facilitator_Checklist__c> lstChk = new List<Order_Facilitator_Checklist__c>();

		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk1', Order__c = objOrder.Id, Sequence__c = 1));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk2', Order__c = objOrder.Id, Sequence__c = 2));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk3', Order__c = objOrder1.Id, Sequence__c = 1));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk4', Order__c = objOrder1.Id, Sequence__c = 2));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk5', Order__c = objOrder2.Id, Sequence__c = 1));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test chk6', Order__c = objOrder2.Id, Sequence__c = 2));
		lstChk.add(new Order_Facilitator_Checklist__c(Checklist_Name__c = 'test ch7', Order__c = objOrder2.Id, Sequence__c = 3));

		insert lstChk;

		objOrder.Status = 'Collecting Documents';
		objOrder.Data_Entry_Assist__c = facilitator.Id;
		objOrder.Facilitator_Work_Start_DateTime__c = System.now();
		objOrder2.Status = 'Onboarding Steps 8 - 9';
		objOrder1.Status = 'Drafted';

		update new List<Order>{ objOrder, objOrder1, objOrder2 };
	}

	@isTest
	private static void testPTAnatyticsBatch() {
		PayrollTransferTimeTrackingBatch batch = new PayrollTransferTimeTrackingBatch();
		Test.startTest();
		Database.executeBatch(batch);
		Test.stopTest();

		System.assert([SELECT COUNT() FROM Analytics_Time_Tracker__c] > 0, 'There should be more than 1 record.');

		Database.executeBatch(batch);
	}
}