force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/Benefit_Order__c.object-meta.xml
<CustomObject>
    <description>A Gusto Health Benefit.</description>
    <label>Benefit Order</label>
    <nameField>
        <label>Benefit Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Benefit Orders</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Open_Enrollment_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Enrollment_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Open Enrollment Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Benefit_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordTypeId</field>
            <operation>equals</operation>
            <value>Benefits New Plan, Benefits Renewal, Benefits Change</value>
        </filterItems>
        <infoMessage>Displaying new plan, change, and renewal opportunities only.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Benefit Orders</relationshipLabel>
    <relationshipName>Benefit_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>Overall status of the Benefit Order.

The picklist values for the Order Status on the Benefit Order and the Implementation Stage on the Carrier Order must be kept in sync.</description>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Closed Admin</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Awaiting Routing</fullName>
            </value>
            <value>
                <fullName>With Sales</fullName>
            </value>
            <value>
                <fullName>With Advising</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
            <value>
                <fullName>Ready for Alignment</fullName>
            </value>
            <value>
                <fullName>Alignment Approved</fullName>
            </value>
            <value>
                <fullName>Alignment Denied</fullName>
            </value>
            <value>
                <fullName>Alignment Approved Post Renewal</fullName>
            </value>
            <value>
                <fullName>Ready for Qualification</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Ready for Intro</fullName>
            </value>
            <value>
                <fullName>Ready for Document Collection</fullName>
            </value>
            <value>
                <fullName>Collecting Documents</fullName>
            </value>
            <value>
                <fullName>Ready for Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Implementing Plans</fullName>
            </value>
            <value>
                <fullName>Ready to Send Plan Review</fullName>
            </value>
            <value>
                <fullName>Plan Review Sent</fullName>
            </value>
            <value>
                <fullName>Plans Confirmed</fullName>
            </value>
            <value>
                <fullName>Blocked Plan Review</fullName>
            </value>
            <value>
                <fullName>Unblock Plan Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Entry in Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Send Enrollment Review</fullName>
            </value>
            <value>
                <fullName>Enrollment Review Sent</fullName>
            </value>
            <value>
                <fullName>Enrollment Confirmed</fullName>
            </value>
            <value>
                <fullName>Ready for OE Prep</fullName>
            </value>
            <value>
                <fullName>OE Prep</fullName>
            </value>
            <value>
                <fullName>OE</fullName>
            </value>
            <value>
                <fullName>OE Extended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <formula>Opportunity__r.Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Benefit_Order__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <description>A renewal benefits order.</description>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/Case/fields/Benefit_Order__c.field-meta.xml
<CustomField>
    <fullName>Benefit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Benefit Order</label>
    <referenceTo>Benefit_Order__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Integration_Id__c.field-meta.xml
<CustomField>
    <fullName>Integration_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Integration Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Order Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>Api</inlineHelpText>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Benefits_New_Plan.recordType-meta.xml
<RecordType>
    <fullName>Benefits_New_Plan</fullName>
    <active>true</active>
    <businessProcess>Benefits New Plan Sales Process</businessProcess>
    <description>Used to track a potential sale for new HI Benefits where the customer does not currently provide HI</description>
    <label>Benefits New Plan</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Benefits_Renewal.recordType-meta.xml
<RecordType>
    <fullName>Benefits_Renewal</fullName>
    <active>true</active>
    <businessProcess>Benefits Renewal Sales Process</businessProcess>
    <description>Used to track a Renewal of Benefits</description>
    <label>Benefits Renewal</label>
</RecordType>

force-app/main/default/classes/OEReminderEmailBatchTest.cls
/**
* @name         OEReminderEmailBatchTest
* @author       Neha Dabas
* @date         August 18, 2020
* @description  Test class for OEReminderEmailBatch
* @revisions    Date ------------ Name ------------ Comments       
**/
@isTest
private class OEReminderEmailBatchTest {
    @testsetup
    static void createTestData(){
        AccountTriggerHelper.skipTrigger = true;
		ContactTriggerHelper.skipTrigger = true;
		CaseTriggerHelper.skipTrigger = true;

        Account objAcc =new Account(Name='test acc1',ZP_Company_Id__c = '100989001');
        insert objAcc;
        Opportunity objOpp = new Opportunity(RecordTypeId = Cache.getRecordTypeId('Opportunity','Benefits New Plan'));
        objOpp.AccountId = objAcc.Id;
        objOpp.StageName ='SAL';
        insert objOpp; 
        Opportunity objOpptyRenewal = TestUtility.BenefitsRenewalOpportunity();

        List<Contact> list_Contact = new List<Contact>();
        list_Contact.add(new Contact(FirstName = 'Neha 1',LastName = 'Test August 6 ', Email='neha.dabastest+1@lirik.io', AccountId = objOpp.AccountId));
        list_Contact.add(new Contact(FirstName = 'Neha 2',LastName = 'Test August 6 ', Email='neha.dabastest+2@lirik.io', AccountId = objOpptyRenewal.AccountId));
        insert list_Contact;

        List<Benefit_Order__c> list_BO = new List<Benefit_Order__c>();
        Benefit_Order__c objBONewPlan = new Benefit_Order__c();
        objBONewPlan.Opportunity__c = objOpp.Id;
        objBONewPlan.RecordTypeId = Cache.getRecordTypeId('Benefit_Order__c','New Plan');
        objBONewPlan.Open_Enrollment_Start_Date__c = system.today().addDays(-3);
        objBONewPlan.Open_Enrollment_End_Date__c = system.today().addDays(1);
        objBONewPlan.OwnerId = userInfo.getUserId();
        objBONewPlan.Order_Status__c = 'OE Extended';
        list_BO.add(objBONewPlan);
        
		Benefit_Order__c objBORenewal = new Benefit_Order__c();
        objBORenewal.Opportunity__c = objOpptyRenewal.Id;
        objBORenewal.RecordTypeId = Cache.getRecordTypeId('Benefit_Order__c','Renewal');
        objBORenewal.Open_Enrollment_Start_Date__c = system.today().addDays(-3);
        objBORenewal.Open_Enrollment_End_Date__c = system.today().addDays(1);
        objBORenewal.OwnerId = userInfo.getUserId();
        objBORenewal.Order_Status__c = 'OE';
        list_BO.add(objBORenewal);

        insert list_BO;

		List<Case> list_Case = new List<Case>();
        Id idNewPlan = Cache.getRecordTypeId('Case','Benefits New Plan Case');
        Id idRenewal = Cache.getRecordTypeId('Case','Benefits Renewal Case');
        list_Case.add(new Case( Subject = 'Test Case 1',contactId = list_Contact[0].Id,
                                AccountId = objOpptyRenewal.AccountId,RecordTypeId = idNewPlan,
                                Priority ='Medium',Direction__c='Inbound',Origin = 'Email',
                                Benefit_Order__c = objBONewPlan.Id,
                                Integration_Id__c = 'hippo-Benefits_New_Plan-'+objOpp.Id,
                                Opportunity__c = objOpp.Id));
        list_Case.add(new Case( Subject = 'Test Case 2',contactId = list_Contact[1].Id,
                                AccountId = objOpp.AccountId,RecordTypeId = idRenewal,
                                Priority ='Medium',Direction__c='Inbound',Origin = 'Email',
                                Benefit_Order__c = objBORenewal.Id,
                                Integration_Id__c = 'hippo-Benefits_Renewal-'+objOpptyRenewal.Id,
                                Opportunity__c = objOpptyRenewal.Id));
		insert list_Case;
    }
    static testmethod void testReminderEmailBatch(){
        test.startTest();
            OEReminderEmailBatch  objBatch = new OEReminderEmailBatch();
            Database.executeBatch(objBatch);
        test.stopTest();
    }
}