force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ZP_User_id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP User id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>ZP User Id</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/ZP_User_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Id__c</fullName>
    <description>The ZP User Id we get from chat</description>
    <encryptionScheme>None</encryptionScheme>
    <label>ZP User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines user types - Integration, Admin, UXR Manager, etc. It can be used in flows and trigger logic for customization and automation.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>UX Researcher Mng</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZP_User__c/ZP_User__c.object-meta.xml
<CustomObject>
    <label>ZP User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Permissions__c.field-meta.xml
<CustomField>
    <fullName>User_Permissions__c</fullName>
    <description>Populated by EPD, JSON of permissions for each user</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User Permissions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>ZP User Roles</relationshipLabel>
    <relationshipName>ZP_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdminPermissionsTest.cls
@isTest
public class AdminPermissionsTest {
	@isTest
	static void testGetAdminPerms() {
		//Method to fetch permissions
		Account objAcc = new Account(name = 'Test', ZP_Company_ID__c = '1111');
		insert objAcc;

		contact objCon = new contact();
		objCon.accountId = objAcc.id;
		objCon.LastName = 'Full';
		objCon.ZP_User_Id__c = '0000';
		objCon.Email = 'test@test.com';
		insert objCon;

		Case objCase = new Case(Status = 'New', Origin = 'Phone', AccountId = objAcc.Id, SuppliedEmail = 'test@test.com', ContactId = objCon.Id);
		insert objCase;

		ZP_User__c objUser = new ZP_User__c(Email__c = 'test@test.com', Created_At__c = System.now(), Updated_At__c = System.now(), Id__c = '122733');
		insert objUser;
		List<ZP_User__c> userList = new List<ZP_User__c>();
		userList.add(objUser);

		ZP_User_Role__c userRoleObj = new ZP_User_Role__c(User_Permissions__c = 'Test Permissions', User_Id__c = objCon.ZP_User_Id__c, Company_Id__c = objAcc.ZP_Company_ID__c, Deleted_At__c = null);
		insert userRoleObj;

		LiveChatVisitor objVisitor = new LiveChatVisitor();
		insert objVisitor;

		LiveChatTranscript objChat = new LiveChatTranscript(CaseId = objCase.Id, liveChatVisitorId = objVisitor.id);
		insert objChat;

		Test.startTest();
		List<String> lst_permission = AdminPermissions.queryAdminPerms(objCase.Id);
		System.assert(lst_permission.size() > 0, 'There should be at least 1 permissions.');
		Test.stopTest();
	}

	@isTest
	static void testGetUserRoles() {
		//Method to fetch user roles
		Account objAcc = new Account(name = 'Test', ZP_Company_ID__c = '1111');
		insert objAcc;

		contact objCon = new contact();
		objCon.accountId = objAcc.id;
		objCon.LastName = 'Full';
		objCon.ZP_User_Id__c = '0000';
		insert objCon;

		Case objCase = new Case(Status = 'New', Origin = 'Phone', AccountId = objAcc.Id, SuppliedEmail = 'test@test.com', ContactId = objCon.Id);
		insert objCase;

		ZP_User__c objUser = new ZP_User__c(Email__c = 'test@test.com', Created_At__c = System.now(), Updated_At__c = System.now(), Id__c = '122733');
		insert objUser;
		List<ZP_User__c> userList = new List<ZP_User__c>();
		userList.add(objUser);

		ZP_User_Role__c objuserRole = new ZP_User_Role__c(
			User_Permissions__c = 'Test Permissions',
			User_Id__c = objCon.ZP_User_Id__c,
			Company_Id__c = objAcc.ZP_Company_ID__c,
			Is_Primary__c = false,
			Deleted_At__c = null,
			Type__c = 'Role::PayrollAdmin'
		);
		insert objuserRole;

		LiveChatVisitor objVisitor = new LiveChatVisitor();
		insert objVisitor;

		LiveChatTranscript objChat = new LiveChatTranscript(CaseId = objCase.Id, liveChatVisitorId = objVisitor.id);
		insert objChat;
		Test.startTest();
		List<String> lst_roles = AdminPermissions.queryUserRoles(objCase.Id);
		System.assert(lst_roles.size() > 0, 'There should be at least 1 user role.');
		Test.stopTest();
	}
}