force-app/main/default/objects/Account/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Case/fields/Authorized_User__c.field-meta.xml
<CustomField>
    <fullName>Authorized_User__c</fullName>
    <description>Check if user is authorized based on Email on ZP User and Contact</description>
    <label>Authorized User</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/ZP_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_Id__c</fullName>
    <formula>Account.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>Ticket-{00000000}</displayFormat>
        <label>Action Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Ticket__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <description>This will get the ZP Company ID from UI Path</description>
    <label>Company ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Issue Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Ticket__c/fields/Reporting_Team__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Team__c</fullName>
    <label>Reporting Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advising Fulfillment</fullName>
            </value>
            <value>
                <fullName>Benefits Care</fullName>
            </value>
            <value>
                <fullName>Benefit Transfer Fulfillment</fullName>
            </value>
            <value>
                <fullName>Member Fulfillment</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>EPD</fullName>
            </value>
            <value>
                <fullName>I&amp;O</fullName>
            </value>
            <value>
                <fullName>Implementation Advocate</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>EPD Support</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Qualifier</fullName>
            </value>
            <value>
                <fullName>Facilitator 1</fullName>
            </value>
            <value>
                <fullName>Facilitator 2</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Carrier IO</fullName>
            </value>
            <value>
                <fullName>BYB Advocate</fullName>
            </value>
            <value>
                <fullName>BYB Member Ops</fullName>
            </value>
            <value>
                <fullName>BoR Sales</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>InProgress</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>SALY</fullName>
            </value>
            <value>
                <fullName>New - Onboarding</fullName>
            </value>
            <value>
                <fullName>Verification Needed</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Account Provisioned</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New / QRE Review</fullName>
            </value>
            <value>
                <fullName>Finalize Portal</fullName>
            </value>
            <value>
                <fullName>Four Part Pending</fullName>
            </value>
            <value>
                <fullName>Onboard Review</fullName>
            </value>
            <value>
                <fullName>Data Load</fullName>
            </value>
            <value>
                <fullName>Report Creation</fullName>
            </value>
            <value>
                <fullName>Calc Approval Pending</fullName>
            </value>
            <value>
                <fullName>Customer Survey Pending</fullName>
            </value>
            <value>
                <fullName>Ready for Additional Qualitative</fullName>
            </value>
            <value>
                <fullName>Credit Determination</fullName>
            </value>
            <value>
                <fullName>Filed Tax Return Needed</fullName>
            </value>
            <value>
                <fullName>Tax Return - Needs Quant Team Review</fullName>
            </value>
            <value>
                <fullName>Load Credits</fullName>
            </value>
            <value>
                <fullName>Gusto Real Time Billing</fullName>
            </value>
            <value>
                <fullName>Payroll Billing (non-Gusto)</fullName>
            </value>
            <value>
                <fullName>Liability Billing - Annually</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Payment Plan</fullName>
            </value>
            <value>
                <fullName>Carryforward Credits</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/ZP_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>ZP_Company_ID__c</fullName>
    <description>Company ID from the Account</description>
    <formula>Account__r.ZP_Company_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ZP Company ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/ZP_User__c.object-meta.xml
<CustomObject>
    <label>ZP User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Last_Sign_In_At__c.field-meta.xml
<CustomField>
    <fullName>Last_Sign_In_At__c</fullName>
    <label>Last Sign In At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>ZP User Roles</relationshipLabel>
    <relationshipName>ZP_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TicketSearchControllerTest.cls
@isTest
private class TicketSearchControllerTest {
	@testsetup
	static void setupTestData() {
		AccountTriggerHelper.skipTrigger = true;
		contactTriggerHelper.skipTrigger = true;
		ZPUserTriggerHelper.skipTrigger = true;
		ZPUserRoleTriggerHelper.skipTrigger = true;

		ZP_User__c zpUser = new ZP_User__c();
		zpUser.Email__c = 'CaseRelatedTicketsController@gusto.com';
		zpUser.Created_At__c = Date.newInstance(2016, 11, 9);
		zpUser.Updated_At__c = Date.newInstance(2016, 12, 9);
		zpUser.Last_Sign_In_At__c = Date.newInstance(2018, 1, 1);
		zpUser.Id__c = '78787878123';
		insert zpUser;

		ZP_User_Role__c zpUserRole = new ZP_User_Role__c();
		zpUserRole.User_Id__c = '78787878123';
		zpUserRole.Company_id__c = '78787878';
		insert zpUserRole;

		Account acc = TestUtility.CompanyAccount();
		acc.ZP_Company_id__c = '78787878';
		update acc;

		Contact objCont = new TestDataFactory.ContactBuilder()
			.setRecordTypeId(Cache.getRecordTypeId('Contact', 'Company'))
			.setPhone('7878787899')
			.setFirstName('Test')
			.setLastName('CaseRelatedTicketsController')
			.setAccountId(acc.id)
			.setEmail('CaseRelatedTicketsController@gusto.com')
			.setZPUserId('78787878123')
			.build();
		insert objCont;

		Case cse = new Case();
		cse.RecordTypeId = cache.getRecordTypeId('Case', 'Benefits Care');
		cse.AccountId = acc.Id;
		cse.Subject = 'Test';
		cse.Description = 'Test';
		cse.Type = 'Benefits Care';
		cse.Origin = 'Email';
		cse.SuppliedEmail = 'test.test1@test.com';
		cse.Authorized_User__c = 'No';
		insert cse;

		Ticket__c ticket = new Ticket__c();
		ticket.RecordTypeId = cache.getRecordTypeId('Ticket__c', 'Benefits Compliance');
		ticket.case__c = cse.id;
		ticket.status__c = 'New';
		ticket.priority__c = 'Low';
		ticket.Description__c = 'test';
		ticket.Reporting_Team__c = 'Benefits Care';
		insert ticket;
	}

	@isTest
	static void testTicketRetrival() {
		case caseRec = [SELECT id FROM Case LIMIT 1];

		apexpages.Currentpage().getParameters().put('id', caseRec.id);
		TicketSearchController controller = new TicketSearchController();
		controller.searchRecords();
		List<TicketSearchController.TicketWrapper> tempList = controller.ticketList;

		list<SelectOption> tempCommentFilterList = controller.getCommentDescriptionFilterList();

		System.assert(tempCommentFilterList.size() > 0, 'There should be more than 0 comment filters.');
		controller.searchTicketVar.Description__c = 'test';
		controller.searchRecords();
		controller.getDeselectRecordType();
		controller.getDeselectedRecordTypeValues();
		controller.getSelectedrecordTypeValues();

		controller.getSelectStatus();
		controller.getDeselectStatus();
		list<SelectOption> tempstatusList = controller.getDeselectedStatusValues();
		System.assert(tempstatusList.size() > 0, 'List should have more than 0 items.');
		controller.getSelectedStatusValues();
	}
}