force-app/main/default/objects/Account/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <description>Used to identify entities that we have a direct relationship with for running payroll.</description>
    <label>Company</label>
</RecordType>

force-app/main/default/objects/Case/fields/CCEmailAddress__c.field-meta.xml
<CustomField>
    <fullName>CCEmailAddress__c</fullName>
    <description>Used on Case.Email feed actions</description>
    <encryptionScheme>None</encryptionScheme>
    <label>CCEmailAddress</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Company_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Company ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>ContractorPayment</fullName>
                <label>Contractor Payment</label>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>AgentPayment</fullName>
                <label>Agent Payment</label>
            </value>
            <value>
                <fullName>HistoricalCompany</fullName>
                <label>Historical Company</label>
            </value>
            <value>
                <fullName>PenaltyCase</fullName>
                <label>Penalty Case</label>
            </value>
            <value>
                <fullName>Payroll Care Email</fullName>
            </value>
            <value>
                <fullName>InternationalContractorPayments::Db::InternationalContractorPayment</fullName>
            </value>
            <value>
                <fullName>InternationalEmployeePayroll</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Genesys_Call_Id__c.field-meta.xml
<CustomField>
    <fullName>Genesys_Call_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Genesys Call Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Large_Scale_Issue__c.field-meta.xml
<CustomField>
    <fullName>Large_Scale_Issue__c</fullName>
    <label>Large Scale Issue</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TaxOps</fullName>
            </value>
            <value>
                <fullName>Pufferfish</fullName>
            </value>
            <value>
                <fullName>MasterTax</fullName>
            </value>
            <value>
                <fullName>EPD</fullName>
            </value>
            <value>
                <fullName>Agency Error</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>No LSI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case_Audit_Log__c/Case_Audit_Log__c.object-meta.xml
<CustomObject>
    <label>Case Audit Log</label>
    <nameField>
        <displayFormat>CAL-{00000000}</displayFormat>
        <label>Case Audit Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Audit Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Audit_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Audit Logs</relationshipLabel>
    <relationshipName>Case_Audit_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Case_Reason_Classification__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Classification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Case Reason that sent the auto email from the Case.</description>
    <label>Case Reason Classification</label>
    <referenceTo>Case_Reason_Classification__c</referenceTo>
    <relationshipLabel>Case Audit Logs</relationshipLabel>
    <relationshipName>Case_Audit_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Audit_Log__c/fields/Direction__c.field-meta.xml
<CustomField>
    <fullName>Direction__c</fullName>
    <label>Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Voicemail</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>CallBack</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Reason_Classification__c/Case_Reason_Classification__c.object-meta.xml
<CustomObject>
    <label>Case Reason Classification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Reason</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Reason Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case_Reason_Classification__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The field determines the type for the case reason.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Care</fullName>
            </value>
            <value>
                <fullName>Benefits Care</fullName>
            </value>
            <value>
                <fullName>Tax Res</fullName>
            </value>
            <value>
                <fullName>Tax Ops</fullName>
            </value>
            <value>
                <fullName>Risk Assurance</fullName>
            </value>
            <value>
                <fullName>Modern Bank</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>PayrollOps Audit</fullName>
            </value>
            <value>
                <fullName>GEP CX</fullName>
            </value>
            <value>
                <fullName>R&amp;D Tax Credits</fullName>
            </value>
            <value>
                <fullName>Engagement</fullName>
            </value>
            <value>
                <fullName>Benefits Care - Read Only</fullName>
                <isActive>false</isActive>
                <label>Benefits Care - Read Only</label>
            </value>
            <value>
                <fullName>Modern Bank - Read Only</fullName>
                <isActive>false</isActive>
                <label>Modern Bank - Read Only</label>
            </value>
            <value>
                <fullName>Payroll Care - Read Only</fullName>
                <isActive>false</isActive>
                <label>Payroll Care - Read Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/ZP_User_Role__c.field-meta.xml
<CustomField>
    <fullName>ZP_User_Role__c</fullName>
    <label>ZP User Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Benefits Admin</fullName>
            </value>
            <value>
                <fullName>Primary Payroll Admin</fullName>
            </value>
            <value>
                <fullName>Signatory</fullName>
            </value>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>International Contractor</fullName>
            </value>
            <value>
                <fullName>Company Member</fullName>
            </value>
            <value>
                <fullName>International Employee</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Company.recordType-meta.xml
<RecordType>
    <fullName>Company</fullName>
    <active>true</active>
    <label>Company</label>
</RecordType>

unpackaged/main/default/objects/User/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines user types - Integration, Admin, UXR Manager, etc. It can be used in flows and trigger logic for customization and automation.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>UX Researcher Mng</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZP_User__c/ZP_User__c.object-meta.xml
<CustomObject>
    <label>ZP User</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ZP User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ZP Users</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User__c/fields/Created_At__c.field-meta.xml
<CustomField>
    <fullName>Created_At__c</fullName>
    <label>Created At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>First Name sent from in App, derived from the &quot;best&quot; zp user role First Name as defined by Eng.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>First Name sent from in App, derived from the &quot;best&quot; zp user role First Name as defined by Eng.</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Last Name sent from in App, derived from the &quot;best&quot; zp user role Last Name as defined by Eng.</description>
    <inlineHelpText>Last Name sent from in App, derived from the &quot;best&quot; zp user role Last Name as defined by Eng.</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User__c/fields/Updated_At__c.field-meta.xml
<CustomField>
    <fullName>Updated_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Updated At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/ZP_User_Role__c.object-meta.xml
<CustomObject>
    <label>ZP User Role</label>
    <nameField>
        <displayFormat>USER-Role-{000000000}</displayFormat>
        <label>ZP User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP User Roles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_User_Role__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <externalId>true</externalId>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ZP_User_Role__c/fields/User_Permissions__c.field-meta.xml
<CustomField>
    <fullName>User_Permissions__c</fullName>
    <description>Populated by EPD, JSON of permissions for each user</description>
    <encryptionScheme>None</encryptionScheme>
    <label>User Permissions</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ZP_User_Role__c/fields/ZP_User__c.field-meta.xml
<CustomField>
    <fullName>ZP_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ZP User</label>
    <referenceTo>ZP_User__c</referenceTo>
    <relationshipLabel>ZP User Roles</relationshipLabel>
    <relationshipName>ZP_User_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EngagementCaseViewExtensionTest.cls
@isTest
private class EngagementCaseViewExtensionTest {
	static Case objCase;
	static EngagementCaseViewExtension extension;

	@testSetup
	static void setUp() {
		AccountTriggerHelper.skipTrigger = true;
		ContactTriggerHelper.skipTrigger = true;
		CaseTriggerHelper.skipTrigger = true;

		ZP_User__c zpUser = new ZP_User__c();
		zpUser.Name = 'EngagementCaseView TestUser';
		zpUser.Created_At__c = System.today();
		zpUser.Updated_At__c = System.today();
		zpUser.Id__c = 'EngagementCaseViewUser1';
		zpUser.Email__c = 'EngagementUser@gusto1.com';
		insert zpUser;

		ZP_User_Role__c userRole = new ZP_User_Role__c();
		userRole.User_Id__c = zpUser.Id__c;
		userRole.Company_Id__c = 'engagementCase4321';
		userRole.First_Name__c = 'EngagementCaseView';
		userRole.Last_Name__c = 'TestUser';
		userRole.User_Permissions__c = 'full_access;';
		userRole.Type__c = 'PayrollAdmin';
		insert userRole;

		Account objAcc = new TestDataFactory.AccountBuilder().setRecordTypeId('Company').setName('Test Company').setZPCompanyId('engagementCase4321').setStates('FL;OR').build();
		insert objAcc;

		list<Contact> list_Contacts = new List<Contact>();
		Contact objContact1 = new TestDataFactory.ContactBuilder()
			.setRecordTypeId('Company')
			.setAccountId(objAcc.Id)
			.setPhone('123456')
			.setFirstName('Test')
			.setLastName('TestEngagementCaseViewExtension')
			.build();
		list_Contacts.add(objContact1);

		Contact objContact2 = new TestDataFactory.ContactBuilder()
			.setRecordTypeId('Company')
			.setAccountId(objAcc.Id)
			.setPhone('123456')
			.setFirstName('Parent')
			.setLastName('TestParentEngagementCaseView')
			.build();
		list_Contacts.add(objContact2);

		insert list_Contacts;

		list<Group> phoneRoutingList = [SELECT Id FROM Group WHERE type = 'Queue' AND Name = 'Phone Routing'];

		Case objCase1 = new Case();
		objCase1.ContactId = objContact1.Id;
		objCase1.AccountId = objAcc.Id;
		objCase1.Direction__c = 'Inbound';
		objCase1.Origin = 'Phone';
		objCase1.RecordTypeId = Cache.getRecordTypeId('Case', 'Payroll Care');
		objCase1.Genesys_Call_Id__c = '222111333';
		if (phoneRoutingList.size() > 0) {
			objCase1.OwnerId = phoneRoutingList.get(0).Id;
		}
		objCase1.ccEmailAddress__c = 'test@test.com';

		insert objCase1;
		list<case> list_Cases = new List<case>();
		Case objCase = new Case();
		objCase.ContactId = objContact2.Id;
		objCase.AccountId = objAcc.Id;
		objCase.Direction__c = 'Inbound';
		objCase.Origin = 'Phone';
		objCase.ParentId = objCase1.Id;
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Tax Res');
		objCase.Genesys_Call_Id__c = '222111333';
		if (phoneRoutingList.size() > 0) {
			objCase.OwnerId = phoneRoutingList.get(0).Id;
		}
		list_Cases.add(objCase);

		Case objCase2 = new Case();
		objCase2.Direction__c = 'Inbound';
		objCase2.ContactId = objContact1.Id;
		objCase2.AccountId = objAcc.Id;
		objCase2.Origin = 'Phone';
		objCase2.RecordTypeId = Cache.getRecordTypeId('Case', 'Payroll Care');
		objCase2.Genesys_Call_Id__c = '222111333';
		if (phoneRoutingList.size() > 0) {
			objCase2.OwnerId = phoneRoutingList.get(0).Id;
		}
		list_Cases.add(objCase2);

		Case objCase3 = new Case();
		objCase3.ContactId = objContact2.Id;
		objCase3.AccountId = objAcc.Id;
		objCase3.Direction__c = 'Inbound';
		objCase3.Origin = 'Phone';
		objCase3.ParentId = objCase1.Id;
		objCase3.RecordTypeId = Cache.getRecordTypeId('Case', 'PayrollOps Audit');
		objCase3.Genesys_Call_Id__c = '222111333';
		if (phoneRoutingList.size() > 0) {
			objCase3.OwnerId = phoneRoutingList.get(0).Id;
		}
		list_Cases.add(objCase3);

		insert list_Cases;

		Case_Reason_Classification__c cseReason = new Case_Reason_Classification__c();
		cseReason.name = 'Test Reason';
		cseReason.Active__c = true;
		cseReason.Type__c = 'Tax Res';
		insert cseReason;

		Large_Scale_Issue__c largeScaleIssues = new Large_Scale_Issue__c();
		largeScaleIssues.name = 'Test LSI';
		insert largeScaleIssues;
	}

	@isTest
	static void callPickUpFunctionality() {
		Test.startTest();
		CaseTriggerHelper.skipTrigger = true;
		Case objCase = [SELECT Id, ownerId FROM Case WHERE Genesys_Call_Id__c != NULL].get(0);

		Case_Audit_Log__c logRec = new Case_Audit_Log__c();
		logRec.Case__c = objCase.Id;
		logRec.Event_Type__c = 'Phone';
		insert logRec;

		Task tsk = new task();
		tsk.whatId = objCase.Id;
		insert tsk;

		apexPages.standardController sc = new apexPages.standardController(objCase);
		EngagementCaseViewExtension controller = new EngagementCaseViewExtension(sc);
		controller.assignUserOnCallPickup();
		controller.setAccessPermission('', 'EngagementUser@gusto1.com');
		controller.checkCaseTask();
		controller.checkCaseTaskFromPoller();
		controller.updateCaseAuditLog(objCase);
		controller.saveAccountNotes();
		controller.initModernBankHighlightsPanel();
		controller.SaveModernBankCase();
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void publishToApIntegoTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Test' LIMIT 1];
		setupTestRun(objCase);
		extension.publishToApIntego();
		extension.getRoutingPageReference('123');
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void acceptCaseTest() {
		Test.startTest();
		Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
		Case objCase = [SELECT Id, Status, OwnerId FROM Case WHERE contact.FirstName = 'Test' LIMIT 1];
		User usr = new User(
			Alias = 'gusst11',
			Email = 'gusto.standarduser2@gustotestorg.com',
			EmailEncodingKey = 'UTF-8',
			LastName = 'TestingCase',
			LanguageLocaleKey = 'en_US',
			LocaleSidKey = 'en_US',
			ProfileId = p.Id,
			TimeZoneSidKey = 'America/Los_Angeles',
			UserName = 'gusto.standarduser2@gustotestorg.com',
			Out_Of_Office__c = false
		);
		insert usr;
		Map<String, Schema.RecordTypeInfo> recordTypesadjustment = Case.sObjectType.getDescribe().getRecordTypeInfosByName();
		System.runAs(usr) {
			setupTestRun(objCase);
			PageReference pageRef = extension.acceptCase();
			objCase = [SELECT Id, Status, OwnerId FROM Case WHERE contact.FirstName = 'Test' LIMIT 1];
		}
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void unmergeCaseTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}

		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();
	}

	@isTest
	static void moveToProgressTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Test' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef = extension.moveToInprogress();
		objCase = [SELECT Id, Status FROM Case WHERE contact.FirstName = 'Test' LIMIT 1];
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertEquals(2, pageMessages.size(), 'There should be 2 page messages.');
		System.assertEquals('In Progress', objCase.status, 'Status should be in progress.');
		Test.stopTest();
	}

	@isTest
	static void moveToOpenTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef = extension.moveToOpen();
		objCase = [SELECT Id, Status FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
		System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
		extension.routeCase();
		PageReference pageRef1 = extension.initPayrollCareCase();
		PageReference pageRef2 = extension.initBenefitCareCase();
		PageReference pageRef3 = extension.initTaxResCase();
		PageReference pageRef4 = extension.initTaxOpsCase();
		PageReference pageRef5 = extension.initPayrollComplianceCase();
		PageReference pageRef6 = extension.initRiskCase();
		extension.getRoutingPageReference('Risk');
		extension.initModernBankCase();
		extension.initBenefitsCompliance();
		extension.SaveRiskAssuranceCase();
		extension.SaveBenefitsComplianceCase();
		Test.stopTest();
	}

	@isTest
	static void taxOpsCaseTest() {
		CaseTriggerHelper.skipTrigger = true;
		Test.startTest();
		Case objCase = [SELECT Id, AccountId FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		setupTestRun(objCase);
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		PageReference pageRef1 = extension.SaveTaxOpsCase();
		extension.initTaxOpsCase();
		extension.initTaxResHighlightsPanel();

		extension.statusChangeEvent();
		extension.saveCaseRecord();
		System.assertEquals(objCase.AccountId, extension.theAccount.Id, 'Account Id should match.');
		Test.stopTest();
	}

	@isTest
	static void payrollCareTest() {
		CaseTriggerHelper.skipTrigger = true;
		Test.startTest();
		Case objCase = [SELECT Id, AccountId FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef1 = extension.SavePayrollCareCase();
		extension.initPayrollHighlightsPanel();
		System.assertEquals(objCase.AccountId, extension.theAccount.Id, 'Account Id should match.');
		Test.stopTest();
	}

	@isTest
	static void taxResTest() {
		CaseTriggerHelper.skipTrigger = true;
		Test.startTest();
		Case objCase = [SELECT Id, AccountId FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef1 = extension.SaveTaxResCase();
		extension.initTaxResHighlightsPanel();
		System.assertEquals(objCase.AccountId, extension.theAccount.Id, 'Account Id should match.');
		Test.stopTest();
	}

	@isTest
	static void benefitsCareTest() {
		CaseTriggerHelper.skipTrigger = true;
		Test.startTest();
		Case objCase = [SELECT Id, AccountId FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		setupTestRun(objCase);
		PageReference pageRef1 = extension.SaveBenefitsCareCase();
		extension.initBenefitsHighlightsPanel();
		System.assertEquals(objCase.AccountId, extension.theAccount.Id, 'Account Id should match.');
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void upsellTest() {
		Test.startTest();
		Case objCase2 = [SELECT Id, AccountId FROM Case WHERE Account.ZP_Company_Id__c = 'engagementCase4321' LIMIT 1];
		setupTestRun(objCase2);

		extension.zpExpId = '123';
		extension.zpCompId = '123';
		extension.zpExpStatusId = '123';
		extension.operation = '123';
		extension.boolIsChat = true;
		extension.operation = 'NotInterested';
		extension.updateCount();
		extension.operation = 'NotApplicable';
		extension.updateCount();
		extension.operation = 'TrackConversation';
		extension.updateCount();
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}
	@isTest
	static void testValidationsForTaxResCase() {
		Test.startTest();
		Case obj_Case = [SELECT Id FROM Case WHERE RecordType.Name = 'Tax Res' LIMIT 1];
		setupTestRun(obj_Case);
		extension.theCase.Status = 'Solved';
		extension.SaveTaxResCase();

		System.assertNotEquals([SELECT Status FROM Case WHERE Id = :obj_Case.Id].Status, 'Solved', 'Case status should not be Solved.');

		extension.theCase.Confirm_Case_Reason__c = '1099 Adjustment';
		extension.SaveTaxResCase();
		extension.unmergeCase();
		System.assertNotEquals([SELECT Status FROM Case WHERE Id = :obj_Case.Id].Status, 'Solved', 'Case status should not be Solved.');
		Test.stopTest();
	}
	@isTest
	static void testValidationsForPayrollOpsAuditCase() {
		Test.startTest();
		CaseTriggerHelper.skipTrigger = true;
		Case obj_Case = [SELECT Id FROM Case WHERE RecordType.Name = 'PayrollOps Audit' LIMIT 1];
		setupTestRun(obj_Case);
		extension.initPayrollAuditCase();
		extension.getRoutingPageReference('PayrollOps Audit');
		extension.theCase.Status = 'Solved';
		extension.theCase.Confirm_Case_Reason__c = '1099 Adjustment';
		extension.SavePayrollAuditCase();
		extension.unmergeCase();
		Test.stopTest();

		System.assertNotEquals([SELECT Status FROM Case WHERE Id = :obj_Case.Id].Status, 'Solved', 'Case status should not be Solved.');
	}
	@isTest
	static void testTakeItPayrollOpsAuditCase() {
		Test.startTest();
		CaseTriggerHelper.skipTrigger = true;
		Case obj_Case = [SELECT Id FROM Case WHERE RecordType.Name = 'PayrollOps Audit' LIMIT 1];
		setupTestRun(obj_Case);
		extension.acceptCase();
		Test.stopTest();

		System.assertEquals([SELECT Status FROM Case WHERE Id = :obj_Case.Id].Status, 'In Progress', 'Case Status should be In Progress');
	}
	static void setupTestRun(Case objCase) {
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		extension.checkCaseStatus();
		extension.statusChangeEvent();
		EngagementCaseViewExtension.getEmailCC(objCase.Id);
		System.assertNotEquals(null, extension, 'extension should not be null.');
	}
	@isTest
	static void unmergeCaseBCareTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Benefits Care');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}
		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();
	}
	@isTest
	static void unmergeCasePCareTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Payroll Care');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}

		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();
	}
	@isTest
	static void unmergeCaseTaxResTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Tax Res');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}

		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();
	}
	@isTest
	static void unmergeCasePAuditTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'PayrollOps Audit');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}

		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();
	}
	@isTest
	static void unmergeCaseMBankTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Modern Bank');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		PageReference pageRef = extension.unmergeCase();
		ApexPages.Message[] pageMessages = ApexPages.getMessages();
		if (pageMessages.size() > 0) {
			System.assertEquals(1, pageMessages.size(), 'There should be 1 page message.');
			System.assertEquals(ApexPages.Severity.INFO, pageMessages[0].getSeverity(), 'Page message severity should be INFO.');
			System.assertEquals('Case is successfully un merged', pageMessages[0].getDetail(), 'Page message detail should match.');
		}

		System.assertEquals('true', pageRef.getParameters().get('refreshPage'), 'refreshPage parameter should be true.');
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}
	@isTest
	static void caseMBankTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Modern Bank');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}
	@isTest
	static void caseTaxOpsTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Tax Ops');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}

	@isTest
	static void casePayrollComTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Payroll Compliance');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}
	@isTest
	static void caseBenefitTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Benefits Compliance');
		update objCase;
		ApexPages.StandardController stdController = new ApexPages.StandardController(objCase);
		extension = new EngagementCaseViewExtension(stdController);
		Test.stopTest();

		System.assert(true, 'Fixing Apex PMD issue.');
	}
	/**
	 * @author Prajjwal Tawri
	 * @description testing initEngagementCase()
	 */
	@isTest
	static void caseEngagementTest() {
		Test.startTest();
		Case objCase = [SELECT Id FROM Case WHERE Contact.FirstName = 'Parent' LIMIT 1];
		objCase.RecordTypeId = Cache.getRecordTypeId('Case', 'Engagement');
		update objCase;
		setupTestRun(objCase);
		PageReference pageRef = extension.initEngagementCase();
		System.assertEquals(null, pageRef, 'pageRef should not be null.');
		Test.stopTest();
	}
}