force-app/main/default/objects/ZP_Company__c/ZP_Company__c.object-meta.xml
<CustomObject>
    <label>ZP Company</label>
    <nameField>
        <displayFormat>COMPANY-{000000000}</displayFormat>
        <label>ZP Company Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Company__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>The external record ID from the source system, company.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Source Model ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/ZP_Company__c/fields/Processing_State__c.field-meta.xml
<CustomField>
    <fullName>Processing_State__c</fullName>
    <description>The current processing state for this record.  Only values in Queued are processed.</description>
    <label>Processing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Integration_Processing_States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ZP_Company_Suspension__c/ZP_Company_Suspension__c.object-meta.xml
<CustomObject>
    <label>ZP Company Suspension</label>
    <nameField>
        <displayFormat>COMPANY-SUSPENSION-{000000000}</displayFormat>
        <label>ZP Company Suspensions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ZP Company Suspensions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ZP_Company_Suspension__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <length>65535</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ZP_Company_Suspension__c/fields/Suspended_At__c.field-meta.xml
<CustomField>
    <fullName>Suspended_At__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Suspended At</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Integration_Processing_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Queued</fullName>
        <default>true</default>
        <label>Queued</label>
    </customValue>
    <customValue>
        <fullName>Processed</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Dead</fullName>
    </customValue>
    <customValue>
        <fullName>Backlog</fullName>
    </customValue>
    <customValue>
        <fullName>Retry</fullName>
    </customValue>
    <customValue>
        <fullName>Manually Enqueued</fullName>
    </customValue>
    <description>Processing state for integration</description>
    <masterLabel>Integration Processing States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ZPCompanySuspensionQueueTest.cls
@isTest
public class ZPCompanySuspensionQueueTest {
	@isTest
	static void testSuspensionQueue() {
		ZP_Company__c objZpCompany = new TestDataFactory.ZPCompanyBuilder()
			.setZPCompanyId('11111111111111')
			.setCompanyLeadId('222222222222')
			.setProcessingState('Error')
			.setCreatedAtDate(System.today())
			.build();

		insert objZpCompany;

		List<ZP_Company__c> companyList = new List<ZP_Company__c>();
		companyList.add(objZpCompany);

		ZP_Company_Suspension__c suspension = new ZP_Company_Suspension__c();
		suspension.Id__c = '22233344553';
		suspension.Company_Id__c = '11111111111111';
		suspension.Reason__c = 'Leaving for other vendor';
		suspension.Suspended_At__c = Date.today();
		suspension.Processing_State__c = 'Queued';
		insert suspension;
		List<ZP_Company_Suspension__c> suspList = new List<ZP_Company_Suspension__c>();
		suspList.add(suspension);

		Test.startTest();
		System.enqueueJob(new ZPCompanySuspensionQueue(suspList));
		Test.stopTest();

		suspension = [SELECT Id, Processing_State__c FROM ZP_Company_Suspension__c WHERE id = :suspension.Id];
        System.assertEquals(suspension.Processing_State__c, 'Processed', 'The Processing_State__c of ZP_Company_Suspension__c records should be Processed.');

	}
}