unpackaged/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <description>This object is used for tracking any exceptions logged from Apex code</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EL-{0}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Out_Of_Office__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out Of Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UserDetailsComponentController_LEXTest.cls
@isTest
public class UserDetailsComponentController_LEXTest {
	@TestSetup
	static void setup() {
		User objUser = new TestDataFactory.UserBuilder()
			.setAlias('testU')
			.setEmail('test@test.com')
			.setLastName('Testing')
			.setEmailEncoding('UTF-8')
			.setLanguageLocaleKey('en_US')
			.setLocaleSidKey('en_US')
			.setTimeZoneSidKey('America/Los_Angeles')
			.setUserName('UserDetailsComponentController_LEXTest@test.com')
			.setProfileId([SELECT Id FROM Profile WHERE Name = 'ZP System Administrator'].Id)
			.setOOO(true)
			.build();
		insert objUser;
	}

	@isTest
	static void testGetUserData() {
		// Get details of currently logged In User
		Test.startTest();
		UserDetailsComponentController_LEX.UserDetailsWrapper wrapper = UserDetailsComponentController_LEX.getUserData();
		System.assertEquals(wrapper.blnIsSuccess, true, 'Unable to find logged in user');
		Test.stopTest();
	}

	@isTest
	static void testUpdateUserWithOutAdvocateData() {
		Test.startTest();
		UserDetailsComponentController_LEX.updateUser(false);
		UserDetailsComponentController_LEX.UserDetailsWrapper objWrapper = UserDetailsComponentController_LEX.getUserData();
		Test.stopTest();
		System.assertEquals(UserInfo.getUserId(), objWrapper.objUser.Id, 'User Id should match.');
	}

	/**
	 * @Author      : Alex Xiong
	 * @Description : tests updateUser() with mismatching out of office values
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	@isTest
	public static void testUpdateUser() {
		User objUser = [SELECT Id FROM User WHERE UserName = 'UserDetailsComponentController_LEXTest@test.com'];
		Test.startTest();
		System.runAs(objUser) {
			UserDetailsComponentController_LEX.updateUser(false);
		}

		User objUserQueried = [SELECT Out_Of_Office__c FROM User WHERE UserName = 'UserDetailsComponentController_LEXTest@test.com'];
		System.assert(!objUserQueried.Out_Of_Office__c, 'Out_Of_Office__c checkbox on user should be unchecked.');
		Test.stopTest();
	}

	/**
	 * @Author      : Alex Xiong
	 * @Description : tests exception handling
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	@isTest
	public static void testGetUserDataException() {
		Test.startTest();
		UserDetailsComponentController_LEX.blnFail = true;

		try {
			UserDetailsComponentController_LEX.UserDetailsWrapper wrapper = UserDetailsComponentController_LEX.getUserData();
		} catch (Exception ex) {
			List<Exception_Log__c> list_Log = [SELECT Id FROM Exception_Log__c];
			System.assertEquals(1, list_Log.size(), 'There should be 1 log.');
		}

		Test.stopTest();
	}

	/**
	 * @Author      : Alex Xiong
	 * @Description : tests exception handling
	 * @Parm        : N/A
	 * @Return      : N/A
	 **/
	@isTest
	public static void testUpdateUserException() {
		Test.startTest();
		UserDetailsComponentController_LEX.blnFail = true;
		User objUser = [SELECT Id FROM User WHERE UserName = 'UserDetailsComponentController_LEXTest@test.com'];

		try {
			System.runAs(objUser) {
				UserDetailsComponentController_LEX.updateUser(false);
			}
		} catch (Exception ex) {
			List<Exception_Log__c> list_Log = [SELECT Id FROM Exception_Log__c];
			System.assertEquals(1, list_Log.size(), 'There should be 1 log.');
		}

		Test.stopTest();
	}
}