force-app/main/default/objects/User/fields/Inactive_User_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Inactive_User_Date_Time__c</fullName>
    <description>Capture date/time when user is inactive</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Inactive User Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Role__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gustie_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_Skill__c/User_Skill__c.object-meta.xml
<CustomObject>
    <label>User Skill</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Skill__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Role</label>
    <referenceTo>User_Role__c</referenceTo>
    <relationshipLabel>User Skills</relationshipLabel>
    <relationshipName>User_Role</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DeleteUserRolesAndSkillsBatch.cls
/**
 * @name         DeleteUserRolesAndSkillsBatch
 * @test class   DeleteUserRolesAndSkillsTest
 * @author       Deepika Saini
 * @date         17th May 2021
 * @description  Delete User Roles And Skills of Inactive users.
 * @revisions    Date ------------ Name ------------ Comments
 */
public with sharing class DeleteUserRolesAndSkillsBatch implements Schedulable, Database.Batchable<SObject>, Database.Stateful {
	public Boolean blnBatchSuccess = true;
	public List<User_Role__c> list_UserRolesToBeDeleted = new List<User_Role__c>();
	public Set<Id> set_UsersIds = new Set<Id>();

	public static void sendEmailOnBatchFailed() {
		String strToAddresses = System.Label.Daily_Limit_Notification_Email_List;
		List<String> list_ToAddresses = strToAddresses.split(';');
		String strEmailSubject = 'Delete User Roles And Skills Batch failed.';
		String strEmailBody = 'Hello Admin, \n\n Delete User Roles And Skills Batch failed. \n Please check Exception Logs.';

		Messaging.SingleEmailMessage objEmail = new Messaging.SingleEmailMessage();
		objEmail.setSubject(strEmailSubject);
		objEmail.setPlainTextBody(strEmailBody);
		objEmail.setToAddresses(list_ToAddresses);
		if(OrganizationUtilities.canSendEmails()){
			Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ objEmail });	
		}
	}

	public void execute(SchedulableContext objSC) {
		DeleteUserRolesAndSkillsBatch objBatch = new DeleteUserRolesAndSkillsBatch();
		Database.executeBatch(objBatch, 1000);
	}

	public Database.querylocator start(Database.BatchableContext objBC) {
		Set<Id> set_UserRolesId = new Set<Id>();

		for (User_Role__c objUserRole : [
			SELECT Id, User__c
			FROM User_Role__c
			WHERE User__c != null AND User__r.Inactive_User_Date_Time__c != null AND User__r.IsActive = FALSE AND User__r.Inactive_User_Date_Time__c >= YESTERDAY
		]) {
			list_UserRolesToBeDeleted.add(objUserRole);
			set_UserRolesId.add(objUserRole.Id);
			set_UsersIds.add(objUserRole.User__c);
		}

		String strQuery = 'SELECT Id ' + 'FROM User_Skill__c ' + 'WHERE User_Role__c != null ' + 'AND User_Role__c IN :set_UserRolesId';

		return Database.getQueryLocator(strQuery);
	}

	public void execute(Database.BatchableContext objBatch, List<User_Skill__c> list_UserSkillsToBeDeleted) {
		try {
			if (list_UserSkillsToBeDeleted != null && list_UserSkillsToBeDeleted.size() > 0) {
				delete list_UserSkillsToBeDeleted;
			}

			if (Test.isRunningTest() && DeleteUserRolesAndSkillsTest.blnRunCatchTest == true) {
				throw new EmailException('Error while Deleting User Skills for testing');
			}
		} catch (Exception objExp) {
			blnBatchSuccess = false;
			ExceptionLogUtil.logException(
				'DeleteUserRolesAndSkillsBatch',
				'execute method',
				'Error while Deleting User Skills (WHERE Inactive_User_Date_Time__c >= YESTERDAY)' +
				' - ' +
				objExp.getMessage(),
				'high'
			);
		}
	}

	public void finish(Database.BatchableContext objBC) {
		try {
			UserRoleTriggerHelper.skipTrigger = true;
			delete list_UserRolesToBeDeleted;
			UserRoleTriggerHelper.skipTrigger = false;

			if (Test.isRunningTest() && DeleteUserRolesAndSkillsTest.blnRunCatchTest == true) {
				throw new EmailException('Error while Deleting User Skills for testing');
			}
		} catch (Exception objExp) {
			blnBatchSuccess = false;
			ExceptionLogUtil.logException(
				'DeleteUserRolesAndSkillsBatch',
				'finish method',
				'Error while Deleting User Roles (WHERE Inactive_User_Date_Time__c >= YESTERDAY)' +
				' - ' +
				objExp.getMessage(),
				'high'
			);
		}

		try {
			UserUtils.updateRequireRoutingOnBOCO(set_UsersIds);
		} catch (Exception objExp) {
			blnBatchSuccess = false;
			ExceptionLogUtil.logException(
				'DeleteUserRolesAndSkillsBatch',
				'finish method',
				'Error while Updating Requires Routing on Benefit Order and Carrier Order.' +
				' - ' +
				objExp.getMessage(),
				'high'
			);
		}

		if (!blnBatchSuccess) {
			sendEmailOnBatchFailed();
		}
	}
}