force-app/main/default/objects/User/fields/Out_Of_Office__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Out Of Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/User_Role__c/fields/Out_of_Office__c.field-meta.xml
<CustomField>
    <fullName>Out_of_Office__c</fullName>
    <description>This will tell if user in a particular user role is OOO or not</description>
    <formula>User__r.Out_Of_Office__c</formula>
    <label>Out of Office</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gustie_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_Role__c/fields/User_Skill_Team__c.field-meta.xml
<CustomField>
    <fullName>User_Skill_Team__c</fullName>
    <description>FW: Hold the team of Skills user have</description>
    <label>User Skill Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Implementation Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Facilitator</fullName>
            </value>
            <value>
                <fullName>Benefit Transfer</fullName>
            </value>
            <value>
                <fullName>Benefits Advising</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Carrier IO</fullName>
            </value>
            <value>
                <fullName>BYB Advocate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User_Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Skill_Type__c</fullName>
    <description>FW: Hold the type of Skills user have</description>
    <label>User Skill Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeOOOUserRoleCtrlTest.cls
/**
 * @name         : ChangeOOOUserRoleCtrlTest
 * @author       : Rushi R
 * @date         : 12-27-2022
 * @description  : Unit test for ChangeOOOUserRoleCtrl
 **/
@isTest
private class ChangeOOOUserRoleCtrlTest {
	@testSetup
	static void setup() {
		User_Role__c objUserRole = new User_Role__c();
		objUserRole.User__c = UserInfo.getUserId();
		insert objUserRole;

		objUserRole.User_Skill_Team__c = 'Implementation Advocate';
		objUserRole.User_Skill_Type__c = 'Core';
		update objUserRole;
	}

	@isTest
	static void testChangeOOOBtn() {
		User_Role__c objUserRole = [SELECT Id, User__c FROM User_Role__c LIMIT 1];
		User objUser = [SELECT Out_Of_Office__c FROM User WHERE Id = :objUserRole.User__c];
		Boolean bln_OooValue = objUser.Out_Of_Office__c;

		Test.startTest();
		ApexPages.currentPage().getParameters().put('id', objUserRole.id);
		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(objUserRole);
		ChangeOOOUserRoleCtrl extension = new ChangeOOOUserRoleCtrl(stdCtrl);
		extension.changeOOOForUser();

		objUser = [SELECT Out_Of_Office__c FROM User WHERE Id = :objUserRole.User__c];
		system.assertNotEquals(bln_OooValue, objUser.Out_Of_Office__c, 'Unable to change Out of Office');

		extension.backToRecord();
		Test.stopTest();
	}
}