force-app/main/default/objects/Carrier_Info__c/Carrier_Info__c.object-meta.xml
<CustomObject>
    <description>Master object that sores all the Carrier information from HI. This object is a combination of both HI Carrier and HI Carrier Detail.</description>
    <label>Carrier Info</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier_Info__c/fields/Address_Addressed_To__c.field-meta.xml
<CustomField>
    <fullName>Address_Addressed_To__c</fullName>
    <label>Address Addressed To</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Address_Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Address_Zip__c</fullName>
    <label>Address Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Carrier_Detail_Id__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Detail_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Detail Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Customer_Support__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support__c</fullName>
    <label>Customer Support</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Lidi_Census_Email__c.field-meta.xml
<CustomField>
    <fullName>Lidi_Census_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lidi Census Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Carrier_Info__c/fields/Min_Eligible_Employees_Required__c.field-meta.xml
<CustomField>
    <fullName>Min_Eligible_Employees_Required__c</fullName>
    <label>Min Eligible Employees Required</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Qualifying_Life_Event_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_Life_Event_Requirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Qualifying Life Event Requirements</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Carrier_Info__c/fields/Sell_Description__c.field-meta.xml
<CustomField>
    <fullName>Sell_Description__c</fullName>
    <label>Sell Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/HI_Carrier__c/HI_Carrier__c.object-meta.xml
<CustomObject>
    <label>HI Carrier</label>
    <nameField>
        <displayFormat>CARRIER-{000000000}</displayFormat>
        <label>HI Carrier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI Carriers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Carrier__c/fields/Carrier_Detail_Id__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Detail_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Detail Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier__c/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HI_Carrier_Detail__c/HI_Carrier_Detail__c.object-meta.xml
<CustomObject>
    <label>HI Carrier Detail</label>
    <nameField>
        <displayFormat>CARRIER-DETAIL-{000000000}</displayFormat>
        <label>HI Carrier Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI Carrier Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Address_Addressed_To__c.field-meta.xml
<CustomField>
    <fullName>Address_Addressed_To__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Addressed To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Address_City__c.field-meta.xml
<CustomField>
    <fullName>Address_City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Address_State__c.field-meta.xml
<CustomField>
    <fullName>Address_State__c</fullName>
    <label>Address State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Address_Street__c.field-meta.xml
<CustomField>
    <fullName>Address_Street__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Address_Zip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Address Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Customer_Support__c.field-meta.xml
<CustomField>
    <fullName>Customer_Support__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Support</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Lidi_Census_Email__c.field-meta.xml
<CustomField>
    <fullName>Lidi_Census_Email__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Lidi Census Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Min_Eligible_Employees_Required__c.field-meta.xml
<CustomField>
    <fullName>Min_Eligible_Employees_Required__c</fullName>
    <label>Min Eligible Employees Required</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Qualifying_Life_Event_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Qualifying_Life_Event_Requirements__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Qualifying Life Event Requirements</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HI_Carrier_Detail__c/fields/Sell_Description__c.field-meta.xml
<CustomField>
    <fullName>Sell_Description__c</fullName>
    <label>Sell Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/HICarrierTriggerHelper.cls
public with sharing class HICarrierTriggerHelper extends TriggerHandler {
	
	public static boolean skipTrigger = false;
    public static boolean queue=false;

    public HICarrierTriggerHelper() {
		super('HICarrierTriggerHelper');
	}

	public override void beforeInsert(){ 
    	processInformation((List<HI_Carrier__c>) Trigger.new);
    }

    public override void beforeUpdate(){
		processInformation((List<HI_Carrier__c>) Trigger.new);
    }
    
    private void processInformation(List<HI_Carrier__c> carrierList){
    	list<Carrier_Info__c> toUpsertCarrierList = new list<Carrier_Info__c>();
    	set<String> carrierDetailSet = new set<String>();
        for(HI_Carrier__c hiCarrier : carrierList){
            if(hiCarrier.Carrier_Detail_Id__c!=null && hiCarrier.Carrier_Detail_Id__c!=''){
                carrierDetailSet.add(hiCarrier.Carrier_Detail_Id__c);
            }
    	}
        map<String,HI_Carrier_Detail__c> carrierFieldsMap = new map<String,HI_Carrier_Detail__c>();
        if(carrierDetailSet.size()>0){
            carrierFieldsMap = getCarrierDetailInfo(carrierDetailSet);
        }
        
    	for(HI_Carrier__c hiCarrier : carrierList){
			if(hiCarrier.Processing_State__c==IntegrationUtils.DEAD_STATE){
                continue;
            }
            HI_Carrier_Detail__c carrierDetail = new HI_Carrier_Detail__c();
            if(hiCarrier.Carrier_Detail_Id__c!=null && hiCarrier.Carrier_Detail_Id__c!=''){
                if(!carrierFieldsMap.containsKey(hiCarrier.Carrier_Detail_Id__c) ){
                    setProcessingState(IntegrationUtils.ERROR_STATE,'Carrier detail does not exist',hiCarrier);
                    continue;
                } else {
                    carrierDetail = carrierFieldsMap.get(hiCarrier.Carrier_Detail_Id__c);
                }
            }
            Carrier_Info__c info = mapCarrierFields(hiCarrier,carrierDetail);
            toUpsertCarrierList.add(info);
    	}
    	
    	if(toUpsertCarrierList.size()>0){	
			Map < String, String > dmlUpsertErrorsMap = new Map < String, String >();
	        if(toUpsertCarrierList.size() > 0){
	            List<Database.UpsertResult> saveResult = database.upsert(toUpsertCarrierList,Carrier_Info__c.Fields.Id__c,false);
	            dmlUpsertErrorsMap = Utils.processUpsertResult(saveResult,toUpsertCarrierList,'Id__c',true,'HICarrierTriggerHelper-processInformation');
	            
                for(HI_Carrier__c hiCarrier : carrierList){
                    if(string.isblank(hiCarrier.ID__c)){
                        setProcessingState(IntegrationUtils.ERROR_STATE,'Carrier Id is missing in the record.',hiCarrier);
                        continue;
                    }
                    
                    if (dmlUpsertErrorsMap.containsKey(hiCarrier.ID__c) ){
                        setProcessingState(IntegrationUtils.ERROR_STATE,dmlUpsertErrorsMap.get(hiCarrier.ID__c),hiCarrier);
                    } else {
                        setProcessingState(IntegrationUtils.PROCESSED_STATE,'Processed',hiCarrier);                            
                    }
                }
	        }			 
    	}
    }

    // maping all the related fields
    private Carrier_Info__c mapCarrierFields(HI_Carrier__c hiCarrier, HI_Carrier_Detail__c hiDatail){

        Carrier_Info__c info = new Carrier_Info__c(
            Name = hiDatail.Name__c,
            Id__c = hiCarrier.Id__c,
            Key__c = hiCarrier.key__c,
            External_Key__c = hiCarrier.External_Key__c,
            Carrier_Detail_Id__c = hiCarrier.Carrier_Detail_Id__c,
            Active__c = (hiCarrier.Deleted_At__c==null),
            Address_Addressed_To__c = hiDatail.Address_Addressed_To__c,
            Address_City__c = hiDatail.Address_City__c,
            Address_State__c = hiDatail.Address_State__c,
            Address_Street__c = hiDatail.Address_Street__c,
            Address_Zip__c = hiDatail.Address_Zip__c,
            Customer_Support__c = IntegrationUtils.getJsonParsedMap(hiDatail.Customer_Support__c,'default'),
            Email__c = hiDatail.Email__c,
            Lidi_Census_Email__c = hiDatail.Lidi_Census_Email__c,
            Min_Eligible_Employees_Required__c = hiDatail.Min_Eligible_Employees_Required__c,
            Qualifying_Life_Event_Requirements__c = hiDatail.Qualifying_Life_Event_Requirements__c,
            Sell_Description__c = hiDatail.Sell_Description__c
        );
        return info;
    }
    
    private map<String,HI_Carrier_Detail__c> getCarrierDetailInfo(Set<String> carrierDetailId){
        map<String,HI_Carrier_Detail__c> detailMap = new map<String,HI_Carrier_Detail__c>();
        for(HI_Carrier_Detail__c info : [Select Id,Id__c,Name__c,Address_Addressed_To__c,Address_City__c,Address_State__c,
                Address_Street__c,Address_Zip__c,Customer_Support__c,Email__c,Lidi_Census_Email__c,Min_Eligible_Employees_Required__c,
                Qualifying_Life_Event_Requirements__c,Sell_Description__c from HI_Carrier_Detail__c where id__c in :carrierDetailId]){
            detailMap.put(info.Id__c, info);
        }
        return detailMap;
    }

    private HI_Carrier__c setProcessingState(String ProcessingState, String message, HI_Carrier__c hiCarrier){
        hiCarrier.Processing_State__c = ProcessingState;
        hiCarrier.Message__c = message;
        hiCarrier.Last_Processed__c=System.now();
        return hiCarrier;
    }
}