force-app/main/default/objects/Carrier_Info__c/Carrier_Info__c.object-meta.xml
<CustomObject>
    <description>Master object that sores all the Carrier information from HI. This object is a combination of both HI Carrier and HI Carrier Detail.</description>
    <label>Carrier Info</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carrier Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/HI_State_Carrier__c/HI_State_Carrier__c.object-meta.xml
<CustomObject>
    <label>HI State Carrier</label>
    <nameField>
        <displayFormat>STATE-CARRIER-{000000}</displayFormat>
        <label>HI State Carrier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HI State Carriers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/HI_State_Carrier__c/fields/Carrier_Id__c.field-meta.xml
<CustomField>
    <fullName>Carrier_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Carrier Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HI_State_Carrier__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <description>The external record ID from the source system, state_carrier.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>HI State Carrier Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <description>ID of company migration record in Zen Payroll</description>
    <externalId>true</externalId>
    <label>ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/HIStateCarrierBatchTest.cls
@isTest
public class HIStateCarrierBatchTest {
	@isTest
	static void testStateBatch() {
		Carrier_Info__c carrierInfo = new Carrier_Info__c();
		carrierInfo.Id__c = 'carrier321';
		insert carrierInfo;

		HI_State_Carrier__c newRec = new HI_State_Carrier__c();
		newRec.id__c = 'Test321';
		newRec.Carrier_Id__c = 'carrier321';
		insert newRec;

		Test.startTest();
		Database.executeBatch(new HIStateCarrierBatch(), 10);
		Test.stopTest();

		//Verify that the batch processed the records and updated HI_State_Carrier__c records.
		List<HI_State_Carrier__c> list_updatedStateCarriers = [SELECT Id, Processing_State__c FROM HI_State_Carrier__c WHERE Id__c = 'Test321'];
		System.assertEquals(1, list_updatedStateCarriers.size(), 'The HI State Carrier record should exist.');

		//Verify that the AsyncApexJob was created and completed successfully. Assert that the batch job status is completed.
		AsyncApexJob asyncJob = [SELECT Status FROM AsyncApexJob WHERE JobType = 'BatchApex' ORDER BY CreatedDate DESC LIMIT 1];
		System.assertEquals('Completed', asyncJob.Status, 'The batch job should have completed successfully.');
	}
}