unpackaged/main/default/objects/Opportunity/fields/ZP_Add_Company_Addresses__c.field-meta.xml
<CustomField>
    <fullName>ZP_Add_Company_Addresses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Company Addresses</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Add_Employees__c.field-meta.xml
<CustomField>
    <fullName>ZP_Add_Employees__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Employees</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Add_Signatory__c.field-meta.xml
<CustomField>
    <fullName>ZP_Add_Signatory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Signatory</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Enter_Unpaid_Tax_Liabilities__c.field-meta.xml
<CustomField>
    <fullName>ZP_Enter_Unpaid_Tax_Liabilities__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enter Unpaid Tax Liabilities</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Ran_Payroll__c.field-meta.xml
<CustomField>
    <fullName>ZP_Ran_Payroll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ran Payroll</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Report_Previous_Paystubs__c.field-meta.xml
<CustomField>
    <fullName>ZP_Report_Previous_Paystubs__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Report Previous Paystubs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Select_a_Payroll_Schedule__c.field-meta.xml
<CustomField>
    <fullName>ZP_Select_a_Payroll_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Select a Payroll Schedule</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Set_Up_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>ZP_Set_Up_Bank_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set Up Bank Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Set_Up_Federal_Taxes__c.field-meta.xml
<CustomField>
    <fullName>ZP_Set_Up_Federal_Taxes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set Up Federal Taxes</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/ZP_Set_Up_State_Taxes__c.field-meta.xml
<CustomField>
    <fullName>ZP_Set_Up_State_Taxes__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Set Up State Taxes</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ZP_Sign_Company_Forms__c.field-meta.xml
<CustomField>
    <fullName>ZP_Sign_Company_Forms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign Company Forms</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Pricebook2/fields/Product_Tier__c.field-meta.xml
<CustomField>
    <fullName>Product_Tier__c</fullName>
    <description>Generic name of the Tier, Used as the tier in the Pricing Plan field on the account as a value.</description>
    <inlineHelpText>Generic name of the Tier, Used as the tier in the Pricing Plan field on the account as a value.</inlineHelpText>
    <label>Product Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payroll_Product_Tier</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Payroll_Product_Tier.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Core</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <customValue>
        <fullName>Concierge</fullName>
    </customValue>
    <customValue>
        <fullName>Select</fullName>
    </customValue>
    <customValue>
        <fullName>Legacy Premium</fullName>
    </customValue>
    <customValue>
        <fullName>contractor_only</fullName>
        <label>Contractor Only</label>
    </customValue>
    <customValue>
        <fullName>Simple</fullName>
    </customValue>
    <customValue>
        <fullName>Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Premium</fullName>
    </customValue>
    <customValue>
        <fullName>Premium CRB</fullName>
    </customValue>
    <customValue>
        <fullName>Premium Multi-EIN</fullName>
    </customValue>
    <customValue>
        <fullName>Wholesale</fullName>
    </customValue>
    <customValue>
        <fullName>basic</fullName>
        <isActive>false</isActive>
        <label>basic</label>
    </customValue>
    <description>The tiers of our main payroll product, which defines the Account customer tier</description>
    <masterLabel>Payroll Product Tier</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrderOnboardingStepsController.cls
/**
 * @description  Get Onboarding Steps from Order
 * @author       Praveen Sethu
 * @date         12-1-2022
 * @see          OrderOnboardingStepsControllerTest
 **/
public with sharing class OrderOnboardingStepsController {
	public static final String OBJ_TYPE_ORDER = 'Order';
	public static final String OBJ_TYPE_OPPORTUNITY = 'Opportunity';

	/**
	 * @description Gather onboarding steps from company opportunity linked to Order
	 * @author      Praveen Sethu
	 * @param       idRecordId - Record Id
	 * @return      Opportunity - Company Opportunity with onboarding steps
	 **/
	@AuraEnabled
	public static Opportunity getOnboardingSteps(Id idRecordId) {
		String strObjectType = idRecordId == null ? null : idRecordId.getSObjectType().getDescribe().getName();
		Opportunity objOppToReturn = null;
		if (strObjectType == OBJ_TYPE_ORDER) {
			Order objOrder = [SELECT Id, AccountId, OpportunityId FROM Order WHERE Id = :idRecordId];
			if (Test.isRunningTest()) {
				objOrder.OpportunityId = null;
			}

			if (objOrder.OpportunityId != null) {
				objOppToReturn = getCompanyOpportunity(objOrder.OpportunityId);
			} else if (objOrder.AccountId != null) {
				objOppToReturn = getCompanyOpportunity(objOrder.AccountId);
			}
		} else if (strObjectType == OBJ_TYPE_OPPORTUNITY) {
			Opportunity objOpportunity = [SELECT AccountId FROM Opportunity WHERE Id = :idRecordId];
			objOppToReturn = getCompanyOpportunity(objOpportunity.AccountId);
		}
		return objOppToReturn;
	}

	/**
	 * @description Query company opportunity based on id/accountId
	 * @param       idQueryBy - OpportunityId/AccountId
	 * @return      Opportunity - Company Opportunity with onboarding steps
	 **/
	private static Opportunity getCompanyOpportunity(Id idQueryBy) {
		Opportunity objOppToReturn = null;
		List<Opportunity> list_Opportunities = [
			SELECT
				Id,
				Name,
				ZP_Add_Company_Addresses__c,
				ZP_Add_Employees__c,
				ZP_Set_Up_Federal_Taxes__c,
				ZP_Set_Up_State_Taxes__c,
				ZP_Set_Up_Bank_Account__c,
				ZP_Select_a_Payroll_Schedule__c,
				ZP_Report_Previous_Paystubs__c,
				ZP_Add_Signatory__c,
				ZP_Sign_Company_Forms__c,
				ZP_Enter_Unpaid_Tax_Liabilities__c,
				ZP_Ran_Payroll__c,
				Pricebook2.Product_Tier__c
			FROM Opportunity
			WHERE
				(Id = :idQueryBy
				OR AccountId = :idQueryBy)
				AND (RecordTypeId = :OpportunityUtil.COMPANY_OPPTY_RT_ID
				OR (RecordTypeId = :OpportunityUtil.ACQUISITION_OPPTY_RT_ID
				AND Type = :OpportunityUtil.OPPTY_TYPE_NEW_BUSINESS))
			ORDER BY CreatedDate DESC
		];
		if (!list_Opportunities.isEmpty()) {
			objOppToReturn = list_Opportunities.get(0);
		}
		return objOppToReturn;
	}
}