unpackaged/main/default/objects/Research_Upload_Info__c/Research_Upload_Info__c.object-meta.xml
<CustomObject>
    <label>Research Upload Info</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Research Upload Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Upload Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Research_Upload_Info__c/fields/Research_Project_Master_Id__c.field-meta.xml
<CustomField>
    <fullName>Research_Project_Master_Id__c</fullName>
    <formula>IF(UXR_CSV_Staging__c!=&apos;&apos;, CASESAFEID(UXR_CSV_Staging__r.Research_Project_Master__c), CASESAFEID(Research_Project_Master__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Research Project Master Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UR_DeleteUploadInfoData.cls
public class UR_DeleteUploadInfoData implements Database.Batchable<sObject>, Database.Stateful {
	public string projectId;
	public Database.QueryLocator start(Database.BatchableContext bc) {
		String strQuery = 'select id from Research_Upload_Info__c where Research_Project_Master_Id__c=:projectId or Research_Project_Master_Id__c=\'\' ';
		return Database.getQueryLocator(strQuery);
	}
	public void execute(Database.BatchableContext bc, List<sObject> scope) {
		try {
			if (scope.size() > 0) {
				UR_ResearchUploadInfoTriggerHelper.skipTrigger = true;
				delete scope;
				UR_ResearchUploadInfoTriggerHelper.skipTrigger = false;
			}
		} catch (Exception ex) {
			ExceptionLogUtil.logException('UR_DeleteUploadInfoData', 'execute', ex.getMessage(), ex.getStackTraceString());
		}
	}
	public void finish(Database.BatchableContext bc) {
		UR_DeleteCSVStagingData deleteBatchObj = new UR_DeleteCSVStagingData();
		deleteBatchObj.projectId = projectId;
		Database.executeBatch(deleteBatchObj, 500);
	}
}