force-app/main/default/objects/User_Role__c/User_Role__c.object-meta.xml
<CustomObject>
    <label>User Role</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Role__c/fields/Original_Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Original_Team_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Original Team &amp; Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Gustie_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/User_Role__c/fields/User_Skill_Team__c.field-meta.xml
<CustomField>
    <fullName>User_Skill_Team__c</fullName>
    <description>FW: Hold the team of Skills user have</description>
    <label>User Skill Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Implementation Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Advocate</fullName>
            </value>
            <value>
                <fullName>Payroll Transfer Facilitator</fullName>
            </value>
            <value>
                <fullName>Benefit Transfer</fullName>
            </value>
            <value>
                <fullName>Benefits Advising</fullName>
            </value>
            <value>
                <fullName>Account Specialist</fullName>
            </value>
            <value>
                <fullName>Coordinator</fullName>
            </value>
            <value>
                <fullName>Carrier IO</fullName>
            </value>
            <value>
                <fullName>BYB Advocate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User_Role__c/fields/User_Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>User_Skill_Type__c</fullName>
    <description>FW: Hold the type of Skills user have</description>
    <label>User Skill Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserRoleTriggerHelperTest.cls
@isTest
public class UserRoleTriggerHelperTest {
	@TestSetup
	static void setup() {
		User_Role__c objUserRole = new User_Role__c();
		objUserRole.User__c = UserInfo.getUserId();
		objUserRole.User_Skill_Team__c = 'Implementation Advocate';
		objUserRole.User_Skill_Type__c = 'Core';
		insert objUserRole;
	}

	/**
	 * @author       Deepika Saini 
	 * @description  Check for Original Team Type
	 * @param        null
	 * @return       null
	 **/
	@isTest
	static void userRolePayroll() {
		Test.startTest();
		User_Role__c objUserRole = [SELECT Id, User_Skill_Team__c, Original_Team_Type__c FROM User_Role__c LIMIT 1];
		System.debug('objUserRole.Original_Team_Type__c==' + objUserRole.Original_Team_Type__c);
		objUserRole.User_Skill_Team__c = 'Payroll Transfer';
		update objUserRole;
		delete objUserRole;
		undelete objUserRole;
		User_Role__c objUsrRole = [SELECT Id, User__c, User_Skill_Team__c, Original_Team_Type__c FROM User_Role__c WHERE Id = :objUserRole.Id LIMIT 1];
		Test.stopTest();

		System.assert(objUsrRole.Original_Team_Type__c != null);
	}
    
	/**
	 * @author       Deepika Saini
	 * @description  Check for Original Team Type
	 * @param        null
	 * @return       null
	 **/
	@isTest
	public static void testCarrierIOUserRole() {
		Test.startTest();
		User_Role__c objUserRole = [SELECT Id, User_Skill_Team__c, Original_Team_Type__c FROM User_Role__c LIMIT 1];
		objUserRole.User_Skill_Team__c = 'Carrier IO';
		objUserRole.User_Skill_Type__c = 'Core';
		update objUserRole;
		Test.stopTest();

		User_Role__c objUsrRole1 = [SELECT Id, User__c, User_Skill_Team__c, Original_Team_Type__c FROM User_Role__c WHERE Id = :objUserRole.Id LIMIT 1];
		System.assert(objUsrRole1.Original_Team_Type__c != null);
	}
}