force-app/main/default/objects/Event/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/Research_Project_Detail__c/Research_Project_Detail__c.object-meta.xml
<CustomObject>
    <label>Research Project Detail</label>
    <nameField>
        <displayFormat>RPD-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Research Project Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Research_Project_Detail__c/fields/Research_Project_Master__c.field-meta.xml
<CustomField>
    <fullName>Research_Project_Master__c</fullName>
    <label>Research Project Master</label>
    <referenceTo>Research_Project_Master__c</referenceTo>
    <relationshipLabel>Research Project Details</relationshipLabel>
    <relationshipName>Research_Project_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Research_Project_Master__c/Research_Project_Master__c.object-meta.xml
<CustomObject>
    <label>UXR Scout</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UXR Scout</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UR_ViewCalendarCtrl_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class UR_ViewCalendarCtrl_Test {

    static testMethod void ViewCalendarTest() {
        // TO DO: implement unit test
         ContactTriggerHelper.skipTrigger = true;
		 AccountTriggerHelper.skipTrigger=true;
         UR_TestDataUtil.createResearchConfig();
         Research_Project_Master__c projectObj = UR_TestDataUtil.createResearchProjectMaster('Test Project');
         //Create Contact 
         List<Contact> lstTestContact=UR_TestDataUtil.createContact(3);
         //Create Project Participant
         List<Research_Project_Detail__c> lstPartDetail=UR_TestDataUtil.ReturnParticipantListTest(projectObj,lstTestContact);
         //Create Notes
         UR_TestDataUtil.createProjectNotesTest(projectObj,3);
         //Create Event
         List<Event> eventList=UR_TestDataUtil.createParticipantEventTest(lstPartDetail);
         
         //Create Note for 
         ApexPages.CurrentPage().getparameters().put('projectId',projectObj.id);
         ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(projectObj);
         UR_ViewCalendarCtrl uv=new UR_ViewCalendarCtrl(sc);
         uv.objNote.Body='test Body';
         uv.AddNote();
         uv.SaveNotes();
         uv.CancelNote();
         uv.eventdata();
         uv.BackToProjectVF();
         ApexPages.currentPage().getParameters().put('currentEventId',eventList[0].Id);
         uv.getobjEventWrapper();
         uv.updateViewCalendarDate();
    }
    
}