force-app/main/default/objects/Agency_Information__c/Agency_Information__c.object-meta.xml
<CustomObject>
    <label>Agency Information</label>
    <nameField>
        <label>Agency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agency Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Agency_Information__c.field-meta.xml
<CustomField>
    <fullName>Agency_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency Information</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure the agency you have selected is active.</errorMessage>
        <filterItems>
            <field>Agency_Information__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Agency_Information__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <externalId>true</externalId>
    <label>Batch Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Compliance_Score__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Score__c</fullName>
    <description>Compliance Score</description>
    <label>Compliance Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_Up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Follow Up Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Tax_Compliance__c/Tax_Compliance__c.object-meta.xml
<CustomObject>
    <description>This is created as part of compliance project and this should exists only with the case record</description>
    <label>Tax Compliance</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Tax Compliance  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Compliance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Compliance__c/fields/Agency_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Agency_Due_Date__c</fullName>
    <description>Agency Due Date is recorded</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Tax Compliance</relationshipLabel>
    <relationshipName>Tax_Compliance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Tax_Compliance__c/fields/Classification_Type__c.field-meta.xml
<CustomField>
    <fullName>Classification_Type__c</fullName>
    <description>Classification Type</description>
    <label>Classification Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>System Defect</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Compliance Requirement</fullName>
            </value>
            <value>
                <fullName>Product Gap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Compliance_Team_POC__c.field-meta.xml
<CustomField>
    <fullName>Compliance_Team_POC__c</fullName>
    <description>Compliance Team POC</description>
    <label>Compliance Team POC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payroll Product Compliance</fullName>
            </value>
            <value>
                <fullName>Regulatory Affairs</fullName>
            </value>
            <value>
                <fullName>Symmetry Compliance</fullName>
            </value>
            <value>
                <fullName>Tax Filing Compliance (STS)</fullName>
            </value>
            <value>
                <fullName>Tax Filing Compliance (PF)</fullName>
            </value>
            <value>
                <fullName>Tax Filing Compliance</fullName>
                <isActive>false</isActive>
                <label>Tax Filing Compliance</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Customer_Comms__c.field-meta.xml
<CustomField>
    <fullName>Customer_Comms__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Comms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Compliance__c/fields/Customer_Count__c.field-meta.xml
<CustomField>
    <fullName>Customer_Count__c</fullName>
    <description>Customer Count</description>
    <label>Customer Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/CX_Comms__c.field-meta.xml
<CustomField>
    <fullName>CX_Comms__c</fullName>
    <label>CX Comms</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Eng_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Eng_Due_Date__c</fullName>
    <description>Eng Due Date</description>
    <label>Eng Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Eng_Status__c.field-meta.xml
<CustomField>
    <fullName>Eng_Status__c</fullName>
    <description>Eng Status</description>
    <label>Eng Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Exploration (Spec/ Design)</fullName>
            </value>
            <value>
                <fullName>No Eng Work Needed</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Idea</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>No Longer Needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/EPDD_DRI__c.field-meta.xml
<CustomField>
    <fullName>EPDD_DRI__c</fullName>
    <description>Assigning tasks to user</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Task Assignee</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Follow_up_Date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_Date__c</fullName>
    <description>Follow up Date</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Follow up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Frequency_of_Update__c.field-meta.xml
<CustomField>
    <fullName>Frequency_of_Update__c</fullName>
    <description>Frequency of Update</description>
    <label>Frequency of Update</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One time Task</fullName>
            </value>
            <value>
                <fullName>Annual Task</fullName>
            </value>
            <value>
                <fullName>Quarterly Task</fullName>
            </value>
            <value>
                <fullName>Bi Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Help_Center_IKB_External__c.field-meta.xml
<CustomField>
    <fullName>Help_Center_IKB_External__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox indicating Help Center/IKB is ready</description>
    <label>Help Center/IKB Ready to Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Help_Center_IKB_Internal__c.field-meta.xml
<CustomField>
    <fullName>Help_Center_IKB_Internal__c</fullName>
    <description>Enter Help Center/IKB URL</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Help Center/IKB Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Impacts__c.field-meta.xml
<CustomField>
    <fullName>Impacts__c</fullName>
    <label>Impacted Change Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contractors</fullName>
            </value>
            <value>
                <fullName>New Tax Creation</fullName>
            </value>
            <value>
                <fullName>Paid Family Leave</fullName>
            </value>
            <value>
                <fullName>Long Term Care</fullName>
            </value>
            <value>
                <fullName>Overtime</fullName>
            </value>
            <value>
                <fullName>Taxable Wages</fullName>
            </value>
            <value>
                <fullName>Tax Rate Change</fullName>
            </value>
            <value>
                <fullName>Garnishments</fullName>
            </value>
            <value>
                <fullName>TaxRecons</fullName>
            </value>
            <value>
                <fullName>Non-Regular Payrolls</fullName>
            </value>
            <value>
                <fullName>Tax Credits</fullName>
            </value>
            <value>
                <fullName>Termination Payroll</fullName>
            </value>
            <value>
                <fullName>New Hire Reporting</fullName>
            </value>
            <value>
                <fullName>Employee Onboarding</fullName>
            </value>
            <value>
                <fullName>W-4</fullName>
            </value>
            <value>
                <fullName>Employer Onboarding</fullName>
            </value>
            <value>
                <fullName>Worker Payments</fullName>
            </value>
            <value>
                <fullName>Amendments</fullName>
            </value>
            <value>
                <fullName>Year Round Accuracy (YRTA)</fullName>
            </value>
            <value>
                <fullName>Authorizations/ POAs</fullName>
            </value>
            <value>
                <fullName>Time Tracking</fullName>
            </value>
            <value>
                <fullName>Regular Rate of Pay (RRoP)</fullName>
            </value>
            <value>
                <fullName>Bulk Electronic Notices</fullName>
            </value>
            <value>
                <fullName>Software Developer Reqs</fullName>
            </value>
            <value>
                <fullName>Licensing</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>EIN Updates</fullName>
            </value>
            <value>
                <fullName>New Agency System</fullName>
            </value>
            <value>
                <fullName>Address Change</fullName>
            </value>
            <value>
                <fullName>Deposit Frequency</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/In_App_content__c.field-meta.xml
<CustomField>
    <fullName>In_App_content__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>In App content</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Tax_Compliance__c/fields/Knowledge_Management_Readiness__c.field-meta.xml
<CustomField>
    <fullName>Knowledge_Management_Readiness__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Knowledge Management Readiness</description>
    <label>Knowledge Management Readiness</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/Resource_Link__c.field-meta.xml
<CustomField>
    <fullName>Resource_Link__c</fullName>
    <description>Enter Google Drive URL or details</description>
    <label>Google Drive</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tax_Compliance__c/fields/System_impacted__c.field-meta.xml
<CustomField>
    <fullName>System_impacted__c</fullName>
    <description>System Impacted</description>
    <label>System Impacted</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Gusto System</fullName>
            </value>
            <value>
                <fullName>Payments &amp; Filings</fullName>
            </value>
            <value>
                <fullName>Compliance Tracker</fullName>
            </value>
            <value>
                <fullName>Gusto&apos;s Garnishment system (ZP)</fullName>
            </value>
            <value>
                <fullName>Master Tax</fullName>
                <isActive>false</isActive>
                <label>Master Tax</label>
            </value>
            <value>
                <fullName>Payment &amp; Filings</fullName>
                <isActive>false</isActive>
                <label>Payment &amp; Filings</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaxComplianceTriggerHelperTest.cls
/**
 * @name         TaxComplianceTriggerHelper
 * @author       Sindhu
 * @date         06/28/2024
 * @description  Test Class for TaxComplianceTriggerHelper and TaxComplianceTriggerHandler
 **/
@isTest
public class TaxComplianceTriggerHelperTest {

   @TestSetup
    static void setupTestData() {
        Case objParentCase = TestDataFactory.createCaseRecord('Compliance', true);
        Case objChildCase = TestDataFactory.createCaseRecord('Compliance', true);
        Tax_Compliance__c objTaxCompliance = new Tax_Compliance__c();
        objTaxCompliance.Agency_Due_Date__c = System.Today();
        objTaxCompliance.Eng_Due_Date__c = System.Today().addDays(1);
        objTaxCompliance.System_impacted__c = 'Compliance Tracker';        
        objTaxCompliance.Case__c = objParentCase.Id;
        objTaxCompliance.Classification_Type__c = 'Compliance Requirement';
        objTaxCompliance.Compliance_Team_POC__c = '	Payroll Product Compliance';
        objTaxCompliance.Customer_Count__c = 20;
        objTaxCompliance.Resource_Link__c = 'https://www.google.com';
        objTaxCompliance.EPDD_DRI__c = UserInfo.getUserId();
        objTaxCompliance.Frequency_of_Update__c = 'One time Task';
        objTaxCompliance.System_impacted__c = 'Payments & Filings';
        objTaxCompliance.Impacts__c = 'Worker Payments';
        objTaxCompliance.CX_Comms__c = 'ABCD';
        objTaxCompliance.Help_Center_IKB_External__c = false;
        objTaxCompliance.Help_Center_IKB_Internal__c = 'https://www.google.com';
        objTaxCompliance.Knowledge_Management_Readiness__c = true;
        objTaxCompliance.Customer_Comms__c = 'BCS';
        objTaxCompliance.In_App_content__c = 'Test ABCD';
        objTaxCompliance.Eng_Status__c = 'In progress';
        objTaxCompliance.Follow_up_Date__c = System.Today();
        objTaxCompliance.Agency_Due_Date__c = System.Today().addDays(2);
        insert objTaxCompliance;
    }
    
    @isTest
    static void unitTestMethod() {
        
        // Parent case
        List<Case> list_Cases = [SELECT Id, Subject,Status, Description, Batch_Id__c, Agency_Information__r.Name, Compliance_Score__c, (SELECT Id, Agency_Due_Date__c, Eng_Due_Date__c, System_impacted__c FROM Tax_Compliance__r) FROM Case WHERE RecordType.Name = 'Compliance' LIMIT 2];
        Case objParentCase = list_Cases[0];
        Case objChildCase = list_Cases[1];
        Tax_Compliance__c objTaxCompliance =  [SELECT Id, Compliance_Team_POC__c FROM  Tax_Compliance__c LIMIT 1];
        TaxComplianceTriggerHandler.resetSkipTriggerFlags();
        Test.startTest();
        // Tax_Compliance__c objTaxCompliance = mapTaxCompliance.values()[0];
        objTaxCompliance.Compliance_Team_POC__c = 'Symmetry Compliance';
        update objTaxCompliance;
        Test.stopTest();
    }   
}